### ISSUE TITLE
mutation createPartnership > Getting "Unable to create file version" error message while giving `mou` to query input

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1000]
**Describe the bug**
mutation createPartnership > Getting "Unable to create file version" error message while giving `mou` to query input.

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
Partnership should be created or Better error/validation message should be displayed

**Actual Result**
Getting "Unable to create file version" error message while giving `mou` to query input.
See video - https://drive.google.com/file/d/1HlIb31QN3uzNZjhgTVwbYc9QC1HL0X8O/view?usp=drivesdk

GraphQL Query ( requestFileUpload ):
https://drive.google.com/file/d/18fDElH_NzHTF0IHzweCyUDicgZdILFfE/view?usp=sharing

GraphQL Query ( createPartnership ):
https://drive.google.com/file/d/1WpwxAm9j_0oxZJMe90aYVmXsB8-zE93G/view?usp=sharing

**Query and Input File**
1. requestFileUpload (no input)
`
mutation {
  requestFileUpload{
    id
    url
  }
}
`
2. createPartnership
https://drive.google.com/file/d/1sL9HUbrDN1FkFvBHeQo331bqc5rHJ0_n/view?usp=sharing

CordAPIV3# 3bec105c

**Comment by izquierdoalfredo** [comment]
@iPiyushPatel 
requestFileUpload query return presigned file URL and id. It didn't upload the file. after that createPartnership request call bucket.headObject that try to access real file to return metadata.
 But the real file was not uploaded yet. So it throws error. 
You need to upload the file and then call createPartnership request.

**Comment by iPiyushPatel** [comment]
Hi @izquierdoalfredo 

I'm following the below steps and it's working fine now :
1. mutation `requestFileUpload`.
2. Uploading file to URL received from response of 'mutation `requestFileUpload`'.
3. giving `uploadId ` and `name ` to `mou` input of 'mutation `createPartnership`'.

**Comment by izquierdoalfredo** [comment]
Hi @iPiyushPatel 
Ok, you can close this issue
Or Do you need other change in this ticket?

**Comment by iPiyushPatel** [comment]
Hi @izquierdoalfredo ,@reneepe,@michaelmarshall 
Verified on latest master and working fine now
I am closing this issue
