### ISSUE TITLE
Change logger.info to logger.debug 

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1063]
I don't like the console blowing up when not running debug mode. I'm changing the info comments to debug comments.

**Comment by CarsonF** [comment]
Why not change your default log level to notice or warning?

It's a one liner
```yml
# logging.yml
defaultLevel: warning
```

**Comment by michaelmarshall** [comment]
I should do that, but I also don't want to pay for such large and unnecessary AWS logs in prod.

**Comment by CarsonF** [comment]
It's like $0.53 / GB
