### ISSUE TITLE
Update ceremony - not found

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1075]
## Current Behavior

Ceremony can be read and & canEdit is true but `updateCeremony` produces a not found error (due to permissions I'm sure).

## Expected Behavior

canEdit to be false & authorization error on update 

## Environment

| Tech      | Version / Name |
| --------- | -------------- |
| API       |    dbc40aa66832d8692b10df23659a9acdfcbf94ba            |
| FE        |                |
| OS/Device |                |
| Browser   |                |

**Comment by tjgersho** [comment]
CanEdit for the ceremony should be taken from the parent engagement ?

**Comment by tjgersho** [comment]
@CarsonF , A user has permissions like canCreateCeremony and canReadCeremonies.
So the user's canCreateCeremony is enough to update a ceremony?

**Comment by CarsonF** [comment]
Whoops sorry I missed this.

I'm not sure why a user has canCreateCeremony permissions, because users's never create ceremonies. They are created automatically when the engagement is created. It was probably a copy/paste job and should be removed.

I guess `canReadCeremonies` is for the `query ceremonies()` but that's not even used.

In terms of which `canEdits`:
- The `Engagement.ceremony.canEdit` should be false. I'm pretty sure we are consistent with this meaning that the user can or cannot change the relationship to the entire object. Since ceremonies are a managed sub-object of engagements their relationships cannot change. Another example would be `LanguageEngagement.language.canEdit`, since we don't allow the language to be changed after the engagement is created.
- The `canEdits` on the properties of the `Ceremony` I don't think should be looked up from engagement on query, but rather some permissions applied to engagements also need to be applied to the ceremony when it's being created.

All in all there is a miss match between the API saying you can edit these properties, and not matching the permissions (giving not found) when actually calling the mutation.

**Comment by tjgersho** [comment]
Good information. Thank you!

After all, this bug happens when anonymous users try to update a ceremony.

**Comment by CarsonF** [comment]
Hmm I was logged in as root. That could be an issue, but I don't think it's the only one.

**Comment by tjgersho** [comment]
Maybe. I could not see this issue(not found error) in other cases. Can you note your thought to reproduce the issue like this?

**Comment by CarsonF** [comment]
Hmm maybe I was wrong. Maybe I wasn't logged in, and I wasn't trying to make any mutations except for that one.

**Comment by tjgersho** [comment]
Ok. I think It is fine to be closed by https://github.com/SeedCompany/cord-api-v3/pull/1120 for now.
