### ISSUE TITLE
Add test into Organization e2e

### ISSUE THREAD

**Issue by izquierdoalfredo** [SeedCompany/cord-api-v3#1081]

**Comment by reneepe** [comment]
![image](https://user-images.githubusercontent.com/38309285/92203917-517a8600-ee50-11ea-951a-dbf0736b5c55.png)

![image](https://user-images.githubusercontent.com/38309285/92204541-b2568e00-ee51-11ea-8c0b-20798f7fde5f.png)

![image](https://user-images.githubusercontent.com/38309285/92204807-4fb1c200-ee52-11ea-91da-22175c6621df.png)

![image](https://user-images.githubusercontent.com/38309285/92205099-f5fdc780-ee52-11ea-94fa-3d0faeae03af.png)

![image](https://user-images.githubusercontent.com/38309285/92205341-77edf080-ee53-11ea-9680-10eae0e754b6.png)

![image](https://user-images.githubusercontent.com/38309285/92208165-a6ba9580-ee58-11ea-8915-e5f48debbdcc.png)

![image](https://user-images.githubusercontent.com/38309285/92208513-5c85e400-ee59-11ea-9156-2da72ea26e8b.png)

**Comment by izquierdoalfredo** [comment]
@CarsonF 
what solution is better for such cases. Possible solutions are:
1. Default sorting like it work now.
2. Throw error like for Education
3. Return error message similar to "Sort value is not valid"

![image](https://user-images.githubusercontent.com/68758109/92843156-6efca200-f3b2-11ea-826f-dd95596f7500.png)
![image](https://user-images.githubusercontent.com/68758109/92843168-7623b000-f3b2-11ea-9e4c-5a5c54988efa.png)
