### ISSUE TITLE
Organization always returns null when returned from project query

### ISSUE THREAD

**Issue by thomas-adev** [SeedCompany/cord-api-v3#1082]
## Current Behavior
When querying the gql API for a Project, organization is always returning null.

## Expected Behavior

Organization should return as specified in the gql schema.

## Steps to Reproduce

1. Create an organization.
2. Create a project.
3. Create a partnership linking the organization and project you just created.
4. Query the project including the organization as a part of your return value.

## Environment
Short commit hash: c4c11b73

**Comment by reneepe** [comment]
PASSED. When querying for a project, organization returns the correct data.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/a2c0dd0b-4bdc-418e-b34a-3cc186a3b0dd)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/9b6b00a8-5967-492e-8116-389e28312a57)
