### ISSUE TITLE
mutation createLiteracyMaterial > Getting 'Could not create literacy material' error when 'scriptureReferences' field in query input

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1091]
**Describe the bug**
mutation createLiteracyMaterial > Getting 'Could not create literacy material' error when 'scriptureReferences' field in query input

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
LiteracyMaterial should be created OR better error/validation message should be displayed.

**Actual Result**
Getting 'Could not create literacy material' error when 'scriptureReferences' field in query input.
See video - https://drive.google.com/file/d/10VKp2bcd06jCrWg8qubbvm77YYO72SAQ/view?usp=drivesdk

GraphQL Query ( createLiteracyMaterial - error ):
![image](https://user-images.githubusercontent.com/5212585/90594734-bd31e180-e208-11ea-9b41-4c7b86a3f78e.png)

GraphQL Query ( createLiteracyMaterial ):
![image](https://user-images.githubusercontent.com/5212585/90594793-e488ae80-e208-11ea-9480-deef55c00719.png)

**Query and Input File**
[createLiteracyMaterial_ERR_dueto_ScriptRef.txt](https://github.com/SeedCompany/cord-api-v3/files/5094156/createLiteracyMaterial_ERR_dueto_ScriptRef.txt)

CordAPIV3# c4c11b73

**Comment by izquierdoalfredo** [comment]
There is no bug in code. You used wrong type of scriptureReferences. It is needed to use array of scriptureReferences.

It's a correct input for postman query
[createLiteracyMaterial_ERR_dueto_ScriptRef - Work.txt](https://github.com/SeedCompany/cord-api-v3/files/5164707/createLiteracyMaterial_ERR_dueto_ScriptRef.-.Work.txt)

Also You used wrong value for book name, book list present in src/components/scripture/books.ts:20. 

You need to use name from array, but only word, not whole name
for example,
![image](https://user-images.githubusercontent.com/68758109/92034110-c65b9c00-ed3a-11ea-9420-29e5b46b8adb.png)
 you can use only "Exodus" or "Ex" or "Exo" as a name
![image](https://user-images.githubusercontent.com/68758109/92034205-e8edb500-ed3a-11ea-8952-4a8887120494.png)

**Comment by reneepe** [comment]
@izquierdoalfredo Should the error message read as "Could not create literacy material" or should there be a specific message stating that the books are invalid?

**Comment by izquierdoalfredo** [comment]
@reneepe The books related to ScriptureReference, not to LiteracyMaterial. 
So this error is correct for LiteracyMaterial. For wrong name should be error in ScriptureReference I think.

**Comment by iPiyushPatel** [comment]
@izquierdoalfredo @reneepe @michaelmarshall 
Verified on the latest master af9851eb and working fine now.

**Comment by izquierdoalfredo** [comment]
@iPiyushPatel 
Now this ticket can be closed?

**Comment by iPiyushPatel** [comment]
@izquierdoalfredo 
Yes, you can close it,
