### ISSUE TITLE
mutation updateLiteracyMaterial > Getting 'No book matched.......' error when 'scriptureReferences' field in query input

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1092]
**Describe the bug**
mutation updateLiteracyMaterial > Getting 'No book matched.......' error when 'scriptureReferences' field in query input

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
LiteracyMaterial should be updated OR better error/validation message should be displayed.

**Actual Result**
Getting 'No book matched.......' error when 'scriptureReferences' field in query input.
See video - https://drive.google.com/file/d/1LT7KvqGyJ6FuKGNMzKNYPmau11EH0XhF/view?usp=drivesdk

GraphQL Query ( updateLiteracyMaterial - error ):
![image](https://user-images.githubusercontent.com/5212585/90596057-c7091400-e20b-11ea-9771-81aff65bd58f.png)

GraphQL Query ( updateLiteracyMaterial ):
![image](https://user-images.githubusercontent.com/5212585/90596195-151e1780-e20c-11ea-9aec-97e23b3574de.png)

**Query and Input File**
[updateLiteracyMaterial_ERR_dueto_ScriptRef.txt](https://github.com/SeedCompany/cord-api-v3/files/5094208/updateLiteracyMaterial_ERR_dueto_ScriptRef.txt)

CordAPIV3# c4c11b73

**Comment by CarsonF** [comment]
The book names you are giving are invalid, so an error is expected. The error should be a validation error though. This is being worked on currently with #1064

**Comment by frankyma** [comment]
Fixed by https://github.com/SeedCompany/cord-api-v3/pull/1069
