### ISSUE TITLE
mutation createPartnership >Getting output  key name should be 'education ' in createPartnership > mou > created by >education 

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1093]
**Describe the bug**
mutation createPartnership >Getting output  key name should be 'education ' in createPartnership > mou > created by >education 
**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
In createPartnership key name should be 'educations' instead of education

**Actual Result**
Getting the output  key name should be 'education ' in createPartnership > mou > created by >education
See video - https://drive.google.com/file/d/1mbZ7B-VkJeduDrd_0HVHS16Uv8gV1V1X/view?usp=sharing

GraphQL Query ( createPartnership ):
https://drive.google.com/file/d/1Z7vDbL3D_yb5UHjTpPnoqzih4lNsCy0v/view?usp=sharing

CordAPIV3# c4c11b73

**Comment by CarsonF** [comment]
@iPiyushPatel You are saying `User.education` should be `User.educations`.
No it shouldn't; "education" is considered plural as well as singular.
