### ISSUE TITLE
Generic read function

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#110]
As an API developer, I want to use a generic function instead of writing a custom read function for every service so that I can avoid duplicated code and save time.

View the file in `src/core/database/property-update.service.ts` (which will get renamed soon)
and a service that calls it is `src/components/user/user.service.ts`

Create a generic function that the services can use to replace their `read` functions. Use the `read` functions as examples of the abstractions the generic will need to allow for.

**Comment by michaelmarshall** [comment]
@subodhsri1 is working this.

**Comment by subodhsri1** [comment]
Hi @michaelmarshall, I have created a [https://github.com/SeedCompany/cord-api-v3/pull/132/](PR) please comment on your thoughts.

**Comment by subodhsri1** [comment]
@michaelmarshall  @candleshine  have refactored... please review. [here](https://github.com/subodhsri1/cord-api-v3/commit/504fae9ad6fc2f173c2db718e8d7b69981974b38)
