### ISSUE TITLE
Register > Getting 'Email address is already in use' error for User details failed to register successfully 

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1101]
**Describe the bug**
Register > Getting 'Email address is already in use' error for User details failed to register successfully 

**Steps to Reproduce**
1. Register the user1 ( User will not be registered successfully due to some error )
2. Again register the user1 with same details ( Email address is already in use' error ) 

**Expected Result**
User should be allowed to register successfully.

**Actual Result**
Getting 'Email address is already in use' error for User details failed to register successfully.
See video - https://drive.google.com/file/d/1dVLm5ynZvfow7ilKoVitrevCbMMb4DcN/view?usp=sharing

GraphQL Query( register First time ):
https://drive.google.com/file/d/1dz7Z7zaStAGu0HUB4W-C04D4k4nYo3oX/view?usp=sharing

GraphQL Error( register First time ):
```
"errors": [
        {
            "message": "fn is not a function",
            "extensions": {
                "code": "InternalServerError",
                "status": 500,
                "codes": [
                    "InternalServerError"
                ],
                "exception": {
                    "message": "fn is not a function",
                    "stacktrace": [
                        "at Query.call (core\\database\\query.ts:48:11)",
                        "at UserService.readOne (components\\user\\user.service.ts:445:8)",
                        "at AuthenticationResolver.register (components\\authentication\\authentication.resolver.ts:120:41)"
                    ]
                }
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "register"
            ]
        }
    ]
```

GraphQL Query( register with same detail):
https://drive.google.com/file/d/15-Pdx1JswxK_mcTA1C6V3diHD6LNl0FK/view?usp=sharing

GraphQL Error( register with same detail):
```
"errors": [
        {
            "message": "Email address is already in use",
            "extensions": {
                "codes": [
                    "Duplicate",
                    "Input",
                    "Client"
                ],
                "status": 400,
                "field": "email",
                "code": "Duplicate",
                "exception": {
                    "message": "Email address is already in use",
                    "stacktrace": [
                        "at UserService.create (components\\user\\user.service.ts:330:15)"
                    ]
                }
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "register"
            ]
        }
    ]
```

**Query and Input File**
https://docs.google.com/document/d/198AoWpOCClv03NsYlJYGzR1KaGr9PoKGe2muPShK1vc/edit?usp=sharing

CordAPIV3# 4c946db8

**Comment by CarsonF** [comment]
This is a local build cache problem from #1098. You just need to delete your `dist/` folder and restart server.

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
It's running now
