### ISSUE TITLE
Re-enable validation on e2e tests

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1107]
- [ ] Delete this
  https://github.com/SeedCompany/cord-api-v3/blob/74d60973ddc49b785b162bf1e282db6a96ebf9c7/test/utility/create-app.ts#L30-L33
- [ ] Fix now failing tests

**Comment by zkhin** [comment]
@CarsonF Seems there's an issue in the `CalendarDate`. After enabling the `ValidationPipe`, I cannot create the project with the following date.
```
...
mouStart: CalendarDate.fromISO('1991-01-01'),
mouEnd: CalendarDate.fromISO('1992-01-01'),
...
```
If I comment out the date fields, I can create the Project successfully.

![image](https://user-images.githubusercontent.com/4212008/92038748-33ad1280-edb7-11ea-9caf-526f07450b3f.png)
