### ISSUE TITLE
Default budget record amount should be null by default

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1108]
- [ ] We want to allow the float value to be null as this indicates better that the user has not filled it out.
- [ ] The output field probably needs it's type changed to a `SecuredFloatNullable`
- [ ] The update input field needs it's type changed to a nullable float as well

**Comment by glassblowerscat** [comment]
Do we also want to update the `total` returned for a budget where all records have an amount of `null`? Currently the total is also `0`

**Comment by CarsonF** [comment]
> Do we also want to update the `total` returned for a budget where all records have an amount of `null`? Currently the total is also `0`

I think that's ok since it's a calculated aggregate.
