### ISSUE TITLE
Organization service returns duplicate records for list

### ISSUE THREAD

**Issue by blakekrammes** [SeedCompany/cord-api-v3#111]
**Describe the bug**
The organization service returns 4 copies of each record in the array of items that is returned when `list` is called. 

**Steps to Reproduce**
Clear and specific actions taken to cause the behavior. Steps should resemble the following:
1. Go to "organizations" on the Cord FE
2. Create an organization if none exists
3. Click organizations again

Alternatively, you can log the results of the organization list in the service itself in the API code as I've screenshotted below.

**Expected and Actual Results**
I would expect there to be only one record per organization, but there are duplicates

**Screenshots**
<img width="549" alt="Screen Shot 2020-02-12 at 5 22 57 PM" src="https://user-images.githubusercontent.com/49688912/74386816-9196f000-4dbc-11ea-938f-cc094c382fa2.png">

**Additional context**
I suspect the bug lies in the Cypher query. The database does not show duplicate records.

**Comment by blakekrammes** [comment]
This was being caused from my own woodshedding on the FE. I had multiple users associated with a single active token. If 4 users were associated with an account, then 4 copies of the org would be returned from the list query. Daniel has confirmed that there isn't a bug as well so I'll close. Sorry for the false alarm.

**Comment by michaelmarshall** [comment]
Probably just need to add DISTINCT to the cypher query return block.

**Comment by michaelmarshall** [comment]
This was fixed by the list generic using `RETURN DISTINCT`
