### ISSUE TITLE
updatePartnership > Getting null value in `types` field while removed the non-mandatory field type

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1111]
**Describe the bug**
updatePartnership > Getting null value in `types` field while removed the non-mandatory field type

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Updated partnership types are equal to the previous value

**Actual Result**
updatePartnership >Getting null value in `types` field while removed the non-mandatory field type
See video -  https://drive.google.com/file/d/1qy62CbMgo-CFLqfOxgZEo22ehldEZqDD/view?usp=sharing

GraphQL Query:
https://drive.google.com/file/d/1eeaMqhevdLi3cAPiJH6ytZTVnBtyPp5D/view?usp=sharing (without null)
https://drive.google.com/file/d/1eIIfoWlxblfEQvBGmQDyiLfgxMEwtEz0/view?usp=sharing (with null)

GraphQL Error
```
{
    "data": {
        "updatePartnership": {
            "partnership": {
                "id": "jrJMv_WqIT",
                "createdAt": "2020-09-02T15:20:59.529+05:30",
                "types": {
                    "value": [],
                    "canRead": true,
                    "canEdit": true
                },
                "agreementStatus": {
                    "value": "AwaitingSignature",
                    "canRead": true,
                    "canEdit": true
                },
                "mouStatus": {
                    "value": "AwaitingSignature",
                    "canRead": true,
                    "canEdit": true
                },
```

**Query and Input File**
https://docs.google.com/document/d/1-jnMvQzXaoT-WVKNqB1KZSTAxUAnPVR3IHD2GUmfZGU/edit?usp=sharing

CordAPIV3# dd939b18

**Comment by CarsonF** [comment]
Ok so `Partnership.types` is changing when it is omitted from the input changes?

**Comment by CarsonF** [comment]
Regression from #1104. We just need to check nullable before uniquing

**Comment by zkhin** [comment]
@iPiyushPatel Can you verify this bug on the latest master again? Thank you

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown 
I've tested on the develop f294fe28 and it's working fine.
See video: 

https://user-images.githubusercontent.com/5212585/117922430-12220480-b310-11eb-9a2e-76b90f97a436.mp4
