### ISSUE TITLE
File Migration Logic

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1113]
We want to add the ability to "import" a file into our DB that already exists in S3 (for migration).

Modifications needed for `FileService.createFileVersion`:
- [ ] Along side checking for the s3 object at `temp/uploadId` we need to also check for uploadId (root).
  - It would be nice to execute both headObjects at the same time in parallel.
- [ ] If both locations do _not_ exist throw not found error
- [ ] If both locations _do_ exist throw a client error saying that upload request has already been used
- If existing S3 object (at root) exists and temp one does not exist:
  - [ ] Check DB for node and throw already uploaded error if found
  - Continue on if not found
- [ ] Skip S3 move if it's not needed

**Comment by zkhin** [comment]
@CarsonF For checking uploadId(root), is it enough to only call `getFileNode`?
```
await this.getFileNode(uploadId, session);
```

**Comment by CarsonF** [comment]
From the first bullet point? No, that's another call to S3 with headObject.

**Comment by zkhin** [comment]
I see... so that should look like this?
```
await this.bucket.headObject(`${uploadId}`);
```
