### ISSUE TITLE
Partial Scripture Ranges

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1114]
- [ ] Allow `ScriptureRangeInput.start.chapter` to be nullable & default to `1`
- [ ] Allow `ScriptureRangeInput.start.verse` to be nullable & default to `1`
- [ ] Allow `ScriptureRangeInput.end.chapter` to be nullable & default to last chapter in book
- [ ] Allow `ScriptureRangeInput.end.verse` to be nullable & default to last verse in chapter in book

I think these could be applied with a `Transform` decorator. ([example](https://github.com/SeedCompany/cord-api-v3/blob/ced9622ed045be2206ead1cd852e3efdc7edba0a/src/common/name-field.ts#L9))

**Comment by tjgersho** [comment]
@CarsonF , nullable means chapter or verse might not be inputted in the query(undefined)? or null value is possible?
https://i.imgur.com/KBvx8Sq.png
When these fields are undefined,  these fields are not passed to the transform decorator.

**Comment by CarsonF** [comment]
@tjgersho Hmm we should allow undefined, but you're right that this skips transformation. Is a transformer on the class possible?

**Comment by tjgersho** [comment]
Not sure exactly. But I think we can not use Transform decorator on the class. I am checking it now.

**Comment by tjgersho** [comment]
`defaultValue: null` in @Field decorator can pass `undefined` to the transformer as null value.
https://github.com/SeedCompany/cord-api-v3/blob/3f29995b6962a329a2e00f8e583d236a90dbb6ae/src/components/scripture/dto/scripture-reference.dto.ts#L58
