### ISSUE TITLE
query Ceremonies > Sorting field 'projectName' is not available within the Ceremony object

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1119]
**Describe the bug**
query Ceremonies > Sorting field 'projectName' is not available within the Ceremony object.

Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Data 'projectName' should be available for Ceremony, In order to sort the list by 'projectName'.
Note: It is as expected in educations listing for sort by 'institution'.

**Actual Result**
Sorting field 'projectName' is not available  within Ceremony object
See video -  https://drive.google.com/file/d/1Gemg94tlGDhegxGYS_RB3FsctK45Irwk/view?usp=sharing

**GraphQL Query:**
https://drive.google.com/file/d/1RLmeY0N0E1isXIZ0nmUuIznSSTM-ut95/view?usp=sharing
https://drive.google.com/file/d/1I9Q0yraAFLdFPyMCNmosjLzROdjVvWmJ/view?usp=sharing

GraphQL Error

```
 {
    "data": {
        "ceremonies": {
            "total": 15,
            "hasMore": false,
            "items": [
                {
                    "id": "uTulsuqZgD",
                    "createdAt": "2020-09-03T16:58:56.379+05:30",
                    "type": "Dedication",
                    "planned": {
                        "value": false,
                        "canEdit": true,
                        "canRead": true
                    },
                    "estimatedDate": {
                        "value": "2020-09-03",
                        "canEdit": true,
                        "canRead": true
                    },
                    "actualDate": {
                        "value": "2020-09-03",
                        "canEdit": true,
                        "canRead": true
                    }
                },
```

_Query and Input File_
https://docs.google.com/document/d/1GDu2CbSHrVB4Yh0aerD_4N4rRbazhoSXEe6APqJz6z4/edit?usp=sharing

CordAPIV3# 35341943

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466601168) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
I'm marking this as a feature instead of a bug. We never expected ceremonies to be sorted by project names. You actually can't even get the project from the ceremony right now.

Additionally `query ceremonies` isn't even used right now. So this is definitely bottom of priority list.
