### ISSUE TITLE
Users query error message "query_1.requestingUser is not a function"

### ISSUE THREAD

**Issue by reneepe** [SeedCompany/cord-api-v3#1125]
Users query throws the error message "query_1.requestingUser is not a function"

**Steps to Reproduce**
1. Go to api playground
2. Query users
3. See error 

API: a97dfd34   
     

**Expected and Actual Results**
Expected: Accurate user data is returned .
Actual: No user data is returned and error message is thrown.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/3db34f80-b9ca-4ad5-8466-61b1716507f9)

**Platform/Environment**  

Desktop:
- OS: Windows 10 Pro 1903
- Browser: Chrome
- Version: 84.0.4147.135

[Users query error message.txt](https://github.com/SeedCompany/cord-api-v3/files/5172792/Users.query.error.message.txt)

**Comment by tjgersho** [comment]
Can you retry it after removing `dist` folder?
FYI: https://github.com/SeedCompany/cord-api-v3/pull/1098

**Comment by reneepe** [comment]
Thanks @tjgersho! It worked. Closing it out.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/e8a7f0bb-a20b-4b07-9855-172d8ace632b)
