### ISSUE TITLE
Create tests for checking the update to every property on the User

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#113]
As an API developer, I want to have automated tests that check for the ability to update each user property individually, so that I know the user service's update function works for all properties.

Write a test to individually update each user property. Use Jest's built-in functionality to prevent duplicating code. Ask Daniel for the function reference.

**Comment by candleshine** [comment]
This means to me, that the test needs to pass in new values in for each property in user and then expect() the new values to be the updated values
