### ISSUE TITLE
createProduct > Getting empty value in `label` field of the `scriptureReferences`

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1133]
**Describe the bug**
createProduct > Getting empty value in `label` field of the `scriptureReferences`

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
The value should be return for the `label` field of the `scriptureReferences`

**Actual Result**
Getting empty value in the `label` field of the `scriptureReferences`
See video - https://drive.google.com/file/d/1C4QA7GDuWDrwjP1Hc-Gf0Mdrk2oEVdj2/view?usp=sharing

**GraphQL Query:**
![image](https://user-images.githubusercontent.com/5212585/92379332-e9b08d80-f124-11ea-82e3-9a5d1881b5c8.png)

**GraphQL Error**
```
"scriptureReferences": {
                    "value": [
                        {
                            "start": {
                                "book": "Genesis",
                                "chapter": 3,
                                "verse": 4,
                                "bookName": "Genesis",
                                "label": "Genesis 3:4"
                            },
                            "end": {
                                "book": "Genesis",
                                "chapter": 3,
                                "verse": 4,
                                "bookName": "Genesis",
                                "label": "Genesis 3:4"
                            },
                            "label": "",
                            "totalVerses": 0
                        }
```

**Query and Input File**
https://docs.google.com/document/d/1PTnnTCXVZJchBm44BTXAEst_gUbiHh0XKLM7jHnIBE8/edit?usp=sharing

CordAPIV3# 3a23f628

**Comment by CarsonF** [comment]
I don't believe it's been implemented yet.
https://github.com/SeedCompany/cord-api-v3/blob/master/src/components/scripture/scripture-range.resolver.ts#L22-23

But yes it needs to be done
