### ISSUE TITLE
createProduct > Getting `0` value in `totalVerses` field of the `scriptureReferences`

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1134]
**Describe the bug**
createProduct > Getting `0` value in `totalVerses` field of the `scriptureReferences`

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
The  `>0` value should be return for the `totalVerses` field of the `scriptureReferences`

**Actual Result**
Getting `0` value in `totalVerses` field of the `scriptureReferences`
See video -  https://drive.google.com/file/d/1_x4FKj0Fn-5Yda1Ztyc4QUy-44hWqK9n/view?usp=sharing

**GraphQL Query:**
![image](https://user-images.githubusercontent.com/5212585/92382370-1b782300-f12a-11ea-9167-535293040ad0.png)

**GraphQL Error**
```
"scriptureReferences": {
                    "value": [
                        {
                            "start": {
                                "book": "Genesis",
                                "chapter": 3,
                                "verse": 4,
                                "bookName": "Genesis",
                                "label": "Genesis 3:4"
                            },
                            "end": {
                                "book": "Genesis",
                                "chapter": 3,
                                "verse": 4,
                                "bookName": "Genesis",
                                "label": "Genesis 3:4"
                            },
                            "label": "",
                            "totalVerses": 0
                        }
```

**Query and Input File**
https://docs.google.com/document/d/1PTnnTCXVZJchBm44BTXAEst_gUbiHh0XKLM7jHnIBE8/edit?usp=sharing

CordAPIV3# 3a23f628

**Comment by CarsonF** [comment]
https://github.com/SeedCompany/cord-api-v3/blob/master/src/components/scripture/scripture-range.resolver.ts#L30-31
