### ISSUE TITLE
 Getting empty value for  scriptureReferences field while creating product with produces field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1138]
**Describe the bug**
createProduct > Getting empty value for  `scriptureReferences` field while creating product with `produces` field 

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
The value should be return for the `scriptureReferences` field

**Actual Result**
 Getting empty value for  `scriptureReferences` field while creating product with `produces` field.
See video -  https://drive.google.com/file/d/1S0uejGWwbPZ737j0Rmy6h1eVza-UpxOQ/view?usp=sharing

**GraphQL Query(createStory):**
![image](https://user-images.githubusercontent.com/5212585/92479344-0b7f4280-f201-11ea-9b36-31c4a510bec3.png)

**GraphQL Query(createProduct):**
![image](https://user-images.githubusercontent.com/5212585/92479576-58631900-f201-11ea-9ecd-138090904781.png)

**GraphQL response**
```
"data": {
        "createProduct": {
            "product": {
                "id": "Q2J7Vsviw",
                "createdAt": "2020-09-08T18:28:45.643+05:30",
                "approach": "Visual",
                "legacyType": "BibleStories",
                "mediums": {
                    "value": [
                        "EBook"
                    ],
                    "canEdit": true,
                    "canRead": true
                },
                "purposes": {
                    "value": [
                        "EvangelismChurchPlanting"
                    ],
                    "canEdit": true,
                    "canRead": true
                },
                "methodology": {
                    "value": "OtherVisual",
                    "canEdit": true,
                    "canRead": true
                },
                "scriptureReferences": {
                    "value": [],
                    "canEdit": true,
                    "canRead": true
                }
```

**Query and Input File**
https://docs.google.com/document/d/1mKZC8m-lpJfnlh1Yx2a9zOJxi0-tmg0cuE6-J_f9u-M/edit?usp=sharing

CordAPIV3# 3a23f628

**Comment by CarsonF** [comment]
Could be fixed by #1096
