### ISSUE TITLE
Validate User Roles on team member creation or update

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#1151]
When creating a new team member or updating his/her roles, validate if that user has that role available.  If not throw relevant error.

Include test.

**Comment by tjgersho** [comment]
@frankyma , when we are talking about the roles that create or update a new team member, we mean `canCreateProjectMember` like [here](https://github.com/SeedCompany/cord-api-v3/blob/ac33147f263b9472c0151565c83abfce14b3c4db/src/components/project/project-member/project-member.service.ts#L199) ?

**Comment by frankyma** [comment]
No, it's [these](https://github.com/SeedCompany/cord-api-v3/blob/2bf6862d8ef4bab065c8e440d63c25b42f7d77a8/src/components/user/dto/user.dto.ts#L47) Roles that each user has access to.  For example, if Frank has FieldOperationsDirector and OfficeOfThePresident roles as part of his user profile, he can only added as those roles as a team member
