### ISSUE TITLE
Partner.types

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1168]
Same as `Partnerships.types` copied to Partners. Maybe rename `PartnershipType` to `PartnerType`.

Like `ProjectMember.roles`, allowed `Partnership.types` need to be limited to a subset of `Partner.types`.

**Comment by CarsonF** [comment]
Ok waiting until we have Partner module and going to put it there

**Comment by zkhin** [comment]
@CarsonF I think we need to wait until this https://github.com/SeedCompany/cord-api-v3/pull/1211 PR is merged
