### ISSUE TITLE
Error creating a new derivative scripture product multiple scripture ranges

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#1173]
## Current Behavior
When creating a new derivative scripture product with multiple scripture references override ranges, get error **Can't create node `sr` with labels or properties here. The variable is already declared in this context**

## Expected Behavior

Able to create or better error message
## Steps to Reproduce

1. Create any language engagement
2. Create derivative scripture product on engagement with multiple scripture reference override ranges

## Screenshots
<img width="1644" alt="Screen Shot 2020-09-10 at 6 34 54 PM" src="https://user-images.githubusercontent.com/43487134/92839012-58dfe900-f394-11ea-87a1-6010cc08b7ee.png">

## Environment

| Tech      | Version / Name |
| --------- | -------------- |
| API       |      af9851eb          |
| FE        |                |
| OS/Device |                |
| Browser   |                |

**Comment by tjgersho** [comment]
Can you check this issue on https://github.com/SeedCompany/cord-api-v3/pull/1096 ?

**Comment by frankyma** [comment]
> Can you check this issue on #1096 ?

@tjgersho not working on that branch unfortunately
