### ISSUE TITLE
createProject > Getting "Cannot query field \"id\" on type \"SecuredDirectory\" error while creating project with rootDirectory field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1174]
**Describe the bug**
createProject > Getting `Cannot query field \"id\" on type \"SecuredDirectory\` error  while creating project with `rootDirectory` field

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
The project should be created

**Actual Result**
Getting `Cannot query field \"id\" on type \"SecuredDirectory\` error  while creating project with `rootDirectory` field
See video -  https://drive.google.com/file/d/1cz_BdduUifWK_5lFXsYNohcgMGa7oDR6/view?usp=sharing

**Note:**
I found the same issue for the Product, Language and Partnership modules also for the `rootDirectory` field.

**GraphQL Query**
![image](https://user-images.githubusercontent.com/5212585/92877685-06044100-f429-11ea-9bc9-de23e1d208a4.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Cannot query field \"id\" on type \"SecuredDirectory\".",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "codes": [
                    "GRAPHQL_VALIDATION_FAILED",
                    "GraphQL",
                    "Client"
                ]
            },
            "locations": [
                {
                    "line": 2009,
                    "column": 9
                }
            ]
        },
```

**Query and Input File**
[CreateProjectSecuredString.txt](https://github.com/SeedCompany/cord-api-v3/files/5207185/CreateProjectSecuredString.txt)

CordAPIV3# af9851eb

**Comment by CarsonF** [comment]
@iPiyushPatel If you see `GraphQL` AND `Client` in the `errors.extensions.codes` that means it's a problem with your query, it's not the API's fault.

See #1070
