### ISSUE TITLE
createStory > "scripture references > end > book" field value is not returned as requested in query input

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1175]
**Describe the bug**
createStory > `scripture references > end > book` field value is not returned as requested in query input

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Value should be returned as requested in the query input field Or an Error message should be returned for unique book inputs.

**Actual Result**
`scripture references > end > book` field value is not returned as requested in query input
See video - https://drive.google.com/file/d/1RYYZWUj5wo0r9jVO64-M8bD26yyEooE4/view?usp=sharing

**GraphQL Query(createStory):**
![image](https://user-images.githubusercontent.com/5212585/92897470-d827f800-f43a-11ea-9519-efb0026bc618.png)

**GraphQL response**
```
{
    "data": {
        "createStory": {
            "story": {
                "id": "QugAmx4J7",
                "createdAt": "2020-09-11T14:21:18.947+05:30",
                "scriptureReferences": {
                    "value": [
                        {
                            "start": {
                                "book": "Genesis",
                                "chapter": 3,
                                "verse": 4,
                                "bookName": "Genesis",
                                "label": "Genesis 3:4"
                            },
                            "end": {
                                "book": "Genesis",
                                "chapter": 5,
                                "verse": 6,
                                "bookName": "Genesis",
                                "label": "Genesis 5:6"
                            },
                            "label": "",
                            "totalVerses": 53
                        }
                    ],

```

**Query and Input File**
[CreateStoryEndBook.txt](https://github.com/SeedCompany/cord-api-v3/files/5207850/CreateStoryEndBook.txt)

CordAPIV3# af9851eb

**Comment by CarsonF** [comment]
@iPiyushPatel Can you still reproduce this? We've made changes but I'm not sure if it's addressed this or not.

**Comment by iPiyushPatel** [comment]
@CarsonF I've tested on the latest master 7e7ba3b4 and its working fine now.
See Video - https://drive.google.com/file/d/1Troovd8dJZe5FAd5DDfkCRNJ6NkFSBcW/view?usp=drivesdk.

**Comment by CarsonF** [comment]
Sweet!
