### ISSUE TITLE
Multiple error messages returned in the response for parameter mismatch request

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1208]
**Describe the bug**
createSong > Multiple error messages returned in the response for parameter mismatch request.

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Single error message should be returned in the response

**Actual Result**
Multiple error messages returned in the response for parameter mismatch request
See video -  https://drive.google.com/file/d/148kqMNpzFCH3yUj2zIyVfvHjGhFEZmY4/view?usp=sharing

**Note:** 
It was working fine till now.
I can also replicate the same issue in most of the modules (Organization, Language, Film, Product, etc.)

**GraphQL Query(createSong):**
![image](https://user-images.githubusercontent.com/5212585/93173635-64dbfa00-f74a-11ea-852d-dc070a83bd88.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Variable \"$input\" got invalid value { name1: \"SongName15092020115025\" } at \"input.song\"; Field \"name\" of required type \"String!\" was not provided.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": []
                },
                "codes": [
                    "INTERNAL_SERVER_ERROR",
                    "Server"
                ]
            },
            "locations": [
                {
                    "line": 1,
                    "column": 21
                }
            ]
        },
        {
            "message": "Variable \"$input\" got invalid value { name1: \"SongName15092020115025\" } at \"input.song\"; Field \"name1\" is not defined by type \"CreateSong\". Did you mean \"name\"?",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": []
                },

```

**Query and Input File**
[CreateSongMultipleError.txt](https://github.com/SeedCompany/cord-api-v3/files/5222852/CreateSongMultipleError.txt)

CordAPIV3# 7e7ba3b4

**Comment by CarsonF** [comment]
We don't control this @iPiyushPatel it's from the GQL server code. There's also not a problem with multiple errors - that's apart of the GQL spec. This also only happens when a query is messed up, which only a dev can do (not a user), so there's no need to try and handle this errors programmatically.

We are reporting that these are `"Server"` errors though, so I've got a PR up #1212 to report them as `"Client"` errors instead.
