### ISSUE TITLE
Password Reset Errors

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1213]
When attempting to create an account on beta.cordfield.com I am informed that the user ID is already in use.

I then attempt to reset the password but receive an error that the password reset cannot be sent because the 
>"Email address is not verified. The following identities >failed the check in region US-EAST-2: >noreply@cordfield.com, seth_mcknight@tsco.org"

<img width="1552" alt="Screen Shot 2020-09-15 at 7 50 39 AM" src="https://user-images.githubusercontent.com/7377802/93213379-634e0a00-f729-11ea-918f-46ae1e5a5e82.png">

**Comment by michaelmarshall** [comment]
@zkhin please replace the last reset password query in the authentication service with this and let me know if it still works for you locally. We'll then push to beta and let Seth try.
```
          MATCH(e:EmailToken {token: $token})
          DELETE e
          WITH *
          MATCH (:EmailAddress {active: true, value: $email})<-[:email {active: true}]-(user:User {active: true})
          OPTIONAL MATCH (user)-[oldPasswordRel:password]->(oldPassword)
          SET oldPasswordRel.active = false, oldPassword.active = false
          WITH user
          LIMIT 1
          MERGE (user)-[:password {active: true}]->(password:Property {active: true})
          SET password.value = $password
          RETURN password
```
