### ISSUE TITLE
Code of the Bible book is not returned for "scriptureReferences >start >book"and "`scriptureReferences >end >book"  field according to schema

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1220]
**Describe the bug**
createFilm > Code of the Bible book is not returned for `scriptureReferences >start >book` and `scriptureReferences >end >book` field according to schema

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Code of the Bible book should be returned for `scriptureReferences >start >book` and `scriptureReferences >end >book` field according to schema

**Actual Result**
Code of the Bible book is not returned for `scriptureReferences >start >book` and `scriptureReferences >end >book` field according to schema
See video -  https://drive.google.com/file/d/1SpYRb4zFa6UM4EgXRhNBjVfnEeyRM65Q/view?usp=sharing

**GraphQL Query(createFilm):**
![image](https://user-images.githubusercontent.com/5212585/93305983-e439fe00-f81c-11ea-8bfb-eaf7ca646b8c.png)

**GraphQL Query(createFilm):**
![image](https://user-images.githubusercontent.com/5212585/93314522-7e9f3f00-f827-11ea-9989-18e7af4173c9.png)

**GraphQL response**
```
{
    "data": {
        "createFilm": {
            "film": {
                "id": "HW68FZDzP",
                "createdAt": "2020-09-16T12:59:32.394+05:30",
                "name": {
                    "value": "FilmName16092020125932",
                    "canRead": true,
                    "canEdit": true
                },
                "scriptureReferences": {
                    "canRead": true,
                    "canEdit": true,
                    "value": [
                        {
                            "totalVerses": 1525,
                            "label": "Genesis 3:4-Exodus 3:4",
                            "start": {
                                "book": "Genesis",
                                "bookName": "Genesis",
                                "label": "Genesis 3:4",
                                "chapter": 3,
                                "verse": 4
                            },
                            "end": {
                                "book": "Exodus",
                                "bookName": "Exodus",
                                "label": "Exodus 3:4",
                                "chapter": 3,
                                "verse": 4
                            }
                        }

```

**Query and Input File**
[CreateFilmBookCode.txt](https://github.com/SeedCompany/cord-api-v3/files/5230872/CreateFilmBookCode.txt)

CordAPIV3# 6070e117

**Comment by CarsonF** [comment]
`book` and `bookName` are being merged into a single `book`.
`book` already returns the name now as you see.
`bookName` will go away with #1202
