### ISSUE TITLE
projects > Getting "Could not find root directory associated to this project" error when the query has a `rootDirectory` field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1228]
**Describe the bug**
projects > Getting `Could not find root directory associated to this project` error when the query has a `rootDirectory` field

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Project listing should be returned.

**Actual Result**
Getting `Could not find root directory associated to this project` error when the query has a `rootDirectory` field.
See video -  https://drive.google.com/file/d/1Dvev-ZAbyPJHEMXQRemhwbLmrAEsX8uD/view?usp=sharing

**GraphQL Query:**
![image](https://user-images.githubusercontent.com/5212585/93431252-802d3d80-f8e1-11ea-8be7-c97d6e9fe7dc.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Could not find root directory associated to this project",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "name": "NotFoundException",
                    "status": 400,
                    "stacktrace": [
                        "at ProjectService.getRootDirectory (components\\project\\project.service.ts:867:13)",
                        "at ProjectResolver.rootDirectory (components\\project\\project.resolver.ts:144:12)"
                    ]
                },
                "codes": [
                    "INTERNAL_SERVER_ERROR",
                    "Server"
                ]
            },
            "locations": [
                {
                    "line": 1745,
                    "column": 7
                }
            ],
            "path": [
                "projects",
                "items",
                5,
                "rootDirectory"
            ]
        }
    ],

```

**Query and Input File**
[GetAllProjectsError.txt](https://github.com/SeedCompany/cord-api-v3/files/5236938/GetAllProjectsError.txt)

CordAPIV3# cf790476

**Comment by CarsonF** [comment]
It's this on v3.cordfield.com? We haven't fixed the messed up database there

**Comment by iPiyushPatel** [comment]
@CarsonF  No, I was testing on local env. Today I'm getting a different error though, a bug is already logged for it https://github.com/SeedCompany/cord-api-v3/issues/1219

Please advice.

**Comment by zkhin** [comment]
@iPiyushPatel Can you wipe your DB and regenerate the issue? I cannot reproduce that issue on my side.

**Comment by iPiyushPatel** [comment]
@zkhin @CarsonF 
Verified on the latest master f1e92283 and working fine now.
