### ISSUE TITLE
Organization list filtering

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#123]
WF version: https://seedcompany.my.workfront.com/task/view?ID=5e4c43f901a94aacf19591218da3b801

**Comment by gowthamrodda** [comment]
@michaelmarshall @candleshine Since @devireddyswetha needs a ticket, I am assigning this one to her.

**Comment by candleshine** [comment]
the query in organization service has this line commented 
```
//      WHERE
//        org.name CONTAINS $filter
```
we need edit this query string so that the WHERE line is included if and only if $filter is defined.  
if it is empty, the line is removed.
