### ISSUE TITLE
BUG | Create Project

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1233]
When attempting to create a new Project an error is returned 'Failed to create Project'. 

The Project does not show up on the Projects list, but can be found when searching. 

Attempting to open the Project throws an error 'Could not find root directory associate with this problem.'

The Project opens but the user who created the project has not been assigned to it and most data is redacted or unable to be selected.

I've recreated this in both v3 and beta environments with both the root user and seth_mcknight@tsco.org

**Comment by CarsonF** [comment]
Probably the same as #1219

**Comment by michaelmarshall** [comment]
![image](https://user-images.githubusercontent.com/1165460/93505258-3ee85e00-f8e0-11ea-8bb8-00e0cf88bc9a.png)

**Comment by zkhin** [comment]
@candleshine @michaelmarshall This bug raises if the `requestingUser` does not have `ProjectManager` role while creating `ProjectMember`
https://github.com/SeedCompany/cord-api-v3/blob/master/src/components/project/project-member/project-member.service.ts#L198~L199

**Comment by michaelmarshall** [comment]
Ok, @frankyma is working on a fix that adds all roles to root. the test may need to give roles as needed to users it creates. please sync with Frank.

**Comment by frankyma** [comment]
That fix is in master: https://github.com/SeedCompany/cord-api-v3/blob/master/src/components/admin/admin.service.ts#L166

**Comment by zkhin** [comment]
@frankyma Yes, that's right. But as Carson mentioned, there's no code to update the `root` user's role in the existing database.
So I think we need to add the `roles` to the root user if it doesn't exist (https://github.com/SeedCompany/cord-api-v3/blob/master/src/components/admin/admin.service.ts#L111~L135)

**Comment by frankyma** [comment]
Ok I guess I don't really know what's going on but reach out if you need me for anything

**Comment by frankyma** [comment]
https://github.com/SeedCompany/cord-api-v3/pull/1254 will give new non-root users ability to create projects.  For existing users on beta/v3 @michaelmarshall will do a data refresh
