### ISSUE TITLE
updateLiteracyMaterial > Getting  " Book \"\" does not exist"  error while "scriptureReferences > end > book"  field is blank

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1261]
**Describe the bug**
updateLiteracyMaterial > Getting  ` Book \"\" does not exist`  error while `scriptureReferences > end > book`  field is blank

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
The proper error message should be returned

**Actual Result**
 Getting  ` Book \"\" does not exist`  error while `scriptureReferences > end > book`  field is blank.
See video -  https://drive.google.com/file/d/1NmA3E7iPyKGDRYIEGYDqikDs_sC18N-8/view?usp=drivesdk

Note : I can found the same issue in product

**GraphQL Query:(updateLiteracyMaterial )**
![image](https://user-images.githubusercontent.com/5212585/94123590-9c952100-fe71-11ea-8995-b890392cbe7b.png)

**GraphQL response**

```
{
    "errors": [
        {
            "message": "Book \"\" does not exist",
            "extensions": {
                "codes": [
                    "NotFound",
                    "Input",
                    "Client"
                ],
                "status": 400,
                "code": "NotFound",
                "exception": {
                    "message": "Book \"\" does not exist",
                    "stacktrace": [
                        "at Function.find (components\\scripture\\books.ts:1272:11)",
                        "at Function.fromRef (components\\scripture\\books.ts:1276:17)",
                        "at Function.fromRef (components\\scripture\\books.ts:1389:17)",
                        "at Function.fromRef (components\\scripture\\books.ts:1478:20)",
                        "at D:\\Project\\Seedcompany\\projects\\cord-api-v3\\src\\components\\scripture\\dto\\scripture-range.dto.ts:64:41",
                        "at Object.exports.mapRange (components\\scripture\\dto\\scripture-range.dto.ts:26:8)",
                        "at Function.fromReferences (components\\scripture\\dto\\scripture-range.dto.ts:64:12)",
                        "at ScriptureReferenceService.update (components\\scripture\\scripture-reference.service.ts:96:33)",
                        "at LiteracyMaterialService.update (components\\literacy-material\\literacy-material.service.ts:192:5)"
                    ]
                }
            },
```

**Query and Input File**
[updateLiteracyMaterial.txt](https://github.com/SeedCompany/cord-api-v3/files/5274705/updateLiteracyMaterial.txt)

CordAPIV3# 8469bd66

**Comment by CarsonF** [comment]
That looks error looks proper to me. What are you expecting @iPiyushPatel?

**Comment by iPiyushPatel** [comment]
@Carson
As shown in the attached video, there is validation message for the empty input to `scriptureReferences > start > book` field, which is missing for `scriptureReferences > end > book` field.

![image](https://user-images.githubusercontent.com/5212585/94229460-336ae780-ff1d-11ea-95a9-bd6c6cdcdecd.png)

**Comment by CarsonF** [comment]
Ok you're right. It should be a validation error not a "NotFound" error.

**Comment by frankyma** [comment]
Not sure how to fix this.  I followed the validator to here but could use some help with how validators/decorators work: https://github.com/SeedCompany/cord-api-v3/blob/d1f28ae2d36ec003ee160a9765dd3aac9f19597b/src/components/scripture/dto/scripture-reference.transformer.ts#L12
