### ISSUE TITLE
Person > Edit > Getting "Could not find object" error while clicking on the submit button

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1263]
**Describe the bug**
Person > Edit > Getting ` Could not find object` error while clicking on the submit button

**Steps to Reproduce**
1. Login
2. Create a new Person and click on `view` 
3. Click on ` Edit` icon and edit information
4. Click on the `Submit` button

**Expected Result**
Person Information should be updated.

**Actual Result**
Getting `Could not find object` error while click on the submit button.
See video-  https://drive.google.com/file/d/1SkEPvO__LqSXqKvWtd0MnjYmcZ7AjTR6/view?usp=drivesdk

cord-field# d9d50245

**Comment by CarsonF** [comment]
Looks like a permission thing, not matching the resource on update.

**Comment by frankyma** [comment]
Fixed on master
