### ISSUE TITLE
Refactor tests to use Powers API

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1291]
The new Powers API changes how we authorize users to do things. To not break tests, all users where given all powers:
![image](https://user-images.githubusercontent.com/1165460/94882858-bb298800-042e-11eb-84ec-68ae9706ab49.png)
A few things need to happen now:
1. Remove the code that grants users all powers.
2. Expose the Powers API to the frontend by creating a resolver for it.
3. Use the new API in the test suite (when applicable) by logging in as the root user and granting another user the power needed. This is only needed for powers that users don't get by default, like CreateLanguage or CreateOrganization. Some tests won't need refactored, some will.

**Comment by zkhin** [comment]
@michaelmarshall What is the `GrantPower` in `Powers` type? I think that's only for the root user for granting powers to other normal users.

**Comment by michaelmarshall** [comment]
The root will grant the `GrantPower` power to other users so that they, in turn, can grant powers to their people. Otherwise, no other admins would be able to delegate creating a language for example.
