### ISSUE TITLE
updateUser > Getting "Could not find object"  error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1297]
**Describe the bug**
updateUser > Getting `Could not find object`  error

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
The user should be updated.

**Actual Result**
Getting `Could not find object`  error.
See video - https://drive.google.com/file/d/18WWweSqJh510_M_3RwWtOiv_tCnKZYpb/view?usp=sharing

**Note:** I can replicate a similar type of issue in organization, unavailability, and project.

**GraphQL Query(updateUser ):**

![image](https://user-images.githubusercontent.com/5212585/95058994-eacdde00-0715-11eb-823a-c864761f695c.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Could not find object",
            "extensions": {
                "codes": [
                    "Input",
                    "Client"
                ],
                "status": 400,
                "code": "Input",
                "exception": {
                    "message": "Could not find object",
                    "stacktrace": [
                        "at DatabaseService.sgUpdateProperty (core\\database\\database.service.ts:385:13)",
                        "at DatabaseService.sgUpdateProperties (core\\database\\database.service.ts:310:17)",
                        "at UserService.update (components\\user\\user.service.ts:295:5)",
                        "at UserResolver.updateUser (components\\user\\user.resolver.ts:173:18)"
                    ]
                }
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],

```

**Query and Input File**
[Updateuser error.txt](https://github.com/SeedCompany/cord-api-v3/files/5326352/Updateuser.error.txt)

CordAPIV3# 56822338

**Comment by frankyma** [comment]
@iPiyushPatel I cannot reproduce with any of my existing users and the attached inputs, on root or regular user.  Can you give complete Steps To Reproduce starting from a clean database?
