### ISSUE TITLE
[BUG] Intern Engagement 'Add Mentor' does not add a Mentor.

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1303]
To reproduce:
- Create an Internship Project
- Create an Intern Engagement
- Open the Engagement and click 'Add Mentor'
- Search for the Mentor and select them
- Click Save
- Don't see Mentor, refresh page
- Still don't see Mentor

Expected Behavior - The Mentor is saved for the Engagement and can be viewed after clicking save

Actual Behavior - The Mentor does not appear to be saved and cannot be viewed on the Engagement.

**Comment by frankyma** [comment]
API issue, the API engagement couldn't update mentor if none existed on engagement create
