### ISSUE TITLE
Refactor delete

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#1313]
Currently the `deleteNode` method only deletes the old baseNode, leaving the property nodes untouched and unable to create new base nodes with the same property value.

**Approach:**
1. Mark any parent base node relationships (pointing to and from the base node) as active = false.
2. Mark the labels `Deleted`. So if deleting a User , remove the `User` and `BaseNode` labels and add `Deleted_User`, and `Deleted_BaseNode`.
3. Convert any uniqueness-constrained properties to a by-convention new name. So let's say we are deleting a language and we need to delete the name by tombstone. 
a.  reset all the labels with the `Deleted_` prefix 
b.  set the value under an `deleted_value` property and delete the `value` prop. This will clear the constraint so a similar named language can be created.
4. do the same ^^ for the id on the base node. save it as `old_id` and clear the `id` prop. This will make it un-findable for normal searches, but still findable when we implement a history api.
5. The property rels are still active true and the permission nodes/relationships untouched

**Comment by michaelmarshall** [comment]
Child base node relationships of the deleted node should be left intact. So on point #1, don't delete rels from the base node. Just rels pointing to the base node.
