### ISSUE TITLE
createLocation > Getting "Socket hangup" error when "iso31663" field is blank

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1314]
**Describe the bug**
createLocation > Getting `Socket hangup` error when `iso31663` field is blank

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
A proper validation message should be displayed. It's working as expected for blank input to the `fundingAccountId` field.

**Actual Result**
Getting `Socket hangup` error when the `iso31663` field is blank.
See video - https://drive.google.com/file/d/19A6JWUdQRrp0yaKwBRknYzXplDtzFm7W/view?usp=drivesdk

**GraphQL Query (createLocation - iso31663 ):**
![image](https://user-images.githubusercontent.com/5212585/95318547-577edf00-08b4-11eb-9d99-b54d0791599e.png)

**GraphQL Query (createLocation - fundingAccountId ):**
![image](https://user-images.githubusercontent.com/5212585/95319941-5353c100-08b6-11eb-8157-6434f936b952.png)

**GraphQL response**
```
Could not get response
Error: socket hang up
```

**Query and Input File**
[iso31663ScoketHangupError.txt](https://github.com/SeedCompany/cord-api-v3/files/5339805/iso31663ScoketHangupError.txt)

CordAPIV3# 65fbe075

**Comment by zkhin** [comment]
@iPiyushPatel can you re-verify this bug on the latest master branch?
![image](https://user-images.githubusercontent.com/4212008/97214913-8206ec80-180f-11eb-8996-c15d6be7a93a.png)

**Comment by iPiyushPatel** [comment]
@zkhin @michaelmarshall  @CarsonF
Verified and working fine on latest master 4fb39928
