### ISSUE TITLE
createOrganization > Getting "user 4A94sYZo8 does not have the requested power: CreateOrganization" error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1325]
**Describe the bug**
createOrganization > Getting `user 4A94sYZo8 does not have the requested power: CreateOrganization` error

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Organization should be created.

**Actual Result**
Getting `user 4A94sYZo8 does not have the requested power: CreateOrganization` error.
See video - https://drive.google.com/file/d/1M-l-Tp_y-AzAKuBG-iFy7Wm9-5Xc7IU6/view?usp=drivesdk

**Note:** I can replicate the same issue in `createLanguage` module.

**GraphQL Query (createOrganization ):**
![image](https://user-images.githubusercontent.com/5212585/95426122-0548c700-0963-11eb-8507-6626e88e4611.png)

**GraphQL response**

```
{
    "errors": [
        {
            "message": "user 4A94sYZo8 does not have the requested power: CreateOrganization",
            "extensions": {
                "codes": [
                    "Unauthorized",
                    "Input",
                    "Client"
                ],
                "status": 403,
                "code": "Unauthorized",
                "exception": {
                    "message": "user 4A94sYZo8 does not have the requested power: CreateOrganization",
                    "stacktrace": [
                        "at AuthorizationService.checkPower (components\\authorization\\authorization.service.ts:286:13)",
                        "at OrganizationService.create (components\\organization\\organization.service.ts:94:5)",
                        "at OrganizationResolver.createOrganization (components\\organization\\organization.resolver.ts:32:26)"
                    ]
                }
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createOrganization"
            ]
        }
    ],
```

**Query and Input File**
[CreateOrganizationError.txt](https://github.com/SeedCompany/cord-api-v3/files/5345907/CreateOrganizationError.txt)

CordAPIV3# c35e1e5a

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466688682) by [Unito](https://www.unito.io)

**Comment by zkhin** [comment]
@iPiyushPatel The new normal user will not have the power to create organization and language. Those powers should be granted from the root admin user. There is a new mutation for granting the power (`mutation grantPower`). So you should logged in as root admin first of all and then grant the power to the new user and logged in as the new user again and then try to create organization and language.
