### ISSUE TITLE
Rename Location.iso31663 field

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1331]
Let's rename the `iso31663` field to something else. For these reasons:
- 31663 is ambiguous. ISO 3166-3 is a list of old codes that have been deleted. We are actually referencing the ISO 3166-1 list and specifically the _alpha 3_ code of that list. More info [here](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes).
- I'd like to have this field to have some kind of suffix so that we can have a field without the suffix that is an object containing all of the fields from the ISO 3166-1 list. This can be looked up via the alpha 3 code.

I don't think we'll ever use the 3166-3 list as it's the deleted one. The 3166-2 is used for states/regions within the country. Maybe this would be used in the future if we want to be more specific than country.

Suggestions:
- iso31661Code
- iso31661Alpha3
- isoCountryAlpha3
- isoAlpha3
- isoCode
- isoAlpha3
- iso3

**Comment by zkhin** [comment]
@CarsonF How's about `isoAlpha3`?

**Comment by CarsonF** [comment]
That's what @blakekrammes voted for too.

Sounds good to me ☺️
