### ISSUE TITLE
[BUG] 'My Projects' filter not working

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1342]
The Projects list is displaying all projects visible to the user, whether the 'My Projects' filter is toggled on or off.

**Comment by zkhin** [comment]
@CarsonF Is this backend issue? I think `mine` filter option is working fine now.

**Comment by CarsonF** [comment]
I thought it was lol.

**Comment by zkhin** [comment]
@iPiyushPatel Can you verify this bug? `mine` filter works fine on my local.

**Comment by iPiyushPatel** [comment]
@zkhin @michaelmarshall @CarsonF 
I can still replicate this issue on the latest master 4fb39928
See video: https://drive.google.com/file/d/1MTTdMkYhB_J0M_QVEYJIkymvsHnlUDDZ/view?usp=drivesdk

Note: Projects created by other users are returned for `mine = true` and projects created by the same user also returned for `mine = false`.

**Comment by sethmcknight** [comment]
This still seems to be an issue.

- We should default the filter to `mine=true`
- 'mine=true' should return any project the user is a team member of (@CarsonF this would be the same list we'll display on a users profile)
- 'mine=false' should return all projects the user has permissions to view (regardless of membership)

**Comment by CarsonF** [comment]
FYI @michaelmarshall reverted the merged PR for this.

**Comment by iPiyushPatel** [comment]
Hi @zkhin @michaelmarshall @CarsonF 
I've verified on the latest develop d2d4e490 branch and it's working fine.
See video: 
https://user-images.githubusercontent.com/5212585/106235840-8df4b700-6221-11eb-8365-974d2326d852.mp4
