### ISSUE TITLE
createPartner > Duplicate values to "types" field is allowed

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1351]
**Describe the bug**
createPartner > Duplicate values to `types` field is allowed

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Proper validation message should be returned for duplicate inputs to `types` field.
It's working as expected for `mediums` field of `Product`.

**Actual Result**
Duplicate values to `types` field is allowed.
See video -  https://drive.google.com/file/d/1oXV2dauW-3YlXn16RGiY36L-rYvS3qQk/view?usp=drivesdk

GraphQL Query ( createPartner ):
![image](https://user-images.githubusercontent.com/5212585/95974113-26f9f080-0e32-11eb-8376-a445d3354343.png)

**Query and Input File**
[CreatePartnerDuplicateValueIssue.txt](https://github.com/SeedCompany/cord-api-v3/files/5377363/CreatePartnerDuplicateValueIssue.txt)

CordAPIV3# 3d374415

**Comment by zkhin** [comment]
@CarsonF  @iPiyushPatel `types` field in `Partner` and `Partnership` modules is transformed into unique so the duplicated value is removed from the array.

**Comment by CarsonF** [comment]
Ah yes I see that [here](https://github.com/SeedCompany/cord-api-v3/blob/433ad555149d802981a55d4df4dab93bcd8cabc6/src/components/product/product.service.ts#L90-L103). I'd rather change products to match what we are doing in the rest of the app. I think it's fine to remove duplicates for the user; it's safe to assume their intent.
