### ISSUE TITLE
query {module} > Data is still returned at times when the "sort" field having invalid data (i.e. any string other than actual sorting param)

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1363]
**Describe the bug**
query {module} > Data is still returned at times when the `sort` field having invalid data (i.e. any string other than actual sorting param)

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Error should be returned for invalid input to the `sort` field.

**Actual Result**
At times, Data is still returned when `sort` field having invalid data (i.e. any string other than actual sorting param)
See video - https://drive.google.com/file/d/17cuz-dYlq3Wy6mVAEWV7pCZXZjnNEr16/view?usp=sharing

**Note**
I can replicate the same issue in Budget, Education, Film, Organization, Language, LiteracyMaterial, Location, Organization, Partner, Partnership, Song, Story, and User.
Some request returns data and some returns error for invalid input to `sort` field.

**GraphQL Query ( partners ):**
![image](https://user-images.githubusercontent.com/5212585/96131985-7b2ad080-0f17-11eb-85fa-0c375aa588f0.png)

**GraphQL Query ( unavailablities ):**
![image](https://user-images.githubusercontent.com/5212585/96130800-04d99e80-0f16-11eb-87c6-fe0d0ff7c587.png)

**GraphQL Query ( films ):**
![image](https://user-images.githubusercontent.com/5212585/96131640-153e4900-0f17-11eb-829c-9840389ec9b7.png)

**GraphQL response( partners ):**
```
{
    "data": {
        "partners": {
            "total": 46,
            "hasMore": true,
            "items": [
                {
                    "id": "tB1pr4cUE",
                    "createdAt": "2020-10-15T18:45:03.871+05:30",
                    "types": {
                        "value": [
                            "Funding"
                        ],
                        "canRead": true,
                        "canEdit": true
                    },
                    "financialReportingTypes": {
                        "value": [],
                        "canEdit": true,
                        "canRead": true
                    },
                    "pmcEntityCode": {
                        "value": "KAK",
                        "canEdit": true,
                        "canRead": true
                    },
                    "globalInnovationsClient": {
                        "value": false,
                        "canEdit": true,
                        "canRead": true
                    },
                    "active": {
                        "value": false,
                        "canEdit": true,
                        "canRead": true
                    },
                    "address": {
                        "value": "2621 McKenzie Gardens",
                        "canEdit": true,
                        "canRead": true
                    },
```

**GraphQL response( unavailablities ):**
```
{
    "errors": [
        {
            "message": "Variable `asdf` not defined (line 9, column 10 (offset: 763))\r\n\"ORDER BY asdf\"\r\n          ^",
            "extensions": {
                "code": "InternalServerError",
                "status": 500,
                "codes": [
                    "InternalServerError"
                ],
                "exception": {
                    "message": "Variable `asdf` not defined (line 9, column 10 (offset: 763))\r\n\"ORDER BY asdf\"\r\n          ^",
                    "stacktrace": [
                        "at Session.run (core\\database\\cypher.factory.ts:58:34)",
                        "at DatabaseService.list (core\\database\\database.service.ts:631:32)",
                        "at UnavailabilityService.list (components\\user\\unavailability\\unavailability.service.ts:199:34)",
                        "at UnavailabilityResolver.unavailabilities (components\\user\\unavailability\\unavailability.resolver.ts:40:25)"
                    ]
                }
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "unavailabilities"
            ]
        }
    ],
```

**Query and Input File**
[InvalidValueForSortField.txt](https://github.com/SeedCompany/cord-api-v3/files/5385140/InvalidValueForSortField.txt)

CordAPIV3# 8e9efc34

**Comment by zkhin** [comment]
@CarsonF Currently the refactored list query does not trigger the error even if the `sort` field is invalid...
```
MATCH (requestingUser:User { id: 'LnGL2VEYl' })<-[:member]-(:SecurityGroup)-[:permission]->(perms:Permission)-[:baseNode]->(node:Partner)
WITH collect(distinct node) as nodes, count(distinct node) as total
unwind nodes as node
WITH *
ORDER BY node.asdf
WITH collect(distinct node.id)[0..25] as items, total
RETURN items, total
```
Do you have any idea to resolve this issue? something like using a validation decorator...

**Comment by CarsonF** [comment]
Yeah I've been punting on that. A decision needs to be made on how to handle sorting by nested objects. Like we want to sort engagement "by name". Well engagement doesn't have a name. So is it `language.name`? What about `user.name` - user doesn't have a single name field. Ok then do we have just have special strings that are not tied directly to properties for this case? I.e. we'll assume `name` means what you'd expect on engagement even though it doesn't  translate to a direct property. 

Overall this is a low priority anyways because the sort options are determined by the UI code, not users. So validation doesn't give much bang for buck here.
