### ISSUE TITLE
Reaction: Add Region/Zone Directors to Project team

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1365]
- When a region gets added/updated on a project we need to pull its director and add them to the project team.
  - The region's zone and its director should also be pulled and added as well.

Question: What happens when a director changes or a region's zone changes? Should this trigger a update on the team as well or no?

**Comment by sethmcknight** [comment]
Checking with Field but I don't believe we will be doing this anymore. This was used in v2 but has caused more issues than it has solved.

**Comment by sethmcknight** [comment]
From Field Ops:
- It would be nice if we can automatically assign the Region/Zone Directors when a Region/Zone is selected.
- Team members should be able to add/remove additional roles from any Directors assigned to a Project.
- The automatically assigned Directors should be able to be removed from the Project if needed.
- It is ok if we don't do this and team members manually add the Directors to the team.

**Comment by CarsonF** [comment]
@sethmcknight Ok I'm assuming if the director changes on either region or zone we shouldn't make any team changes. And if/when a region's zone changes we shouldn't make any changes either.

What about when a project's region changes from one to another. Do we automatically change the directors? What if the director has been manually changed, etc.
It gets complicated really fast.

The simplest thing I can think of is only add the directors if the project doesn't already have them. If they already exist we do nothing, and probably put a note in UI that says to check and make sure they are correct now.

**Comment by sethmcknight** [comment]
@CarsonF yes, it gets complicated fast.
