### ISSUE TITLE
Change FinancialReportingType to plural on create and update partnership

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#1377]
On CreatePartnership and UpdatePartnership, change the FinancialReportingType field to FinancialReportingTypes (plural) just like on create and update partner.  Still keep it a subset of the partner.

**Comment by CarsonF** [comment]
Wait I'm sorry I may have been confused on the other PR. _Partnership_ should only have a single `financialReportingType`. _Partner_ should have multiple.

**Comment by frankyma** [comment]
Partner does have multiple currently.  I just pointed out in partnership it's single to make sure that's not a mistake

**Comment by CarsonF** [comment]
Correct that's not a mistake. Sorry for the confusion.

**Comment by frankyma** [comment]
All good 🙂
