### ISSUE TITLE
Typescript Strict Mode

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#138]
The following should be applied to `tsconfig.json` (`compilerOptions`):
```json
    "strict": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
```

After this any errors need to be fixed.

There were lots of errors with the previous code style, which is why we held off. The new code should be fine.
I'm hoping we are close enough now to move forward with this and maybe just fix the remaining errors.

**Comment by richardgirges** [comment]
I'll give this one a go 👍
