### ISSUE TITLE
Edit language > Getting "Could not find object" error 

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1386]
**Describe the bug**
Edit language > Getting `Could not find object` error 

**Steps to Reproduce**
1. Login
2. Click on ` Language menu > Select Language > Edit Language`
3. Click on the `Submit` button

**Expected Result**
Language  should be updated Or If it is a session issue, the user should be redirected to log in screen

**Actual Result**
Getting `Could not find object` error.
See video -  https://drive.google.com/file/d/11brlNL7jPHy5ankgn1YFDc3Zk_aIno7B/view?usp=drivesdk

cord-field# 756f703b

**Comment by frankyma** [comment]
Seeing the same on update project, will investigage

**Comment by frankyma** [comment]
Tested and seems fixed
