### ISSUE TITLE
[BUG] Cannot add Location or Field Region to Project

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1398]
Users can see the fields to add Location and Field Region to a Project. They are able to look up Locations and Field Regions and select one. 

However after clicking save the data does not appear to save. 

Refreshing, navigating back to the Project or logging out and back in again does not resolve the issue. The Location and Field Region remain empty.

**Comment by CarsonF** [comment]
`fieldRegion` appears to update, but `primaryLocation` does not. `fieldRegion` can also not be set to null.
