### ISSUE TITLE
[BUG] Can't Create Project 'Failed to Fetch'

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1399]
When attempting to create a Project the system takes a long time and then returns an error 'Failed to Fetch'.

Searching for the Project shows that it was actually created but the user is instead shown the 'Failed to Fetch' error and an error message 'Could not communicate with CORD Platform'

**Comment by sethmcknight** [comment]
Had the same error pop up when creating an engagement.

**Comment by CarsonF** [comment]
I bumped the API load balancer timeout from 1 min to 5 mins.
