### ISSUE TITLE
[BUG] Creating a Managing Partnership with a Financial Reporting Type times out, no indicator to show that the system is working to create a new partnership.

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1409]
Currently it is possible to create a Managing Partnership on a Project, though it is slow.

However, when adding a Managing Partnership and selecting an available Financial Reporting Type the system times out and the Partnership is never created.

**Comment by frankyma** [comment]
API issue, not giving the proper input error
