### ISSUE TITLE
Create Project > Getting "Project with this name already exists" error even if the project with that name is not created

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1415]
**Describe the bug**
Create Project > Getting `Project with this name already exists` error even if the project with that name is not created

**Steps to Reproduce**

1. Login 
1. Click on ` Create New Item > Select Project menu > Create new project `
1. Click on the `Submit` button
1. Again click on the `submit` button

**Expected Result**
Project should be created.

**Actual Result**
I can find the same project by search and not displayed on the listing page.
See video -  https://drive.google.com/file/d/1g8KBYmw6151ern4VKdAIJBzExo6UMKQV/view?usp=drivesdk

cord-field# 02aaa9c6

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466706910) by [Unito](https://www.unito.io)

**Comment by zkhin** [comment]
@CarsonF @iPiyushPatel If the user does not have the `ProjectManager` role, it cannot create a project member while creating a project.
https://github.com/SeedCompany/cord-api-v3/blob/master/src/components/project/project.service.ts#L322~L326
But the project is already created before creating a project member.

**Comment by michaelmarshall** [comment]
It will always be possible for a project to exist that the user can't see. Is that what this might be?
