### ISSUE TITLE
Create Project > Project is not created for specific user roles i.e. "RegionalDirector","FieldOperationsDirector"

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1416]
**Describe the bug**
Create Project > Project is not created for specific user roles i.e. `RegionalDirector`,`FieldOperationsDirector`

**Steps to Reproduce**
1. Register user with roles i.e. `RegionalDirector`,`FieldOperationsDirector`
1. Login 
1. Click on ` Create New Item > Select Project menu > Create new project `
1. Click on the `Submit` button
4. Again click on the `submit` button

**Expected Result**
Project should be created.

**Actual Result**
Project is not created for specific user roles i.e. `RegionalDirector`,`FieldOperationsDirector`.

See video (user roles: RegionalDirector,FieldOperationsDirector):
https://drive.google.com/file/d/19n2xl-iUfq3X27BB5zcozm8yk5eHzye0/view?usp=drivesdk

See video (user roles: FieldOperationsDirector):
https://drive.google.com/file/d/17R_b6TuyXRYcmx-MrzlyZKd2CPLr6Lrd/view?usp=drivesdk

cord-field# 02aaa9c6

**Comment by zkhin** [comment]
@CarsonF , @iPiyushPatel https://github.com/SeedCompany/cord-api-v3/issues/1415#issuecomment-715482087
