### ISSUE TITLE
Switch all Enums to Pascal Case

### ISSUE THREAD

**Issue by richardgirges** [SeedCompany/cord-api-v3#142]
In order to avoid interoperability issues when executing server-side queries and mutations (this mostly happens in e2e tests), we need to switch all enums to have matching key and value. 

Action item: switch all enums to have the exact same key and value in pascal case (e.g. `BibleStories`). This will be a breaking change and should be documented as such in the forthcoming PR. 

See here for more information: https://typegraphql.ml/docs/enums.html#interoperability

**Comment by michaelmarshall** [comment]
closing, old.
