### ISSUE TITLE
[BUG] Regional Director and Field Ops Director roles do not have the correct permissions

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1424]
I created a user with the Regional Director and Field Ops Director roles.

That user was assigned to a project with both roles.

The user is unable to view most information or change the Project step.

**Comment by frankyma** [comment]
I just re-ran the STR in a fresh database and the new user has all the permissions on a project.  I was able to change project step, start and end dates, create an engagement, and create/edit team members

**Comment by zkhin** [comment]
@frankyma Can you just follow these steps?
- Create a new user with the `ProjectManager` role
- Login as a project manager
- Create a new project
- Create a new user with `RD` and `FOD` roles
- Login as a director
- Try to update the project.

And if you follow these steps, it will work fine.
- Create a new user with the `ProjectManager` role
- Create a new user with `RD` and `FOD` roles
- Login as `ProjectManager` user
- Create a new project
- Login as director
- Try to update the project.

**Comment by frankyma** [comment]
^I confirmed that following those steps, in the first block of steps the edit/view is hidden to the `Director`, but in the 2nd block the Director has all permissions
