### ISSUE TITLE
query projects > Getting "Could not find root directory associated to this project" error  when query output has a "rootDirectory" field and filter "mine" has "false" value

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1440]
**Describe the bug**
query projects > Getting `Could not find root directory associated to this project` error  when query output has a `rootDirectory` field and filter `mine` has `false` value

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Projects listing should be returned.

**Actual Result**
Getting `Could not find root directory associated to this project` error when query output has a `rootDirectory` field and filter `mine` has `false` value.
See video - https://drive.google.com/file/d/1keUC-WAbyepTrSZ0Q3NHlCKGKWRwDYPA/view?usp=drivesdk

**GraphQL Query (mine false):**
![image](https://user-images.githubusercontent.com/5212585/97267357-0b3e1380-1850-11eb-983e-08b612303bd8.png)

**GraphQL Query (mine true):**
![image](https://user-images.githubusercontent.com/5212585/97267439-2f99f000-1850-11eb-8949-e5aa5ca76516.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Could not find root directory associated to this project",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "name": "NotFoundException",
                    "status": 400,
                    "stacktrace": [
                        "at ProjectService.getRootDirectory (components\\project\\project.service.ts:997:13)",
                        "at ProjectResolver.rootDirectory (components\\project\\project.resolver.ts:176:12)"
                    ]
                },
                "codes": [
                    "INTERNAL_SERVER_ERROR",
                    "Server"
                ]
            },
            "locations": [
                {
                    "line": 1815,
                    "column": 7
                }
            ],
            "path": [
                "projects",
                "items",
                1,
                "rootDirectory"
            ]
        }
    ],
```

**Query and Input File**
[RootDirectryErrorInProjectsMineFalse.txt](https://github.com/SeedCompany/cord-api-v3/files/5443477/RootDirectryErrorInProjectsMineFalse.txt)

CordAPIV3# 4fb39928

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel Looks like this is working now. Going to put in review for when you have time to confirm.....
FYI, @ParkeBrown 
<img width="1282" alt="Screen Shot 2020-12-16 at 5 24 00 PM" src="https://user-images.githubusercontent.com/15220335/102418578-9ec7d100-3fc3-11eb-9b7c-81e33d4ca5e1.png">

**Comment by iPiyushPatel** [comment]
@elisabeth-sorrell @ParkeBrown 
I've verified on the latest develop b2c47c7d branch and it's working fine.
