### ISSUE TITLE
[BUG] Sort Projects by Dates

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1446]
When trying to sort by Dates the results do not appear correctly. They're all mashed up.

**Comment by sethmcknight** [comment]
@frankyma you're right, dates look good to me now!

I'll add this over on the Sensitivity ticket as well, but I'm getting weird interspersing of Lows in with the Highs. Is it possible this is a data issue on Beta @michaelmarshall?

**Comment by frankyma** [comment]
Closed because date working as expected
