### ISSUE TITLE
updateProject > Getting "Cannot read property 'status' of undefined" error while update any field of project

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1460]
**Describe the bug**
updateProject > Getting `Cannot read property 'status' of undefined` error while update any field of project

**Steps to Reproduce**
1. Login as a Root admin
2. Create Project
3. Click on the created project 
4. Update the `step` of the project

**Expected Result**
Project should be updated.

**Actual Result**
Getting `Cannot read property 'status' of undefined` error while update any field of project.
See video -  https://drive.google.com/file/d/1jswSE3OTwrW_6YoSaQ1OQF1Ef_ugjPIY/view?usp=drivesdk

cord-field# 1772f10d

**Comment by CarsonF** [comment]
Can you post the exception stacktrace?
