### ISSUE TITLE
createProject > Project is created with "Consultant" user role

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1461]
**Describe the bug**
createProject > Project is created with `Consultant` user role

**Steps to Reproduce**
1. Register the user with the `Consultant` role
2. Login
3. Click on `Create New Item` > `Project` > `Enter project data`
4. Click on the `Submit` button

**Expected Result**
Project should not be created with `Consultant` user role.

**Actual Result**
Project is created with `Consultant` user role
See video -  https://drive.google.com/file/d/1LtSKhH2BiTbZplpMrnPTxiqDJRmcPp20/view?usp=drivesdk

cord-field# 1772f10d

**Comment by iPiyushPatel** [comment]
@sethmcknight @CarsonF @michaelmarshall 
As per [CORD Field v3 Beta Sheet](https://docs.google.com/spreadsheets/d/1MxpNMTEkhSYptWsJxTy9RdF9kipxYm2jDFzAP-8GhdY/edit#gid=1413317393), a user with a `consultants` role is not allowed to create a project.

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown change is merged in. See https://github.com/SeedCompany/cord-api-v3/pull/1537

**Comment by ParkeBrown** [comment]
@iPiyushPatel would you test to confirm bug is resolved?

**Comment by iPiyushPatel** [comment]
@ParkeBrown 
I've checked on the latest master and It's working fine.
