### ISSUE TITLE
BUG: New users can see too much info on other users.

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1470]
New user without any roles was able to see a list of people and view people details. A user without any roles should not be able to see any People info.

More details: SeedCompany/management#1

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466753394) by [Unito](https://www.unito.io)

**Comment by ParkeBrown** [comment]
@michaelmarshall @sethmcknight very little detail here but is this still valid with all the permission changes since then?
