### ISSUE TITLE
updateBudget > Getting "You do not have permission to update this file" error while input has a "universalTemplateFile" field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1471]
**Describe the bug**
updateBudget > Getting `You do not have permission to update this file` error while input has a `universalTemplateFile` field

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Budget should be updated with `universalTemplateFile` field.

**Actual Result**
Getting `You do not have permission to update this file` error while input has a `universalTemplateFile` field.
See video - https://drive.google.com/file/d/1LBCZLh55Is-vTpO0zJQPPkFF4-yjNQ_j/view?usp=drivesdk

**GraphQL Query (updateBudget) :**
![image](https://user-images.githubusercontent.com/5212585/97865655-90ce3180-1d30-11eb-8847-269147a0cd0e.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "You do not have permission to update this file",
            "extensions": {
                "codes": [
                    "Unauthorized",
                    "Input",
                    "Client"
                ],
                "status": 403,
                "field": "budget.universalTemplateFile",
                "code": "Unauthorized",
                "exception": {
                    "message": "You do not have permission to update this file",
                    "stacktrace": [
                        "at FileService.updateDefinedFile (components\\file\\file.service.ts:412:13)",
                        "at BudgetService.update (components\\budget\\budget.service.ts:410:22)",
                        "at BudgetResolver.updateBudget (components\\budget\\budget.resolver.ts:92:20)"
                    ]
                }
            },
```
**Query and Input File**
[UpdateBudgetPermissionIssue.txt](https://github.com/SeedCompany/cord-api-v3/files/5474894/UpdateBudgetPermissionIssue.txt)

CordAPIV3# 5a708dc2

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown and @iPiyushPatel just checked into this, and the error is different now. It says "Already uploaded" as the error. I'm not sure, but I think it's behaving as expected...? I just don't know about the business rules well enough to be sure. 
<img width="1440" alt="Screen Shot 2020-12-16 at 4 05 09 PM" src="https://user-images.githubusercontent.com/15220335/102412382-03316300-3fb9-11eb-9cad-1cdbd3b04e86.png">

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel Can you verify that the error is different now?

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel could you check my above comments when you get a chance?

**Comment by iPiyushPatel** [comment]
Hi, @elisabeth-sorrell

This is an expected error if you are trying to update the budget with the same `uploadId` you have used for creating a budget and I've verified on the latest develop ad57fe94 branch and it's working fine.

See video: https://drive.google.com/file/d/1L1_gqb_-OIfCnHsOMpHjJc9UMesFa_KF/view?usp=drivesdk

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel cool. I'll put this into Sprint Closed, then.
