### ISSUE TITLE
updateProduct > Getting "You do not have permission to update property: mediums" error while input has a "mediums" field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1472]
**Describe the bug**
updateProduct > Getting `You do not have permission to update property: mediums` error while input has a `mediums` field

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Product should be updated with the `mediums` field.

**Actual Result**
Getting `You do not have permission to update property: mediums` error while input has a `mediums` field
See video - https://drive.google.com/file/d/153WJS86JemiIwnccZQspQaA9TknzeBBu/view?usp=drivesdk

**Note:** I can replicate the same issue for the `purposes` and `methodology` field.

**GraphQL Query (updateProduct ) :**
![image](https://user-images.githubusercontent.com/5212585/97866255-9d06be80-1d31-11eb-8cce-7a6252669412.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "You do not have permission to update property: mediums",
            "extensions": {
                "codes": [
                    "Unauthorized",
                    "Input",
                    "Client"
                ],
                "status": 403,
                "field": "mediums",
                "code": "Unauthorized",
                "exception": {
                    "message": "You do not have permission to update property: mediums",
                    "stacktrace": [
                        "at DatabaseService.sgUpdateProperty (core\\database\\database.service.ts:209:13)",
                        "at DatabaseService.sgUpdateProperties (core\\database\\database.service.ts:130:17)",
                        "at ProductService.update (components\\product\\product.service.ts:478:12)",
                        "at ProductResolver.updateProduct (components\\product\\product.resolver.ts:102:21)"
                    ]
                }
            },
```

**Query and Input File**
[UpdateProductPermissionIssue.txt](https://github.com/SeedCompany/cord-api-v3/files/5474851/UpdateProductPermissionIssue.txt)

CordAPIV3# 5a708dc2

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel just tested this manually and it looks successful. @ParkeBrown if it's okay, I'm going to put this into review for @iPiyushPatel to confirm that it is fixed.

**Comment by iPiyushPatel** [comment]
@elisabeth-sorrell @ParkeBrown 
I've verified on the latest develop b2c47c7d branch and it's working fine.
