### ISSUE TITLE
login > Unable to log in "Root Admin"

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1488]
**Roles:**  Administrator

**Describe the bug**
login > Unable to LogIn by `Root Admin`

**Steps to Reproduce**
1. Login with `Root Admin` credential i.e. 
ID: devops@tsco.org
Password: admin

**Expected Result**
`Root Admin` should be able to log in.

**Actual Result**
Unable to log in `Root Admin`.
See video -  https://drive.google.com/file/d/1lcWAVJNCzfxmNuh-vMerudkWGQ3JdJNg/view?usp=drivesdk

**Env:** beta

cord-field# ae2afea7

**Comment by CarsonF** [comment]
@iPiyushPatel if you are using data from a dump file the admin password could be different.

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
I'm NOT using a dump file. I'm spinning up the Docker DB instance and using it. Am I missing anything here?

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel This is working now on latest development branch. I believe that it has something to do with https://github.com/SeedCompany/cord-api-v3/issues/1496. When the constraint error is reached, the root/admin user is not auto-created upon start up. The workaround for now is to keep restarting the app until the constraint error doesn't show up. Can you verify when you get a chance?

@ParkeBrown putting this into QA/Review until it's verified.

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell @ParkeBrown 
I've verified on the latest develop a99ebf10 branch and it's working fine.
