### ISSUE TITLE
users > Getting "Could not find user" error 

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1489]
**Roles:**   Administrator, ProjectManager, RegionalDirector, FieldOperationsDirector, Consultant, FinancialAnalyst, Intern

**Describe the bug**
users > Getting `Could not find user` error 

**Steps to Reproduce**
1. Register and login user with `ProjectManger` User role
2. Click on the `People` list and select user 

**Expected Result**
User detail should be displayed.

**Actual Result**
Getting `Could not find user` error.
See video -  https://drive.google.com/file/d/1FihsJYsXkFXI--7HhZ6i9psMSY5giW26/view?usp=drivesdk

**Env:** beta

cord-field# ae2afea7

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel just confirmed that this is working on latest develop branch. Will put into review for you to confirm when you have time.
FYI, @ParkeBrown

**Comment by iPiyushPatel** [comment]
@elisabeth-sorrell @ParkeBrown 
I can not check this issue due to an error on cord-field UI with the latest develop branch b2c47c7d while setting up the environment.

**Comment by iPiyushPatel** [comment]
@elisabeth-sorrell @ParkeBrown 
I can not check this issue due to an error on cord-field UI with the latest develop branch b2c47c7d while setting up the environment.

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel I think Carson resolved the cord-field environment setup issue. Could you try verifying again when you get a chance?

**Comment by iPiyushPatel** [comment]
Hi, @elisabeth-sorrell @ParkeBrown 
I've verified on the latest develop a99ebf10 branch and it's working fine.

**Comment by elisabeth-sorrell** [comment]
Putting into sprint closed, then
