### ISSUE TITLE
register > Getting "Cannot return null for non-nullable field SecuredOrganizationList.canCreate." error while query output has field  "organizations"

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1501]
**Roles:** ProjectManager

**Describe the bug**
register > Getting `Cannot return null for non-nullable field SecuredOrganizationList.canCreate.` error while query output has field  `organizations`

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
User should be registered with the `organizations` field.

**Actual Result**
Getting `Cannot return null for non-nullable field SecuredOrganizationList.canCreate.` error while query output has field  `organizations`.
See video - https://drive.google.com/file/d/14pHJZ5-CO5-YMksuy_7edSs7ngKM6uhP/view?usp=drivesdk

**Note:** I can replicate the same issue for `unavailabilities` and `education` field
 
**GraphQL Query (register ):**
![image](https://user-images.githubusercontent.com/5212585/98081471-28509300-1e9d-11eb-8e2d-bff251be65d2.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Cannot return null for non-nullable field SecuredOrganizationList.canCreate.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "codes": [
                    "INTERNAL_SERVER_ERROR",
                    "GraphQL",
                    "Server"
                ]
            },
            "locations": [
                {
                    "line": 111,
                    "column": 9
                }
            ],
            "path": [
                "register",
                "user",
                "organizations",
                "canCreate"
            ]
        }
    ],
```

**Query and Input File**
[RegistrationIssue.txt](https://github.com/SeedCompany/cord-api-v3/files/5486134/RegistrationIssue.txt)

CordAPIV3# 1e9b4ed8

**Comment by frankyma** [comment]
cannot reproduce, tried on clean db and latest master `29f823ab`, with the values in the registrationIssue.txt.  @iPiyushPatel  Can you retry on latest master?  I think we pushed in some fixes this morning.

If still an issue please give STR from clean db.  Thanks
<img width="1483" alt="Screen Shot 2020-11-04 at 2 58 28 PM" src="https://user-images.githubusercontent.com/43487134/98176873-41ae0b00-1eae-11eb-86cb-a361874b2b57.png">

**Comment by iPiyushPatel** [comment]
@frankyma 
After Clearing DB and restarting the server, It's working fine on the latest master 29f823ab.
