### ISSUE TITLE
ProjectManager is not allowed to advance the project from "Concept Approval" step

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1514]
**Roles:** ProjectManager

**Describe the bug**
ProjectManager is not allowed to advance the project from `Concept Approval` step.

**Steps to Reproduce**
1. Login as `ProjectManager`
2. Create New Project and go to created Project's detail page.
3. Click on `Early Conversation` > `Submit for Concept Approval`
4. Navigate Back to Project detail page by clicking the button from redirected page.
5. Click on `Pending Concept Approval`

**Expected Result**
ProjectManager should be allowed to advance the project from `Concept Approval` step.

**Actual Result**
ProjectManager is not allowed to advance the project from `Concept Approval` step.
See video - https://drive.google.com/file/d/1LesqrtcLmkPKq11ZAJ9r2llPOZ-zrK6d/view?usp=drivesdk

CordAPIV3# 29f823ab

**Comment by sethmcknight** [comment]
@iPiyushPatel this is actually functioning as expected.

Only these roles should be able to move a Project from `Pending Concept Approval`

- `Regional Director`
- `Field Operations Director`
- `Administrator`

**Comment by iPiyushPatel** [comment]
@sethmcknight @ParkeBrown 

Ok, got it. But I was following sheet shared by Park [Beta Tester Checklist](https://docs.google.com/spreadsheets/d/1MxpNMTEkhSYptWsJxTy9RdF9kipxYm2jDFzAP-8GhdY/edit#gid=1413317393), so thought it's a bug. Please suggest if any.

**Comment by elisabeth-sorrell** [comment]
This is working in accordance to https://github.com/SeedCompany/cord-api-v3/wiki/Project-Workflows. 
@sethmcknight @ParkeBrown if that's correct, we can close this issue.
Putting into QA/Review until I hear back.

**Comment by iPiyushPatel** [comment]
@elisabeth-sorrell @ParkeBrown 
I can not check this issue due to an error on cord-field UI with the latest develop branch b2c47c7d while setting up the environment.

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel Hey, do you think you could try verifying again? I think the environment issue with cord-field UI is resolved.

**Comment by iPiyushPatel** [comment]
Hi, @elisabeth-sorrell @ParkeBrown 
I've verified on the latest develop a99ebf10 branch and it's working fine.

**Comment by elisabeth-sorrell** [comment]
Putting into sprint closed then
