### ISSUE TITLE
[BUG] Set FinancialReportingType on Partner

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1517]
Administrator, Controller and Financial Analyst roles should be able to update the Financial Reporting Types on Partners.

Currently it looks like the update is accepted but the data is never updated/changed.

**Comment by zkhin** [comment]
@sethmcknight I cannot reproduce this bug on the latest master. Can you write the steps in detail to repro? Thanks

**Comment by elisabeth-sorrell** [comment]
@sethmcknight Tried to reproduce, as well. created users with controller, financial analyst, and with default admin user created a partner with each. Toggled the FinancialReporting type of each and checked with each user. The only time I wouldn't be able to see the update was when I didn't refresh the page correctly. Any way to check if this is still an issue?
FYI, @ParkeBrown

**Comment by sethmcknight** [comment]
@elisabeth-sorrell thanks for reminding me about this today! I need to get access to the beta environment again and then I'll check on this.

**Comment by michaelmarshall** [comment]
@sethmcknight we've merged some PRs. please verify this is done.

**Comment by sethmcknight** [comment]
@elisabeth-sorrell @michaelmarshall yes, it looks like this has been resolved.
