### ISSUE TITLE
Set Engagement Status when Project Status changes.

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1527]
When a Project is In Development, the Engagement Status should be In Development. Users should not be able to change the Engagement Status.

When a Project is changed to Active, update the Engagement status' to Active.

**Comment by zkhin** [comment]
@sethmcknight @CarsonF @michaelmarshall if the Project is changed to `Terminated` or `Completed`, the Engagement's status should be the same as the Project's status?

**Comment by CarsonF** [comment]
Maybe only if the engagement isn't finished. If an engagement was completed and then later the project terminated, I would expect the engagement to stay completed.
