### ISSUE TITLE
Bug: modifiedAt perm not letting some roles advance project step

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1530]
Jim Schmidt in beta ran into this error. I believe his role is Financial Analyst.
![LackPermission](https://user-images.githubusercontent.com/1165460/98413592-80bf9600-203f-11eb-8744-26385c09b9ef.jpg)
We need to pinpoint which `modfiedAt` property is throwing the error. There are several base nodes with this property.

Let me know which base node and I can troubleshoot in the DB proc.

**Comment by zkhin** [comment]
@michaelmarshall In the project workflow e2e, I can reproduce the perm issue.
```
You do not have permission to update property: step
```
https://github.com/SeedCompany/cord-api-v3/blob/master/test/project-workflow.e2e-spec.ts#L369~L373
Right now it's logging in with `FinancialAnalyst` and `Controller` roles, but if we use only the `FinancialAnalyst` role, it will fail.

Like below:
```
await login(app, {
   email: financialAnalyst.email.value,
   password,
});
await changeProjectStep(app, project.id, ProjectStep.FinalizingProposal);
```
Even if the `financialAnalyst` is added to that project, the same perm error occurs.

**Comment by zkhin** [comment]
@michaelmarshall I can repro this issue following the below steps
- register FA user with only `FinancialAnalyst ` role.
- register PM user with only `ProjectManager` role.
- create a new project.
- add FA to the project.
- log in as FA user.
- read project.
The `step.canEdit` value is always `false`.
