### ISSUE TITLE
"Intern", "ProjectManager" and "Consultant" is not allowed to advance the project from `Consultant Endorsement` step.

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1533]
**Roles:** Intern, Project Manager, Consultant

**Describe the bug**
`Intern`, `ProjectManager` and `Consultant` is not allowed to advance the project from `Consultant Endorsement` step.

**Steps to Reproduce**
1. Login as `ProjectManager`,`Intern`
2. Create New Project and go to created Project's detail page
3. Click on `Early Conversation` > `Submit for Concept Approval`
4. Navigate Back to Project detail page by clicking the button from redirected page.
5. Login as `Administrator` and search project created by `Intern` and `Project Manager`
6. Click on `Pending Concept Approval` >`Approve`
7. Click on `Prep For Consultant Endorsement` > `Submit for Consultant Endorsement`
8. Login as `ProjectManager` , `Intern`
9. Click on `Pending Consultant Endorsement`

**Expected Result**
`Intern`, `ProjectManager` and `Consultant` should be allowed to advance the project from `Consultant Endorsement` step.

**Actual Result**
`Intern`, `ProjectManager` and `Consultant` is not allowed to advance the project from `Consultant Endorsement` step.
See video -  https://www.awesomescreenshot.com/video/1664602?key=ac6476b9fbaeb8a671f6dc7d4464a2b4

CordAPIV3# 13948548

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel @ParkeBrown according to this doc, https://github.com/SeedCompany/cord-api-v3/wiki/Project-Workflows, only a consultant or consultant manager (and of course, the default root user who can do anything) are allowed to advance the project step from `pending consultant endorsement` to `preparing for financial endorsement`. Just verified that that's working as expected in latest dev branch. 
Please verify and let me know. Moving this to QA/Review

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell @ParkeBrown 
I could not check this issue because of https://github.com/SeedCompany/cord-api-v3/issues/1585.

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown Okay, putting this back into backlog for now until I get the blocking issue fixed. Not sure if I'll be putting it in the right column though...

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel just verified this again, due to https://github.com/SeedCompany/cord-api-v3/issues/1585 magically working again.

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell 
I've verified again and I can still replicate the issue. But I see there is no new code pushed to the Develop branch after Fri. If you've made any changes, can you push/merge to Develop, please?

thanks

**Comment by ParkeBrown** [comment]
@elisabeth-sorrell catching up on my mentions. Sorry. Any thoughts on the above?

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown this issue is blocked by issue https://github.com/SeedCompany/cord-api-v3/issues/1585, which I think is working correctly. We're currently in the process of trying to smooth out confusion on that one. I think once we have it settled for issue https://github.com/SeedCompany/cord-api-v3/issues/1585, we can take a look at this again.

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel since #1585 is resolved, could you verify if this is working when you get a chance? thanks!

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell 
I have verified on latest  f0d18b81 develp 
As per [Wiki](https://github.com/SeedCompany/cord-api-v3/wiki/Project-Workflows#step-4--pending-consultant-endorsement) `Intern` and `ProjectManager` is not able to perform the step from `pending consultant endorsement` to `preparing for financial endorsement` 
For the `Consultant` user Getting `Current user cannot read budget thus record sync cannot continue` error
**See Video:** https://drive.google.com/file/d/1Q0yAn2wPf_ZmhAg_WujM0DomZl0MoPI7/view?usp=sharing

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown I believe the bug mentioned by Piyush is covered by https://github.com/SeedCompany/cord-api-v3/issues/1538, so I'll go ahead and put this into Sprint Closed.
