### ISSUE TITLE
Getting "Current user cannot read thus record sync cannot continue" error when Consultant "EndorsePlan" Project and next step is displayed on reload the page

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1538]
**Roles:** Consultant

**Describe the bug**
Getting `Current user cannot read thus record sync cannot continue` error when Consultant `EndorsePlan` Project and next step is displayed on reload the page

**Steps to Reproduce**
1. Login as Consultant user.
2. Create New Project and go to created Project's detail page.
3. Login as `admin` and go to Project detail page.
4. Advance project step upto `SubmitforConsultantEndorsement`.
5. Login as `Consultant ` and go to Project detail page.
6. Click on `EndorsePlan`.
7. Refresh Page.

**Expected Result**
Consultant should be allowed to advance the project from `EndorsePlan` step without error.

**Actual Result**
Getting `Current user cannot read thus record sync cannot continue` error when Consultant `EndorsePlan` Project and next step is displayed on reload the page
See video - https://www.awesomescreenshot.com/video/1679517?key=6b0d3c229dc908296128d1c1e8500013

CordAPIV3# 3f519f5c

**Comment by michaelmarshall** [comment]
The way a handler query is written requires certain permissions on budgets when a project step change takes place.
