### ISSUE TITLE
[BUG] Department ID should be 5 digits when calculated, not 6.

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1542]
When calculating the Department ID, we are currently assigning a 6 digit number starting with the Funding Account number (eg. #NNNNN). 

The Department ID needs to be a 5 digit number in total, starting with the Funding Account number (eg. #NNNN).

**Comment by zkhin** [comment]
@CarsonF I think we should add a validation decorator for the `accountNumber` in `FundingAccount` and that should be in this range - [0, 9]

**Comment by CarsonF** [comment]
Sure. I said previously to not be so strict, but I think it's ok now.

Is that the reason the the department ID was 6 digits or was it another reason?

**Comment by zkhin** [comment]
I investigated the `set-department-id.handler` and confirmed that it's because of `accountNumber`. 
I am sure that the `nextId` is 4 digit here.
https://github.com/SeedCompany/cord-api-v3/blob/master/src/components/project/handlers/set-department-id.handler.ts#L53

**Comment by CarsonF** [comment]
All of the funding account numbers current in beta are 1 digit. @sethmcknight you were seeing this in beta?

**Comment by sethmcknight** [comment]
> All of the funding account numbers current in beta are 1 digit. @sethmcknight you were seeing this in beta?

@CarsonF yes, in Beta. example: 5.00001. So it looks like it's putting 5 digits after the funding account digit.

**Comment by CarsonF** [comment]
@zkhin That looks like we are getting `5.0` instead of `5`. Can you fix?

**Comment by zkhin** [comment]
@zkhin Sure, I am investigating the query now.
