### ISSUE TITLE
mutation createFundingAccount > Getting "accountNumber must not be greater than 9" error even if "accountNumber" field length is <=9

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1545]
**Roles:** ProjectManager

**Describe the bug**
mutation createFundingAccount > Getting `accountNumber must not be greater than 9` error even if `accountNumber` field length is <=9

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
fundingAccount should be created.

**Actual Result**
Getting `accountNumber must not be greater than 9` even input field `accountNumber` have a valid value.
See video - https://drive.google.com/file/d/1K1_CpzbhBuBohEf_d9OWWNVOivLjI4LT/view?usp=drivesdk

**GraphQL Query ( createFundingAccount):**
![image](https://user-images.githubusercontent.com/5212585/99056118-d821b100-25bf-11eb-9499-eadce4a76991.png)

**Query and Input File**
[FundingAccountIssue.txt](https://github.com/SeedCompany/cord-api-v3/files/5535875/FundingAccountIssue.txt)

**GraphQL Response:**
```
{
    "errors": [
        {
            "message": "Input validation failed",
            "extensions": {
                "codes": [
                    "Validation",
                    "Client"
                ],
                "status": 400,
                "errors": {
                    "fundingAccount.accountNumber": {
                        "max": "accountNumber must not be greater than 9"
                    }
                },
                "code": "Validation"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createFundingAccount"
            ]
        }
    ],
```
CordAPIV3# 8c61fd8c

**Comment by zkhin** [comment]
@iPiyushPatel `accountNumber` should be in [0, 9]

**Comment by iPiyushPatel** [comment]
Hi @zkhin 
Sorry, I didn't get you. You mean to say it's value should have max 10 chars count? otherwise, as it's a number so always be in 0-9 :) 
Please suggest.
Thanks,

**Comment by iPiyushPatel** [comment]
Hi @sethmcknight @zkhin @michaelmarshall 
I've verified on latest develop 03765d75  and still replicate the issue, Attaching the video for reference. Reopening the task. Thanks! 
See video : 

https://user-images.githubusercontent.com/5212585/113818748-deded980-9795-11eb-96f2-a0a1abac5277.mp4

**Comment by sethmcknight** [comment]
@iPiyushPatel unfortunately I can't view the video.

To clarify, the `accountNumber` for a  `fundingAccount` must be a single digit from 0 to 9. No other numbers are allowed as the `accountNumber`.

Does that resolve this to where we can close it or is there another issue?
