### ISSUE TITLE
Getting `Field "status" of type "SecuredEngagementStatus!" must have a selection of subfields. Did you mean "status { ... }"?" error while open the project

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1551]
**Roles:** ProjectManager ,Admin ,Controller, RegionalDirector ,Intern ,FinancialAnalyst ,FieldOperationsDirector

**Describe the bug**
Getting `Field "status" of type "SecuredEngagementStatus!" must have a selection of subfields. Did you mean "status { ... }"?` error while opening the project

**Steps to Reproduce**
1. Login as ProjectManager.
2. Create New Project and go to the created Project's listing page.
3. Open the Created project by the Project manager.

**Expected Result**
Project should be open without error.

**Actual Result**
Getting `Field "status" of type "SecuredEngagementStatus!" must have a selection of subfields. Did you mean "status { ... }"?` error while opening the project
See video - https://drive.google.com/file/d/11DB9oSGjp98iR0MGTevhcJoYbQoEAHT1/view?usp=sharing

CordAPIV3# 73f6e558

**Comment by CarsonF** [comment]
@iPiyushPatel The `status` field changed to secured.
```gql
status {
  value
  ...
}
```
