### ISSUE TITLE
Getting "Current user cannot read budget thus record sync cannot continue" error while entering "MOU" dates

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1553]
**Roles:** Consultant

**Describe the bug**
Getting `Current user cannot read budget thus record sync cannot continue` error while entering `MOU` dates

**Steps to Reproduce**
1. Login as Consultant.
2. Create New Project and go to the created Project's listing page.
3. Open the Created project by the Consultant.
4. Enter `MOU` dates

**Expected Result**
Project should be updated with entered `MOU` dates.

**Actual Result**
Getting `Current user cannot read budget thus record sync cannot continue` error while entering `MOU` dates.
See video - https://drive.google.com/file/d/1Q-FpclHPw6wnzMTl3r8x9roEIZMqnaSb/view?usp=drivesdk

**Note:** I can replicate the same issue on `High sensitivity`, `Location and Field region`, `Estimated submission date` field

CordAPIV3# 73f6e558

**Comment by sethmcknight** [comment]
This should be resolved.
