### ISSUE TITLE
Users have read permissions when should be a member

### ISSUE THREAD

**Issue by elisabeth-sorrell** [SeedCompany/cord-api-v3#1555]
## Current Behavior
Users have read permissions on entities objects when they should only have read permissions if they're a member or added to that object. For instance, a user with the Role 'Consultant' that is yet assigned to a project can read a project card whether they're a member or not.

This behavior only happens when the user in question is created after the project. If the 'Consultant' user were created before the project, then we get expected behavior.

## Expected Behavior
Users should only be able to read an object only if they're a member of that object. In this case, it's Project, but I'm suspecting that it's for other objects too.

## Role(s), if applicable
[Consultant]... I'm assuming that this happens for other roles where they only have read if they're a member

## Steps to Reproduce
1. Create a project (under a different user), get the project's id
2. Create a user with the role of 'Consultant'
3. logged in as the consultant go to the [base_url]/projects/[project_id_that_you_got_earlier]

## Screenshots

| Tech      | Version / Name |
| --------- | -------------- |
| API       |                |

**Comment by sethmcknight** [comment]
Closing due to new authorization system
