### ISSUE TITLE
Terminate not an option for Engagement Status

### ISSUE THREAD

**Issue by elisabeth-sorrell** [SeedCompany/cord-api-v3#1557]

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown changes are merged in. See https://github.com/SeedCompany/cord-api-v3/pull/1558

**Comment by ParkeBrown** [comment]
@iPiyushPatel would you test to confirm bug is resolved?

**Comment by iPiyushPatel** [comment]
@ParkeBrown 
I've checked on the latest master ff394e1b for API as well as FE and It's working fine.
