### ISSUE TITLE
Query Performance Refactor

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1560]
- [x] Update session object and query to return the global roles a user has.
- [x] Write function that takes a session object and base node type and returns the permission list for that user on that object.
- [ ] Write new abstraction suite that all service's read function will use. The goal is to remove the knowledge of security groups and permissions from the calling service.

**Comment by elisabeth-sorrell** [comment]
@CarsonF  Okay, have a branch `sessionObjectWithRoles` for attaching a `DbRole` array of the roles that the user has with the session object. I can go ahead and start on the second bulletin.

**Comment by elisabeth-sorrell** [comment]
@CarsonF and @michaelmarshall I've added more changes for the second bullet point to the `sessionObjectWithRoles` branch and I also have a draft PR #1603
