### ISSUE TITLE
query projects > Getting "Not Found" error after creating the "Translation" Project

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1564]
**Roles:** ProjectManager 

**Describe the bug**
query projects > Getting `Not Found` error after creating the `Translation` Project

**Steps to Reproduce**
1. Login as a project manager
2. Create a project with a `Translation` type 
3. Hit the request of `query projects`

**Expected Result**
Projects listing should be returned.

**Actual Result**
Getting `Not Found` error after creating the `Translation` Project
See video - https://drive.google.com/file/d/1UsUnubKqZcN1QSqV2MKPGObEeSZfk76e/view?usp=drivesdk

**GraphQL Query ( projects ):**
![image](https://user-images.githubusercontent.com/5212585/100452161-9b38dc80-30de-11eb-8b54-3cfa4bdba730.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Not Found",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "name": "NotFoundException",
                    "status": 400,
                    "stacktrace": [
                        "at first (components\\file\\file.repository.ts:535:11)",
                        "at FileRepository.getBaseNodeBy (components\\file\\file.repository.ts:140:12)",
                        "at FileRepository.getBaseNodeById (components\\file\\file.repository.ts:43:12)",
                        "at FileService.getFileNode (components\\file\\file.service.ts:80:18)",
                        "at FileService.getDirectory (components\\file\\file.service.ts:54:18)",
                        "at ProjectService.getRootDirectory (components\\project\\project.service.ts:1126:14)",
                        "at ProjectResolver.rootDirectory (components\\project\\project.resolver.ts:179:12)"
                    ]
                },
                "codes": [
                    "INTERNAL_SERVER_ERROR",
                    "Server"
                ]
            },
            "locations": [
                {
                    "line": 2330,
                    "column": 7
                }
            ],
            "path": [
                "projects",
                "items",
                1,
                "rootDirectory"
            ]
        }
    ],
```

**Query and Input File**
[NotFoundErrorInProjects.txt](https://github.com/SeedCompany/cord-api-v3/files/5607931/NotFoundErrorInProjects.txt)

CordAPIV3# 73f6e558

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel HI! I think this is working now. Can you verify when you have a chance?

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell 
I've tested on the develop ad57fe94 and it's working fine.

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel thanks! @ParkeBrown putting into Sprint Closed since it's been verified.
