### ISSUE TITLE
createProject > Getting "Cannot return null for non-nullable field Unavailability.canDelete" error for "canDelete" property of "unavailabilities" present in query output

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1566]
**Roles:** ProjectManager 

**Describe the bug**
createProject > Getting `Cannot return null for non-nullable field Unavailability.canDelete` error for `canDelete` property of `unavailabilities` present in query output

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Project should be created.

**Actual Result**
Getting `Cannot return null for non-nullable field Unavailability.canDelete` error for `canDelete` property of `unavailabilities` present in query output
See video - https://drive.google.com/file/d/1YQiN_HJXFWKHv4q-_ufl4yyfBCLts8-4/view?usp=drivesdk

**GraphQL Query ( createProject ):**
![image](https://user-images.githubusercontent.com/5212585/100597043-f0653000-3322-11eb-9bc5-2c25f5f64ca7.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Cannot return null for non-nullable field Unavailability.canDelete.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "codes": [
                    "INTERNAL_SERVER_ERROR",
                    "GraphQL",
                    "Server"
                ]
            },
            "locations": [
                {
                    "line": 452,
                    "column": 23
                }
            ],
            "path": [
                "createProject",
                "project",
                "fieldRegion",
                "value",
                "fieldZone",
                "value",
                "director",
                "value",
                "unavailabilities",
                "items",
                0,
                "canDelete"
            ]
        }
    ],
```

**Query and Input File**
[CanDeleteErrorCreateProject.txt](https://github.com/SeedCompany/cord-api-v3/files/5615334/CanDeleteErrorCreateProject.txt)

CordAPIV3# 73f6e558

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel Not getting the error for me now, tried with users `root` and `field operations director`. Can you verify when you get a chance? Thanks!

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell 
Verified on latest develop and getting `Cannot return null for non-nullable field SecuredOrganizationList.canCreate.` error when output query has `canCreate` field.
See video:https://drive.google.com/file/d/1kTGXCnpbIEB-FPpQp0zCZ_I33MBFyaHL/view?usp=drivesdk

**Comment by elisabeth-sorrell** [comment]
PR: https://github.com/SeedCompany/cord-api-v3/pull/1589

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel Can you verify when you get a chance? code is merged in in latest develop branch

**Comment by iPiyushPatel** [comment]
Hi, @elisabeth-sorrell 
I have verified on the latest develop 080a4abd and still replicate the same issue

**See Snap:** 
![image](https://user-images.githubusercontent.com/5212585/103741013-5037b080-501e-11eb-9c77-217bb82bc0e4.png)

**Query file**
[CreateProjectQuery.txt](https://github.com/SeedCompany/cord-api-v3/files/5774796/CreateProjectQuery.txt)

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel hmmmmmm, it's working for me.... I even added `canDelete` under `Unavailabilites{items...{ }}` and it still worked. Not sure what is going on.

**Comment by iPiyushPatel** [comment]
Hi, @elisabeth-sorrell
I have verified on the latest develop e5dbd13f and it's working fine.

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown putting this into Sprint Closed since it's verified and working.

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell 
I have replicated this issue on the latest develop 2173ced5
See Video: https://drive.google.com/file/d/1Z0jLNKZEzFJKyT0-NZmOGemnzxCD1aFd/view?usp=drivesdk

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel looks to me that this could probably be in another ticket, as it's in list unavailabilities after creating. I'll make a ticket for it.

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel and @ParkeBrown created https://github.com/SeedCompany/cord-api-v3/issues/1608 to cover for the above error that Piyush mentioned.
