### ISSUE TITLE
Internship > Getting `Variable "$input" got invalid value "LanguageSoftwareSupportSpecialist" at "input.engagement.position"; Value "LanguageSoftwareSupportSpecialist" does not exist in "InternshipPosition" enum.` error while select intern positon for admin user

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1572]
**Roles:** Admin

**Describe the bug**
Internship > Getting `Variable "$input" got invalid value "LanguageSoftwareSupportSpecialist" at "input.engagement.position"; Value "LanguageSoftwareSupportSpecialist" does not exist in "InternshipPosition" enum.` error while select intern position for admin user

**Steps to Reproduce**
1. Login root user
2. Create a project with `internship`
3. Create a new internship with admin user
4. Select the intern position

**Expected Result**
Internship position should be selected.

**Actual Result**
Getting `Variable "$input" got invalid value "LanguageSoftwareSupportSpecialist" at "input.engagement.position"; Value "LanguageSoftwareSupportSpecialist" does not exist in "InternshipPosition" enum.` error while select intern positon for admin user.
See video - https://drive.google.com/file/d/1PTnHf_-XoHAsQCMDYZi9C0YOy3Kq1qjh/view?usp=drivesdk

CordAPIV3# 73589b84

**Comment by CarsonF** [comment]
Yeah the positions got updated with #1570
