### ISSUE TITLE
[BUG] Sort Projects by Name with Non-Roman Characters

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1580]
When trying to sort Project by Name the results do not appear to sort correctly.

When sorting by Name non-roman characters do not show up where expected (e.g. Ñ should show up after N, not after Z)

**Comment by ParkeBrown** [comment]
@iPiyushPatel would you test to confirm bug is resolved?

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown I can't test this issue as we've blocker issue already open: https://github.com/SeedCompany/cord-api-v3/issues/1563
Please advice.

**Comment by ParkeBrown** [comment]
Thank you, @iPiyushPatel. Linking this moves us a step forward. Feedback may need to come post launch items.

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel https://github.com/SeedCompany/cord-api-v3/issues/1563 changes have been merged in, so can you verify that this is working if you get a chance?

**Comment by iPiyushPatel** [comment]
Hi, @elisabeth-sorrell 
I have verified on the latest develop 080a4abd and it's working fine.
See Snap : 
![image](https://user-images.githubusercontent.com/5212585/103739808-254c5d00-501c-11eb-8ab8-c46c3f78463e.png)

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel awesome. @ParkeBrown putting this into Sprint Closed.
