### ISSUE TITLE
updatePartnership > Getting "Unable to create file version" error while the input field "uploadID" has a blank value

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1599]
**Roles:** ProjectManager

**Describe the bug**
updatePartnership > Getting `Unable to create file version` error while the input field `uploadID` has a blank value

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Better error/validation message should be returned.

**Actual Result**
Getting `Unable to create file version` error while the input field `uploadID` has a blank value.
See video - https://drive.google.com/file/d/1_vLOZLoNl7yCqaHwHGc3PVFYT_-sErym/view?usp=drivesdk

**Note:** I can replicate the same issue for `createInternshipEngagement` ,`createLanguageEngagement` module of `uploadID`

**GraphQL Query (updatePartnership ):**
![image](https://user-images.githubusercontent.com/5212585/105032098-4f6e3800-5a7c-11eb-91e6-6f8fe05f5e0a.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Unable to create file version",
            "extensions": {
                "codes": [
                    "Server"
                ],
                "status": 500,
                "code": "Server",
                "exception": {
                    "message": "Unable to create file version",
                    "stacktrace": [
                        "at FileService.createFileVersion (components\\file\\file.service.ts:278:13)",
                        "at FileService.updateDefinedFile (components\\file\\file.service.ts:459:7)",
                        "at PartnershipService.update (components\\partnership\\partnership.service.ts:425:5)",
                        "at PartnershipResolver.updatePartnership (components\\partnership\\partnership.resolver.ts:109:25)"
                    ]
                }
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "updatePartnership"
            ]
        }
    ],
```
**Query and Input File**
[UpdatePartnership issue.txt](https://github.com/SeedCompany/cord-api-v3/files/5835743/UpdatePartnership.issue.txt)

CordAPIV3# 8ab5e110

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel I think the error is different now. Can you confirm? I did a minimal partnership with blank ID and got this:
<img width="1402" alt="Screen Shot 2021-02-09 at 10 58 32 AM" src="https://user-images.githubusercontent.com/15220335/107399144-041cd780-6ac6-11eb-8cfc-d60da0f9f21b.png">

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell 
I've verified on latest develop be13e0d6 and it's working fine
See video: 

https://user-images.githubusercontent.com/5212585/107477500-d60ac680-6b9d-11eb-85d4-3e4b8ee650c4.mp4

**Comment by elisabeth-sorrell** [comment]
Closing since it's verified.
