### ISSUE TITLE
createPartnership > Getting "Internal server error" message when downloading the uploaded file

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1600]
**Roles:** ProjectManager

**Describe the bug**
createPartnership > Getting `Internal server error` message when downloading the uploaded file

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
The file should be download.

**Actual Result**
Getting `Internal server error` message when downloading the uploaded file.
See video - https://drive.google.com/file/d/1ZRWMRJgExfkHpjdaoVeN-mC_zNDwdR8A/view?usp=drivesdk

**GraphQL Query (createPartnership ):**
![image](https://user-images.githubusercontent.com/5212585/105179709-a55fe000-5b4f-11eb-9eaf-425de6f3ed4d.png)

**GraphQL response**
```
{
    "statusCode": 500,
    "message": "Internal server error"
}
```
CordAPIV3# e5dbd13f

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel I can't find the attached notepad file.... :\

**Comment by iPiyushPatel** [comment]
Hi, @elisabeth-sorrell  It was my bad, For the download file request there is no body parameters are present. So not attaching any notepad file for that. Thanks!

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel looks like it's working to me...? I did it manually, so not sure if I did it right. Here's a video
https://www.awesomescreenshot.com/video/2695164?key=e55c99c7c92821a70c29ee53c9e94d58

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel I think it's working now...? I went through the steps manually on latest develop of field, api, and docker db and got this.....

https://user-images.githubusercontent.com/15220335/107403675-05043800-6acb-11eb-8466-767c56646c13.mp4

**Comment by elisabeth-sorrell** [comment]
Of course, I think it's highly probable that I did it wrong. Just let me know

**Comment by iPiyushPatel** [comment]
Hi, @elisabeth-sorrell 
I've verified on latest develop be13e0d6 and it's working fine.
See video: 

https://user-images.githubusercontent.com/5212585/107488067-dfe7f600-6bac-11eb-9571-5c5ab321641c.mp4

**Comment by elisabeth-sorrell** [comment]
Awesome! closing since it's been verified....
