### ISSUE TITLE
Make the email field an optional field when creating a person. We should be able to come back and add an email to the person later.

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1610]
The email field is currently showing as required when creating a Person. If a user attempts to create a Person without an email address entered they get an error that it is required and are not allowed to create the person.

Users should be able to create a person with only a First Name and Last Name

**Comment by sethmcknight** [comment]
This appears to be reverted.

The email field is currently showing as required when creating a Person. If a user attempts to create a Person without an email address entered they get an error that it is required and are not allowed to create the person.

Users should be able to create a person with only a First Name and Last Name

**Comment by CarsonF** [comment]
Probably a UI change needed

**Comment by mosesintech** [comment]
While investigating another open issue, [I found that creating a new user without an email address would give me a Neo4j error](https://github.com/SeedCompany/cord-api-v3/issues/1822). The GraphQL schema doesn't care if there is an email address or not, but we have two database constraints for email addresses that would cause a database error if the email is not provided: 
```cql
CREATE CONSTRAINT ON (n:EmailAddress) ASSERT EXISTS(n.value)
CREATE CONSTRAINT ON (n:EmailAddress) ASSERT n.value IS UNIQUE
```
It looks like if we remove the first constraint, Neo4j will accept multiple null values for user emails.

**Comment by michaelmarshall** [comment]
I think our API is functioning as it should. Project managers can create a 'person' without creating a registered user. Let's have Carson attack this from a UI perspective first.

**Comment by ParkeBrown** [comment]
Clearing assignees as is backlog. Reassign and move if picking up.
