### ISSUE TITLE
P&P Status Not Updating in Cord Field

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1614]
Amy Easterline: "The PnP statuses are not being updated in Cord Field. Looks like the harvester is not working again. Please resolve soon since we are trying to monitor PnP migration status and some DevReps are trying to update investors on progress."

Halp Ticket #2109

**Comment by ParkeBrown** [comment]
Seth McKnight  11 minutes ago
Hmm, looks like it is working correctly now

**Comment by CarsonF** [comment]
Yeah it's running as we speak. Everyday at 6pm. However I'm changing it to midnight after the run finishes tonight
