### ISSUE TITLE
Update Roles

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1634]
We are refactoring code to now use the role definitions in the API repo instead of the DB repo. We need to update the API code with the properties from the role definitions in Java.

1. Look at the java role defs.
2. Update the ts role defs with the new properties.
3. Ensure any changes are reflected in the flowchart schema and spreadsheet schema by pinging Michael with the changes.

**Comment by elisabeth-sorrell** [comment]
Here's what I have so far from the Administrator role:

Changes for the Schema Doc

- Budget:
  - add property: ‘canDelete'
    -  Admin role: Read
  - Remove Budget*
  - Remove universalTemplateFileNode*
- BudgetRecord:
  - add property: ‘canDelete'
    - Admin role: Read
  - Remove partnership*
- Ceremony:
  - add property: ‘canDelete'
    - Admin role: Read
- Directory:
  - add property: ‘canDelete'
    - Admin role: Read
  - remove property: ‘parent’ -> only one parent in java.
  - remove property: ‘rootDirectory’*
- Education:
  - add property: ‘canDelete'
    - Admin role: Read
  - remove property: ‘education’*
- EthnologueLanguage:
  - add property: ‘canDelete'
    - Admin role: Read
- FieldRegion:
  - add property: ‘canDelete'
    - Admin role: Read
  - remove property: ‘region’*
  - rename property ‘zone’ with type ‘ZONE’ to ‘fieldZone’
- FieldZone:
  - add property: ‘canDelete'
    - Admin role: Read
  - remove property: ‘zone’*
- File
  - add property: ‘canDelete'
    - Admin role: Read
  - remove duplicate ‘parent’*
  - add property: ‘mimeType’
    - type: STRING
    - Admin role: Read, Write
- FileVersion
  - add property: ‘canDelete'
    - Admin role: Read
  - remove property: ‘category’*
- Film
  - add property: ‘canDelete’**
    - Admin role: Read
  - add property: ’scriptureReferences**
    - type: SCRIPTURE_RANGE
    - Admin role: ReadWrite
- FundingAccount
  - add property: ‘canDelete'
    - Admin role: Read
  - remove property: ‘fundingAccount’*
- InternshipEngagement
  - add property: ‘canDelete’**
    - Admin role: Read
  - add property: ‘communicationsCompleteDate’**
    - Admin role: ReadWrite
  - add property: ‘completeDate’**
    - Admin role: ReadWrite
  - add property: ‘disbursementCompleteDate’**
   - Admin role: ReadWrite
  - add property: ‘endDate’**
    - Admin role: ReadWrite
  - add property: ‘endDateOverride’**
    - Admin role: ReadWrite
  - remove property: ‘growthPlanNode’*
  - add property: ‘initialEndDate’**
    - Admin role: ReadWrite
  - add property: ‘lastReactivatedAt’**
    - Admin role: ReadWrite
  - add property: ‘lastSuspendedAt’**
    - Admin role: ReadWrite
  - change property: ‘methodology’ to ‘methodologies’
    - type: Enum List? —> in code, it’s SecuredEnumList type
  - add property: ’startDate’ 
    - Admin role: ReadWrite
  - add property: ’startDateOverride’
    - Admin role: ReadWrite
  - add property: ’statusModifiedAt’
    - Admin role: ReadWrite
  - add property: ‘modifiedAt’
    - Admin role: ReadWrite
  - add property: ’status’
    - Admin role: ReadWrite
- Language
  - add property: ‘canDelete’
    - Admin role: Read
  - remove property: ‘goals’*
  - remove property: ‘knownLanguage’*
  - remove property: ‘language’*
  - add property: ‘displayNamePronunciation’
    - Admin role: ReadWrite
  - add property: ‘hasExternalFirstScripture’
    - type: boolean
    - Admin role: ReadWrite
  - add property: ’tags’
    - type: String List? SecuredPropertyList in code
- LanguageEngagement
  - add property: ‘canDelete’
    - Admin role: Read
  - remove property: ‘ceremonyPlanned’*
  - remove property: ‘pnpNode’*
  - remove property: ‘projectEngagementTag’
  - change sentPrinting: ’sentPrintingDate’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ‘communicationsCompleteDate’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ‘completeDate’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ‘dispursementCompleteDate’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ‘endDate’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ‘endDateOverride’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ‘initialEndDate’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ‘lastReactivatedAt’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ‘lastSuspendedAt’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ’startDate’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ’startDateOverride’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ’statusModifiedAt’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ‘modifiedAt’
    - type: ‘DATE’
    - admin role: ReadWrite
  - add property: ’status’
    - type: ‘ENUM'
    - admin role: ReadWrite
  - add property: ‘historicGoal’
    - type: ’STRING'
    - admin role: ReadWrite
- LiteracyMaterial
  - add property: ‘canDelete’
    - Admin role: Read
  - add property: ’scriptureReferences’
    - type: ’SCRIPTURE_RANGE’
    - Admin Role: ReadWrite
- Location
  - add property: ‘canDelete’
    - admin role: Read
    - remove property: ‘markingLocation’*
    - remove property: ’nonPrimaryLocations’*
    - remove property: ‘primaryLocation’*
    - remove properties: ‘locations’ x2*
- Organization
  - add property: ‘canDelete’
    - admin role: Read
    - remove property: ‘organization’*
    - remove property: ‘organizations’*
- Partner
  - add property: ‘canDelete’
    - admin role: Read
    - remove property: ‘partner’*
    - remove property: ‘address’*
- Partnership
  - add property: ‘canDelete’
    - admin role: Read
  - remove property: ‘agreementNode’*
  - remove property: ‘comment’*
  - remove property: ‘mouNode’*
  - remove properties: ‘partnership’* x2
- Product
  - add property: ‘canDelete'
    - admin role: Read
  - change property: ‘methodologies’ to ‘methodology’
    - type: enum
  - add property: ’scriptureReferencesOverride
    - type: ’SCRIPTURE_RANGE’
    - admin role: ReadWrite
  - add property: ‘isOverriding’
    - type: ‘boolean’
    - admin role: ReadWrite
- Project
  - add property: ‘canDelete’
    - admin role: read
  - add property: ’sensitivity’
    - admin role: RW
    - type: enum
  - add property: ’stepChangedAt’
    - admin role: RW
    - type: DateTime
  - add property: ’tags’
    - admin role: RW
    - type: StringList? SecuredPropertyList type in API
  - add property: ‘financialReportReceivedAt’
    - admin role: RW
    - type: DateTime
- ProjectMember
  - add property: ‘canDelete’ 
    - admin role: read
  - remove property: ‘member’*
- Song
  - add property: ‘canDelete’
    - admin role: read
  - add property: ’scriptureReferences’
    - type: SCRIPTURE_RANGE
    - admin role: RW
- Story
  - add property: ‘canDelete’
     - admin role: read
  - add property: ’scriptureReferences’
     - type: SCRIPTURE_RANGE
    - admin role: read
- Unavailability
  - add property: ‘canDelete’
    - admin role: read
  - remove property: ‘unavailability’*
- User
  - add property: ‘canDelete’
    - admin role: read
  - remove property: ‘emailToken’*
  - remove property: ‘member’*
  - remove property: ‘password’*
  - remove property: ‘picture’*
  - remove property: ’skill’*
  - rename ’timeZone’ to ’timezone’
  - remove property: ’token’*
  - ? property ‘partners’ is in Java, but not API or schema. investigated the user service, and found that the partners are listed via the partner service, and can’t find partners as part of the DbUser or User object…. so, not sure what to do here.
- 


**Updates I suspect were made after java code was written**
- defaultFieldRegion
- User -> partners. Partners is gathered by the partner service, and isn’t part of user object… so go with API or Java?
- User -> knownLanguage exists in API, but not in Java, and there’s code for it in the corresponding service.


         
 *Property doesn’t exist in API or Java
 ** Property exists in API or Java, but not in Schema

**Note**: have been making canDelete=false by default for Db Object of each component. Is that a good idea?

**Comment by elisabeth-sorrell** [comment]
@michaelmarshall the `canDelete` property is assigned `No permissions` in Java, but I'm wondering what that means. Won't the user need read permissions to see if he can true/false delete an object?

**Comment by elisabeth-sorrell** [comment]
@michaelmarshall more differences/observations:
### FA on Project role:
- Java -> Ceremony properties are RW, but property table shows them as ReadOnly. Sided with property table
- Java -> Education properties are ReadOnly, property table shows that Mine is RW. Can't be expressed based solely on the role definition.
- Java -> Film properties are RW, property table shows ReadOnly. sided with property table
- Java -> Internship engagement props are RW, property table shows Global Read only, sided with property table
- Java -> Language engagement props are RW, property table shows Global Read only, sided with property table
- Java -> Project props are RW, but property table shows a mixture of Global Read only, RW, and Global Read + calculated W. Sided with property table wherever possible and just used W for calculated W
- Java -> Song props are RW, but property table shows Global read only, sided with property table
- Java -> Story props are RW, but property table shows Global read only, sided with property table
- There are properties where Write is calculated according to the property table but not sure how to show that in the Role.

**Comment by elisabeth-sorrell** [comment]
@michaelmarshall 
### Fundraising
- Java -> properties in below components are RW, Property table: Global R only. Sided with property table
  - Budget
  - budgetRecord
  - Ceremony
  - Directory. 
  - File
  - FileVersion
  - Film
  - InternshipEngagement
  - LanguageEngagement
  - LiteracyMaterial
  - Partner
  - Partnership
  - Product
  - Project
  - ProjectMember
  - Song
  - Story
