### ISSUE TITLE
mutation createFundingAccount > Getting "null" values for "name" and "accountNumber" fields even if values provided for both

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1639]
**Roles:** All

**Describe the bug**
mutation createFundingAccount > Getting `null` values for `name` and `accountNumber` fields even if values provided for both

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
The given value should be returned.

**Actual Result**
Getting `null` values for `name` and `accountNumber` fields even if values provided for both
See video - 

https://user-images.githubusercontent.com/5212585/107915958-750f3400-6f8b-11eb-8e62-546b5cfba7f4.mp4

**GraphQL Query ( createFundingAccount):**
![image](https://user-images.githubusercontent.com/5212585/107916050-9839e380-6f8b-11eb-893f-a90688d88311.png)

**Query and Input File**
[CreateFundingAccount.txt](https://github.com/SeedCompany/cord-api-v3/files/5980003/CreateFundingAccount.txt)

**GraphQL Response:**
```
{
    "data": {
        "createFundingAccount": {
            "fundingAccount": {
                "id": "aLRGKdVrc5t",
                "createdAt": "2021-02-15T12:37:30.577+05:30",
                "canDelete": true,
                "name": {
                    "value": null,
                    "canEdit": false,
                    "canRead": false
                },
                "accountNumber": {
                    "value": null,
                    "canEdit": false,
                    "canRead": false
                }
            }
        }
    },
```
CordAPIV3# 5d098088

**Comment by CarsonF** [comment]
You're getting null because the user doesn't have permission to see the values

**Comment by iPiyushPatel** [comment]
Hi,@CarsonF 
Thanks for the clarification, 
but my concern is if users have access to create a funding account then also user has access to view details for the same. 
Please suggest!
