### ISSUE TITLE
FA and LFA cannot change the financial reporting type on a project

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1640]
A user put in a ticket that says she and her team cannot change the financial reporting type on a project. She is a LFA and FA in most projects.

Project: Timothy Intern https://cordfield.com/projects/5d7aaeb35ad0b438ce357582

![108093777-b531ed80-7043-11eb-9e70-044ff93a03cc](https://user-images.githubusercontent.com/5691814/108098290-32179400-7051-11eb-8b4f-540ce4002b7a.png)

**Comment by ParkeBrown** [comment]
@blakekrammes here it is. 

Private support details here: https://github.com/SeedCompany/management/issues/3

**Comment by ParkeBrown** [comment]
@elisabeth-sorrell

**Comment by blakekrammes** [comment]
@elisabeth-sorrell it looks like Liz DeOtte (Nolan mentioned she was trying to make the change in the original issue) is not on the team for this project. I'm unsure if this should be a limitation based on her roles, but it was unexpected for me.

**Comment by elisabeth-sorrell** [comment]
@blakekrammes she probably doesn't have the permission on the financialReportingType on the FA role. checking...

**Comment by sethmcknight** [comment]
@blakekrammes @elisabeth-sorrell There were 2 users who attempted to do this. 

1) Is a Lead Financial Analyst (which we don't have permissions for) and was not on the team. 
2) Is a Financial Analyst listed as a Financial Analyst on the Project Team. This should have worked for this user without any issues.

**Comment by blakekrammes** [comment]
Thanks, Seth. Number 2 is the problem to solve at the moment.

**Comment by ParkeBrown** [comment]
Examples from users: SeedCompany/management#3

**Comment by blakekrammes** [comment]
This should be fixed since we've opened up updating, but we'll eventually need to restrict permissions for all roles to what they should be. Not sure if that means we should close it. Perhaps we should wait for user confirmation.

**Comment by ParkeBrown** [comment]
We're trying to get a clear confirmation on this. I've not seen one yet. @sethmcknight have you?

**Comment by sethmcknight** [comment]
@ParkeBrown I haven't seen any confirmation that this has been resolved for users, but I haven't seen additional reports. I'll go ahead and call this one closed.
