### ISSUE TITLE
Data Displays as "Null Null" in project searches and people lists for some users

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1641]
Writers, EDRs and Office of Pres. find that when they search for a project, it only shows null null as results.

![108077915-b1e23600-7032-11eb-9858-26e983f37e78](https://user-images.githubusercontent.com/5691814/108099403-8ff8ab80-7052-11eb-9a2f-62447d5a2fd3.png)

Scrum master sees list of "null null" in people list. From Seth: "When a user with only the base role logs in they are able to see Cards on the People List, without names returned. For all other lists no cards/results are returned. We should probably handle People the same as all other lists."

![107892144-da5e1900-6ee8-11eb-9f6d-ac713e01178c](https://user-images.githubusercontent.com/5691814/108099451-9dae3100-7052-11eb-854c-742e018171be.png)

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466769458) by [Unito](https://www.unito.io)

**Comment by ParkeBrown** [comment]
Private support details here:
1. https://github.com/SeedCompany/management/issues/1
2. https://github.com/SeedCompany/management/issues/2

**Comment by ParkeBrown** [comment]
@elisabeth-sorrell this one as well

**Comment by ParkeBrown** [comment]
@sethmcknight is this addressed by other tickets in the system?

**Comment by sethmcknight** [comment]
@ParkeBrown I don't think so, but this one is a low priority issue.
