### ISSUE TITLE
Add Permissions to Lead Financial Analyst Role

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1642]
I missed the Lead Financial Analyst role when defining permissions on the CORD Schema - Properties by Base Node sheet. I've added those in Column N on the sheet.

 We need to update permissions to match the Lead Financial Analyst role on the CORD Schema sheet:
https://docs.google.com/spreadsheets/d/1Y5HPK3M2ECsreDqmR-Z9q7e2sJoL6WzD6low9N_aptc/edit#gid=0

**Comment by CarsonF** [comment]
@elisabeth-sorrell This is done right?

**Comment by elisabeth-sorrell** [comment]
@CarsonF yup
