### ISSUE TITLE
Remap v2 Roles to v3 Roles

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1643]
It looks like some of the roles in v2 did not get mapped to v3 roles for migration.

Here's what needs to change:

- `Writer` > `Marketing`
- `Executive Development Representative` & `Office of the President` > `Fundraising` (Fundraising should be updated to Advancement)
- `Supporting Project Manager` > `Project Manager`
- `Executive Leadership` > `Leadership`

**Comment by blakekrammes** [comment]
And I'm guessing these roles need to change on users as well as project team members or just users?

**Comment by sethmcknight** [comment]
@blakekrammes ideally the team members but on the users will get us 95% of the way there

**Comment by blakekrammes** [comment]
Ok. Getting a better view of the data now. Doing both shouldn't be a problem.

**Comment by blakekrammes** [comment]
@sethmcknight ok. It's not as straightforward. The best thing might be to update through the API. This would leave updated at timestamps on team members. Are you ok with that?

**Comment by blakekrammes** [comment]
Awaiting verification that permissions are working.

**Comment by sethmcknight** [comment]
@blakekrammes this should be resolved, thanks for taking care of this!

**Comment by blakekrammes** [comment]
Much thanks to Michael, too.
