### ISSUE TITLE
Duplicate Projects and Dropped Projects in Domo Sync

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1644]
2020-02-16
Ken Jones  8:06 PM
@here Just started receiving alerts from Domo in the past couple of hours as it is processing data.  We are getting duplicate projects in the CORD V3 Projects API.  2 project name examples are "Lafi e Devleso 2" and "Kamaka NT".  This is very bad for Domo as it will inflate any aggregations we are doing.

Ken Jones  10:57 PM
All, FYI - As of this evening at 10:30 PM EST, I reverted all of the data in Domo coming from the CordField V3 API back to the last good push at 9AM EST this morning.  I also turned off further processing of any additional pushes of data from the API from being processed in Domo.
As of now, the data in Domo from CORD V3 will be stale, but it should be accurate (i.e. no duplicates or missing projects).
Tomorrow, we will need to discuss the issues that Blake and I encountered tonight which caused the Domo alerts to be generated.

**Comment by ParkeBrown** [comment]
@kjones140 @blakekrammes @sethmcknight here it is

**Comment by blakekrammes** [comment]
@CarsonF don't know if you'll get the chance to look at this here, but my guess at this point is that the class where the schema is stored `this.schema.columns` isn't be recreated between runs and results in stale data:
````typescript
schema: {
  columns: Object.entries(this.schema.columns).map(([name, type]) => ({
  name,
  type: type.domoType,
  })),
},

**Comment by CarsonF** [comment]
> My guess at this point is that the class where the schema is stored `this.schema.columns` isn't be recreated between runs and results in stale data on updates:

The schema does not contain data. It only knows how to format cell data, order columns, etc.

**Comment by CarsonF** [comment]
Update: I've confirmed that duplicate items are given to the domo sync process, meaning that they originate from CORD's cypher list queries. This is happening infrequently so it's hard to track down.

I've updated the DOMO sync code to detect these duplicate items and retry/fail when found. This prevents DOMO from having to deal with them while we track down the root issue in CORD.
