### ISSUE TITLE
Changing/reseting password should invalidate all current sessions

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1645]
## Environment

| Tech      | Version / Name |
| --------- | -------------- |
| API       |                |
| FE        |                |
| OS/Device |                |
| Browser   |                |

**Comment by CarsonF** [comment]
@zkhin Can you address the comment on that merged PR?

**Comment by zkhin** [comment]
@CarsonF Here's [PR](https://github.com/SeedCompany/cord-api-v3/pull/1698).
