### ISSUE TITLE
Funding Partner Missing After User Attempted to Delete and Re-Add

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1646]
Field Project Manager: "Chakhi 3 Seed Co is not listed as partner. Neither I nor my supervisor can see it. Seed Co should be the funding partner. I admit that this is most likely my fault. When I was unable to change Seed Co from Resource to Funding partner, I deleted Seed Co as partner, then tried to add them back as Funding partner, but CORD says Seed Co already exists."

**Comment by CarsonF** [comment]
I believe this should be covered by #1661 and #1647

**Comment by blakekrammes** [comment]
I fully deleted the Partnership node manually in the db and added Seed Company as the funding partner on the project.

**Comment by CarsonF** [comment]
Did you add via API? If not you need to run the java procedure as well

**Comment by blakekrammes** [comment]
I added via UI, so yes.

**Comment by ParkeBrown** [comment]
@blakekrammes does that complete this limited fix request then?

**Comment by blakekrammes** [comment]
I think so, yes. I'll close.
