### ISSUE TITLE
Field Project Manager Unable to Change Partner Designation from Resource to Funding

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1647]
FPM: I was unable to change the type of partner from Resource to Funding. I had to ask supervisor t to correct this for me (so this problem has been fixed now, but this should be fixed for other FPM's). As FPM I need to be able to change my own projects' information without getting supervisor involvement

Confidential details: https://github.com/SeedCompany/management/issues/12

**Comment by ParkeBrown** [comment]
@sethmcknight did you want to verify if this is a bug or feature request?

**Comment by sethmcknight** [comment]
@ParkeBrown I can't verify right now but believe this is a Project Manager permissions issue, related to the other issue with Budgets and possibly Status
