### ISSUE TITLE
Marketing role user unable to view or open documents. Attempting gives message saying "could not retrieve file."

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1650]
See user details here: https://github.com/SeedCompany/management/issues/18

**Comment by ParkeBrown** [comment]
User reports:
"it applies to all of the projects I've tried it on so far. This is from Daleki 2. Here's what the outside of the "files" folder looks like, and the message I get when I try to view one."

![108419216-dd624d80-71f7-11eb-88b7-6bfd6dcad5dd](https://user-images.githubusercontent.com/5691814/108419771-f28faa00-7200-11eb-96e6-b427c2721f80.png)

![108419236-e18e6b00-71f7-11eb-9f2d-ef54d8edf9b2](https://user-images.githubusercontent.com/5691814/108419783-f58a9a80-7200-11eb-89d8-bb538502ef43.png)

**Comment by ParkeBrown** [comment]
- Seth is able to preview this doc so it looks like this is most likely a permissions issue
- Support asking user if they can download

**Comment by blakekrammes** [comment]
I think I have a lead here and am working towards a solution. I believe there was a problem when we remapped these roles (Marketing, EDR, etc.)
