### ISSUE TITLE
List refactor

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1653]
We need to figure out how to implement new list queries using the new role/security paradigm.

**Comment by sethmcknight** [comment]
Blocked by #1736 

Blocks #1830

**Comment by CarsonF** [comment]
I believe #1813 might be a good starting to point to replicate

**Comment by elisabeth-sorrell** [comment]
Tickets to be done for this to complete: 

- [ ] #1787 
- [ ] #2362
