### ISSUE TITLE
Error Messages When Changing Project Step

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1654]
When users with the correct role attempt to change the Project Step on a Project, they receive an error message that they do not have permissions or that the step is not in an authorized sequence. The Step change is still completed correctly.

**Comment by ParkeBrown** [comment]
Potential user step issues here: https://github.com/SeedCompany/management/issues?q=is%3Aissue+is%3Aopen+label%3Asteps
