### ISSUE TITLE
Users Unable to Update Budget Records

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1655]
Users assigned to a Project with the roles of Administrator, Project Manager, Financial Analyst or Lead Financial Analyst are not being allowed to make changes to Budget Records. This may affect other roles as well.

**Comment by ParkeBrown** [comment]
Multiple user examples here https://github.com/SeedCompany/management/issues/14

**Comment by sethmcknight** [comment]
User report as resolved.
