### ISSUE TITLE
Department ID's Must Be Unique | Internship Projects with Duplicate Department ID's

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1664]
The Department ID is a unique field for each Project, both Translation and Internship. A Department ID should only be assigned once. After a Department ID has been assigned to a Project it should not be assigned to another Project.

Projects `Jacklyne Shisia` & `Winnie Adoyo` were both assigned the Department ID `20001`. This Department ID is already assigned to `FO - Africa Catalyst Opportunities`. 

We need to correct this by 

1. Assigning the next available Department ID's in the `2` Funding Account to `Jacklyne Shisha` &`Winnie Adoyo`
2. Implementing a business rule to check for uniqueness on Department ID for all Project Types.

**Comment by sethmcknight** [comment]
@blakekrammes this might be a good next one for you

**Comment by sethmcknight** [comment]
Additional clarity from Phil Bohaker:

Department ID's should not end in X0000 or X0001, any other combination is valid.
Department ID's must be unique

**Comment by sethmcknight** [comment]
@blakekrammes would you let me know as soon as those two internships have new Department IDs? Phil just reached out to me anxious to be able to transfer funds.

**Comment by blakekrammes** [comment]
Ok, so 20002 and 20003 should work? I'll need to hop on with Michael or Carson to do a manual db change.

**Comment by blakekrammes** [comment]
@sethmcknight those two have been updated to unique dept ids.

**Comment by sethmcknight** [comment]
@blakekrammes sorry to have this resurface, Phil reached back out and said 

"Unfortunately, both of those Dept IDs are already used in Intacct. I would recommend using a number higher than xxx10. Sorry, I didn’t realize that was going to be an issue."

So we need to come back and make sure it's higher than xxx10 on the validation, and we need new Department IDs for these 4 Projects:
- `Jacklyne Shisia`
- `Winnie Adoyo`
- `Ket-Lik-Ki Cluster 2`
- `Coronation Cluster 3`

They are asking that we get those changed by end-of-day Monday so that they can transfer funds to the Projects

**Comment by sethmcknight** [comment]
@blakekrammes would you let me know as soon as these 4 have new Department ID's and what they are?

**Comment by blakekrammes** [comment]
Sure. It's interesting that they're used in intacct, but aren't on any projects in the db.

**Comment by blakekrammes** [comment]
Todo: add ability to update dept id in API - not UI.

**Comment by blakekrammes** [comment]
@sethmcknight those 4 have been fixed.

**Comment by ParkeBrown** [comment]
Seth confirmed they all match what was asked for by Phil
