### ISSUE TITLE
Correct the Engagement Status for 3 Projects that `Did Not Develop`

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1666]
The Engagement Status' for each of these 3 Projects should all be set to `Did Not Develop`:

- Kiibo
- Carib
- Sumbi 2

**Comment by blakekrammes** [comment]
Ok. I've updated these three. Users should be able to do that after the update changes went through yesterday. I'll try and knock out the automatic engagement status update in the API.
