### ISSUE TITLE
Outstanding Permissions Issues

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1667]
4 key roles are still reporting permissions issues this morning. We need to get these resolved ASAP.

Access to view, download and upload files is the top issue. I've broken down all the other reported issues by role below:

Lead Financial Analyst / Financial Analyst
- Can’t upload files
- Can’t download or preview files
- Can’t change budget records
- Get error when changing step, but step changes
- Can’t change Managing Partnership’s `Financial Reporting Type`
- Can’t change Partnership’s `MOU Status`
- Can’t upload UBT

Project Manager
- Can’t upload files
- Can’t download or preview files
- Can’t change budget records
- Get error when changing step, but step changes
- Can’t change Partnership `Type`

Marketing
- Can’t upload files
- Can’t download or preview files
- Can’t change engagement’s `Communications Complete Date` (user anon does not have the requested power: CreateFileVersion)

**Comment by sethmcknight** [comment]
Lead Financial Analyst - #1642 
Lead Financial Analyst & Financial Analyst - #1640 
Budget Records - #1655 
Project Step - #1654 
Marketing File Access - #1650 
Project Manager Partnership - #1647

**Comment by ParkeBrown** [comment]
@michaelmarshall I've assigned you to this but it's probably all hands or someone else. Feel free to modify.

**Comment by ParkeBrown** [comment]
@sethmcknight team may need more specificity on what steps are getting error

Get error when changing step, but step changes

I'll look where I can at issues

**Comment by ParkeBrown** [comment]
On Devops:
Seth McKnight a quick fix for many of the step bugs may be to grant Budget/BudgetRecord read access to all project roles. Can we do this while we study a longer-term fix?

**Comment by ParkeBrown** [comment]
Seth ok'd fix with plan for documentation of long-term fix

**Comment by sethmcknight** [comment]
Fundraising (Advancement) role is also reporting issues previewing/downloading documents

**Comment by ParkeBrown** [comment]
Nolan is checking with users who reported file issues to Halp. One has already confirmed they can access files. More expected tomorrow.

@sethmcknight do you want to go back to your Fundraising reporters?

**Comment by sethmcknight** [comment]
Marketing role issues have been confirmed as fixed

**Comment by sethmcknight** [comment]
Most issues have been confirmed as resolved. Closing this issue and will work with the individual issues listed as items are confirmed fixed or still outstanding.
