### ISSUE TITLE
Correct the Step to Status mapping

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1687]
When a Project has a Step of `Did Not Develop`, the Status should also be `Did Not Develop`.

Currently a Step of `Did Not Develop` maps to the Status of `Terminated`.

See here: https://github.com/SeedCompany/cord-api-v3/wiki/Project-Workflows

**Comment by sethmcknight** [comment]
It looks like this has reverted.

Projects with a Step of `Did Not Develop` still display the Status of `Terminated` on the Project card instead of the correct Status of `Did Not Develop`

**Comment by CarsonF** [comment]
Just needs a data update. status value is written to db.

**Comment by ParkeBrown** [comment]
Clearing assignees as is backlog. Reassign and move to in progress etc. if picking up.

**Comment by ParkeBrown** [comment]
**User Experience with This:**
User searches for a project that is at the step "Did Not Develop" in project view and in playground query.
https://cordfield.com/projects/5ee3a61b74761c5556e3fc07

The search results list shows the the step as "Terminated."
https://cordfield.com/search?q=georges

**Comment by blakekrammes** [comment]
Assigning to resolve stale data in the database.

**Comment by blakekrammes** [comment]
Data has been fixed.
