### ISSUE TITLE
Project.stepChangedAt is missing from Projects

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1688]
Another user has received this error when attempting to change the Project step: "Could not find Project.stepChangedAt to update"

We need to check all Projects for the stepChangedAt field and create if it does not exist.

SeedCompany/management#40
SeedCompany/management#32

**Comment by blakekrammes** [comment]
@sethmcknight we applied a fix for this on Thursday. Have the users verified this still exists? Those two reports are from 4-5 days ago.

**Comment by blakekrammes** [comment]
Just saw the other issue with a report that it's still happening. Checking it out.

**Comment by sethmcknight** [comment]
@blakekrammes if I understand correctly, the Project.stepChangedAt issue should be resolved for all Projects. Is that correct?

If so I can have Nolan follow up with user to confirm or give us a specific case where that has happened since Friday.

**Comment by blakekrammes** [comment]
Yes. I believe that to be correct.
