### ISSUE TITLE
Error when attempting to change Project step - `(destructed parameter).project is undefined`

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1689]
SeedCompany/management#56

**Comment by sethmcknight** [comment]
Alternate error message of `cannot read property step of undefined`

**Comment by sethmcknight** [comment]
@blakekrammes is this a different issue or do you believe this was resolved with the Project.stepChangedAt fix?

**Comment by blakekrammes** [comment]
Yeah. That looks like a different problem. It's interesting that Nolan said he could change it though. Maybe a role issue.

**Comment by sethmcknight** [comment]
@blakekrammes FYI this is the highest priority bug

**Comment by blakekrammes** [comment]
Thanks, Seth. I'll look into it soon. Do you know if it's widespread?

**Comment by sethmcknight** [comment]
@blakekrammes yes this is a widespread issue. We're keeping track of all of the reports over in seedcompany/management#63

I'm seeing at least 12 tickets open with Helpdesk, but I believe more users are experiencing this as well

**Comment by CarsonF** [comment]
Fixed by #746
