### ISSUE TITLE
Reassign all users with the role of `Development` to the role of `Fundraising`

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1694]
seedcompany/management#1

**Comment by blakekrammes** [comment]
@michaelmarshall If you have time to work this there are 16 users with active Development roles. There are no team members on projects that have this role thankfully, which makes this update easier. Here are the roles below.

["5c3d88a07219425288a3cc24", "5c3d88a27219425288a3cc31", "5c3d88a37219425288a3cc33", "5c3d88a77219425288a3cc57", "5c4278d69503d5cd78e82bf8", "5c4278d69503d5cd78e82bfc", "5c4278d69503d5cd78e82bff", "5c4278d69503d5cd78e82c00", "5c4278d69503d5cd78e82c08", "5c4278d69503d5cd78e82c11", "5c4741e07e96a6307636844d", "5c4a1f997e96a66acb39478a", "5c4a1fbb7e96a649f339479a", "5c4f82ec8a0ddd0b79b5c69b", "5c950f2919eefb5ae4ec52b8", "5d2787f2231ca435b5524307"]

**Comment by blakekrammes** [comment]
@sethmcknight, @michaelmarshall  I think we need to make updates to the API roles as well. 

Here are the roles Seth requested to be remapped previously:
```
Writer > Marketing
Executive Development Representative & Office of the President > Fundraising (Fundraising should be updated to Advancement)
Supporting Project Manager > Project Manager
Executive Leadership > Leadership
```

This is the current list of roles we have in the API with outdated role names struck through:

Administrator 
  BibleTranslationLiaison 
  Consultant 
  ConsultantManager 
  Controller 
  ~~Development~~ 
  ~~ExecutiveDevelopmentRepresentative~~
  ~~ExecutiveLeadership~~
  FieldOperationsDirector 
  FieldPartner 
  FinancialAnalyst 
  Fundraising 
  Intern 
  LeadFinancialAnalyst 
  Leadership 
  Liaison 
  Marketing 
  Mentor 
  ~~OfficeOfThePresident~~
  ProjectManager 
  RegionalCommunicationsCoordinator 
  RegionalDirector 
  StaffMember 
  ~~SupportingProjectManager~~ 
  Translator 
  ~~Writer~~ 
  
-------------------
@sethmcknight  can you confirm the above list?

**Comment by sethmcknight** [comment]
@blakekrammes @michaelmarshall I'll make the changes to these users

**Comment by blakekrammes** [comment]
Here's a PR to be merged once Seth has finished and we verify that role doesn't exist in the DB.

https://github.com/SeedCompany/cord-api-v3/pull/1702

**Comment by sethmcknight** [comment]
All 16 users have been assigned the role of Fundraising.

**Comment by blakekrammes** [comment]
Great. Thanks, Seth.
