### ISSUE TITLE
Register > New user is not registered

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1714]
**Roles:** All

**Describe the bug**
Register > New user is not registered

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
A new user should be registered

**Actual Result**
A new user is not registered
See video - 

https://user-images.githubusercontent.com/5212585/110102618-045d7980-7dcb-11eb-9a76-a3766b3c573c.mp4

**Note:** I am able to register & login using the below users only:
         rdfod@gmai.com, intern@yopmail.com,consultant@yopmail.com, etc

**Note:** Same issue on UI side.
See video - 

https://user-images.githubusercontent.com/5212585/110097631-44b9f900-7dc5-11eb-8e45-0b706d3e6b33.mp4

**GraphQL Query ( register ):**
![image](https://user-images.githubusercontent.com/5212585/110095074-86957000-7dc2-11eb-9dc8-1468b2a49dc4.png)

**Query and Input File**
[UnableToRegisterNewUser.txt](https://github.com/SeedCompany/cord-api-v3/files/6089479/UnableToRegisterNewUser.txt)

**GraphQL Response:**
```
Not get any response

```
CordAPIV3# 2ed15ae2

**Comment by CarsonF** [comment]
Can you reconfirm this @iPiyushPatel with latest develop?

**Comment by iPiyushPatel** [comment]
Yep will @CarsonF  - I see you've pushed new changes so !

**Comment by iPiyushPatel** [comment]
Hi @CarsonF  
I've verified the issue on the latest develop 474289ae and still replicate the issue, Attaching the latest video for reference.
Thanks!

See video :

https://user-images.githubusercontent.com/5212585/110431811-4987f100-80d4-11eb-8dad-ff1787fae036.mp4
