### ISSUE TITLE
Attempting to Upload File to Project Results in Error "Post-Upload Action Failed"

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1715]
Various users are experiencing issues uploading files. See one example here:

![109824495-80569680-7bfe-11eb-8459-45e466a35bcf](https://user-images.githubusercontent.com/5691814/109991689-891b9b00-7cd8-11eb-856e-b72c84bfdd10.png)

Another here:
![109869399-6a60ca00-7c2e-11eb-97f0-6072c8794cbf](https://user-images.githubusercontent.com/5691814/109991822-abadb400-7cd8-11eb-87fb-a20cc12f4bfc.jpg)

See user engagement summary ticket with links to examples here: https://github.com/SeedCompany/management/issues/79

**Comment by CarsonF** [comment]
@ParkeBrown this is fixed now!
