### ISSUE TITLE
Dynamically replace labels of deleted node

### ISSUE THREAD

**Issue by blakekrammes** [SeedCompany/cord-api-v3#1717]
Currently when deleting nodes we explicitly enumerate the node labels to be replaced by `Deleted_` prefixed labels. In the case below, this caused a bug when deleting files since the `FileNode` label was not listed. This caused a faulty match later on.

https://github.com/SeedCompany/cord-api-v3/blob/2ed15ae2d88f007303f5f8323593244db9ef1929/src/components/file/file.repository.ts#L473-L479

We need to list the labels of the node being deleted dynamically `labels(n)` and cycle through, replacing each with a `Delete_` prefixed label. 

See https://github.com/SeedCompany/cord-api-v3/pull/1713 for more details.

**Comment by sethmcknight** [comment]
fixed in cord-field-api#1755 and cord-field-api#1752
