### ISSUE TITLE
DTOs for Team

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#172]
The language service DTOs are a good example to use.

**Comment by CarsonF** [comment]
Let's rename this object `ProjectMember`. It was previously `TeamMember` but there could be multiple teams in this app, so Project is more explicit to the relation.

Ok so this follows the same concept as _Partnerships_.
```
Project <-> Partnership <-> Organization
```
```
Project <-> ProjectMember <-> User
```
`ProjectMember` should have the following properties
- `user: SecuredUser` - required, not updatable, `userId: string` on create
- `roles: SecuredRoles (SecuredPropertyList)` - optional, updatable
- `modifiedAt: DateTime`

`editable` and `description` are not needed.
Follow the pattern of Partnerships for everything else.
