### ISSUE TITLE
PROJECT: Pinned Items

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1721]
As a user, I want to pin certain items in a list so that I can view those items in a separate list of pinned items.

For the v1 of this feature, we will only let users pin `Projects`, but we will write the code abstract enough for future versions to easily allow anything to be pinned to anything else.

Requirements:
- When viewing a list of projects, the user will be able to determine whether a project has been pinned or not.
- A user will be able to pin and unpin a project when viewing it in a list or on its detail page.
- A user will have the option of viewing all of their pinned items.

![image](https://user-images.githubusercontent.com/1165460/110253295-28e25e80-7f4f-11eb-95f5-c40e4d11b939.png)

^^ the pin on the project card and the pinned tab on the tab bar are features this project will add.

The database schema below is how we will store `pinned` relationships in the database. User -> Projects is shown in blue.
![image](https://user-images.githubusercontent.com/1165460/110253821-f38b4000-7f51-11eb-93de-d91a1ba26d5e.png)

A branch in the API and FE repo is being scaffolded with classes and functions. There will be a new `pinned` service that will be responsible for CRUD operations on the `pinned` relationship between any two `:BaseNode`s. In addition to the new service, the project service will need to be modified to return `pinned` data on projects relevant to the requesting user. Which also means model classes will need to be updated. The pinned service will be exposed via GraphQL resolvers so that the FE can before CRUD operations on it.

At a minimum, the following functions or concepts will need to be created and integrated with the rest of the codebase:
- [x] Function to create a pinned relationship between any two base nodes
- [x] Function to delete a pinned relationship 
- [x] Modification to the project model to include a boolean for if the requesting user has pinned it 
- [x] Modification to the project list view and project detail view to return the pinned boolean of the requesting user
- [x] UI component to show whether a project is pinned, and functionality to pinned/unpin it, both on list and detail views
- [x] UI component to show a list of pinned projects

Milestones:
- [x] API for pinning items and listing pinned projects.
- [x] Abstract UI components to implement the API.
- [x] Designs completed by the design team.
- [x] Implement the FE designs.

**Comment by CarsonF** [comment]
API branch started at `feature/pin`. I left TODOs for work to be done.

**Comment by sethmcknight** [comment]
Designs are completed and available on SeedCompany/cord-field#718

**Comment by sethmcknight** [comment]
Blocked by seedcompany/cord-field#749
