### ISSUE TITLE
PROJECT: Posts + Discussion

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1722]
As a user, I want to be able to leave comments on a project or engagement so that I can communicate updates, questions, prayer requests, and anything else to the other members of the project. I also want to be able to have discussion around what is posted so that resolution or understanding can occur.

The v1 of this feature will add posts and discussion on project and engagement detail pages, but will be coded in an abstract way so that this feature can be easily added to anything else in the future.

The designs for project posts/discussion are not ready yet, but work can still proceed with API development and abstract UI components.

At a high level, the following requirements are required on the FE and API:
1. The user needs to be able to create a 'thread' post on a project or engagement. This post can have tags associated with it. Only tags from an approved list will be available (ex. dropdown/checklist).
2. The user should be able to edit their post. If a post is edited, it should indicate so.
3. A user should be able to delete their post.
4. A user should be able to respond to a post, with all the above features.

On the API, a model will need to be created and exposed via GraphQL. The discussion service (name pending) will need to provide CRUDL operations on discussions. It will probably be called exclusively for this data, we may not need the other services to be aware of the discussion model, it may only be that resolvers need to be modified. As such, this service needs to be abstract so that discussions can occur on any `:BaseNode` in the future.

The threading model will be simple. Root posts begin a thread. Other posts are responses to the root posts. PHP bulletin boards are a closer approximation than modern nested comment systems like Reddit or Facebook.

The database schema is not finalized because the development of this feature may steer it in a different direction. Here is an example of what the schema may look like:
![image](https://user-images.githubusercontent.com/1165460/110255012-5af7be80-7f57-11eb-9daf-8f8bfd632347.png)

Posts should all be rich text with emoticons. The specific library to use has not been decided. We anticipate the implementor helping the team make an informed decision on which library to use.

Milestones:
- [x] Create API for threads, posts, and tagging.
- [x] Create abstract UI components to implement API calls.
- [x] Designs should be completed by the design team.
- [x] Implement FE designs.

**Comment by sethmcknight** [comment]
@richardgirges designs can be found here: [Comments Design – Ready for Development](https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/Cord-Field---Current?node-id=4211%3A0)

**Comment by sethmcknight** [comment]
🤦🏼 Note to self - Don't click `Close with comment` if you're just trying to leave a comment...

**Comment by richardgirges** [comment]
I have a super-beta version of comments ready (still pending reviews and some architectural updates on the FE) but the feature is "demo-able" as-is if both the front-end and backend are pulled down locally. The branch name is called `1722-post-discussion` in both the cord-field _and_ the cord-api-v3 repos.

**Comment by sethmcknight** [comment]
@richardgirges what I've seen so far is looking great!

**Comment by sethmcknight** [comment]
### Posts v1 Requirements

- Posts attached to Projects
- Each Post captures and displays the username of the poster and the date/time posted
- Posts displayed newest to oldest
- User selects a type/category for each Post they create, the type/category is displayed on the Post
- User selects a Sharing setting for each Post they create, the Sharing selection is displayed on the Post

## Type or Category
I'm not sure which would be better to call this, open to y'alls input.

For v1:
- Note
- Story
- Prayer or Prayer Request

## Sharing selections
We probably need to come up with a better term for this but it gets the point across

For v1:
- Project Team Only
- Internal Use Only
- Ask Before Sharing Publicly
- Share Publicly

@michaelmarshall let me know if y'all need any more clarity

**Comment by michaelmarshall** [comment]
@sethmcknight  Looks good. We'll make enums of the types and shareables that the user can select from. I would like a blessing from design that the UI was made with new-first ordering. If we ever want to add slack-like threads, nows a good time to pre-think that part in the event it influences the ordering.

**Comment by sethmcknight** [comment]
@AmyRickwartz let's connect tomorrow for a quick discussion on how Posts should be ordered
