### ISSUE TITLE
PROJECT: Project Reports

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1723]
As a project member, I want to be able to upload specific reports for my project to meet my reporting obligations, so that my supervisors can see which report is for each specific requirement.

As a project manager, I want to ensure a report is for a specific requirement and has not be uploaded for an incorrect requirement so that I know I'm getting all the reports I have required of the project. I should also be able to preview a report without downloading it, as well as simply download the report.

This feature adds a section the to project details page and provides a mechanism for the project member to upload a file and tag it (or equivalent) in such a way to identify it as fulfillment of a specific requirement. The project member should be able to see which reports they've submitted, and which requirements they have yet to submit a report for. 

This feature should also include the ability to preview a report without downloading it by anyone with access to it.

This feature is similar to the 'defined files' concept and as such, much of the work may already be accomplished with defined files. Yet to be added is the fact that every project as a few reports periodically (each may be a different period) that need their own identification so everyone knows if a report has been uploaded or not.

We are still awaiting designs on this feature. We can begin API development and make abstract UI components until we have the final FE designs.

For communication purposes, a simple UI would provide for a file upload dialog with a dropdown for which specific report is being uploaded. Another component would show the list of reports that have been uploaded and which are missing.

The database schema will attach `:ProjectReport` nodes off of the `:Project` node.
![image](https://user-images.githubusercontent.com/1165460/110255825-503f2880-7f5b-11eb-9462-505312eba4e2.png)

GraphQL is used to expose data to the FE. After the model is created, resolvers will need to be written that call the new project service functions for report file CRUDL.

Milestones:
- [x] API for project report CRUDL. 
- [x] Abstract UI components to implement the new API.
- [x] Design completes the final FE designs.
- [ ] Implement FE designs.

**Comment by michaelmarshall** [comment]
@sethmcknight can we list all report types, their periods, and any other meta data needed?
e.g.:
1. financial, quarterly
2. progress, monthly

**Comment by sethmcknight** [comment]
> @sethmcknight can we list all report types, their periods, and any other meta data needed?
> e.g.:
> 
> 1. financial, quarterly
> 2. progress, monthly

Financial Report
- Monthly or Quarterly
- Month/Quarter the Report Covers
- Date/Time Submitted
- User Submitting

Progress
- Quarterly
- Quarter the Report Covers
- Date/Time Submitted
- User Submitting

Narrative
- Quarterly
- Quarter the Report Covers
- Date/Time Submitted
- User Submitting

**Comment by CarsonF** [comment]
@sethmcknight what's the difference between the 1st and 3rd bullet points?

**Comment by CarsonF** [comment]
It seems like these reports would be viewed separately from each other right? Permissions would probably be distinct on which report it is as well right?

**Comment by sethmcknight** [comment]
> @sethmcknight what's the difference between the 1st and 3rd bullet points?

@CarsonF the first is the timeframe the frequency of reporting, the third is when the report was received. I'll update.

**Comment by sethmcknight** [comment]
> It seems like these reports would be viewed separately from each other right? Permissions would probably be distinct on which report it is as well right?

That's correct. Each type of report should be managed distinctly from the others.

**Comment by CarsonF** [comment]
More Q&A with Seth:
> Carson: For project reports really it’s only the latest one that people are concerned about right? Just like with files, we really just show the latest version but give the option to see history separately.

Seth: We don’t have designs from Patrick yet so I’m not 100% sure what that will look like.
When submitting a report it’s only about the latest one. We will probably want the latest to be easily accessible and then a history of other reports to be visible by drilling in. Each report should be able to have versions for each reporting period… So for the February 2021 financial report I could have 3 versions.

> What are the odds that we’ll want to capture different data points on different reports in the future?

High

> There should be only one report per period right? Excluding file versions

Yes.
So there is one February 2021 Financial Report, though there may be multiple versions.
There is one Q2 FY21 Narrative Report, though there may be multiple versions.
There is one Q2 FY21 Progress Report per Engagement, though there may be multiple versions.
etc.

**Comment by CarsonF** [comment]
CF: What if a report needs to cover more than one period - two months or quarters?
SM: Not an option. Financial reports are the outlier because they could be monthly or quarterly periods. But once set the reports are for a specific period.
CF: Oh gotcha so the period is dynamic per financial report
SM: Idk. There are two options for reporting periods but it’s selected for the project so it wouldn’t change during the lifetime of the project.
SM: So basically for financial reports we’ll end up asking at the project level if this is a Monthly or Quarterly frequency. Once that’s set then they won’t have the choice to change it for this project
CF: So the project would set the period length for each financial report
SM: Yes
CF: Progress and Narrative reports should always be quarterly then or should that be set per project too?
SM: Currently those are always quarterly. Not sure how you want to code that

**Comment by CarsonF** [comment]
Reports can created based on project date range & when "financial reporting period" changes. If that's the case then we don't need to allow users to be able to create them, only add files.
Reports can be deleted when the date range changes if they don't have any files.

**Comment by CarsonF** [comment]
In the future, we'll want to replace/augment the _file_ with a _form/object_. Need to make sure we design so that works well with GQL. The form/object would different per report type.

**Comment by CarsonF** [comment]
In the future, we want to have a reports due X days after the end of the period. Instead of a period type and period date, I think it makes more sense to define this period as a _start_ date and an _end_date. This provides more clarity on the range it covers. Instead of a random day within the month/quarter, we have an exact end date that can be queried & logically compared in the database.
This also gives us room to expand/change the period length with minimal changes.

**Comment by CarsonF** [comment]
Financial & Narrative reports are per project. Progress reports are per engagement
