### ISSUE TITLE
Random authorization procedure failure preventing projects from being fully created

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1729]
~Carson Full Today at 2:39 PM
@Blake Krammes we are having a problem with root directories not being created/connected to new projects. Can you look to this? (assuming it’s a priority but Seth can confirm)~

**Comment by ParkeBrown** [comment]
Related conversation
Ken Jones:spiral_calendar_pad:  1 hour ago
Hi @Carson Full FYI, for some reason the Projects, LanguageEngagements and Products API data is late for the last push.  The other 6 were all received by 11:39 AM ET.






Carson Full  40 minutes ago
It looks like a project was renamed during the sync, causing it to show up twice, which stopped the sync.

Carson Full  40 minutes ago
I’m going to change the sort order to not be based on the name.

Parke Brown  33 minutes ago
Still exploring and may be unrelated but we’re seeing some reported project creation issues.
https://github.com/SeedCompany/management/issues/86
https://github.com/SeedCompany/management/issues/85 (edited) 

Carson Full  33 minutes ago
This is the project whose name changed https://cordfield.com/projects/5da491e738339de3954f82d7

**Comment by CarsonF** [comment]
The authorization procedure is failing after the project is created. This prevents the event handlers from running (i.e. to create the root directory, etc.) This also explains why search is failing, because the search query still uses db security groups. Since those failed to create there's no match.

**Comment by CarsonF** [comment]
Instead of waiting for that refactor, I went ahead and looked into what it would take to make the procedure work inside of the current transaction. It turns out it mostly just involved removing code. https://github.com/SeedCompany/cord-procedures/pull/13

**Comment by CarsonF** [comment]
This is actually because of a deadlock on the user node. The procedure wasn't failing it was just waiting for the lock to be released.

**Comment by CarsonF** [comment]
I believe this was fixed with #1735
