### ISSUE TITLE
Resolve duplicate project department ids in database

### ISSUE THREAD

**Issue by blakekrammes** [SeedCompany/cord-api-v3#1732]
There's also some TODO work involving fixing projects that have duplicate dept ids.

_Originally posted by @blakekrammes in https://github.com/SeedCompany/cord-api-v3/issues/1731#issuecomment-794767599_

The above PR should resolve the bug, but there's data cleanup to do.

**Comment by blakekrammes** [comment]
Also need to add the DepartmentId label to all properties that are active.

**Comment by blakekrammes** [comment]
All dups that have surfaced since migration have been taken care of and the `DepartmentId` label has been added to the dept id property nodes to ensure uniqueness (the create dept id query does this as well). 

The exceptions to this are 15 dept ids from V2 projects that we had to split because of connected engagements that had the same project and language id. These need to be handled still.

**Comment by CarsonF** [comment]
These v2 duplicates have been marked with a `DuplicateProjectDepartmentId` label instead of a `DepartmentId` label.

I don't think there's anything we can do to handle these.

**Comment by blakekrammes** [comment]
Thanks for including that. And yeah. Maybe not. Those numbers should still be included in the list of existing ids because we're just checking `()-[:departmentId]->(:Property)` not the list of `DepartmentId` node values.

**Comment by CarsonF** [comment]
I'm going to close this. We shouldn't be keying on department ID anyways. I think the only place that matters currently is with donations and these are all completed projects.
