### ISSUE TITLE
updateUser > All requests hangs when trying to change user role by "roles" field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1733]
**Describe the bug**
updateUser > All requests hangs when trying to change user role by `roles` field

**Steps to Reproduce**
1. Register the user with `ProjectManager` userrole.
2. login with the same user.
3. update the user with the `Controller` userrole.

**Expected Result**
User should be allowed to update data as per `input` fields

**Actual Result**
All requests hang when trying to change user role by `roles` field.

**Note:** 
` match (n) detach delete n` query also not working in neo4j browser after `updateUser` request.

See video -

https://user-images.githubusercontent.com/5212585/110626870-46216200-81c7-11eb-9bdd-0074d7f027c6.mp4

**GraphQL Query:(updateUser )**
![image](https://user-images.githubusercontent.com/5212585/110626973-694c1180-81c7-11eb-9779-a034e6558b81.png)

**GraphQL response**
```
No response
```
**Query and Input File**
[UpdateUser.txt](https://github.com/SeedCompany/cord-api-v3/files/6115677/UpdateUser.txt)

CordAPIV3# 32e3ddc1

**Comment by CarsonF** [comment]
Fixed with #1735
