### ISSUE TITLE
Add Sensitivity level view permissions for Sensitive fields.

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1736]
To better manage our sensitive data, we need to add the ability to restrict access to a field based on the sensitivity of the field or a related field.

We should be able to assign sensitivity view levels for a field both Globally and based on Membership.

Example:
Location is a sensitive field.
Global Access to Location for a specific role is limited to Medium, meaning a user with that role can see Location in Medium and Low sensitivity contexts, but not High sensitivity contexts.
Member Access to Location for this same role is granted for High, meaning if the user is a Member of a High sensitivity context, they will be able to view the data.

A non-exhaustive mapping of permissions by role to sensitive data fields can be viewed here: https://docs.google.com/spreadsheets/d/1GBAyYtzztRGgdIJY44XI27obITYCEDkxY_mLk9IS4jE/edit?usp=sharing

I'll need to go through our data schema with Michael to insure there are no other fields that should be marked as sensitive.

**Comment by sethmcknight** [comment]
Thinking aloud as I look back over the Sensitivity mapping... we do not have any instances where we would restrict access to a Team Member based on Sensitivity. All Team Member permissions are either yes or no.

We only need to add the Sensitivity permission to the Global role.

**Comment by sethmcknight** [comment]
@michaelmarshall this is the issue for Sensitivity that we just discussed with Justin. Would you look at this and decide if work can take place now or needs to wait?

**Comment by elisabeth-sorrell** [comment]
- [ ] #1874
