### ISSUE TITLE
Change Two Intern Email Addresses

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1739]
Joel Istifanus should be isandujob@gmail.com 

Basuna Magaji should be magajibasuna@gmail.com

Users and admins are unable to correct

**Comment by blakekrammes** [comment]
These two emails have been updated. I was able to do this through the playground, so this is something support can do in future. Not sure why there's a difference between UI and API playground. 

First you want to find the user in the UI and get their ID. When you go to the detail view of a person, the user id follows `/users` in the url as in `/users/{userId}`

Here are the queries to run once you have the id:

```gql
query getUser {
  user(id: "") {
    id
    email {
      value
    }
    displayFirstName {
      value
    } 
    displayLastName {
      value
    }
    realFirstName {
      value
    }
    realLastName {
      value
    }
  }
}

mutation updateUser {
  updateUser(input: { user: { id: "" email: "" } }) {
    user {
      id
      email {
        value
      }
     displayFirstName {
        value
      }
      displayLastName {
        value
      }
    }
  }
}
