### ISSUE TITLE
Update 'Active' Workflow Notification Recipients

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1746]
When a Project is changed from `Pending Finance Confirmation` to `Active`, the notification should be emailed to all users with the role of `Controller` & projects@tsco.org, in addition to the Project Team.

**Comment by CarsonF** [comment]
Currently we've coded the notifiers to be for all transitions from a step to another. I want to confirm distinct notifiers for from a step to a specific other step (`Active` in this case). That makes sense, it's just a new logical path.

**Comment by sethmcknight** [comment]
@michaelmarshall @ParkeBrown I just got emailed about this issue again, it's starting to turn into a fire. Who could pick this up to insure it gets delivered this sprint?

**Comment by CarsonF** [comment]
Let me just knock it out right now

**Comment by sethmcknight** [comment]
@CarsonF I made a mistake when I originally typed this. We need the following notified anytime this transition happens:

- Users with the role of `Controller`, even if they aren't on the team
- `projects@tsco.org`
- `project_approval@tsco.org`

Sorry for the inconvenience
