### ISSUE TITLE
Uniqueness constraints not enforced on updates

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1754]
## Current Behavior

Not sure how widespread this is but at least `ProjectName` is only being applied at creation. Any changes to the project name do not create new `Property` nodes with the `ProjectName` label. Thus the uniqueness constraint is not enforced

## Expected Behavior

Labels should be applied on update as well as create.

**Comment by blakekrammes** [comment]
We should write a function that takes a property relationship name (or names) to be updated, like `email`, grabs the labels of that property and creates a new property node with those labels. After the new node is created with the labels, mark the labels on the old property node as `Deleted_`. We should probably augment or conjoin the `query.helpers` function `deleteProperties` to accomplish this. This function also takes property relationship names as input.
