### ISSUE TITLE
PRODUCT GOALS: Create branch and model for Product Goals

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1760]

**Comment by CarsonF** [comment]
Waiting on @sethmcknight for input on the product's new steps list

**Comment by sethmcknight** [comment]
Steps for Written Approach:

1. Exegesis and First Draft
2. Team Check
3. Community Testing
4. Back Translation
5. Consultant Check
6. Publish

**Comment by sethmcknight** [comment]
Steps for Oral Translation Approach:

1. Internalization & Drafting
2. Peer Revision
3. Community Testing
4. Back Translation
5. Consultant Check
6. Publish

**Comment by sethmcknight** [comment]
Steps for Oral Storytelling Approach:

1. Craft
2. Test
3. Check
4. Record

**Comment by sethmcknight** [comment]
Steps for Sign Language Methodology:

1. First Draft & Team Check
2. Exegetical Checking
3. Community Testing
4. Reviewing
5. Consultant Check
6. Completed (need a text field or list to select from to define completed)

**Comment by sethmcknight** [comment]
All of the other Products will be a single step that we will track a % complete for.

**Comment by sethmcknight** [comment]
@CarsonF Here are the steps as I know of them today. Some of the wording may change but this should get you started with the model.

**Comment by CarsonF** [comment]
It looks like these steps are a progress reporting metric. So the users will never enter which steps they are picking for the product. But instead they'll say they are this far in the "pipeline". I.e. 4 out of 5 steps done.

 I remember seeing that progress percents needed to be captured by quarter. Is that truly necessary or can we just maintain a history and show when the percentages change?

**Comment by sethmcknight** [comment]
> It looks like these steps are a progress reporting metric. So the users will never enter which steps they are picking for the product. But instead they'll say they are this far in the "pipeline". I.e. 4 out of 5 steps done.

The steps are both a planning and a progress reporting item. For a given project we may plan to Complete the book of Luke, Consultant Check the book of Acts and only Draft the book of Romans.

Users then track their progress in each step. (ideally the actual verses but in the interim just a %)

> I remember seeing that progress percents needed to be captured by quarter. Is that truly necessary or can we just maintain a history and show when the percentages change?

I'm open to discussing how we capture that data in the DB. What we need to keep in mind is that (1) we do not currently require progress to be updated more than once/quarter and (2) the progress information is often reported after-the-fact, so users are reporting when the progress happened regardless of when it's being reported.

**Comment by CarsonF** [comment]
Parent issue #1737

**Comment by CarsonF** [comment]
@sethmcknight for `Completed` what additional info is needed from user?

**Comment by CarsonF** [comment]
Each step has it's own progress info?

**Comment by CarsonF** [comment]
At least one step is required right?

**Comment by sethmcknight** [comment]
> @sethmcknight for `Completed` what additional info is needed from user?

For planning we need a definition of complete. I think we can get that down to a pre-defined list for each Approach.

For we'll also need to capture progress % like we are for the other steps.

**Comment by CarsonF** [comment]
[product-progress](https://github.com/SeedCompany/cord-api-v3/compare/1723-project-reports...product-progress) branch pushed.
