### ISSUE TITLE
Attempt to Add Person to Project Succeeds but Button Shows Still Processing and Name Doesn't Display Till Time Passes

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1771]
Log Rocket log: https://app.logrocket.com/x6d22y/cord-prod/issue/29970216?from=issues&issueType=EXCEPTION

User attempted to add team member to project but delay in display

Additional user details: https://github.com/SeedCompany/management/issues/119

**Comment by CarsonF** [comment]
This is due to a database lock timeout. I'm hoping it gets mitigated with #1764. Other than that there's no direct action for me to take at the moment.
