### ISSUE TITLE
Project Manager Can't View Products

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1772]
There appears to be a permissions configuration issue with the Project Manager role.

A Project Manager has reported they are unable to view Products for Language Engagements of Projects they are not a member of. They should be able to read Products globally, but only write if they are a Member.

Helpdesk Ticket here: SeedCompany/Management#120

**Comment by sethmcknight** [comment]
@ParkeBrown @michaelmarshall Can we get someone to look into this as soon as there is bandwidth?

**Comment by CarsonF** [comment]
The security group [query](https://github.com/SeedCompany/cord-api-v3/blob/9c28a0252deebd8e5114bdedb22ea80e2e5ee250/src/components/engagement/engagement.service.ts#L1108-L1144) for products for returned no records.

Best course of action is to probably update that code to use app permissions instead of DB security groups.

**Comment by ParkeBrown** [comment]
This is another example of someone who might be seeing the same issue and not necessarily knowing it. (Dadiya 2) https://app.logrocket.com/x6d22y/cord-prod/s/4-28ef249c-9684-43bd-be23-1a1d1bcd78b9/4?filters=%255B%257B%2522id%2522%253A%2522ByKphjhSd%2522%252C%2522type%2522%253A%2522email%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522luke_vakis%2540tsco.org%2522%255D%257D%255D&fromTab=latest&t=1617819721015.3152

**Comment by CarsonF** [comment]
Thanks. I've found that database doesn't have the proper permissions setup for these people. This is the old way we are going away from. Updating the code specifically for product list to use new permission strategy.

**Comment by ParkeBrown** [comment]
Original reporting project manager reports being able to see two products but not third. I see it as well.

See log here: https://app.logrocket.com/x6d22y/cord-prod/s/4-45ec6fe0-37fd-4e56-892f-90b8a6b81601/0?filters=%255B%257B%2522id%2522%253A%2522SyJ6wIjLd%2522%252C%2522type%2522%253A%2522href%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522https%253A%252F%252Fcordfield.com%252Fprojects%252F5c4278fe9503d5cd78e83fad%252Fengagements%252F5c4279179503d5cd78e85438%252Fproducts%252F5ea82eab2257df829a28df18%2522%255D%257D%255D&fromTab=latest&t=1618848211551.9507

**Comment by ParkeBrown** [comment]
Bug in sprint backlog for work

**Comment by CarsonF** [comment]
That logrocket shows a crash. Is that the intended one?

**Comment by sethmcknight** [comment]
@CarsonF yeah that's the right one. It's happening on a number of Products.

Here's a representative Product in [Production](https://cordfield.com/projects/5d2de693abc8f499add79463/engagements/5d2de6daabc8f42cfed79505/products/5ebc1159ba4acfa32f555b4f) 

And here's one in [Dev](https://dev.cordfield.com/projects/g26CWMNOcBB/engagements/v18B1JO20lx/products/JEb1pZTmmGU)

**Comment by CarsonF** [comment]
Can we open a new ticket for this in cord-field? It's a separate issue.

**Comment by ParkeBrown** [comment]
Opened here: https://github.com/SeedCompany/cord-field/issues/821
