### ISSUE TITLE
CRUD + List for Ceremony using latest generics and schema

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#178]
Use the user, org, and language service + resolvers as an example.

**Comment by richardgirges** [comment]
This is code complete but E2E tests aren't written yet. E2E tests depend on Engagements CRUD since ceremonies are created by engagements. I will resume work on this task after Engagements CRUD is merged in.

**Comment by michaelmarshall** [comment]
closing, duplicate.
