### ISSUE TITLE
Budget Records Not Updating

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1785]
A Financial Analyst assigned to a Project is unable to update the Budget Records. They are able to edit the Budget Record field but the changes are not saved.

Helpdesk Ticket here: SeedCompany/Management#121

LogRocket session here: https://app.logrocket.com/x6d22y/cord-prod/s/4-70ba530f-49ff-4a15-a5a9-378a3961fd10/16?filters=%255B%257B%2522id%2522%253A%2522Hy-c_jxBO%2522%252C%2522type%2522%253A%2522name%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522Gary%2520Chew%2522%255D%257D%255D&fromTab=latest&network_id=1-xhr-6&network_root_tab_id=d932932a-2fde-4f61-96fc-e6c1e191a346&network_tab_id=d932932a-2fde-4f61-96fc-e6c1e191a346&t=1617042511550.14

**Comment by sethmcknight** [comment]
@ParkeBrown @michaelmarshall Can we get someone to look into this as soon as there is bandwidth?

**Comment by CarsonF** [comment]
Project is active, budget is final. Will update UI to reflect this.
