### ISSUE TITLE
Change to Plan: CR Workflow

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1789]
So far we have CRUD on CRs and we can update/view the project name when in CR mode. Now we need to attach workflow to a CR so that the changes can go through the approval process and be approved or rejected.

1. First review the project workflow API code and then use the FE to step through the entire workflow (use the root admin account).
2. Copy over the functionality of the project workflow. We'll modify it in another ticket, the priority right now is to get a hello world version of change to plan up and running ASAP. This includes the necessary modifications to DTOs, new resolvers, and updating the plan change service to accommodate workflow.

**Comment by elisabeth-sorrell** [comment]
Just saw https://github.com/SeedCompany/cord-api-v3/issues/1738 and it looks like I've prematurely started this. moving back to sprint backlog
