### ISSUE TITLE
Project Manager Can't Change Engagement Status

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1793]
"I can't change the status of the Epie language to Discuss Change to Plan (or any other status). The Ekpeye Cluster is in the process of a change to plan (and I was able to change that status a couple of weeks ago)."

LogRocket Session: https://app.logrocket.com/x6d22y/cord-prod/s/4-ce2d7518-31fc-459c-a0b4-3a11cc054804/0?cursor=1617722720086&fromTab=sessions

**Comment by sethmcknight** [comment]
@ParkeBrown @michaelmarshall Can we get someone to look into this as soon as there is bandwidth?

**Comment by blakekrammes** [comment]
Looking into this.

**Comment by CarsonF** [comment]
https://github.com/SeedCompany/cord-field/blob/master/src/scenes/Engagement/EditEngagement/EngagementWorkflowDialog.tsx#L75-L75

https://github.com/SeedCompany/cord-field/pull/746

**Comment by CarsonF** [comment]
Deploying to prod now
