### ISSUE TITLE
Script to create training data

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1796]
We need a script that creates the kind of data the training team needs. It will also be useful for devs and designers to use in the course of work.

@sethmcknight we need a list of training's requirements for this data set. How many projects? What roles for each project? These can be defined in any way: ratios, simple totals needed, even a list of everything spelled out verbatim.

**Comment by CarsonF** [comment]
Possible library: https://github.com/CyriacBr/class-fixtures-factory
