### ISSUE TITLE
Intern Workflow Prevents User from Advancing Intern from Active to Another State

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1812]
Financial Analyst and Field Project Manager cannot change the intern status from active to another state to close it. 

**Engagement:** https://cordfield.com/projects/5c4279049503d5cd78e847e6 

**Log Rocket log:** https://app.logrocket.com/x6d22y/cord-prod/s/4-b255abe6-2edb-46a9-854e-0bb713c78d33/6?filters=%255B%257B%2522id%2522%253A%2522ByGtDs3ru%2522%252C%2522type%2522%253A%2522href%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522https%253A%252F%252Fcordfield.com%252Fprojects%252F5c4279049503d5cd78e847e6%2522%255D%257D%255D&fromTab=latest

**Comment by sethmcknight** [comment]
@blakekrammes should this be fixed by SeedCompany/cordfield#799 ?

**Comment by CarsonF** [comment]
I think this is fixed by #1815

**Comment by ParkeBrown** [comment]
@CarsonF temporarily reopening because affected user feels they were still experiencing as of end of Friday. Is it possible this change is made but not merged or working?

<img width="1163" alt="Screen Shot 2021-04-12 at 12 03 43 PM" src="https://user-images.githubusercontent.com/5691814/114425953-90f81600-9b87-11eb-9acf-443ef338bf7e.png">

**Comment by CarsonF** [comment]
That was for the dev env @ParkeBrown and a later merge deployed successfully which would've included that code with it. If you hover over the ❌ ✅  you can see the envs by name.

Sounds like we need to further expand the workflow. Prob need to jump on a call with @sethmcknight to determine the best course of action here.

**Comment by ParkeBrown** [comment]
Closing as we'll open a ticket re workflow
