### ISSUE TITLE
Projects > Getting "Cannot read property 'status'" error while the consultant user opens the project

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1819]
**Roles:** Consultant

**Describe the bug**
Projects > Getting `Cannot read property 'status'` error while the consultant user opens the project

**Steps to Reproduce**
1. Login as an admin user
2. Create a project and add a team member as a `consultant` user
3. Login as a consultant user
4. Open project which is created by an admin user

**Expected Result**
The project should be opened or a better error message should be displayed.

**Actual Result**
Getting `Cannot read property 'status'` error while the consultant user opens the project

See video -  

https://user-images.githubusercontent.com/5212585/114139620-e8e71080-992c-11eb-935f-5a604683c4ef.mp4

CordAPIV3# 5d327655

**Comment by CarsonF** [comment]
Stacktraces are always helpful @iPiyushPatel.  You can see those logged in the browser's console and your API process' output.

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
See video for Stacktraces  :

https://user-images.githubusercontent.com/5212585/114378364-7c426080-9b3c-11eb-98a5-1039e23dac65.mp4

I can't attach the HAR file let me know if you need it
Thanks

**Comment by parashara1** [comment]
@iPiyushPatel I was unable to reproduce this bug as well

**Comment by CarsonF** [comment]
```
at ProjectService.currentBudget (components/project/project.service.ts:1135:26)
...
```
@iPiyushPatel I was looking for the console tab. Both there and the API logs have the stacktrace formatted. Posting a stacktrace as text is almost always going to be more helpful than a video.

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
Please find the attached file for logs and let me know if is there any other information needed. 
Thanks! 

**Stacktrace  file:** [Bug1819Stacktraces.txt](https://github.com/SeedCompany/cord-api-v3/files/6308484/Bug1819Stacktraces.txt)

**Comment by ParkeBrown** [comment]
Thanks, Piyush. We've not been able to reproduce it with a couple different people so let's let this one in Seth's someday backlog and keep looking for other ones as you are.

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown @CarsonF @parashara1 
I've verified on latest develop 5f8f59c and can't reproduce this issue
See video :

https://user-images.githubusercontent.com/5212585/134861928-3f9e33bd-e8eb-4cec-b112-b47a3b726b68.mp4
