### ISSUE TITLE
Database throws error when creating user with no email address

### ISSUE THREAD

**Issue by mosesintech** [SeedCompany/cord-api-v3#1822]
## Current Behavior

When attempting to create a new user without an email address, the database will throw an error because of the constraint: `      'CREATE CONSTRAINT ON ()-[r:email]-() ASSERT EXISTS(r.active)',`

The Error:
Neo4jError: Node(###) with label `EmailAddress` must have the property `value`

## Expected Behavior

To create a new user without an email address, since the GraphQL Schema doesn't demand one.
[If email addresses are not required for administrators to create new persons, then the frontend will be receiving a 500 Server Error.](https://github.com/SeedCompany/cord-api-v3/issues/1610)

## Steps to Reproduce
1. In Apollo Studio, Playground, or Neo4j attempt to create a new user without an email address with either the `register` or `createPerson` mutations. 

## Screenshots

![](https://user-images.githubusercontent.com/50815816/114287436-5fb70300-9a2c-11eb-8e31-a8d114c529b9.png)

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466794060) by [Unito](https://www.unito.io)

**Comment by michaelmarshall** [comment]
@mosesintech  You should be able to create a person without an email, correct? Creating a user must still require an email.

**Comment by mosesintech** [comment]
@michaelmarshall, I somehow missed this comment. Apologies.

It looks like both `createPerson` and `register` are using the same function `create`, which requires an email and makes a user. From what I can tell, a `Person` and a `User` are the same to both the frontend and the API. I can't see anything in either that distinguishes one from another, though I could just be overlooking it.
