### ISSUE TITLE
"The project has never been in any of these previous steps" Error

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1826]
User attempts to go to a language page and gets red error message. Appears to apply to multiple languages and users.

Engagement: 5c4278fe9503d5cd78e84333

Report: this appeared in the Ibani project: "The project 5c4278fe9503d5cd78e84333 has never been in any of these previous step: Active..." 

![Screen Shot 2021-04-12 at 3 49 41 PM](https://user-images.githubusercontent.com/5691814/114454121-3e7b2180-9ba8-11eb-9b06-988f544367e2.png)

**Comment by CarsonF** [comment]
Due to https://github.com/SeedCompany/cord-api-v3/commit/7010ed48ca5fddd30ec81de29f5d4606fe50c53f

**Comment by sethmcknight** [comment]
https://app.logrocket.com/x6d22y/cord-prod/s/4-1e3261b4-5d55-4aaa-b1c9-69b1673211f9/0?fromTab=latest&t=1618257005771.4966

**Comment by blakekrammes** [comment]
We need to update those labels to be `Deleted_Property`, right?

**Comment by CarsonF** [comment]
I think I'm just going to remove the match label from the query.

**Comment by blakekrammes** [comment]
Or that works too. My bad. Should've known that this would cause a bug.
