### ISSUE TITLE
Lead FA or FA Can't Enter Disbursement Date

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1829]
Two instances this morning of FA and Lead FA unable to enter disbursement date

One example:
Project: 5c4278fe9503d5cd78e841cd
Log Rocket: [pending]

![114570427-6ff0fd00-9c3b-11eb-80c7-3b5401030631](https://user-images.githubusercontent.com/5691814/114573475-67ea8a80-9c46-11eb-82bd-cd604ca9d3e8.png)

**Comment by CarsonF** [comment]
To be clear, what is the permission change being asked for? Both of these roles have read only access to this property in both the global scope and team membership scope.

**Comment by sethmcknight** [comment]
@CarsonF the Financial Analyst should have Member Edit access, the Lead Financial Analyst should have Global Edit access
