### ISSUE TITLE
Projects From Philippines Displaying as Congo (Kinshasa) and Philippines Not Available as Country Choice

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1833]
**Engagement:** 5c4278e79503d5cd78e838f3
**Log Rocket:**
https://app.logrocket.com/x6d22y/cord-prod/s/4-cfb66c7f-6a6e-4a2f-a021-afb7b0a0873e/0?filters=%255B%257B%2522id%2522%253A%2522r1gugK4IO%2522%252C%2522type%2522%253A%2522href%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522https%253A%252F%252Fcordfield.com%252Flanguages%252F5c4278e79503d5cd78e838f3%2522%255D%257D%255D&fromTab=latest&t=1618406519014.4585

**Comment by ParkeBrown** [comment]
Additional engagement example: https://cordfield.com/languages/5c4278e79503d5cd78e83977

**Comment by CarsonF** [comment]
What's the problem? We don't have a Philippines location currently.

**Comment by sethmcknight** [comment]
> What's the problem? We don't have a Philippines location currently.

@CarsonF that's exactly the problem...` Philippines` existed as a location and a number of Languages & Projects were assigned to that location. Now the location doesn't appear to exist and all of those Languages and Projects seem to be assigned to `Congo (Kinshasa)`. Additionally there are a batch that should be assigned to `Congo (Kinshasa)

**Comment by ParkeBrown** [comment]
User previously changed language name record to incorrect name. Corrected and Seth will reach out for training.
