### ISSUE TITLE
Financial Analyst Can't Change Status of Project to Complete

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1837]
**Engagement:** 5c4279049503d5cd78e8483f and 5c4279049503d5cd78e8493f
**Log Rocket:** https://app.logrocket.com/x6d22y/cord-prod/s/4-4017e762-5589-4f99-9bfc-04c68630ef5e/0?filters=%255B%257B%2522id%2522%253A%2522ByEHmzjLu%2522%252C%2522type%2522%253A%2522href%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522https%253A%252F%252Fcordfield.com%252Fprojects%252F5c4279049503d5cd78e8483f%2522%255D%257D%255D&fromTab=latest&t=1618597875420.5999

**Comment by ParkeBrown** [comment]
Referred to the team

**Comment by ParkeBrown** [comment]
FA is assigned to engagements and workflow seems to indicate they can (https://github.com/SeedCompany/cord-api-v3/wiki/Workflow-%7C-Project), but they get this error when they attempt to do so.
![115253093-0caf1100-a0fa-11eb-9796-1085893f0041](https://user-images.githubusercontent.com/5691814/115257045-be037600-a0fd-11eb-8028-9d207aab6d58.png)

**Comment by sethmcknight** [comment]
bug open here: https://github.com/SeedCompany/cord-api-v3/issues/1823
