### ISSUE TITLE
Administrator Can't Change Language Sensitivity Level

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1838]
**Engagement:** Adia 2 (5eb3be96afd9accc5cabd01d), Khily 2 (5eb3bffdafd9ac1df5abf83e), Melichi 2 (5cd109d41c6585905e873116), Nosko 2 (5e44ed0982792471ee8cbe5f), Dawnu (5c4278fe9503d5cd78e843c3)
**Log Rocket:** https://app.logrocket.com/x6d22y/cord-prod/s/4-c9e164a4-b2cf-4fd8-aa9f-fcf7d0f58993/0?filters=%255B%257B%2522id%2522%253A%2522B1YIIzsUd%2522%252C%2522type%2522%253A%2522href%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522https%253A%252F%252Fcordfield.com%252Fprojects%252F5eb3be96afd9accc5cabd01d%2522%255D%257D%255D&fromTab=latest&t=1618835742417.776
**Description:** Change sensitivity from Med to High at request of FPM & Partner. I am not able to do this: Adia 2, Khily 2, Melichi 2, Nosko 2, Dawnu Cl: Weida, Unda

**Comment by ParkeBrown** [comment]
Administrator goes into language and attempts to change the sensitivity level:
![Screen Shot 2021-04-19 at 11 13 00 AM](https://user-images.githubusercontent.com/5691814/115260325-a5e12600-a100-11eb-9921-1257b5779e16.png)

Receives "Failed to update ethnologue language" error:
![Screen Shot 2021-04-19 at 11 13 17 AM](https://user-images.githubusercontent.com/5691814/115260487-ca3d0280-a100-11eb-8414-1f0343b65229.png)

**Comment by sethmcknight** [comment]
@ParkeBrown I think we have a fix for this that just hasn't been deployed to Product: https://github.com/SeedCompany/cord-api-v3/pull/1836

@michaelmarshall @CarsonF can we get the latest `develop` merged to `master`?

**Comment by ParkeBrown** [comment]
Aditya will test and close after this is merged

**Comment by CarsonF** [comment]
It's live

**Comment by parashara1** [comment]
The latest develop has been merged with master, I have since tested the bug and can confirm that the error does not appear. Changing language sensitivity levels to an existing language as an Admin has no errors anymore.
