### ISSUE TITLE
Add validation to insure `Location Name` is Unique

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1840]

**Comment by CarsonF** [comment]
It is now https://github.com/SeedCompany/cord-api-v3/blob/07630675615f9bb33808d8ff7273585325d5c76c/src/components/location/dto/location.dto.ts#L31-L32
https://github.com/SeedCompany/cord-api-v3/blob/07630675615f9bb33808d8ff7273585325d5c76c/src/components/location/location.service.ts#L37-L43
