### ISSUE TITLE
Project Manager Not Able to Open "Click to Edit" Field to Update Budget Record

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1848]
Project Manager for engagement 5cdadfc2edc5293e5ebe1616 not able to edit FY24 budget by clicking "click to edit" in project in early conversations.

Log Rocket Log: https://app.logrocket.com/x6d22y/cord-prod/s/4-f8cc47e8-0564-4849-986b-7da1aef138e6/0?filters=%255B%257B%2522id%2522%253A%2522r11iO2BPu%2522%252C%2522type%2522%253A%2522email%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522nyanjugu_githui%2540tsco.org%2522%255D%257D%252C%257B%2522id%2522%253A%2522ryEi_nBPO%2522%252C%2522type%2522%253A%2522href%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522https%253A%252F%252Fcordfield.com%252Fprojects%252F5cdadfc2edc5293e5ebe1616%252Fbudget%2522%255D%257D%255D&fromTab=latest&t=1619503049811.8713

Sensitive info: https://github.com/SeedCompany/management/issues/163

**Comment by ParkeBrown** [comment]
Referred to ASMs to replicate

**Comment by ParkeBrown** [comment]
Appears we have another case https://github.com/SeedCompany/management/issues/217

**Comment by ParkeBrown** [comment]
@parashara1 Can you take another pass at reproducing this when you can to see if it is still an issue? Thain isn't seeing this on his local or in code.

**Comment by parashara1** [comment]
Absolutely I’ll get right on that

**Comment by ParkeBrown** [comment]
@tmpacifitech let's considered this blocked. We're checking back in with the user.

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown @CarsonF @parashara1 
I've verified on latest develop 5f8f59c and can't reproduce this issue
See video :

https://user-images.githubusercontent.com/5212585/134863838-43adee2a-902a-4ca9-914e-3a9abf05b65f.mp4
