### ISSUE TITLE
PROJECT: Posts v2

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1851]
Richard is currently researching editors for Posts v2. This Project ticket is to capture any convos around the next iteration of posts.

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466851225) by [Unito](https://www.unito.io)

**Comment by michaelmarshall** [comment]
some thoughts on the new editor/v2 features:
- rich text
- favicons, emoticons, whatever.
- media (youtube, twitter, gifs, etc. ) the more the better but they all may have small differences.
- link preview
- image embed. we would store our own images so this may go with file upload into a v3 if a heavy lift.
- file upload. can be a v3 but something we'll want eventually. will obviously use our already existing codebase/infra to put files and preview in comments.
- @ mentions haven't been discussed yet but i'm sure that'd be a win if the editor has it. not a big deal, could be a v4.

**Comment by michaelmarshall** [comment]
@sethmcknight could you give us a list of priorities to include v2, v3, v4, etc? Thanks.

**Comment by sethmcknight** [comment]
@michaelmarshall here's my initial pass at prioritizing functionality for Posts with 2 caveats.

1. If something further down the list is easy to implement with something higher on the list we can batch those together.
2. I'm biased toward small, iterative releases. I'd value y'alls input on what we makes sense to batch together in releases.

### Future Posts Functionality
- edit/delete
- rich text
- filter posts by `Type` and `Share Setting`
- sort posts by `Date Posted`, `Type`, `Share Setting`, & Poster
- image embed
- file upload
- comments/replies
- @ mentions
- references to CORD items (Project, Language, Engagement, Partner, Product, etc)
- emoji
- gifs & other media
- link preview

**Comment by richardgirges** [comment]
Here are the ones that I'm thinking of, based on the feature requests listed here:

This one provides us with an interface. We're going to have to implement things like "link preview" and "@ mentions" and "references to CORD items" parts ourselves, but I don't anticipate wrestling with the API to get these features done.
https://jpuri.github.io/react-draft-wysiwyg/#/

This might be the better choice, although we have to build the entire WYSIWYG interface ourselves:
https://draftjs.org/

I can vouch for draftjs as I've used it before and it has strong community support, so I believe this is probably the best route to go. It also gives us the most control over building our own custom interface.

Any thoughts or concerns so far?

**Comment by richardgirges** [comment]
Oh, and both of these packages are WYSIWYG frameworks that compile down to Markdown as the internal language
