### ISSUE TITLE
Posts: Update Share Setting Options

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1852]
Rather than a simple Public/Private boolean, we need to give users the ability to select from a set of multiple audience/sharing options.

These will need to be applied in such a way that we can apply different permissions and business rules to Posts based on the Share Setting.

At this time we need 4 options:
- Project Team
- Internal
- Ask to Share Publicly
- Public

**Comment by michaelmarshall** [comment]
@richardgirges I think most of the business rules won't need to be implemented by you. I believe the boolean logic we have now will map directly to this and you won't need to write new queries. So we are moving from a boolean to an enum with 4 options, but I believe `Public:true` maps to `Share.Public` and `Public:false` maps to `Share.ProjectTeam`. The other 2 enum values only have logic that applies when an integration takes data out of Cord and puts it in another system.

**Comment by richardgirges** [comment]
Got it @michaelmarshall so if I'm understanding correctly, I'm going to implement the 4 enums, in place of the current "shareable" boolean. But I won't actually implement `Internal` or `Ask to Share Publicly` and instead just map the true/false boolean logic to the `Public` and `ProjectTeam` enum values respectively.

**Comment by michaelmarshall** [comment]
Yes, but let's go ahead and map `Public:false` to the others. This'll be a v1 for share ability so we can get something in the hands of the beta users. Seth will probably want to queries updated after this but before Posts v2.

**Comment by richardgirges** [comment]
Perfect, this should be quick!
