### ISSUE TITLE
Migration Script for Primary Partner

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1856]
pre-existing Partnerships do not display as a Primary Partner and do not have the option to set a Partnership as the Primary Partner.

We need to apply this to all pre-existing Partnerships and assign the first Managing Partner as the Primary.

**Comment by blakekrammes** [comment]
@sethmcknight when you say first Managing Partner, that's arbitrary, right?

**Comment by blakekrammes** [comment]
Or the first one added?

**Comment by sethmcknight** [comment]
@blakekrammes I thought we were using the first one added in the feed we are sending to DOMO, but whatever the logic was that you and Ken worked out for the DOMO feed of Primary Partner before this field was added is what we should do to assign it to existing Projects.

**Comment by blakekrammes** [comment]
This should be fixed now. I checked projects that were new and old and both are as expected. Don't know if y'all want to do your own manual verification before closing.
