### ISSUE TITLE
createSong > Getting "Could not create song" error while input field "scriptureReferences > end > book " have a "blank" value

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1858]
**Describe the bug**
createSong > Getting `Could not create song` error while input field `scriptureReferences > end > book ` have a `blank` value

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
The valid error message should be returned.

**Actual Result**
Getting `Could not create song` error while input field `scriptureReferences > end > book ` have a `blank` value.

**Note:** Same issue is replicate in create LiteracyMaterial, Story, and Film module.

See video -  

https://user-images.githubusercontent.com/5212585/116870013-5f76e580-ac2f-11eb-9550-2f5018e08ee2.mp4

**GraphQL Query:(createSong)**
![image](https://user-images.githubusercontent.com/5212585/116871799-766b0700-ac32-11eb-8b05-08e2dfcfcd14.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Could not create song",
            "extensions": {
                "codes": [
                    "Server"
                ],
                "status": 500,
                "code": "Server",
                "exception": {
                    "message": "Could not create song",
                    "stacktrace": [
                        "at SongService.create (components\\song\\song.service.ts:138:13)",
                        "at SongResolver.createSong (components\\song\\song.resolver.ts:47:18)"
                    ]
                }
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createSong"
            ]
        }
    ],
```

**Query and Input File**
[createSongBug.txt](https://github.com/SeedCompany/cord-api-v3/files/6414551/createSongBug.txt)

CordAPIV3# 84d680b4

**Comment by ParkeBrown** [comment]
Referred to ASMs

**Comment by parashara1** [comment]
Was able to successfully reproduce the bug after creating the API request with the mentioned notepad file. The output was the same error message, "Could not create song" with a status 500.
