### ISSUE TITLE
Organization list returns wrong total

### ISSUE THREAD

**Issue by blakekrammes** [SeedCompany/cord-api-v3#188]
<img width="462" alt="Screen Shot 2020-03-03 at 5 46 05 PM" src="https://user-images.githubusercontent.com/49688912/75830779-4e0a2300-5d77-11ea-948c-3fb379e6ca5d.png">

**Comment by blakekrammes** [comment]
The same is true for users, which means the bug must be in `propertyUpdater.list`

**Comment by richardgirges** [comment]
@blakekrammes - I'm having some trouble reproducing this, would you mind sending me some example queries that you're running so I can get a solid repro on my end? Are you using filters on some of these queries?

**Comment by blakekrammes** [comment]
@richardgirges, looks like this has been fixed. Just ran again and wasn't getting an inflated total.
