### ISSUE TITLE
Incorrect Language Data for Three Languages

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1881]
These are only related by the reporter at the moment. We can break apart as needed.
- The Yuhup (yab) language in Brazil is missing
- The Hyan (code is?) language in Nigeria is missing
- The Hyam language has an incorrect language code of "jab" vs "yab" (Hyam engagement: 5c4278e79503d5cd78e83618)

User data info: https://github.com/SeedCompany/management/issues/176

**Comment by blakekrammes** [comment]
It looks like Yuhup's display name is Hupde, which comes up in search. The eth code matches. I'm not sure why we're using the display name if it's low sensitivity. I've only heard of using that for sensitive languages.

https://cordfield.com/languages/5c4278e79503d5cd78e83a5e

**Comment by ParkeBrown** [comment]
@njross33 Let's skip the Hyan. It appears that was a typo for Hyam and is not missing. That just leaves a check on Hyam eth code being a sign of something wrong. Since it is a close typo, I'd suggest we don't do too deep a dive.

**Comment by blakekrammes** [comment]
Ok. Just real quick. Hyam's ethCode in the V2 database was "jab" and Yuhup/Hupde's was "yab". I'm wondering if there was a difference in how V2 worked. Anyway, I think the data was migrated as it was in V2. 

<img width="649" alt="Screen Shot 2021-05-17 at 10 58 14 AM" src="https://user-images.githubusercontent.com/49688912/118519513-cfd93880-b6fe-11eb-9cf0-f98300c8d56e.png">

<img width="679" alt="Screen Shot 2021-05-17 at 10 59 10 AM" src="https://user-images.githubusercontent.com/49688912/118519714-fb5c2300-b6fe-11eb-9f2c-5c951a31ea80.png">

**Comment by ParkeBrown** [comment]
@blakekrammes this is very helpful. It confirms it is likely a Data Analytics discussion. I've referred it to them.
