### ISSUE TITLE
Products | Update Mediums: Oral Translation > Trained Story Tellers

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1884]
Change "Oral Translation" to “Trained Storytellers” in the Product Medium options.

We need to make this change in
- FE
- API
- DB

We also need to coordinate with Data Analytics to update DOMO ETL based on this enum change.

**Comment by ParkeBrown** [comment]
@michaelmarshall would you be able to look at this and tell me the cost to period reports roughly if we bump this up to top priority?

**Comment by parashara1** [comment]
PR successfully removes "Oral Translation" and adds "Trained Story Tellers" & "OBS Trainers" to Choose Mediums.

**Comment by ParkeBrown** [comment]
We've referred this to the user to test out. Closing out.

**Comment by blakekrammes** [comment]
Ken needs to look at the ramifications of the change in Domo and get back to me. https://seedcompany.slack.com/archives/GKY4W705D/p1623177810227500
