### ISSUE TITLE
Financial Reports Period Descending Sort Order Inconsistent

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1887]
Beta progress report feature displays financial reports in sequence when sorted descending.

Example: https://dev.cordfield.com/projects/eIM4CNGgybM/reports/financial
<img width="727" alt="Screen Shot 2021-05-21 at 11 07 14 AM" src="https://user-images.githubusercontent.com/5691814/119158963-c6b0da00-ba24-11eb-8d05-58d6a431c64b.png">

**Comment by sethmcknight** [comment]
Resolved for release
