### ISSUE TITLE
Financial Report Card Indicates No Report Available and Shows Now Upload File Link When Financial File is in Detail View

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1888]
Card Example: https://dev.cordfield.com/projects/aZa36FoLD4b
<img width="1114" alt="Screen Shot 2021-05-21 at 11 10 06 AM" src="https://user-images.githubusercontent.com/5691814/119159624-6cfcdf80-ba25-11eb-8179-bd4810a58e36.png">

Detail Example: https://dev.cordfield.com/projects/aZa36FoLD4b/reports/financial
<img width="696" alt="Screen Shot 2021-05-21 at 11 13 11 AM" src="https://user-images.githubusercontent.com/5691814/119159751-8e5dcb80-ba25-11eb-8f97-e735ace67ab8.png">

**Comment by sethmcknight** [comment]
Solved for release
