### ISSUE TITLE
CRUD on Location

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#189]

**Comment by candleshine** [comment]
@michaelmarshall  This ticket should triple in estimate.  There is CRUD for zone, CRUD for Region and CRUD for Country
@ibohalsinghkoijam be aware that the term Country is in flux and will probably change soon.  We are waiting for the users to come back to us with what they want to call it.

**Comment by candleshine** [comment]
@ibohalsinghkoijam 
Implement the functions that are stubbed out.  There is no need for a createLocation function.
