### ISSUE TITLE
Intern Budget Lines Blank Not Allowing Project Manager to Edit

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1891]
1. Project Manager goes to urls:  https://cordfield.com/projects/5c4279049503d5cd78e84811 & https://cordfield.com/projects/5c4279049503d5cd78e8479b
2. Project Manager sees no lines to edit but seems to have MOU dates
![118997855-f85b6f80-b956-11eb-84b3-9cccad616152](https://user-images.githubusercontent.com/5691814/119184373-49489200-ba43-11eb-9647-e1e2c81f3ee6.png)

Sensitive details: https://github.com/SeedCompany/management/issues/182

**Comment by CarsonF** [comment]
There's no funding partnership

**Comment by sethmcknight** [comment]
Seed Company should be assigned as the `Funding` partner for budget records to display.

They are currently only assigned as a `Resource` partner. Changing this should resolve the issue.
