### ISSUE TITLE
Periodic Reports | Stop Auto-Generating Some Folders

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1895]
When we release Periodic Reports we need to stop auto-generating these folders for newly created Projects. We need to maintain these folders for existing Projects.

- [x] Financial Reports
- [x] Narrative Reports
- [ ] ~~Progress Reports~~ (Not generated on project create, but inherited from V2 projects)

**Comment by blakekrammes** [comment]
@sethmcknight we have a folder called `Consultant Reports`. Should that be removed?

**Comment by CarsonF** [comment]
Done in 3f364af7a6c09c4d1b3d4ab781715b228ffa9096
