### ISSUE TITLE
Periodic Reports | Change Timing of Report that Displays on Card

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1897]
We may need to change the way we select which report displays on each report card.

Most likely we will show the Previous reporting periods report.
- Quarterly we will show Q2 during Q3
- Monthly we will show Month 6 during Month 7

**Comment by sethmcknight** [comment]
Update on the timeframes that we show.

Quarterly
- The Reporting Period displayed one the card should be one quarter behind

Monthly
- The Reporting Period displayed on the card should be

**Comment by CarsonF** [comment]
In talking with @sethmcknight:
The reports will never be uploaded until after the period ends. Like submitting a time card for 2 weeks, you can’t do it until after the 2 weeks are done. So the current report due is always the previous period. So I think both of those words are important. So how about `current(Narrative|Progress|Financial)ReportDue` and `nextXReportDue` for the names.
Now the actual due date is a month after the report period ends. This IMO is still business logic so I’d like it in the API. It could easily be a field resolver called dueDate that just adds a month to the endDate.

Seth says we want to show the current & next report due for the entire reporting period. So these are always just a report behind, completely separate from +1 month logic.

**Comment by sethmcknight** [comment]
Fixed in SeedCompany/cord-field#853
