### ISSUE TITLE
sensitivity on language

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#190]
Add sensitivity to language DTOs. Get with Carson for an explanation.

**Comment by elliottcrif** [comment]
I think this has been already completed and should be closed out. I believe @CarsonF has already added the sensitivity to language DTO's

**Comment by elliottcrif** [comment]
It might just need to be added to `create-language.dto.ts` and `update-language.dto.ts`

**Comment by sethmcknight** [comment]
@CarsonF @michaelmarshall is this done or does it still need to be done?

**Comment by CarsonF** [comment]
Closed by #1182
