### ISSUE TITLE
Budget Records return list of nulls when not allowed to see BudgetRecord list

### ISSUE THREAD

**Issue by elisabeth-sorrell** [SeedCompany/cord-api-v3#1910]

**Comment by ParkeBrown** [comment]
@elisabeth-sorrell it might not hurt to do a quick skim of the board for budget. Sounds like there is some possible crossover here, but perhaps not.
https://github.com/orgs/SeedCompany/projects/4?card_filter_query=budget

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown yeah, I think of it as kind of a technical debt ticket from https://github.com/SeedCompany/cord-api-v3/issues/1874. A cousin ticket :)
