### ISSUE TITLE
createPartnership > uploadFile > Returned "application/octet-stream" mime type when Uploading png file

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1911]
**Roles:** Administrator

**Describe the bug**
createPartnership > uploadFile > Returned `application/octet-stream` mime type when Uploading png file

**Steps to Reproduce**
1. Create Organization
2. Create Partner
3. Request file URL
4. Upload  `image.png` file on Requested URL
5. Hit Create Partnership Request without mimeType
6. Repeat step 1 to 4 and then after hit the create partnership requests with mimeType input

**Expected Result**
Valid mimeType should be returned as per file type

**Actual Result**
Returned `application/octet-stream` mime type when Uploading png file.

**Note:** Same issue is replicate for video/mp4 file type.

See video -  

https://user-images.githubusercontent.com/5212585/120429230-a8d36580-c392-11eb-9ae7-e4113f5b4b5e.mp4

**GraphQL Query:(without mimeType)**
![image](https://user-images.githubusercontent.com/5212585/120429416-f8199600-c392-11eb-8d10-a7d90f0b54d4.png)

**GraphQL Query:(with mimeType)**
![image](https://user-images.githubusercontent.com/5212585/120429635-5c3c5a00-c393-11eb-8da3-0c512e509793.png)

**GraphQL Query:(Requested URL)**
![image](https://user-images.githubusercontent.com/5212585/120431965-d8846c80-c396-11eb-8330-4bc8cead2fb8.png)

**GraphQL response**
```
{
    "data": {
        "createPartnership": {
            "partnership": {
                "id": "bTWeqmBdsOs",
                "createdAt": "2021-06-02T11:12:40.116+05:30",
                "canDelete": true,
                "types": {
                    "value": [
                        "Managing"
                    ],
                    "canRead": true,
                    "canEdit": true
                },
                "agreementStatus": {
                    "value": "NotAttached",
                    "canRead": true,
                    "canEdit": true
                },
                "mouStatus": {
                    "value": "NotAttached",
                    "canRead": true,
                    "canEdit": true
                },
                "mouStart": {
                    "value": "2021-06-01",
                    "canRead": true,
                    "canEdit": false
                },
                "mouEnd": {
                    "value": "2021-06-01",
                    "canRead": true,
                    "canEdit": false
                },
                "mouStartOverride": {
                    "value": "2021-06-01",
                    "canRead": true,
                    "canEdit": true
                },
                "mouEndOverride": {
                    "value": "2021-06-01",
                    "canRead": true,
                    "canEdit": true
                },
                "mou": {
                    "canRead": true,
                    "canEdit": true,
                    "value": {
                        "id": "3PBKIz7G6tH",
                        "createdAt": "2021-06-02T11:12:40.178+05:30",
                        "type": "File",
                        "mimeType": "application/octet-stream",
                        "name": "MOU",
                        "size": 0,
                        "modifiedAt": "2021-06-02T11:12:40.258+05:30",
                        "downloadUrl": "http://localhost:3000/file?signed=%7B%22operation%22%3A%22getObject%22%2C%22key%22%3A%22vIwrO89Vg9M%22%2C%22expires%22%3A1622613461894%7D",
```

**Query and Input File**

[mimeTypeBug.txt](https://github.com/SeedCompany/cord-api-v3/files/6582278/mimeTypeBug.txt)

CordAPIV3# 86351d50

**Comment by CarsonF** [comment]
The problem is on step No. 4. You don't show it in the video but I'm guessing you aren't sending the `Content-Type` header with that POST request. We, like S3, default to `application/octet-stream` when this isn't provided.

**Comment by iPiyushPatel** [comment]
got it, thanks for the info @CarsonF
