### ISSUE TITLE
Periodic Reports | Date Report Received

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1924]
Add an input field for ` Date Received` when a user is submitting a Periodic Report. This should be a date field that is manually input by the user.

It would also be nice if we can add the date and record that a report was received, without having to upload a file.

**Comment by blakekrammes** [comment]
@sethmcknight I'm guessing `Date Received` should be visible and editable in the report list view?

**Comment by blakekrammes** [comment]
And for `Date Received`. Should it include the time when the report was received or just the date? Carson was thinking it could be helpful to have more info.

**Comment by CarsonF** [comment]
I was thinking it was an override for when an action took place - report uploaded, thus a date time. I figured field had the time when the email was received.

**Comment by sethmcknight** [comment]
@blakekrammes yes this should be visible/editable in the report list view as well as the report submission view. Based on conversations with Field Ops this should be a simple Date field, we don't need date-time.

@CarsonF this is not an override for the report uploaded date-time, but a secondary field to track when we consider the report received from the Managing Partner.

**Comment by blakekrammes** [comment]
@sethmcknight should `Date Received` be optional?

**Comment by sethmcknight** [comment]
@blakekrammes yes, it would be best to have it be optional

**Comment by CarsonF** [comment]
Also it should be set to now if the first file is uploaded and this left blank.

**Comment by blakekrammes** [comment]
It seems like it should just be left blank if it's a distinct/secondary data point? @sethmcknight ^

**Comment by CarsonF** [comment]
I think they should be set in the same request. When you are uploading the file, you set received date... That does require some UI changes to do file upload & extra data but this seems best.

**Comment by blakekrammes** [comment]
I like setting the date along with the file upload. I still think that may lead to data confusion if you default received date to the file upload time. It may get set automatically and then users might assume it's the correct date when in fact there's another date.

**Comment by CarsonF** [comment]
Sounds like a user problem. What do you think @sethmcknight?

**Comment by sethmcknight** [comment]
I would:

1. Make Date Received a required field
2. If Date Received does not exist default to null (but require input to submit)
3. If Date Received exists default to the existing data and allow submission.
4. When users click to open a calendar date view we can default the option to today

@CarsonF @blakekrammes 

Let me know if a quick call would help

**Comment by blakekrammes** [comment]
So if a user is just uploading a file, they can select "No report received date" or something similar, which will default to null, or enter a calendar date.

**Comment by CarsonF** [comment]
No Seth is saying they must enter a date.

**Comment by sethmcknight** [comment]
@blakekrammes sorry I wasn't more clear, I'll try to clarify.

- Date Received must be entered.
- If a report already has a Date Received (ie a Report has already been submitted for that reporting period), show that date and keep it unless the user submitting a new version manually changes the Date Received.
- For any Report being submitted that does not have a Date Received, make the user manually select a date before they can submit.

**Comment by blakekrammes** [comment]
@sethmcknight do you want to show submitted date (file upload date) and received date?

<img width="1347" alt="Screen Shot 2021-07-15 at 6 28 36 PM" src="https://user-images.githubusercontent.com/49688912/125870253-6842a5fe-5da2-4651-936a-d21d0a7c288c.png">

**Comment by sethmcknight** [comment]
@blakekrammes yes

**Comment by blakekrammes** [comment]
FE PR: https://github.com/SeedCompany/cord-field/pull/901
