### ISSUE TITLE
Update Postman files in docs folder

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#193]

**Comment by iPiyushPatel** [comment]
Hi @michaelmarshall 

I've created new branch 'cord-api-193' and pushed the required files. It is under /docs folder, Snap below. Let me know if any questions.

![image](https://user-images.githubusercontent.com/5212585/76101055-ca109f00-5ff3-11ea-8b86-f47d8f9e731a.png)

Thanks!
