### ISSUE TITLE
Lead Financial Analyst gets "Could not find Translationproject.ReportPeriod to update" error when trying to change partner reporting frequency

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1941]
I am trying to update the reporting frequency for a new project (needs to be quarterly). But, I got the error below. 

![121562926-8cad7500-c9df-11eb-9890-ca16298511d1](https://user-images.githubusercontent.com/5691814/121699192-b8426500-ca9c-11eb-94e8-ab3260b0b7c0.png)

**Engagement:** https://cordfield.com/projects/5f3ab1c8e03be53606de4126

**Log Rocket Log:** https://app.logrocket.com/x6d22y/cord-prod/s/4-05a57ba0-c571-4797-b008-f1a58dc6b08f/42?filters=%255B%257B%2522id%2522%253A%2522BkhPBp1sO%2522%252C%2522type%2522%253A%2522href%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522https%253A%252F%252Fcordfield.com%252Fprojects%252F5f3ab1c8e03be53606de4126%2522%255D%257D%255D&fromTab=latest

**Support Details:** https://github.com/SeedCompany/management/issues/196

**Comment by ParkeBrown** [comment]
@parashara1 this user bug could stand a test to flesh out more details before the developers dive in

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown @CarsonF @parashara1 
I've verified on the latest develop 5f8f59c and can't reproduce this bug.
See video :

https://user-images.githubusercontent.com/5212585/134861035-56f6d433-8e3d-4ba9-bccf-530c72e726b2.mp4

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown @CarsonF @parashara1 @daniel-leod 
I've verified on the latest develop 5f8f59c and can't reproduce this issue
See video :

https://user-images.githubusercontent.com/5212585/134861035-56f6d433-8e3d-4ba9-bccf-530c72e726b2.mp4
