### ISSUE TITLE
Project > Budget > User can edit budget amount  value even user have only "Global R" access and value is not saved which is entered by the user

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1947]
**Roles:** Consultant Manager

**Describe the bug**
Project > Budget > User can edit budget amount  value even user have only `Global R` access and value is not saved which is entered by the user

**Steps to Reproduce**
1. Login as Admin user
2. Create a project and go to the project detail page
3. Add `Consultant Manager` as a team member
4. Login as a Consultant manager user
5. Open Project which is created by an admin user
6. Add `Start - End` date
7. Click on the `Add Partnership` button and add the `Funding` type of Partner 
8. Click on the `Budget` button 

**Expected Result**
User should not be allowed to edit budget details if he is having global R access only 

**Actual Result**
User can edit budget amount  value even user have only `Global R` access and value is not saved which is entered by the user

**Note:**  Working fine for `Fundraising` user
 
See video - 

https://user-images.githubusercontent.com/5212585/122224823-1d012380-ced2-11eb-9f5c-9633e52fbaf0.mp4

![image](https://user-images.githubusercontent.com/5212585/122225039-533ea300-ced2-11eb-9df7-21fc6074fd10.png)

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 8e5bf458

**Comment by iPiyushPatel** [comment]
@CarsonF @parashara1 

Currently, we got this type of behavior with the latest develop 0395794 Attaching a video & link [CORD Field | Sensitive Field Permissions
](https://docs.google.com/spreadsheets/d/1GBAyYtzztRGgdIJY44XI27obITYCEDkxY_mLk9IS4jE/edit#gid=1648651465) for reference. Thanks! 

See video :

https://user-images.githubusercontent.com/5212585/132692962-acea615a-96d1-4f61-8663-389003fc737e.mp4

![image](https://user-images.githubusercontent.com/5212585/132693331-35cd135e-26cb-4f7f-b943-092b0561499c.png)

**Comment by CarsonF** [comment]
@iPiyushPatel Are you saying it's still wrong? Or the functionality matches the spreadsheet?

**Comment by iPiyushPatel** [comment]
@CarsonF 

Yes it is still wrong as `Consultant Manager` is a member of the Project and has `Global Read` access, still, he can't view budget information.
