### ISSUE TITLE
G&P | Partner Producing Medium

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1949]
For each Medium a goal is being produced in, select the Partner responsible for production

This is an optional field.

**Comment by sethmcknight** [comment]
Based on Partnerships

**Comment by ParkeBrown** [comment]
@sethmcknight Carson needs additional information here

**Comment by sethmcknight** [comment]
> @sethmcknight I believe this is what we previously discussed, confirm/correct:
> 
> * For each medium selected, a single partner (on the project) should be able to be selected (in product form).
> * We'll show this on the product detail page
> * Partners producing medium is not unique to/different per product. It's unique per engagement.
>   
>   * Therefore, changing "Print" on one product will change it for all products in the engagement.

Yes this sounds correct
