### ISSUE TITLE
createProjectMember > Multiple error message returned  while user give mismatch parameter value for "useriD" and "projectId" from input 

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1968]
**Roles:** ProjectManager

**Describe the bug**
createProjectMember > Multiple error message returned  while user give mismatch parameter value for `useriD` and `projectId` from input 

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
The single error message should be returned for one field

**Actual Result**
Multiple error message returned  while user give mismatch parameter value for `useriD` and `projectId` from input 

See video -  

https://user-images.githubusercontent.com/5212585/123074926-5fc47d80-d435-11eb-8a00-64fc01a01a99.mp4

**GraphQL Query:(createProjectMember )**
![image](https://user-images.githubusercontent.com/5212585/123076191-846d2500-d436-11eb-84a7-4a4c92cb1f39.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Variable \"$input\" got invalid value { userId1: \"R7xHyGwoB7e\", projectId: \"aH2hDazYjcW\", roles: \"ProjectManager\" } at \"input.projectMember\"; Field \"userId\" of required type \"ID!\" was not provided.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "codes": [
                    "GraphQL",
                    "Client"
                ]
            },
            "locations": [
                {
                    "line": 1,
                    "column": 30
                }
            ]
        },
        {
            "message": "Variable \"$input\" got invalid value { userId1: \"R7xHyGwoB7e\", projectId: \"aH2hDazYjcW\", roles: \"ProjectManager\" } at \"input.projectMember\"; Field \"userId1\" is not defined by type \"CreateProjectMember\". Did you mean \"userId\"?",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "codes": [
                    "GraphQL",
                    "Client"
                ]
            },
            "locations": [
                {
                    "line": 1,
                    "column": 30
                }
            ]
        }
    ],
```

**Query and Input File**
[BugProjectMember.txt](https://github.com/SeedCompany/cord-api-v3/files/6700844/BugProjectMember.txt)

CordAPIV3# da1255f9

**Comment by CarsonF** [comment]
This is working as intended. While the API commonly gives back a single error, it is an array of errors for a reason. Multiple errors are allowed.

In this case specifically it's very hard for a machine to know that you've given an input that's intended to be used as one parameter but has been misspelled. Therefore there's two errors: a missing parameter, and an extra, unknown one.
