### ISSUE TITLE
Periodic Reports | "Could not find `TranslationProject.financialReportPeriod` to update"

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1970]
Users are unable to change the Financial reporting frequency from Monthly to Quarterly.

When attempting to make this change users receive an error "Could not find `TranslationProject.financialReportPeriod` to update"

This occurs even when signed in as an Admin.

This is a significant and urgent bug. Every project in CORD was defaulted to monthly, but in some regions almost every project and internship are quarterly. Those reports will start arriving in July. 

Users need to update the reporting frequency of each project from monthly to quarterly before submitting those financial reports.

**Comment by sethmcknight** [comment]
seedcompany/management#204

**Comment by CarsonF** [comment]
This should be fixed now.
