### ISSUE TITLE
Partner List sort is incorrect

### ISSUE THREAD

**Issue by elisabeth-sorrell** [SeedCompany/cord-api-v3#1986]
When sorting partners in ascending order, they sort by `createdBy` instead of by partner name. They should be sorted by organization `name`

**Comment by CarsonF** [comment]
This might've been fixed with a0b0c8baa6a7379377d9862f8422a98144fbdcd8

**Comment by CarsonF** [comment]
Or definitely this https://github.com/SeedCompany/cord-field/pull/940
