### ISSUE TITLE
SearchBar > Getting "Invalid Regex: Unmatched closing ')' near index 5 (?i).*))).* ^" error when user enter special characters in searchTextbox

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1987]
**Roles:** All

**Describe the bug**
SearchBar > Getting `Invalid Regex: Unmatched closing ')' near index 5 (?i).*))).* ^` error when user enter special characters in searchTextbox

**Steps to Reproduce**
1. Login as Admin user
2. Enter data in "SearchTextBox"

**Expected Result**
A proper validation message should be displayed

**Actual Result**
Getting `Invalid Regex: Unmatched closing ')' near index 5 (?i).*))).* ^` error when user enter special characters in searchTextbox.

See video - 

https://user-images.githubusercontent.com/5212585/122047923-4f415100-cdfe-11eb-862f-34fb1bc0aaba.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 8e5bf458

**Comment by CarsonF** [comment]
Fixed #2098
