### ISSUE TITLE
Posts | Migrate 87six Comments & Prayer Requests to CORD Field Project Posts

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1999]
Migrate array of historic 87six comments & prayer requests to Project Posts.

1) Project description > Note
2) Project proposal > Note
3) Project prayer requests > Prayer

**Comment by blakekrammes** [comment]
@sethmcknight what should the shareability of these posts be? Should it be base on the project's sensitivity?

**Comment by sethmcknight** [comment]
@blakekrammes let's just set all of the Note's to 'Internal' and the prayer requests to 'Ask To Share Externally'
