### ISSUE TITLE
CreatePost > Returned "A post must be associated with a parent node." error while the user removed "ParentID" from the input value

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2002]
**Roles:** All 

**Describe the bug**
CreatePost > Returned `A post must be associated with a parent node.` error while the user removed `ParentID` from the input value

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
A relevant error message should be displayed.

**Actual Result**
Returned `A post must be associated with a parent node.` error while user removed `ParentID` from the input value

**Note:** Expected as per update project request.

See video -  

https://user-images.githubusercontent.com/5212585/124715703-e6db2080-df20-11eb-90ad-9ccaadc7d1d0.mp4

**GraphQL Query:(createPost)**
![image_2021_07_07T06_51_58_262Z](https://user-images.githubusercontent.com/5212585/124715744-f0648880-df20-11eb-9857-382890c29139.png)

**GraphQL response**
```
 {
    "errors": [
        {
            "message": "A post must be associated with a parent node.",
            "extensions": {
                "codes": [
                    "Server"
                ],
                "status": 500,
                "code": "Server",
                "exception": {
                    "message": "A post must be associated with a parent node.",
                    "stacktrace": [
                        "at PostService.create (components\\post\\post.service.ts:76:13)",
                        "at PostResolver.createPost (components\\post\\post.resolver.ts:34:18)"
                    ]
                }
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createPost"
            ]
        }
    ],
```

**Query and Input File**
[createpost.txt](https://github.com/SeedCompany/cord-api-v3/files/6775115/createpost.txt)

CordAPIV3# 136c06a1

**Comment by CarsonF** [comment]
Looks like we just need to change the DTO to require this field.
