### ISSUE TITLE
G&P | Import Historic Data from Catalogue of Books

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2009]
Import historic data for Goals & Progress from this spreadsheet: https://drive.google.com/file/d/1DBUZkPwZItE6QBTvoAowKIePXCZRP4Ya/view

We will need to follow up with Data Analytics to get an updated spreadsheet for the final version.

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466872822) by [Unito](https://www.unito.io)

**Comment by sethmcknight** [comment]
How do we capture a number of verses that are an unknown range?

**Comment by CarsonF** [comment]
- (C) Project Name
  - Ignored
- (D)Project ID #
  - Match as `departmentId`
- (E) TSC Field Name
  - Language name. Match engagement based on this.
- (F) Methodology (nullable) 
  - Bible Stories - StoryTogether?
  - Bible Storying - SeedCompanyMethod?
  - Film - Film
  - OneStory - OneStory
  - Other (Oral Stories) - OtherOralStories
  - Other (Oral Translation) - OtherOralTranslation
  - Other (Written) - OtherWritten
  - ParaText - Paratext
  - Render - Render
  - Sign Language - SignLanguage
- (G) Medium (nullable, csv)
  - Simple match to our enum: `App`, `Audio`, `E-book`, `Other`, `Print`, `Video`, `Web`
- (H) Jesus Film (nullable)
  - If `1`, find Jesus Film film and create derivative with it
- (I) Stories (nullable)
  - This is all over the place. I'm not sure what to do here. 
  - Ideally we create/match a story and create derivative product from it, but that requires a "name"
  - We could capture as _other products_ with the title as given & try to parse the number as the progress target
  - Value sampling:
    - `#`
    - `#+`
    - `#-#`
    - Named Stories, CSV
    - `# Topical/Bible/Situational/Words of Wisdom/Evangelistic`
- (J) Songs
  - Same assumed conversion and problem as Stories
  - Values here are only total song count
- (K-BX) Bible Book Name
  - Each of these columns should lead to to their own direct scripture products. Unless a story/song as been specified, in that case they can be ranges on producible (if it ends up becoming a producible and not other).
  - `1` means full book
  - `# verses` can map to new `unspecifiedScripturePortion` field. Need to be loose with matching here. Some have uppercase V others don't. Some have line breaks others just have spaces. Some have no space.
  - `1 & The Greatest Gift` - Is this the full book & a story?
  - `2:4-25` scripture range we should parse
  - `21 Stories` - Ignore. It has 21 in stories column so whatever we decide for that.
  - `Chapters/Chps/Chpt/Chpts/Ch {range}` scripture range we should parse. Just need to fuzzy ignore that "chapter" prefix. Could be separated with new line, space, or no space, just like verse.
  - `Gen Chpts 1-20` I guess we need to fuzzy match "chapter" and then ignore anything before it.
  - `Publish`, `Publish by 2020` - Ignore?
  -  Ignore, meaningless to us
  - Unspecified blurb - Ignore as there's nothing we can do with this
    - `Selected Verses`
    - `Several Chpts & verses`
    - `Several Chtps & verses`
    - `Various Verses`
  - `History` - Ignore?
  - `Gideon` - Ignore?
  - `Psalms Selections` - Ignore?
  - `Gospel Selections` - Ignore?
  - `Revision of Luke` - Ignore?

- Verse formats we need to parse
  - `5`
    - Chapter 5 (full)
  - `3:1`
    - Chapter 3 verse 1
  - `6:8-23`
    - Chapter 6 verses 8-23
  - `1-8`
    - Chapters 1-8
  - `4:35-5:43`
    - Chapter 4 verse 35 to chapter 5 verse 43
  - `17:1,7-24`
    - Is this chapters or verses 7-24? Can assume or do we need to guess? If so, maybe based on what chapters/verses are actually available?
  - `1:1, 52` same question as above
  - `71\n:20-21\n103:13`
    - This is tricky because the first line break should be ignored, but the second one is the split for the separate range.
    - This should be parsed as chapter 71 verses 20-21 and chapter 103 verse 13.
  - `3&6`, `3 & 6`
    - Chapter 3 and Chapter 6
  - [`26-27-28\nSeveral verses`](https://docs.google.com/spreadsheets/d/1DBUZkPwZItE6QBTvoAowKIePXCZRP4Ya/edit#gid=392934339&range=AX675)
    - Is this several verses of those 3 chapters? If so, probably ignore?
  - ```
    Chpts
    8:1-11
    10:1-18,
    22-42
    14:1-14
    18:8-40
    ```
    - Looks like comma is another verse range on chapter 10
    - Not sure if comma separation always means this
  - ```
    Chpt 1:
    26-33,
    2:1-18,
    15:1-7,
    11-24
    ```
    - Commas seem to separate chapters, not verse ranges of a previously specified chapter
  - `8:1b-25`
    - We don't currently support partial verses. Can we just assume full verse 1-25?
  
@sethmcknight can you comment on these `?`s and generally confirm correct info or update anything wrong?
