### ISSUE TITLE
Notification emails for Training env

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#2018]
We need the training env to send emails for project step changes, but we don't want to spam prod email accounts. I'd like to determine if we can use a couple env vars to toggle the sending of project step changes to a single training email. So there'd be a ENV=training var, and a NOTIFICATION_OVERRIDE=training@tsco.org var to redirect all training. Let's discuss if this meets training's needs and is a light lift.

**Comment by ParkeBrown** [comment]
Discussion here: https://seedcompany.slack.com/archives/GKY4W705D/p1626102068055900

**Comment by sethmcknight** [comment]
It would also be helpful to have some type of warning/banner in non-prod emails noting the environment they came from

**Comment by CarsonF** [comment]
I've re-enabled step change notifications for training env. Notifying distribution list stills everything that's disabled.

Seth open a new ticket for that.
