### ISSUE TITLE
Periodic Reports | Closing Report

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2026]
After the close of a Project we receive a final set of reports to close out the Project. We need to provide a way to capture these reports that are received after the close of the Project.

Specifically for Financial Reports, we receive a report for the final reporting period with the balances listed, then we receive a final 'zero balance' report once all funds have been settled and repatriated.

**Comment by ParkeBrown** [comment]
Need more information on when report should be shown as due

**Comment by CarsonF** [comment]
I think it makes sense to just add one more at the end of the list that starts/ends as the end date of the project. So the range is empty.
