### ISSUE TITLE
Project > ChangeRequest > Getting "The project AeclOsV1kKx has never been in any of these previous steps: Active, ActiveChangedPlan" error when user change project status

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2037]
**Roles:** Admin

**Describe the bug**
Project > ChangeRequest > Getting `The project AeclOsV1kKx has never been in any of these previous steps: Active, ActiveChangedPlan` error when user change project status

**Steps to Reproduce**
1. Login as Admin user
2. Create a project and Open created project
3. Update project status `Earlyconversation` to `Active` and  Add change request
4. Select `Time` type and Click on the `View` button
5. Update project status `Active`  to `Finalize Completion` and Refresh the page

**Expected Result**
Project status should be changed.
 
**Actual Result**
 Getting `The project AeclOsV1kKx has never been in any of these previous steps: Active, ActiveChangedPlan` error when user change project status

**Note:**
`Discuss Change to Plan` and `Discuss Termination` status also give similar types of errors.

**Stacktraces:**
```
{
  "errors": [
    {
      "message": "The project JtSP5RoQND8 has never been in any of these previous steps: Active, ActiveChangedPlan",
      "extensions": {
        "codes": [
          "Server"
        ],
        "status": 500,
        "code": "Server",
        "exception": {
          "message": "The project JtSP5RoQND8 has never been in any of these previous steps: Active, ActiveChangedPlan",
          "stacktrace": [
            "at ProjectRules.getMostRecentPreviousStep (components/project/project.rules.ts:1005:13)",
            "at ProjectRules.getStepRule (components/project/project.rules.ts:751:19)",
            "at ProjectRules.getNotifications (components/project/project.rules.ts:925:48)",
            "at ProjectStepChangedNotificationHandler.handle (components/project/handlers/step-changed-notification.handler.ts:33:24)",
            "at SyncEventBus.publish (core/events/event-bus.service.ts:24:7)",
            "at ProjectService.update (components/project/project.service.ts:378:5)",
            "at ProjectResolver.updateProject (components/project/project.resolver.ts:286:21)"
          ]
        }
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateProject"
      ]
    }
  ],
```

See video - 

https://user-images.githubusercontent.com/5212585/126274597-70a79c62-2dd3-4be6-a0e3-e7f75c0808cc.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 02d4604
CordAPIV3# 6073305

**Comment by daniel-leod** [comment]
Fixed by #2186
