### ISSUE TITLE
Completion Description searching with symbols fails

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2050]
**Roles:** All

**Describe the bug**
createProduct > Completion Description > Getting `Failed to invoke procedure db.index.fulltext.queryNodes: Caused by: org.apache.lucene.queryparser.classic.ParseException: ` error while user enter special character

**Steps to Reproduce**
1. Login as an Admin user
2. Create a project and add a `language engagement`
3. Click on the `view details` button and Add `Product`  
4. Select a `Methodology` and Enter data in `Completion Description`

**Expected Result**
Proper Validation message should be displayed

**Actual Result**
Getting `Failed to invoke procedure db.index.fulltext.queryNodes: Caused by: org.apache.lucene.queryparser.classic.ParseException: ` error while user enter special character

**Note** 
Getting error in given special character.`!,^,(,),-,+,[ , ]` 

See video - 

https://user-images.githubusercontent.com/5212585/127323092-8c99d5bc-daa1-40c6-b146-de6b51c61d54.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 95ffcd0

**Comment by CarsonF** [comment]
Ok an oversight was the query parameter of `db.index.fulltext.createNodeIndex` is actually Lucene syntax. This gives us more power but now we need to convert user input from simple string to valid Lucene syntax.
