### ISSUE TITLE
Goals & Progress | Parse Step Progress from PnP

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2055]
When a new Progress Report PnP is uploaded to an Engagement's Progress Report for a specific Period, parse the PnP Spreadsheet to pull the Progress for each Step on each Goal.

If the Progress for a Step is updated in CORD, write it back to the PnP spreadsheet.

**Comment by sethmcknight** [comment]
Here is an example of the PnP Spreadsheet to Parse as an .xlsx file: ExamplePnP.xlsx

The actual PnP is an .xlsm file, if an example in that format is needed please reach out to me. .xlsm files cannot be attached to GitHub issues.

Parsing for Progress should be based on the most current version of each Progress Report. We want to parse and save this data for each reporting period.

In the PnP Workbook you will look at the 'Progress' tab.

Start on row 23 and go through row 88 or until a merged cell for columns Q-Z is encountered.

Each row is a Goal. We need to match an existing Goal for each row. Parsing should pull and update the step progress for each Goal.

First look at columns P & Q. Use this combination to match an existing Goal.
Column P: Book Name
Column Q: Total Verses

Then look at each Step's progress data to parse and update the step progress for that Goal in CORD. Step progress on the PnP is recorded in percentages of 25%, 50%, 75% or 100%. 

When a step is 100% complete, the PnP records this with the quarter is was completed in. If Q1, Q2, Q3, or Q$ are found in a cell for step progress the step's progress in CORD should be set to 100%.

Columns for Step Progress:
Column R: Exegesis & First Draft
Column T: Team Check
Column V: Community Testing
Column X: Back Translation
Column Z: Consultant Check
Column AB: Completed

**Comment by sethmcknight** [comment]
@CarsonF updated with example PnP and info on the cells to parse. This should be ready to work.

**Comment by CarsonF** [comment]
Doesn't look like the file was attached

**Comment by sethmcknight** [comment]
🤦🏼 fixed it

**Comment by CarsonF** [comment]
See [ExtractPnpFileOnUploadHandler](https://github.com/SeedCompany/cord-api-v3/blob/08f111e3953adf33088cb1e96e59cc5b65b8b21d/src/components/progress-summary/handlers/extract-pnp-file-on-upload.handler.ts) and [ProgressExtractor](https://github.com/SeedCompany/cord-api-v3/blob/08f111e3953adf33088cb1e96e59cc5b65b8b21d/src/components/progress-summary/progress-extractor.service.ts) for examples of how similar data is extracted and saved. This data should be able to be persisted via https://github.com/SeedCompany/cord-api-v3/blob/08f111e3953adf33088cb1e96e59cc5b65b8b21d/src/components/product-progress/product-progress.service.ts#L52-L52

**Comment by blakekrammes** [comment]
I'm available to do a knowledge transfer if necessary too for whoever picks this up. I wrote ye olde P&P parsing code. It should be pretty straightforward, but sometimes the column name you see in the spreadsheet doesn't match the column when you're parsing through the data. Just make sure that the data you're expecting (from the visible spreadsheet) is that data you're pulling when parsing.
