### ISSUE TITLE
Register Login > Email field validation message is not returned while a user leaves a blank email field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2058]
**Describe the bug**
Register Login > Email field validation message is not returned while a user leaves a blank email field

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Email field validation message should be returned

**Actual Result**
Email field validation message is not returned while a user leaves a blank email field

**GraphQL Query:(Register_Login)**
![Desktop screensh](https://user-images.githubusercontent.com/5212585/127820250-fb52665e-6564-43b7-89f0-baa2d1a0fb27.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Input validation failed",
            "extensions": {
                "codes": [
                    "Validation",
                    "Client"
                ],
                "status": 400,
                "errors": {
                    "password": {
                        "minLength": "password must be longer than or equal to 6 characters"
                    },
                    "realFirstName": {
                        "minLength": "realFirstName must be longer than or equal to 1 characters"
                    },
                    "realLastName": {
                        "minLength": "realLastName must be longer than or equal to 1 characters"
                    },
                    "displayFirstName": {
                        "minLength": "displayFirstName must be longer than or equal to 1 characters"
                    },
                    "displayLastName": {
                        "minLength": "displayLastName must be longer than or equal to 1 characters"
                    }
                },
                "code": "Validation"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "register"
            ]
        }
    ],
```

**Query and Input File**
[register_login.txt](https://github.com/SeedCompany/cord-api-v3/files/6915080/register_login.txt)

CordAPIV3# 704a76e

**Comment by CarsonF** [comment]
Emails are now optional with #2006. Empty strings are assumed to be null as well.

If you are trying to get that validation message you could use a string like "asd" which is a value but not a valid email.
