### ISSUE TITLE
Quarterly Report Form

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2062]
As part of providing better reporting and communications with Investors, we need to capture the answers to a set of Narrative questions for each Language Engagement in a Project. These should be stored in a manner that allows them to be shared to other systems via an API. One location these may be shared is a set of Google Spreadsheets.

Questions:
Team Update

* Biographies of team members (1st report)
* Personal Updates of team members (all other reports)
* General update on team (Testimony, Biography, Personal reflection of a challenge or success, etc.)

Impact of Work

* Narrative, Stories, & Stats
* Story about partner interaction, achievement, challenge, gathering, etc.

Prayer Update

* Answers
* New Requests
* Update on past requests

Translation Example

* Reference
* Translation

Annual Highlight (Q3 only)

* What went well
* What didn’t go well
* What was learned
* Accomplishments
* Goals for next year

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466890361) by [Unito](https://www.unito.io)

**Comment by sethmcknight** [comment]
- One form per Language Engagement per Quarter
- Project Manager or CORD sends to the Field Partner at the beginning of the Quarter
- Field Partner is required to log in
    - Could be a unique link in their email for each report
    - Could display a list of Projects/Languages they have reports due for
- Provide a list of questions for the Field Partner to answer
    - Some of these will have a set of questions for the Field Partner to select from, then a place for them to input their answer.
    - Will need the ability to upload media linked to specific questions
- Give Field Partners the ability to Save & Exit, then pick up later
- Once the form is filled out, Field Partners submit and it is sent to the Project Manager
- Project Manager reviews and can edit information on the form
- Once the Project Manager has reviewed & edited then can select to accept the report
- The report questions & answers are then fed into the BlueNorth update tool

**Comment by CarsonF** [comment]
- Field Partner = All team members with (new) role
- Send email notification at beginning of quarter to all with FieldPartner role & ProjectManager role
  - How to schedule task? Based on report date?
  - In future, provide field on engagement for a specific person to be chosen.
- Reviewers = Team members with ProjectManager, RegionalDirector, FieldOpsDirector. They can edit answers, but not create or delete.
  - Only send notification to Project Managers
- Some questions will be required. Categories will have a min number required.
  - How to convey via API?
