### ISSUE TITLE
Goals & Progress | Parse Overall Progress from PnP

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2064]
When a new Progress Report PnP is uploaded to an Engagement's Progress Report for a specific Period, parse the PnP Spreadsheet to pull the Overall Progress for the Translation Goals.

**Comment by sethmcknight** [comment]
Here is an example of the PnP Spreadsheet to Parse as an .xlsx file: ExamplePnP.xlsx

The actual PnP is an .xlsm file, if an example in that format is needed please reach out to me. .xlsm files cannot be attached to GitHub issues.

Parsing for Overall Progress should be based on the most current version of each Progress Report. We want to parse and save this data for each reporting period.

In the PnP Workbook you will look at the 'Progress' tab.

There are 3 sections of data we want to capture for each Fiscal Year:
- Progress each Quarter
- Progress each Year
- Cumulative Progress

Each row on the Progress section represents a Fiscal Year. Start on Row 20 and go down until the Fiscal Years are outside of the range of the Projects MOU Dates, or a merged cell is encountered.

Look in Column AG for the Fiscal Year.

Progress each Quarter by Fiscal Year:
Each quarter in a Fiscal Year has the % of the translation work that has been completed during that quarter.
Column AH: Q1 by FY
Column AI: Q2 by FY
Column AJ: Q3 by FY
Column AK: Q4 by FY

Progress by Fiscal Year:
Each Fiscal Year has a sum of the progress planned and progress recorded as a %.
Column AL: Planned Progress by FY
Column AM: Actual Progress by FY

Cumulative Progress by Fiscal Year:
Each Fiscal Year has a sum of the cumulative planned and recorded progress to date, as well as the variance between the two recorded as a %.
Column AN: Cumulative Planned Progress by FY
Column AO: Cumulative Actual Progress by FY
Column AP: Cumulative Variance by FY

Total Cumulative Progress:
The total cumulative progress can be found on the Harvest Tab, and is currently parsed from the PnP.
This included the Planned Progress, Actual Progress, and Variance to-date.

**Comment by sethmcknight** [comment]
@CarsonF updated with example PnP and info on the cells to parse. This should be ready to work.

**Comment by CarsonF** [comment]
See [ExtractPnpFileOnUploadHandler](https://github.com/SeedCompany/cord-api-v3/blob/08f111e3953adf33088cb1e96e59cc5b65b8b21d/src/components/progress-summary/handlers/extract-pnp-file-on-upload.handler.ts) and [ProgressExtractor](https://github.com/SeedCompany/cord-api-v3/blob/08f111e3953adf33088cb1e96e59cc5b65b8b21d/src/components/progress-summary/progress-extractor.service.ts) for examples of how similar data is extracted and saved.

**Comment by CarsonF** [comment]
This involves more data points than we are currently capturing so I'll need to add some schema

**Comment by CarsonF** [comment]
Ok I've got a branch started [`feature/new-progress-summary-periods`](https://github.com/SeedCompany/cord-api-v3/compare/feature/new-progress-summary-periods). The only thing left is to find the data in the excel workbook and return it. Saving to DB has been handled.

I'm just going to edit @sethmcknight comment above to not add confusion.

**Comment by CarsonF** [comment]
Ok updated @sethmcknight's comment (The diff can be viewed by clicking on "edited by..." in the comment header).

I believe this is ready to work by someone else now.

@sethmcknight Because of my comment under "Cumulative Progress by Fiscal Year", I'm assuming it's cool to remove logic for older versions of the spreadsheet. Yes?

**Comment by sethmcknight** [comment]
@CarsonF yes that's correct.
