### ISSUE TITLE
Beta Flag | Add new Beta Flag permissions

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2065]
Create a new role called `Beta Tester`

This role should not be assigned any of the regular permissions.

Remove permissions to view features with the Beta Flag from the `Administrator` role.

Add permissions to view features with the Beta Flag to the `Beta Tester` role.

Only users with the role of `Beta Tester` should be able to see features with the Beta Flag.

**Comment by sethmcknight** [comment]
@CarsonF did my best to capture what we discussed. Please update with anything I missed.

**Comment by CarsonF** [comment]
Yeah we just need a new role with the BetaFeatures power
