### ISSUE TITLE
Projects > Moving from Pinned/Mine to All > Error Message: Cannot return null for non-nullable field TranslationProject.modifiedAt.

### ISSUE THREAD

**Issue by parashara1** [SeedCompany/cord-api-v3#2067]
Roles: Admin
dev.cordfield.com

Describe the bug
Project > Moving from Pinned/Mine tab to All > Getting `Error Message: Cannot return null for non-nullable field TranslationProject.modifiedAt.`

Steps to Reproduce

Login as Admin user
Go to Projects in Menu
Switch from Pinned/Mine tab to All tab

Expected Result
All projects should be displayed under the tab.

Actual Result
Getting Error Message: Cannot return null for non-nullable field TranslationProject.modifiedAt.

Screenshot:
![image](https://user-images.githubusercontent.com/55298180/128250839-25adcf86-5dd9-452a-9265-871a74073251.png)

FYI: @ParkeBrown @michaelmarshall

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown @CarsonF @parashara1 
I've verified on the latest develop 5f8f59c and can't reproduce this issue.
See video :

https://user-images.githubusercontent.com/5212585/134860698-2c03430c-adc9-4a97-83a1-6323f648048c.mp4
