### ISSUE TITLE
Preset Inventory Flag

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2070]
Preset Inventory Flag

Field will be selecting Preset Inventory for Advancement to connect Investors to as part of our Language Offering.

Project Managers will make this selection at the Project level, but it will be applied to the Language Engagements. If a Language Engagement has an Investor connected we may need to automatically flag new Language Engagements with that Language as Approved Inventory.

This flag will need to be:
- Selected, stored, and displayed on the Project Details page
- Displayed on the Project Card
- Displayed on the Language Engagement Card
- Displayed on the Language Engagement Details
- Displayed on the Language Card
- Displayed on the Language Details

We'd also like to add Preset Inventory as a filter to the Projects list and Languages list

If a language has a project marked as Preset Inventory, that language should show (read-only) as Preset Inventory.

**Comment by sethmcknight** [comment]
Design examples:

<img width="685" alt="Screen Shot 2021-08-10 at 2 26 37 PM" src="https://user-images.githubusercontent.com/7377802/128930351-43f6dc9a-5e3a-4d96-b760-f9cacfd61c96.png">
<img width="684" alt="Screen Shot 2021-08-10 at 2 27 15 PM" src="https://user-images.githubusercontent.com/7377802/128930355-c01f1800-92d3-4c1e-9615-920d615fcb2e.png">
<img width="684" alt="Screen Shot 2021-08-10 at 2 27 06 PM" src="https://user-images.githubusercontent.com/7377802/128930356-5c81e709-167a-49ad-be58-1cc0ebdb7d92.png">
<img width="679" alt="Screen Shot 2021-08-10 at 2 26 44 PM" src="https://user-images.githubusercontent.com/7377802/128930357-1d71e03d-54f4-4051-a98e-d577a5831af4.png">

**Comment by sethmcknight** [comment]
Use the blue pills, don't add red pills

**Comment by CarsonF** [comment]
I think the flag is a poor icon to describe this. "Flag" in general is just a boolean, yes/no, for a certain data point. Every place I I've seen it used requires a user action. i.e. "flag for abuse" = review needed; or in email, where you flag a message to revisit later.

Something describing the actual use of this data point would be more relevant, aka "**approved/available for investors**".

Some suggestions from a quick search:
![Screen Shot 2021-08-11 at 4 04 45 PM](https://user-images.githubusercontent.com/932566/129104453-84b181ae-ae43-4006-acc9-fc0816f9823c.png)
![Screen Shot 2021-08-11 at 4 16 13 PM](https://user-images.githubusercontent.com/932566/129104490-ce9b5974-feae-40d5-9a5b-ef0c9dd38da8.png)
![Screen Shot 2021-08-11 at 4 16 57 PM](https://user-images.githubusercontent.com/932566/129104586-8e9dec2c-a07e-4bb6-aa08-0bd791fedb2a.png)

**Comment by CarsonF** [comment]
I personally don't even like "Inventory" - it's just another noun that adds nothing. The property could simply be called `investable`. Something _investable_ is looking for _investors_ which is a noun we use everywhere. Also the _approval_ of such a boolean is irrelevant to the state of it. If it's _true_ it assumed to be approved, so that word is not needed either.

**Comment by sethmcknight** [comment]
@CarsonF I agree on the icon, Aaron is look at alternatives to the flag icon.

I don't care what this is call in the database or code, but for the UI it needs to be called "Approved Inventory" if this is selected. This term was selected, vetted and approved by Field, Finance, Marketing, & Advancement, and is the term that will be used internally when communicating about these Projects and Language Engagements.

**Comment by CarsonF** [comment]
sigh it always gets to me too late 😢

**Comment by CarsonF** [comment]
Probably better to be consistent then. We can just explain/translate in comments.

**Comment by sethmcknight** [comment]
# Final Designs

<img width="936" alt="Screen Shot 2021-08-17 at 7 43 27 AM" src="https://user-images.githubusercontent.com/7377802/129737055-c4d512fe-c7bc-4432-8971-f260b16b331a.png">
<img width="561" alt="Screen Shot 2021-08-17 at 7 45 25 AM" src="https://user-images.githubusercontent.com/7377802/129737064-ff35ae6c-7a1e-4b10-8619-ea5d9a5a1902.png">
<img width="505" alt="Screen Shot 2021-08-17 at 7 45 06 AM" src="https://user-images.githubusercontent.com/7377802/129737068-595570b3-9325-44e0-b3e7-9c49c37b5230.png">
<img width="366" alt="Screen Shot 2021-08-17 at 7 44 43 AM" src="https://user-images.githubusercontent.com/7377802/129737071-df89cf37-bf68-44d7-b3db-fff4820d273b.png">
<img width="635" alt="Screen Shot 2021-08-17 at 7 44 15 AM" src="https://user-images.githubusercontent.com/7377802/129737075-9a261f33-06b4-4873-99aa-84b9e1c0db2e.png">
<img width="652" alt="Screen Shot 2021-08-17 at 7 44 03 AM" src="https://user-images.githubusercontent.com/7377802/129737079-35304ff6-d1a3-409c-9137-ad46b076934e.png">
<img width="639" alt="Screen Shot 2021-08-17 at 7 43 50 AM" src="https://user-images.githubusercontent.com/7377802/129737082-cb2234ad-d2d4-485c-9a24-8134f0230c56.png">
<img width="643" alt="Screen Shot 2021-08-17 at 7 43 43 AM" src="https://user-images.githubusercontent.com/7377802/129737085-12e0a1dc-9cac-40a4-a7c4-fc93e0e17b5e.png">

**Comment by CarsonF** [comment]
A tag? That's literally the same meaning/usage as a flag.

Why would we not pick an icon representing money/funding?

**Comment by Rhuan288souza** [comment]
I used another icon for the flag, but here's a video of demonstration:
https://www.awesomescreenshot.com/video/4910098?key=7901f19e93c6a71bd7e23aa9f4692f61
