### ISSUE TITLE
Partnership > "Types" and "Financial Reporting Type" is not displayed even user have read access and the user is a member of that project

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2095]
**Roles:** Liaison ,Staff Member

**Describe the bug**
Partnership > `Types` and `Financial Reporting Type` is not displayed even user have read access and the user is a member of that project

**Steps to Reproduce**

1.  Login as a root user
1.  Create a project and open a project detail page
1.  Add `Liaison` as a team member
1.  Click on the `Partnership` button and add partnership
1.  Login as a liaison user and open project created by the root user
1.  Click on the `Partnership` button and open the partnership

**Expected Result**
Partnership `Types` and `Financial Reporting Type` should be displayed

**Actual Result**
`Types` and `Financial Reporting Type` is not displayed even user have read access and the user is a member of that project

See video - 

https://user-images.githubusercontent.com/5212585/130190527-683f27d0-3fa5-47c0-8478-fbf55d08f50d.mp4

**FYI:** ParkeBrown michaelmarshall

cord-field# d49b012

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466896443) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
Liaison has readonly access to these fields, and we don't give special access for projects they are apart of. @sethmcknight is this right?
