### ISSUE TITLE
partnership > Getting "Could not find partnership" error while input field id have a "blank" or "invalid" value

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2101]
**Roles:** All 

**Describe the bug**
partnership > Getting `Could not find partnership` error while input field id have a `blank` or `invalid` value

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Proper validation message should be displayed

**Actual Result**
Getting `Could not find partnership` error while input field id have a `blank` or `invalid` value

**Note:** It's working expected as per film request.

See video -  

https://user-images.githubusercontent.com/5212585/130747614-27c8821c-7ba9-4fb8-b70c-3a7f719c9330.mp4

**GraphQL Query:(partnership)**
![image](https://user-images.githubusercontent.com/5212585/130747070-7b28cf44-6c2b-4377-ae32-ea6f993d5fdd.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Could not find partnership",
            "extensions": {
                "codes": [
                    "NotFound",
                    "Input",
                    "Client"
                ],
                "status": 400,
                "code": "NotFound",
                "exception": {
                    "message": "Could not find partnership",
                    "stacktrace": [
                        "at PartnershipRepository.readOne (components/partnership/partnership.repository.ts:151:13)",
                        "at PartnershipService.readOneUnsecured (components/partnership/partnership.service.ts:147:12)",
                        "at PartnershipService.readOne (components/partnership/partnership.service.ts:137:17)",
                        "at PartnershipResolver.partnership (components/partnership/partnership.resolver.ts:57:12)"
                    ]
                }
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "partnership"
            ]
        }
    ],

```
**Query and Input File**

[partnershipBug.txt](https://github.com/SeedCompany/cord-api-v3/files/7044727/partnershipBug.txt)

CordAPIV3# 9bda33b

**Comment by daniel-leod** [comment]
Reproduced successfully. It occurs when querying engagement and project with an invalid ID as well.
