### ISSUE TITLE
Project > Created Project is not displayed for "Mentor" user roles

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2106]
**Roles:** Mentor, Regional Communication Coordinator

**Describe the bug**
Project > Created Project is not displayed for `Mentor` user roles

**Steps to Reproduce**
1. Login as Admin user
2. Create a new project and assigned team member `Mentor`
3. Login as Mentor user
4. Click on the project sidebar menu

**Expected Result**
The created project should be displayed

**Actual Result**
Created Project is not displayed for `Mentor` user roles

**Note:** Same issue happens for the `Regional Communication Coordinator` user role
See video - 

https://user-images.githubusercontent.com/5212585/131462047-c10f1c87-a757-42f0-8273-6333c33b815d.mp4

cord-field# d49b012
CordAPIV3# 84d4385

**Comment by daniel-leod** [comment]
#2400 Fixes this issue.
