### ISSUE TITLE
The output of "unavailabilities" and "education"  is wrong in user resolver

### ISSUE THREAD

**Issue by ibohalsinghkoijam** [SeedCompany/cord-api-v3#214]
**Describe the bug**
This output of "unavailabilities" and "education" is wrong in user resolver. It needs to be a "SecuredUnavailabilityList" and "SecuredEducationList" per the ResolveProperty type.

1
@ResolveProperty(() => SecuredUnavailabilityList)
  async unavailabilities(
    @Session() session: ISession,
    @Parent() { id }: User,
    @Args({
      name: 'input',
      type: () => UnavailabilityListInput,
      defaultValue: UnavailabilityListInput.defaultVal,
    })
    input: UnavailabilityListInput
  ): Promise"UnavailabilityListOutput" {
    input = { ...input, filter: { userId: id } };
    return this.unavailabilityService.list(input, session);
  }

2
@ResolveProperty(() => SecuredEducationList)
  async education(
    @Session() session: ISession,
    @Parent() { id }: User,
    @Args({
      name: 'input',
      type: () => EducationListInput,
      defaultValue: EducationListInput.defaultVal,
    })
    input: EducationListInput
  ): Promise"EducationListOutput" {
    input = { ...input, filter: { userId: id } };
    return this.educationService.list(input, session);
  }

**Comment by michaelmarshall** [comment]
We'll do this in Sprint 4

**Comment by michaelmarshall** [comment]
Talked with Daniel. I didn't know we needed this done so I changed it to this sprint.

**Comment by candleshine** [comment]
merged on #229
