### ISSUE TITLE
Project > File > Getting "You do not have permission to view files for this project" even user has "Global R" access

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2143]
**Roles:** ConsultantManager, StaffMember

**Describe the bug**
Project > File > Getting `You do not have permission to view files for this project ` even user has `Global R` access

**Steps to Reproduce**
1. Login as admin user
2. Create a project and upload the file
3. Login as a ConsultantManager user
4. Open created project
5. Click on the `View File` button

**Expected Result**
The uploaded file should be displayed

**Actual Result**
Getting `You do not have permission to view files for this project ` even user has `Global R` access
 
![image](https://user-images.githubusercontent.com/5212585/133206689-5677ed71-d96a-4ce0-8e65-3c773a5172bb.png)

**Note:** File is displayed after add `ConsultantManager` as a team member

See video - 

https://user-images.githubusercontent.com/5212585/133206719-f5933373-b773-489e-8c01-22040ecbf4dc.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 851d128
CordAPIV3# 5008609

**Comment by daniel-leod** [comment]
This is similar to #2191. It's working fine, if users don't have the correct sensitivity they can't see the project root directory.

@CarsonF What do you think about it? Can we close this?

**Comment by CarsonF** [comment]
@daniel-leod Can you find and link the commit that made the permissions change to fix this?

**Comment by CarsonF** [comment]
Thanks!
