### ISSUE TITLE
Project > Budget >  User can read the budget details even that user has "No read" permission

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2146]
**Roles:** Staff Member,Consultant

**Describe the bug**
Project > Budget >  User can read the budget details even that user has `No read` permission

**Steps to Reproduce**
1. Login as Admin user
2. Create a project and go to the project detail page
3. Add `Staff Member` as a team member
4. Add `Start - End` date
5. Click on the `Add Partnership` button and add the `Funding` type of Partner
6. Login as a `Staff Member` user and open created project
7. Click on the budget button

**Expected Result**
`You do not have permission to view this project's field budget` message should be displayed. Find attached screenshot for reference 

![image](https://user-images.githubusercontent.com/5212585/133267530-f7c4821d-0657-4b36-a285-a83a58c097de.png)

**Actual Result**
User can read the budget details even that user has `No read` permission
 
See video - 

https://user-images.githubusercontent.com/5212585/133265839-ac620cc5-8ba4-42c7-8a1f-7f09ce55ee62.mp4

![image](https://user-images.githubusercontent.com/5212585/133265951-c36827f0-521e-4338-84ee-70473cfe1442.png)

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 851d128
CordAPIV3# 5008609

**Comment by daniel-leod** [comment]
Please check this again, I think this issue can be closed via [#2175](https://github.com/SeedCompany/cord-api-v3/pull/2175).

This [line](https://github.com/SeedCompany/cord-api-v3/pull/2175/commits/b091f2d07f74115d9b34cb8034bdf00405b0df57#diff-288fb951eb5019b7cfeee636f32a64ea1f260e0a1f73a574fba0c4dc4ac56da7R344) fixes it.

**Comment by daniel-leod** [comment]
Since [this commit](https://github.com/SeedCompany/cord-api-v3/pull/2175/commits/b091f2d07f74115d9b34cb8034bdf00405b0df57#diff-288fb951eb5019b7cfeee636f32a64ea1f260e0a1f73a574fba0c4dc4ac56da7R344), which is already in `develop`, fixes the budget permission issue for Staff Member role it cannot be reproced for that particular role. However this permission issue is still present on Consultant role, the linked PR may fix that. 

Could you please check this issue again and update it to be only for Consultant role? Thanks!

**Comment by iPiyushPatel** [comment]
Hi @daniel-leod @CarsonF 
I've verified on the latest develop afede2f and it's working fine for the `Staff Member` user role. but still facing an issue for the `Consultant` user role. Attaching a video for a reference. Thanks!

See video: 


https://user-images.githubusercontent.com/5212585/140700215-6af26bf9-b35a-44ba-b243-2eaaee7f33b8.mp4
