### ISSUE TITLE
Project > LanguageEngagement > User can read  the "ParaTextRegisterId" even that user has "No" read access

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2161]
**Roles:** Controller

**Describe the bug**
Project > LanguageEngagement > User can read  the `ParaTextRegisterId` even that user has `No` read access

**Steps to Reproduce**
1. Login as Admin user
2. Create a project and go to the project detail page
3. Add `LanguageEngagement` and details
4. Login as a `Controller` user and open created project
5. Click on the `ViewDetails` button and Click on the `ParatextRegisterId` button

**Expected Result**
`ParaTextRegisterId` should not be readable

**Actual Result**
User can read  the `ParaTextRegisterId` even that user has `No` read access

**Note:** : Same issue for `disbursementCompleteDate` is not updated even user has a Global `update` access
 
See video - 

https://user-images.githubusercontent.com/5212585/134002182-6be0a94d-8c7a-40f1-befe-60bd18a88611.mp4

![image](https://user-images.githubusercontent.com/5212585/134002159-ac6fc8dc-e5b8-4b8b-96eb-9c5c5bea5005.png)

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 04a062c
CordAPIV3# 19658e4

**Comment by daniel-leod** [comment]
[This commit](https://github.com/SeedCompany/cord-api-v3/commit/67f6ee6aa98c42aca1bbb77c6dcc73e33a3705ec#diff-e5d61caaf401c8801ab66fb9a5cf722462ee83efe194834922d7c013372003b6R232) fixes `paraTextRegisterId` issue. `disbursementCompleteDate` update issue can be fixed via the PR linked.

**Comment by bryanjnelson** [comment]
@iPiyushPatel - @daniel-leod and myself did some investigation on this and we discovered that PR #2136 actually already took care of this `paraTextRegisterId` issue.  And #2265 will address #2176 (which is the `disbursementCompleteDate`) and is tracked there.  Therefore, this issue can be closed.
