### ISSUE TITLE
mutation togglePinned > Input validation missing for "pinned" field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2181]
**Describe the bug**
mutation togglePinned > Input validation missing for `pinned` field

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Proper validation message should be returned for input mismatch of `pinned` field.

**Actual Result**
Input validation missing for `pinned` field

See video - 

https://user-images.githubusercontent.com/5212585/135467175-db513a5b-bd8c-4fb3-a9a2-2f984f161074.mp4

**GraphQL Query ( togglePinned ):**
![image](https://user-images.githubusercontent.com/5212585/135467408-48bfe39d-6ff8-4d1e-a609-30cc5e81a989.png)

**Query and Input File( togglePinned ):**
[togglepinnedMismatch.txt](https://github.com/SeedCompany/cord-api-v3/files/7259971/togglepinnedMismatch.txt)

CordAPIV3# 32bf73a

**Comment by CarsonF** [comment]
`pinned` input is optional. You've even defined that as an optional input in your operation `$pinned: Boolean` not `$pinned: Boolean!`. 

The extra `pinned1` variable is ignored. It may have been an error in the past, maybe it changed with Apollo Server 3. I'm not worried about it. No different than allowing extra unknown parameters on a GET request or POST body - they are just ignored.
