### ISSUE TITLE
Project > Goal > User can "Add" and "Delete" the goal even user has "No" create  and delete  access

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2183]
**Roles:** Consultant

**Describe the bug**
Project > Goal > User can `Add` and `Delete` the goal even user has `No` create  and delete  access

**Steps to Reproduce**

1.  Login as a root user
1.  Create a project and open a project detail page
1.  Add team member `Consultant`
1. Add `LanguageEngagement`
1.  Add Goal and details
1.  Login as a `Consultant` user
1.  Open created a project details page
1. Click on created `goals` button and the `Edit` icon 
1. Click on the `Delete Goal` button

**Expected Result**
Goal `Add` button should not be displayed or Goal should not be deleted

**Actual Result**
User can `Add` and `Delete` the goal even user has `No` create  and delete  access

See video - 

https://user-images.githubusercontent.com/5212585/135808491-1a4ce189-0432-4774-938f-18303cd9c6b3.mp4
![image](https://user-images.githubusercontent.com/5212585/135808620-1dead746-62ca-4f8b-8c72-5f58ba9850e6.png)

**FYI:** ParkeBrown michaelmarshall

CordAPIV3# c761327
cord-field# 684cfb8

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466907221) by [Unito](https://www.unito.io)

**Comment by daniel-leod** [comment]
https://github.com/SeedCompany/cord-field/pull/1113/commits/ac304cdc67b0a5a84093b4f8758db0efc63a2c7e will fix the UI part for this issue.
