### ISSUE TITLE
Language > User can not read the "Language" even user has "Global Read" access

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2196]
**Roles:** LeadFinacialAnalyst

**Describe the bug**
Language > User can not read the `Language` even user has `Global Read` access

**Steps to Reproduce**
1. Login as an admin user
2. Create the language
3. Log in as a LeadFinacialAnalyst user 
4. Find a created language

**Expected Result**
User should be able to read the `Language`

**Actual Result**
User can not read the `Language` even user has `Global Read` access

See Video -

https://user-images.githubusercontent.com/5212585/136508842-e974b413-5b26-4600-bc6e-63daa94955b4.mp4

See Screenshot -
![image](https://user-images.githubusercontent.com/5212585/136508958-b242da1e-02b3-4151-bbdd-32cb1594ed1d.png)

CordAPIV3# 818dac6
cord-field# 960f8f0

**Comment by daniel-leod** [comment]
#2400 Fixes this issue.
