### ISSUE TITLE
Project > InternshipEngagement > User can not read the "InternshipEngagement" even user has "Global Read" access

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2197]
**Roles:** LeadFinacialAnalyst

**Describe the bug**
Project > InternshipEngagement > User can not read the `InternshipEngagement` even user has `Global Read` access

**Steps to Reproduce**
1. Login as an admin user
2. Create Project and add `LeadFinacialAnalyst` as a member
3. Create an `InternshipEngagement`
4. Log in as a `LeadFinacialAnalyst` and find created a project

**Expected Result**
User should be able to read the `InternshipEngagement`

**Actual Result**
User can not read the `InternshipEngagement` even user has `Global Read` access

**Note:** Same issue is for `LanguageEngagment`.

See Video -

https://user-images.githubusercontent.com/5212585/136510329-378bbd61-e7f6-436b-829e-cf1d6c5dbdea.mp4

See Screenshot -
![image](https://user-images.githubusercontent.com/5212585/136510535-5cb316f3-0ff8-4891-a4f5-734d02ac8f66.png)

CordAPIV3# 818dac6
cord-field# 960f8f0

**Comment by daniel-leod** [comment]
#2400 Fixes this issue
