### ISSUE TITLE
Search > Getting "No results found" error when user search the available project and partner name

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2198]
**Roles:** LeadFinancialAnalyst

**Describe the bug**
Search > Getting `No results found` error when user search the available project and partner name

**Steps to Reproduce**
1. Login as a LeadFinancialAnalyst user
2. Search `Project` name
3. Search `Partner` name

**Expected Result**
Searched results should be displayed if available

**Actual Result**
Getting `No results found` error when user search the available project and partner name

See video - 

https://user-images.githubusercontent.com/5212585/136529708-811bd53d-2f1e-45ee-9599-fb933b90fda0.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 960f8f0

**Comment by daniel-leod** [comment]
Fixed by #2400
