### ISSUE TITLE
Research using transaction functions to solve routing table updates in Aura

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#221]
We are getting weird log entries in Neo4j Aura (integration env) that show the cluster routing table being updated almost every query. Neo4j support suggests we need to use [transaction functions](https://neo4j.com/docs/driver-manual/1.7/sessions-transactions/#driver-transactions-transaction-functions) in all our queries.

Verify this problem is solved by transaction functions. To troubleshoot, you can point your local environment to the integration database and monitor the API's console. Ask @michaelmarshall for the creds to the integration database.

**Comment by michaelmarshall** [comment]
@CarsonF I need your help verifying our current driver setup is what we think it is.

**Comment by CarsonF** [comment]
Could be fixed by #1596

**Comment by sethmcknight** [comment]
> Could be fixed by #1596

@michaelmarshall do you know if that ☝🏼 fixed the issue or do we still need to address this?

**Comment by CarsonF** [comment]
If it's needing transactions to actually be used that happens in #1630. Which is currently blocked until we can change list and search functions to not pull security groups from the database.
