### ISSUE TITLE
G&P | Goals are not exported from the PnP if there are blank rows

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2247]
Some PnP's have blank rows at the beginning with Goals listed below, or have some blank rows in the middle of the Goals.

To insure we are capturing all of the Goals we need to update the extraction code to continue iterating through the rows of Goals until it hits cell Q89/ a cell that says "Other Goals and Milestones"

**Comment by sethmcknight** [comment]
Example: https://docs.google.com/spreadsheets/d/1ynAE3HwRczNz4YjYcOtF5X1kFSPhEJz3/edit?usp=sharing&ouid=103781340369405856620&rtpof=true&sd=true

**Comment by CarsonF** [comment]
Looks like this a regression from 5dc0c8469f53ac7108e88dfbd5ac7356cb060305. Looks like these cells are undefined but there are ones after them. So we need a better way to to stop iteration when "Other Goals and Milestones" cannot be found. Perhaps just a hardcoded limit, or maybe something more elegant. Maybe excel defines the sheet range that can be used.
