### ISSUE TITLE
G&P | Goals are not exported if the Steps are not matched on wording

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2248]
If a PnPs Steps are not worded the same as the Steps in CORD, the PnP Goals will not be exported.

We need to determine the Steps based on the Methodology selected and the Column it is in, rather than relying on the text that is in the Column Header of the PnP file.

**Comment by sethmcknight** [comment]
Example: https://docs.google.com/spreadsheets/d/123Cf9n3TDlcaepOQqf5cKB--sraKOPoj/edit?usp=sharing&ouid=103781340369405856620&rtpof=true&sd=true

**Comment by CarsonF** [comment]
@sethmcknight what does it look like for less than 6 available steps?

**Comment by sethmcknight** [comment]
@CarsonF the only PnP/Approach (therefore. methodologies) that does not have 6 steps is Oral Storytelling. We aren't currently parsing those, so they'll be ignored.

**Comment by CarsonF** [comment]
So that would mean this:
| PnP | Parsed |
| - |-|
| Exegesis & First Draft | Exegesis & First Draft
| Team Check | Team Check
| Exeg. check & Team Revision | Community Testing
| Film & Community Testing | Back Translation
| Consultant Check | Consultant Check
| Completed | Completed

Doesn't this look like community testing is in the wrong spot?

**Comment by sethmcknight** [comment]
Yep, in this case it does... This PnP hasn't been standardized yet and the Project Manager will need to make that fix.

That said, they can still edit/change the wording and we want to account for that. A different example would be a PnP that has been translated to another language for collaboration with the Partner.

**Comment by CarsonF** [comment]
For now we'll continue to fuzzy match steps by name. This will gracefully handle steps that aren't standard which causing incorrect data to be extracted.

This won't handle pnp's in different languages though.
