### ISSUE TITLE
Can we trigger an extract of all Active Engagement PnP's?

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2261]
Ideally we would trigger an extract of the existing PnP's for all Active Engagement's Planning sheet so that Project Managers do not have to reupload the plan for each Project. We can look at the existing Scripture goals Methodology to determine which Methodology to select when parsing the Planning sheet.

**Comment by CarsonF** [comment]
We can for most but there are edge cases:
- We'd need to skip pnp's that don't have any products with a methodology.
- We'd need to decide how to handle pnp's with multiple methodologies found. I've seen Film & Paratext for example.

**Comment by CarsonF** [comment]
Here are the actual stats right now of uploaded pnp's and their corresponding methodologies.
These are the counts of engagements/pnps that have these methodologies found.
```json5
{
  "[OtherOralTranslation, Paratext]": 1,
  "[]": 3602, // This is null/none, could be that there are no products.
  "[OtherWritten]": 2,
  "[OtherOralTranslation]": 27,
  "[Render]": 10,
  "[SeedCompanyMethod]": 3,
  "[Film, Paratext]": 2,
  "[Audacity]": 6,
  "[OtherWritten, Paratext]": 4,
  "[OtherVisual]": 1,
  "[Paratext]": 449,
  "[OtherOralTranslation, OtherWritten, Paratext]": 1,
  "[SignLanguage]": 4,
  "[OtherWritten, OtherOralTranslation, Paratext]": 2
}
```

**Comment by CarsonF** [comment]
This would also result in duplicated products because none of the existing ones will match based on total verses as thats a new feature
