### ISSUE TITLE
forgotPassword > Returned success response when user leave blank "Email" field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2271]
**Roles:** All

**Describe the bug**
forgotPassword > Returned success response when user leave blank `Email` field

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
`Error` or `Input` validation message should be returned

**Actual Result**
Returned success response when user leave blank `Email` field

See video -  

https://user-images.githubusercontent.com/5212585/140915954-6b5fa757-0c11-43bf-92d3-e8a7601cb028.mp4

**GraphQL Query:(forgotPassword)**
![image](https://user-images.githubusercontent.com/5212585/140916128-14f7a402-6b03-4f85-934d-1889a6c07560.png)

**GraphQL response**
```
{
    "data": {
        "forgotPassword": true
    }
}
```

**Query and Input File**
[BugForgotPasswordEmailBlank.txt](https://github.com/SeedCompany/cord-api-v3/files/7504287/BugForgotPasswordEmailBlank.txt)

CordAPIV3# 600901f

**Comment by parashara1** [comment]
No error message for a blank `Email` field. Successfully reproduced

**Comment by iPiyushPatel** [comment]
Hi @daniel-leod @CarsonF 
It returns the same success response when tried with passing actual `email` and  `""` blank to `email` field on the latest develop 7d845b3 . 

Attaching a video for a reference. Thanks!

https://user-images.githubusercontent.com/5212585/141990882-01db25be-016e-44b2-abfc-d42eb655ce16.mp4
