### ISSUE TITLE
createDerivativeScriptureProduct > Returned "Field \"engagementId\" of required type \"ID!\" was not provided." error even user provide the correct input value in "engagementID" field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2282]
**Roles:** All

**Describe the bug**
createDerivativeScriptureProduct > Returned ` Field \"engagementId\" of required type \"ID!\" was not provided.` error even user provide the correct input value in `engagementId` field

**Steps to Reproduce**  
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Product should be created when the user provides correct input value in the `engagementId` field

**Actual Result**
Returned ` Field \"engagementId\" of required type \"ID!\" was not provided.` error even user provide the correct input value in `engagementId` field

**Note:** Same issue is happening for `producesId` and `reportId`

See video -  

https://user-images.githubusercontent.com/5212585/141270021-c0c016fa-030a-4878-8d99-a9d3a521c19f.mp4

**GraphQL Query:(createDerivativeScriptureProduct )**
![image](https://user-images.githubusercontent.com/5212585/141270202-6029d066-103d-4577-b998-a8c3254b668f.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Variable \"$input\" got invalid value { product: { produces: \"rVD4PZ5ka87\", engagementId: \"kmrFP3wGEwz\", mediums: \"Video\", purposes: \"ChurchLife\", methodology: \"OtherWritten\", steps: [Array], progressStepMeasurement: \"Number\", describeCompletion: \"describeCompletion11112021023138\", progressTarget: 35.145981303917395 } }; Field \"engagementId\" of required type \"ID!\" was not provided.",
            "extensions": {
                "code": "BAD_USER_INPUT",
                "codes": [
                    "GraphQL",
                    "Client"
                ]
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ]
        },
        {
            "message": "Variable \"$input\" got invalid value { product: { produces: \"rVD4PZ5ka87\", engagementId: \"kmrFP3wGEwz\", mediums: \"Video\", purposes: \"ChurchLife\", methodology: \"OtherWritten\", steps: [Array], progressStepMeasurement: \"Number\", describeCompletion: \"describeCompletion11112021023138\", progressTarget: 35.145981303917395 } }; Field \"produces\" of required type \"ID!\" was not provided.",
            "extensions": {
                "code": "BAD_USER_INPUT",
                "codes": [
                    "GraphQL",
                    "Client"
                ]
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ]
        },
        {
            "message": "Variable \"$input\" got invalid value { product: { produces: \"rVD4PZ5ka87\", engagementId: \"kmrFP3wGEwz\", mediums: \"Video\", purposes: \"ChurchLife\", methodology: \"OtherWritten\", steps: [Array], progressStepMeasurement: \"Number\", describeCompletion: \"describeCompletion11112021023138\", progressTarget: 35.145981303917395 } }; Field \"product\" is not defined by type \"CreateDerivativeScriptureProduct\". Did you mean \"produces\"?",
            "extensions": {
                "code": "BAD_USER_INPUT",
                "exception": {
                    "stacktrace": []
                },
                "codes": [
                    "BAD_USER_INPUT",
                    "Server"
                ]
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ]
        },
        {
            "message": "Variable \"$reportId\" of required type \"ID!\" was not provided.",
            "extensions": {
                "code": "BAD_USER_INPUT",
                "codes": [
                    "GraphQL",
                    "Client"
                ]
            },
            "locations": [
                {
                    "line": 3,
                    "column": 3
                }
            ]
        }
    ]
}
```

**Query and Input File**
[BugEngagementIdError.txt](https://github.com/SeedCompany/cord-api-v3/files/7519193/BugEngagementIdError.txt)

CordAPIV3# d542523

**Comment by daniel-leod** [comment]
I think `product` key in the JSON input should be omitted. It should be something like:

```
{
  "input": {
    "produces": "{{producesId}}",
    "engagementId": "{{engagementId}}",
    ...
  },
  "reportId": "{{reportId}}"
}
```
Please review this issue again using the updated input. Thanks!

**Comment by iPiyushPatel** [comment]
Hi @daniel-leod @CarsonF
I have tried by removing the 'product ' key but it provides with the error of 'Field \"product\" of required type \"CreateProduct!\" was not provided." on the latest develop '7d845b3' . Attaching a video for a reference. Thanks!

https://user-images.githubusercontent.com/5212585/141987119-95b0b7d6-35eb-450c-a206-1d07351d5f31.mp4

**Comment by CarsonF** [comment]
@iPiyushPatel try using the graphql sandbox at /graphql to see how your operations are invalid. It'll give you inline hints that postman doesn't have.

**Comment by daniel-leod** [comment]
@iPiyushPatel Yes, that's right. `createProduct` mutation requires `product` key in the input. 

However, `createDerivativeScriptureProduct` mutation, which is the one attached to the issue, doesn't require `product` key.

Please review this issue again using the updated input. Thanks!

**Comment by iPiyushPatel** [comment]
Hi @CarsonF @daniel-leod 
I've verified on the latest develop ff53b6b and it's working fine thanks for the detailed input.

**See screenshot:**

![image](https://user-images.githubusercontent.com/5212585/142143190-4c9ced20-42b1-4a13-bf20-7c5ced968273.png)
