### ISSUE TITLE
Add new field to cf3.LanguagEngagements.prod for Domo

### ISSUE THREAD

**Issue by kjones140** [SeedCompany/cord-api-v3#2294]
Devops,
Please add the new field "Open to Investor Visit" that is part of the LanguageEngagement  to the CF3.LanguageEngagements.PROD dataset in Domo.  Please name the field as OpenToVisitsFlag and provide a value of Y or N.

**Comment by ParkeBrown** [comment]
@sethmcknight as seen in Slack

**Comment by CarsonF** [comment]
Duplicate of https://github.com/SeedCompany/seed-api/issues/194
