### ISSUE TITLE
BUG: PnP parse on Abureni 2

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#2301]
From Lola Adegoke (FPM):
```
When I uploaded the Pnp for Abureni 2, it did not strip the books properly. I had to manually do this for acts which will only have drafting done
```

**Comment by CarsonF** [comment]
It looks like the step column labels were changed so we were not able to match them automatically. 

| PnP | Cord |
| - | - |
| Exegesis, 1st draft. Keyboard | Exegesis & First Draft
| Team Check & 1st test | Team Check
| Paratext chks & back-translation | Back Translation
| Testing & reviewing | Consultant Check _or maybe_ Community Testing

**Comment by CarsonF** [comment]
Closing because @sethmcknight agrees that the users will need to not change these labels
