### ISSUE TITLE
users > Filter by "pinned" returns one item when the input field has a "true" value and even more than one user is pinned

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2313]
**Roles:** All 

**Describe the bug**
users > Filter by `pinned` returns one item when the input field has a `true` value and even more than one user is pinned

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Users list should be returned with `pinned` users 

**Actual Result**
Filter by `pinned` returned one item when the input field has a `true` value and even more than one user is pinned

See video -  

https://user-images.githubusercontent.com/5212585/146159518-f8608e86-a566-4920-96e7-941cc8e6ecd2.mp4

**GraphQL Query:(users)**
![image](https://user-images.githubusercontent.com/5212585/146159748-74d7487a-7e62-49f0-8e20-e86f43f29628.png)

**GraphQL response**
```
{
    "data": {
        "users": {
            "total": 1,
            "hasMore": false,
            "items": [
                {
                    "id": "YUoSbwJKYlo",
                    "fullName": "FirstName15122021025338 LastName15122021025338",
                    "canDelete": true,
                    "email": {
                        "value": "email15122021025338@test.com"
                    },
                    "knownLanguages": [],
                    "pinned": true
                }
            ]
        }
    }
}
```

**Query and Input File**
[BugUsersFilterPiined.txt](https://github.com/SeedCompany/cord-api-v3/files/7649517/BugUsersFilterPiined.txt)

CordAPIV3# 0c12921

**Comment by tmpacifitech** [comment]
@iPiyushPatel @CarsonF I can't reproduce this issue on both dev site and local. All works as expected on graphql explorer and UI.
