### ISSUE TITLE
Products | Placeholder

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#2315]
## Idea

We have products defined in PnPs that are only there to indicate the actual product will be determined later. This is used for planning. So these rows/"products" have steps & planned completed dates for these steps.
However, the "name" of the row is along the lines of "TBD" and possible the event/time name when it will be determined.

Creating several stories as the name of this event, e.g. "Cycle 2", "Cycle 3", seems wrong. As that's not a story but rather a placeholder.
It also seems like a good idea to distinguish these. That would allow:
- "Hide placeholder goals" toggle in the UI
- Hide from some reports. i.e. "Cycle 2" is not an actual story being worked, so don't give that to DOMO.
- User flow to convert placeholder product to a real one with determined data

All of this seems like a good idea.

## Implementation

Implementation could be tricky.

This is essentially another dimension. i.e. "Scripture Placeholder" or "Story Placeholder".

Maybe this could be marked the same way we do "deprecated". i.e. If this product has a placeholder text then it is a placeholder.

The placeholder text could factor into the label as well. So story products could have the constant "unknown" story but be labelled via the placeholder (and maybe the order #2314). This would prevent cluttering the producibles just to give the product a unique label.

"Conversion" would be simple then, as only the placeholder field and relevant fields would change; instead of having to actually convert the object or delete & create a different one.

@sethmcknight @daniel-leod thoughts?

**Comment by daniel-leod** [comment]
@CarsonF Sounds good to me

**Comment by CarsonF** [comment]
This is really needed for #2228 to be complete.
