### ISSUE TITLE
BUG: Adding a large number of goals seems to break the 

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#2320]
Repro:
1. Go to Sudest 3 project.
2. Add a goal.
3. It should show a "Could not find engagement" error.
4. If you go back to Sudest 3 and click on the engagement it should show the same "Could not find engagement" error.
5. Logout then login and the engagement now can be displayed and the goal shows as added.

**Comment by CarsonF** [comment]
I've never seen this before. I'm guessing it's a problem with migrated data. Or at least that project/engagement specifically.
