### ISSUE TITLE
uploadPeriodicReport > Returned "Assertion Error: no additional info provided" when query output have a "parent"  field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2321]
**Roles:** All 

**Describe the bug**
uploadPeriodicReport > Returned `Assertion Error: no additional info provided` when query output have a `parent`  field

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Report should be upload with the `parent` field in the query output

**Actual Result**
 Returned `Assertion Error: no additional info provided` when query output has a `parent` field

See video -  

https://user-images.githubusercontent.com/5212585/147218196-26fb3415-614e-476c-b448-eed95b21d790.mp4

**GraphQL Query:(uploadPeriodicReport )**
![image](https://user-images.githubusercontent.com/5212585/147218305-6af3c0ff-a852-4487-becd-a20c1ae586e8.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Assertion Error: no additional info provided",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "at resolveType (common/resource.dto.ts:14:11)",
                        "at async Promise.all (index 8)"
                    ]
                },
                "codes": [
                    "INTERNAL_SERVER_ERROR",
                    "Server"
                ]
            },
            "locations": [
                {
                    "line": 11,
                    "column": 5
                }
            ],
            "path": [
                "uploadPeriodicReport",
                "parent"
            ]
        }
    ],
    "data": null
}
```

**Query and Input File**
[uploadReportAssertionError.txt](https://github.com/SeedCompany/cord-api-v3/files/7768163/uploadReportAssertionError.txt)

CordAPIV3# 0c12921

**Comment by CarsonF** [comment]
:+1: Could've sworn I handled this...
