### ISSUE TITLE
BUG: User reported improper progress

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#2332]
Hey team, I was working in Cord Field with @Steve Doerr and we saw that several of his projects were not properly displaying language progress for the reporting period. The Planned/Actual/Variance box is showing the correct %s, but the Progress for Goals section is not showing any progress for the specific translation goals that were worked on in that reporting period. The specific projects we looked at were:
[Dudziro Emazwi Cluster 2 FY21 Q3 Progress - all languages](https://cordfield.com/projects/5cc0dc661c6585c2148301d5/engagements/5cc0ddd91c6585b25a831271/reports/progress/UFDSqbTQCkt)
[Ngangala 2 Fy21 Q4 Progress - all languages](https://cordfield.com/projects/5cc0dab4edc5294af0b60c91/engagements/5cc0db4e1c6585a2db82f9a0/reports/progress/IWHispjrt0H)
[Zimbabwe Tonga 2 FY21 Q4 Progress](https://cordfield.com/projects/5dfa17b3164335ff872d915f/engagements/5dfa182038339d240b7a6dd0/reports/progress/qeu6SPise3a)
We looked at the PnPs and they do appear to be filled out correctly. Thanks! (edited)

**Comment by CarsonF** [comment]
All those PnP's were uploaded before we had step progress extraction. That went live 11/16/21. I believe I asked about re-extracting all previously uploaded files and @sethmcknight said don't worry about it.

**Comment by sethmcknight** [comment]
@CarsonF beat me to it... so what he said for Dudziro Emazwi.

We may consider running an extraction on all old progress reports in the future, but that wasn't needed at the time we went live.

@michaelmarshall they can re-upload the Q2/Q3 reports to extract the step progress if they would like.

Zimbabwe Tonga 2 does not have a planning sheet uploaded and the Goals do not have steps assigned, so the steps won't show even if the progress is extracted. Uploading the Planning sheet or editing the Goals to select the Steps should resolve this one.

I can't find an Ngangala 2 so I don't have anything to add on that one.

**Comment by sethmcknight** [comment]
@michaelmarshall just saw Abby's post in the Slack channel... following the link shows it's actually called Nkangala 2, not <s>Ngangala 2<s>

This is probably the same issue as @CarsonF noted for Dudziro Emazwi

**Comment by CarsonF** [comment]
Added links to OP so we don't have to search again
