### ISSUE TITLE
FA cannot change engagement status

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#2335]
From Abby:

````
FW: Projects to Close in Cord
Dear helpdesk,
Financial Analysts should have permission to mark internship and translation projects complete in Cord. It is the last step of the closing process. However, Benn Samuel was unable to do that for Samuel Marew Intern. I was able to override on this request, but would you please make sure his permissions are correct in the system? Is there a way to double check this for all FSG staff?
Thank you so much!
Abby Roberts
````

Please investigate if our code/perms for FAs is accurate.

**Comment by CarsonF** [comment]
It looks like the engagement was still `Active` when the project was set to `Complete`.
We disallow completing a project while engagements are not terminal. (022f8c1570f317892c4a4e74f2bf31f3ef76ad75)
https://github.com/SeedCompany/cord-api-v3/blob/8e58268201959b0c6ac550a60dca850449386dc5/src/components/project/project.rules.ts#L768-L774
We do show this message in the UI when hovering over the disabled Complete button.

@sethmcknight thoughts?

**Comment by sethmcknight** [comment]
@CarsonF yes that sounds correct. I'll follow up with Abby to discuss

**Comment by michaelmarshall** [comment]
I've gotten tickets where FAs haven't been able to close the engagemen
![eeoug1ky8z8hyh-image](https://user-images.githubusercontent.com/1165460/148851714-57fd25c8-4f18-4d88-9fd2-993e9380cf2b.png)
t

**Comment by michaelmarshall** [comment]
a user is still reporting they can't update the engagement status.

**Comment by iPiyushPatel** [comment]
Hi @michaelmarshall @CarsonF  
I've tested on latest a236612  devops and it's working fine for me.
Please find attached video and let me know if any
Thanks

See video: 

https://user-images.githubusercontent.com/5212585/149077269-e6541f08-e8eb-4851-b330-90a124ebaa68.mp4
