### ISSUE TITLE
Paratext PnP Failing to Extract

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2341]
When uploading the attached PnP, user selects to Extract with the Methodology of ParaText.

The file uploads and gives a Completed checkmark showing the post-upload actions should be completed.

No goals/steps are created.

https://docs.google.com/spreadsheets/d/1FM7GfM-A-sF-Eo13PmYmpeDsVMDX9IDx/edit?usp=sharing&ouid=103781340369405856620&rtpof=true&sd=true

**Comment by CarsonF** [comment]
No steps were matched because they are called: Key Terms, Footnotes, New Alphabet
