### ISSUE TITLE
Orality PnP Extract Error: `Expected parameter(s): id`

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2342]
When uploading the attached Orality PnP and selecting to export with the `Craft2Tell` methodology, users receive a post-upload action error stating `Extract Error: 'Expect parameter(s): id'`

No goals/steps are created.

https://docs.google.com/spreadsheets/d/1cmniwOoQLozbbA2X18jD1cMCm4Y52TfL/edit?usp=sharing&ouid=103781340369405856620&rtpof=true&sd=true

**Comment by CarsonF** [comment]
@sethmcknight FYI All of these rows are parsed as placeholders because no scripture has been given.

**Comment by sethmcknight** [comment]
@CarsonF yes, that sounds great as long as we have the total # of goals created
