### ISSUE TITLE
Project > Engagement > status > User can't update the status "InDevelopment "to "Active"

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2353]
**Roles:** ProjectManager,RegionalDirector,FieldOperationsDirector,Controller

**Describe the bug**
Project > Engagement> status > User can't update the status `InDevelopment` to `Active`

**Steps to Reproduce**
1. Log in as an admin user
2. Create a project 
3. Add LanguageEngagement in a created project
4. Login as a `ProjectManager` user and update the engagement status

**Expected Result**
User should update the status  `InDevelopment` to `Active`

**Actual Result**
User can't update the status `InDevelopment` to `Active`

**Note:** 
I've tested and concluded that any of the mentioned approvers (as per : [EnagementStatusFlow](https://github.com/SeedCompany/cord-api-v3/blob/56d7a63fba5e8b04439510d3d0c6bbcadbf309ab/src/components/engagement/engagement.rules.ts#L49-L355))  can not update the status of the languagEngagement 

See Screenshot -
![image](https://user-images.githubusercontent.com/5212585/150503809-9f8e9696-ea03-4908-bb05-49ef55f005c8.png)

See video: 

https://user-images.githubusercontent.com/5212585/150504366-6fe2616b-b4c8-4dc2-85bf-6ab98f4671cc.mp4

CordAPIV3# 1df03dd
cord-field# 1ae8d52

**Comment by daniel-leod** [comment]
@iPiyushPatel I think that to be able to update the engagement status you need to change the project status.  [Here](https://github.com/SeedCompany/cord-api-v3/blob/56d7a63fba5e8b04439510d3d0c6bbcadbf309ab/src/components/engagement/engagement.rules.ts#L64) on the engagement status flow shows the required project status to update the engagement status.

For example, if you want to update the engagement status from `InDevelopment` to `Active` the project status must be [`Active`](https://github.com/SeedCompany/cord-api-v3/blob/56d7a63fba5e8b04439510d3d0c6bbcadbf309ab/src/components/engagement/engagement.rules.ts#L64).

**Comment by CarsonF** [comment]
Yes we also update engagement status automatically in some cases when the project step is changed. This is one of those cases.

**Comment by CarsonF** [comment]
This is just because the project wasn't active yet. The engagement cannot be moved to active until the project is active.
