### ISSUE TITLE
BUG | Engagement Status not transitioning with Project Step

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2366]
When a Project's Step is updated, the Engagement Status is not always transitioning alongside the Project Step change.

Expected transitions can be found here: https://github.com/SeedCompany/cord-docs/wiki/Workflow-%7C-Engagement

**Comment by kjones140** [comment]
FYI - for reference the following card in Domo lists all of the current combinations that Domo considers invalid. 
 Both Seth and Carson have access to this card in Domo.
https://seedcompany.domo.com/page/1313621637/kpis/details/1404103103

**Comment by bryanjnelson** [comment]
More info from another user that points to the same issue:

On 4.11.22 a user noted that there were 18 projects with a status of "Active" which also contained Language Engagements with statuses of "In Development."

He noticed that when he confirms projects the languages don't always switch to "Active" when the project becomes "Active."  He has to click approve project twice to get it to work.

**Comment by CarsonF** [comment]
I believe this was fixed by #2406
