### ISSUE TITLE
Update Available Intern Positions

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2473]
On Intern Engagements we need to remove 2 positions as options (but keep the existing/historic data intact) and add a new option.

- Positions to remove from options but not database
    - Exegetical Facilitator
    - Translation Facilitator
- Position to add to options
    - Mid-Level Quality Assurance (under Quality Assurance program)

<img width="461" alt="Screen Shot 2022-07-20 at 10 13 39 AM" src="https://user-images.githubusercontent.com/7377802/180031411-1cfa9a54-793f-470a-9923-37bd13321c76.png">

**Comment by bryanjnelson** [comment]
@sethmcknight - What Domain would this new Mid-Level QA role map to?

**Comment by sethmcknight** [comment]
Hey @bryanjnelson I just checked this in Dev and the app crashes when you click on the box to select the Intern Position. Can you look at this?

**Comment by bryanjnelson** [comment]
@sethmcknight - Please try again now sir; the UI needed a build in Dev.  My apologies.

**Comment by sethmcknight** [comment]
Looks great @bryanjnelson ! I'm good to recluse this issue and push to master/prod whenever y'all are ready.
