### ISSUE TITLE
Add list view to Location

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#25]
As an API consumer, I want to list all locations and optionally query them using filter, order, sort, count, and page, so that I can see only the locations I want to.

Use organization service as example. The update organization test file also has a simple test for list view.

**Comment by ibohalsinghkoijam** [comment]
This ticket is done after #189 is implemented.

**Comment by michaelmarshall** [comment]
updated SP because this was really 3 tickets in one.
