### ISSUE TITLE
Intern Project should allow Completion when at Finalizing Completion

### ISSUE THREAD

**Issue by bryanjnelson** [SeedCompany/cord-api-v3#2526]
We had a Financial Analyst in a situation where an Intern Project was in Finalizing Completion, as well as the single Internship Engagement, but he did not have the option to Complete the Project.  The option should be available and should automatically advance the Internship Engagement to Complete as well.

**Comment by CarsonF** [comment]
I think we should just return the engagement statuses from that DB query used and then exclude engagement's with `FinalizingCompletion` status from that check.
