### ISSUE TITLE
Workflow for Project

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#254]
Once the workflow API is done, use it to create a workflow on project nodes when they are created. We will hard code Seed Company's business rules at this time. Get with Carson or Daniel for a knowledge transfer on those business rules.

**Comment by sethmcknight** [comment]
Project Workflow business rules are documented here: 

https://github.com/SeedCompany/cord-api-v3/wiki/Project-Workflows

**Comment by sethmcknight** [comment]
Cord Field 2's email templates are here: https://github.com/SeedCompany/cord-api-plo/tree/6400b4c618aa2efe8ca85d0d2af51c191a5dc31f/src/config/templates/email/field/status-changed
