### ISSUE TITLE
Workflow for Engagements

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#255]
Set Workflow options on Engagements that match the Workflow options on Projects, except for In Development

**Comment by elisabeth-sorrell** [comment]
Bug: https://github.com/SeedCompany/cord-api-v3/issues/1557

**Comment by elisabeth-sorrell** [comment]
Iteration 2 PR: https://github.com/SeedCompany/cord-api-v3/pull/1568

**Comment by elisabeth-sorrell** [comment]
PR last iteration: https://github.com/SeedCompany/cord-api-v3/pull/1579
ignore PR #1568 because this one is pretty much branched off of that one.
