### ISSUE TITLE
PnP progress sheet upload is not extracting the step percentages  

### ISSUE THREAD

**Issue by atGit2021** [SeedCompany/cord-api-v3#2563]
## Current Behavior
Books with multiple chapter/verse goals which have scripture references in the notes columns of the PnP planning sheet are not being extracted correctly in the  PnP progress upload because the progress sheet does not have a notes section to also specify or pull in the same scripture reference.  The system cannot process more than one unspecified scripture from the same book with the same number of verses to translate, and therefore, does not extract the step percentages for those books/goals.

## Expected Behavior
The step percentages for each step should be extracted correctly for each book/goal.

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3521773836) by [Unito](https://www.unito.io)

**Comment by atGit2021** [comment]
> The progress rows correspond one for one to the planning sheet rows. Can we just match & extract this info from the planning sheet? Matching based on index is like a last, last resort IMO.

I'm not sure if I follow you, maybe this will be easier to discuss.  During the progress sheet upload the only info we have to work with during the extraction handler process is: bookName, totalVerses, rowIndex, order, and steps.

**Comment by CarsonF** [comment]
Fixed with #2564. It's live as well.
