### ISSUE TITLE
Refactor session query out of resolver

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#276]
Back in the day we thought that each service function would require an authenticated user and so Carson made a decorator for resolvers to get the user's session from the token parameter. This meant that each query hit the DB before a request got to a service. 

Now I'm thinking that wasn't the best thing because a service may what to do more/less with a token/user and it'd be better to keep all that logic in a service to make more efficient use/minimization of DB calls.

Task:

1. Remove the use of the @Session() decorator in all resolvers.
1. Add the use of the @Session() decorator in each service function that needs the token converted into a session object.
1. Update tests as necessary.

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466938082) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
@michaelmarshall Session decorators have to stay at the _resolver_ level. _Resolvers_ are like _controllers_ and only _controllers_ know about _requests_.

What's included in the `SessionPipe` and the shape of `ISession` result can easily be changed though. (Other than having to change usage across the codebase.)

If continuing in this direction, it might be a good idea to abstract that piece of the query into a helper function so it's not copied in hundreds of queries.

Technically there could be a way to move them to services with let each request get it's own instance of a service, but that would require a lot more work.

**Comment by michaelmarshall** [comment]
@CarsonF Thanks Carson. So let's put this as a new function in the common folder that all services can call. For now I think it should be a stand-alone query that simply replaces the decorator. This will be the easiest way to refactor. Whoever takes this should just ping me and we can have a quick discussion.

**Comment by CarsonF** [comment]
Let's try again. Services exist independent of requests, so there's no way for a service to determine info for "the current request". This is why it has to be passed from a controller/resolver which gets passed "the request" (via decorators).

**Comment by michaelmarshall** [comment]
lol. I forgot the token is in the header. The resolver just needs to snag the token and pass it to the service without a DB call. That is what I was going for.

**Comment by CarsonF** [comment]
Yep that will work. 

Though I doubt this is the best way to optimize. We already have more than on db query on most calls. Removing one isn't going to help that much.
