### ISSUE TITLE
List all partnerships given a projectId

### ISSUE THREAD

**Issue by candleshine** [SeedCompany/cord-api-v3#34]
the list query should be given as input a projectId and get all the partnerships
follow the pattern of also allowing someone to filter, order, sort, count, and page.  This will probably be unnecessary as the maximum number of partnerships on a project rarely exceeds 2.  But who knows.

**Comment by michaelmarshall** [comment]
match (proj {id:"10"}), (org {id:"11"})
create (proj)-[:partnership {active: true}]->(partner:Partnership {active: true})-[:mouStart {active: true}]->(:Property {value: "iso datetime"}),
(partner)-[:organization {active: true}]->(org),
(partner)-[:mouEnd {active: true}]->(:Property {active: true, value: "asdf"})
return *
