### ISSUE TITLE
Implement script to create training data set

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#384]
We need to create a script to create training data for the new training environment. sethmcknight will provide the description of the data we need. This script should go in the /scripts folder and run as a standalone TS script the calls the API to create the data set. The data will be hardcoded, either in the script file or a /training subfolder if needed.

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466949373) by [Unito](https://www.unito.io)

**Comment by sethmcknight** [comment]
Training data will be provided in #383
