### ISSUE TITLE
Create "verse range" concept with CRUD+L

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#387]
The Product DB schema has been refactored and now needs to be implemented in the API and service. Consult the Lucidchart doc to see the changes. 

The big change is the use of an array of verse ranges that products will be identified with (as applicable to the product). 

We need to determine the best way to convert two Bible references to an integer range (absolute verse). 

1. Figure out how to convert a Bible reference to its absolute verse.
2. Create a submodule within `product` to do CRUD+L on your new verse range. This will be an API that will be used to attach ranges to different types of products. Not all products will have a verse range.  Remember that a product may have multiple `:Range`s.

**Comment by candleshine** [comment]
closed with #487
