### ISSUE TITLE
Fix Internship engagements

### ISSUE THREAD

**Issue by gowthamrodda** [SeedCompany/cord-api-v3#439]
When creating an internship engagement, its not connected with intern/mentor node. function has to be updated to get intern/mentor

**Comment by candleshine** [comment]
Those are nullable fields.  They will probably be added in an update, not in create.  Make sure the update Function also is able to make the connection.

**Comment by candleshine** [comment]
My note about being nullable is probably unclear.  So make sure that when you add the queries, you check for existence of the variable first.  It might be missing and you might get a Neo4J error if you pass in null

**Comment by CarsonF** [comment]
- intern is required and has to be set when creating the engagement
- intern cannot be changed later
- mentor can be given at creation and/or on updates. it is nullable because of this.
