### ISSUE TITLE
User.status property

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#459]
From an API perspective add a `status` property like this:
```tsx
interface User {
  status: UserStatus;
}
enum UserStatus {
  'Active',
  'Disabled'
}
```
This would allow for other/finer-grain states in the future, like 'Inactive' or 'Online'.

However, we also need to not let someone login if they are disabled.
Which means we need this to be editable from the API. So we probably need a `disabled` property as well. Though I'm frowning at the double negative - i.e. "are you not disabled". Would `enabled` be better? I know the DB uses `active` all over the place but that's not exposed to the API.

**Comment by candleshine** [comment]
Regarding the naming of the statuses.  
Are we tracking Offline and Online status of a user?  Or are we tracking something else.  Users have that `active: true` flag for when we delete a user. 

I think we need to avoid `disable` because that has other meanings.
