### ISSUE TITLE
User.primaryOrganization

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#460]
Add a `primaryOrganization` property to `User`

- Does this need to be secured?

**Comment by michaelmarshall** [comment]
for now let's not `secure` this. see what happens.

**Comment by candleshine** [comment]
we won't store this as a property.  We will take one of the one-to-many relationships between User and Organization and set that relationship to `primaryOrganization`

**Comment by candleshine** [comment]
When you create `primaryOrganization` is null
When you update `primaryOrganization` is set as a link to the organizations linked out from the User, with the relationship named `primaryOrganization`.  That will be a second relationship in the Neo4J world.  
when you read.  You need to return the Organization that you link to
