### ISSUE TITLE
ProjectService.listProjectMembers does not filter correctly

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#499]
`ProjectService.listProjectMembers` should only return members of the given project.

**Comment by ibohalsinghkoijam** [comment]
<img width="1167" alt="Project-teams-playground-query" src="https://user-images.githubusercontent.com/24403111/85151378-56786200-b271-11ea-93e6-37d97f7ce55f.png">

**Comment by ibohalsinghkoijam** [comment]
This ticket is handled via 551 (Unable to query `team` field values in `project()` query)
