### ISSUE TITLE
sgUpdateProperty method is updating new properties but not making old properties as false

### ISSUE THREAD

**Issue by gowthamrodda** [SeedCompany/cord-api-v3#532]
sgUpdateProperty –this  method is updating new properties but not making old properties as false

**Comment by ibohalsinghkoijam** [comment]
<img width="969" alt="After-Project-update" src="https://user-images.githubusercontent.com/24403111/87565850-d0b8cc80-c6df-11ea-8657-b1935b8270a5.png">
