### ISSUE TITLE
Unable to query name on an organization in the users query

### ISSUE THREAD

**Issue by candleshine** [SeedCompany/cord-api-v3#536]
I am confirming with @glassblowerscat that this query
```
mutation assignOrganizationToUser(
          $orgId: ID!
          $userId: ID!
          $primary: Boolean!
        ) {
          assignOrganizationToUser(
            input: {
              request: { orgId: $orgId, userId: $userId, primary: $primary }
            }
          )
        }
```
was called.  

We have a working e2e test for getting org.  

DEV: please add `name` field specifcally to the e2e test

**Comment by glassblowerscat** [comment]
@candleshine The issue here is not that including the `organization` field in the `users` query doesn't return data for any given user; it's that including this field causes the entire query to return an error. Sorry, I should have been more clear in my description.

Here's an example of a query that returns an error:

```
{
  users {
    items {
      email {
        value
      }
      fullName
      organizations {
        items {
          id
        }
      }
    }
  }
}
```

Removing the `organizations` field from this query will cause it to run correctly.

**Comment by candleshine** [comment]
User A cannot get the details of User B without being given those permissions.  WHich is why when you query more than one user, you can't get those orgs.  Unless you get those permissions.  To circumvent this, we will give you an update where the permissions are wide open as a temporary measure.  
@michaelmarshall will be rethinking how to get the permissions right.  Step one will be to add notion of public data.  He should have a new ticket for this soon.  

Also, Michael, there is an API to add a person to a security group, but not a way to find out what another person's or even node's security groups are.  THink through how the workflow is to get User B read access to User A

**Comment by michaelmarshall** [comment]
@candleshine I've merged my public data ticket into master. please review the new functionality in the playground and let me know if this helps/hurts you. I've made org names public so it should still work.
