### ISSUE TITLE
refactor create* functions out of e2e-spec.ts files

### ISSUE THREAD

**Issue by candleshine** [SeedCompany/cord-api-v3#54]
As a developer, it would be better to move all the create* functions out of their individual e2e testfiles and move them to the test-utility.ts for example move createLanguage to that file.

**Comment by michaelmarshall** [comment]
@ibohalsinghkoijam take a look at carson's latest master. we'll want to use the new graphql method.

**Comment by candleshine** [comment]
Koijam the files are now separated in a test/utility folder.  Match the current pattern.  
Google GraphQL fragments to see what he's doing in `create-user`

**Comment by candleshine** [comment]
Looking at the `test/utility` folder these are done.  user, organization, language, education, unavailability.  
TODO: 
- [ ] project
- [ ] project-engagement
- [ ] internship
- [ ] internship-engagement
- [ ] product
