### ISSUE TITLE
organizations query doesn't return name

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#563]
![image](https://user-images.githubusercontent.com/1165460/85078926-2eaece80-b18b-11ea-959a-d50ed30e2c39.png)

**Comment by michaelmarshall** [comment]
still broke 
![image](https://user-images.githubusercontent.com/1165460/85185602-42753600-b25a-11ea-94ac-d5c9cd7a6a68.png)

**Comment by michaelmarshall** [comment]
we have a bug in projects read/list. I need to refactor lists and reads. #576 was created for this.

**Comment by punamasawa777** [comment]
Here is Fix

<img width="1433" alt="Screenshot 2020-06-19 at 8 31 25 PM" src="https://user-images.githubusercontent.com/64840907/85215709-182a9200-b39a-11ea-9028-6c2b55bde0d0.png">
