### ISSUE TITLE
Project Initial Budget Status

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#574]
The first budget created with the project creation should have a status of _Current_ instead of _Pending_.

Need to pass parameter here to make that happen
https://github.com/SeedCompany/cord-api-v3/blob/67721f328dd20846b400e2ea090aeb1298799a58/src/components/project/project.service.ts#L714

**Comment by CarsonF** [comment]
Only the first budget created for a project should be current. Subsequent budgets should be pending.

**Comment by CarsonF** [comment]
After talking through this more I want to change the logic.
- Budgets should _always_ be created as a pending status
- Budget records are only editable if the budget is pending
- `ProjectService.currentBudget` should filter to the budget that is current (as it's doing now) but then fallback to the first pending budget (new logic).
  - Thus `project.budget` can either be a current budget or a pending one
- The pending budget should be set to active when the project gets set to active

This way isolates budget mutably logic from project logic, and the only connection point is their statuses. This is easier to reason about.

**Comment by candleshine** [comment]
@CarsonF Budget does not have an Active Status.  The enum is 
```
export enum BudgetStatus {
  Pending = 'Pending',
  Current = 'Current',
  Superceded = 'Superceded',
  Rejected = 'Rejected',
}
```

Also there is no field for status in UpdateProject DTO

**Comment by CarsonF** [comment]
Sorry I meant _current_.
Yes project status gets changed through a workflow API, which still needs to be addressed. That specific logic could wait to be done later.

**Comment by candleshine** [comment]
@ibohalsinghkoijam do not change updateProject DTO.
