### ISSUE TITLE
Organization Filter Bug

### ISSUE THREAD

**Issue by punamasawa777** [SeedCompany/cord-api-v3#579]
Unexpected Filter results

**Comment by michaelmarshall** [comment]
My refactor didn't do filtering. @punamasawa777 let's chat when you get a chance. Also please post a screenshot to show what you mean.

**Comment by punamasawa777** [comment]
@michaelmarshall , This filter Issue is before ur refactor

Let me show u in screenshot placed here

<img width="1430" alt="Screenshot 2020-06-24 at 3 17 23 PM" src="https://user-images.githubusercontent.com/64840907/85533275-03662c80-b62e-11ea-953a-71b214e21130.png">

**Comment by punamasawa777** [comment]
@michaelmarshall , This Issue is Fixed now with PR  #580
