### ISSUE TITLE
Data Migration

### ISSUE THREAD

**Issue by blakekrammes** [SeedCompany/cord-api-v3#58]
We need to migrate our data from Mongo to Neo4j. The final iteration of this will use the API, but for now I'll be running this migration to a local Neo4j database using Cypher queries. 

** This issue is an on-going, work-on-as-time-allows sort of thing.

**Comment by blakekrammes** [comment]
@michaelmarshall, you probably were account for https://github.com/SeedCompany/cord-api-v3/issues/86 in the estimate so maybe this issue should be re-estimated. I thought I should show more of what I did work on last week so it doesn't look so nebulous.

**Comment by michaelmarshall** [comment]
closing, duplicate.
