### ISSUE TITLE
Project Partnerships list is empty

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#584]
![Screen Shot 2020-06-23 at 10 49 51 AM](https://user-images.githubusercontent.com/932566/85425878-6036e980-b53f-11ea-87df-94bf150900eb.png)
![Screen Shot 2020-06-23 at 10 50 21 AM](https://user-images.githubusercontent.com/932566/85425882-6200ad00-b53f-11ea-92fe-f94db2b8de21.png)

**Comment by ibohalsinghkoijam** [comment]
<img width="1132" alt="Project-Partnershipl-list" src="https://user-images.githubusercontent.com/24403111/85569697-649ef780-b650-11ea-9072-02bb7406fab7.png">

**Comment by michaelmarshall** [comment]
@ibohalsinghkoijam awesome, I love seeing the screenshots. thx Koijam.
