### ISSUE TITLE
Check every read and list query for cartesian product

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#586]
Our read and list queries may need to be further optimized. We need to check each one to ensure they are written correctly.

To check the query, I made a convenience function in `src/core/database/query.helper.ts` to print to the console:
![image](https://user-images.githubusercontent.com/1165460/85456726-df8ae400-b564-11ea-9da4-85fa7fe37c70.png)

Which will print out the query:
![image](https://user-images.githubusercontent.com/1165460/85457375-9edf9a80-b565-11ea-9573-d7aff95c4cca.png)

Copy that into the Neo4j Browser:
![image](https://user-images.githubusercontent.com/1165460/85457422-ae5ee380-b565-11ea-9c17-05100b825436.png)

Look for a hazard symbol showing that the query forms a cartesian product. 
Here is an example I made:
![image](https://user-images.githubusercontent.com/1165460/85457766-0564b880-b566-11ea-9eb7-36837c33ebdb.png)

Then add the word `explain` before your query:
![image](https://user-images.githubusercontent.com/1165460/85459569-ec5d0700-b567-11ea-853a-69a59d3e75c2.png)

and check the result to see if there is a box that says cartesian product:
![image](https://user-images.githubusercontent.com/1165460/85459619-fbdc5000-b567-11ea-90ba-82dc2fab5046.png)

If you find that a query forms a cartesian product, simply create another ticket to address it. This ticket is only to print out and check all read and list queries. 

Here are some links to read about cartesian product:
https://neo4j.com/developer/kb/cross-product-cypher-queries-will-not-perform-well/
https://community.neo4j.com/t/avoid-cartesian-product-when-create-relationships/13624
https://community.neo4j.com/t/neo4j-browser-exercises-suggests-queries-that-leads-to-cartesian-product-warning/9015
https://community.neo4j.com/t/compare-nodes-from-one-group-without-cartesian-product/10256
https://stackoverflow.com/questions/33352673/why-does-neo4j-warn-this-query-builds-a-cartesian-product-between-disconnected

**Comment by punamasawa777** [comment]
@michaelmarshall ,
i have gone through entire Project
I have found issue with four queries
here is list that forms a cartesian product.

Issues
1. InternshipEngagement (readOne Function)
2. LanguageEngagement (readOne Function)
3. Ceremony (readOne Function)
4. Product (readOne Function) but still uses ACL

**Comment by michaelmarshall** [comment]
Awesome Punam. Good job! this helps.
