### ISSUE TITLE
Add root admin user to all security groups when they are created

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#588]
Whenever we create a security group we need to add the root user to it so that account has access to all data. 

1. Find all places security groups are created.
2. Update the query or make a separate query that adds the root admin (id: `rootadminid`) to the newly created security group(s).
3. Run the test suite.
4. Run the following query in the Neo4j browser after the test suite is done
```
match (sg:SecurityGroup)
match (user:User {id: "rootadminid"})
where not (user)<-[:member]-(sg)
return count(sg)
```
5. If the return is 0, you are good. If its not, there is still some security groups that are being created that the root admin is not being added to.

**Comment by punamasawa777** [comment]
Here is the Fix

<img width="1332" alt="Screenshot 2020-06-25 at 11 46 18 PM" src="https://user-images.githubusercontent.com/64840907/85778364-1e28c600-b740-11ea-8163-a797c0d7b96a.png">
