### ISSUE TITLE
Create Project > Getting "Unhandled Rejection (Error): Could not resolve project type"  error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#591]
**Describe the bug**
Create Project > Getting "Unhandled Rejection (Error): Could not resolve project type"  error

**Steps to Reproduce**
Refer Video : https://www.awesomescreenshot.com/video/259559?key=09e3d2c19024579a0e6eff4552609de1

CoreField - 6adc145
CordAPIV3 - 31f55a2

**Comment by punamasawa777** [comment]
@michaelmarshall , In Create Project > property [Type] is commented, Is there any purpose ?
As i am uncommenting those lines

**Comment by michaelmarshall** [comment]
@punamasawa777  Yes, if I remember correctly, I moved the type property to be on the baseNode itself. I believe those lines can be deleted.

**Comment by punamasawa777** [comment]
This is Fixed with #649

<img width="1429" alt="Screenshot 2020-07-01 at 5 41 00 PM" src="https://user-images.githubusercontent.com/64840907/86272639-866a2280-bbec-11ea-9bbd-b78aa51cd173.png">
