### ISSUE TITLE
Create Language > Can't create successfully

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#592]
Describe the bug
Create Project > Can't create successfully

Steps to Reproduce
Refer Video : https://www.awesomescreenshot.com/video/259576?key=6bce1cf65ef7aec23e234b770a6a6321

CoreField - 6adc145
CordAPIV3 - 31f55a2

**Comment by iPiyushPatel** [comment]
Hi @michaelmarshall I can still replicate this issue. Here is the video - https://www.awesomescreenshot.com/video/311754?key=73fe9bd1799086ec27b25a14fd30217a

Please suggest if any.

**Comment by punamasawa777** [comment]
Hi @iPiyushPatel , RodNumber input must be String (Not Number)

**Comment by iPiyushPatel** [comment]
Hi @punamasawa777 Got it finally :) , I will update cases accordingly. But I see validation message isn't user friendly. So should I raise a new bug for that ? @CarsonF @michaelmarshall

**Comment by CarsonF** [comment]
What's the error object you see?

**Comment by iPiyushPatel** [comment]
@CarsonF  This is what I'm getting - 

![image](https://user-images.githubusercontent.com/5212585/86372278-9858cd80-bc9f-11ea-949c-5b8a350b3950.png)

**Comment by punamasawa777** [comment]
Hi @iPiyushPatel , Here is CreateLanguage with RodNumber

<img width="1428" alt="Screenshot 2020-07-02 at 8 18 35 PM" src="https://user-images.githubusercontent.com/64840907/86373519-208ba280-bca1-11ea-9f76-c93af02e1c45.png">

**Comment by CarsonF** [comment]
Yeah that's fine. That's a great dev message and a user won't ever see that.
Btw the latest frontend code already had that fixed.

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
I've verified on FE locally (have taken latest of CoreField API/UI repo as well). Still I see FE doesn't allow String to enter as Rod Number and still message is displayed. 

https://www.awesomescreenshot.com/video/319851?key=904b54ad0379bdc4ad932c283ecd6046

Please suggest. 

thanks,
Piyush

cc @michaelmarshall @reneepe
