### ISSUE TITLE
fix file service and unskip test

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#594]
A recent bug fix wouldn't pass a file test. I believe this is actually an intermittent file bug I've seen many times before. This ticket is the address this. 

Unskip the test and try to find a way to repro the bug. Maybe run the file test after wiping the DB, or delete the `dist` folder. Try to find a way to repro this intermittent bug.

Here is the commit where the test was unskipped:
![image](https://user-images.githubusercontent.com/1165460/85606800-22a68f00-b619-11ea-8ad2-bb75536a0efa.png)

**Comment by ibohalsinghkoijam** [comment]
<img width="617" alt="testcasesCI" src="https://user-images.githubusercontent.com/24403111/85714465-10efe500-b708-11ea-845d-48459a01ee19.png">

**Comment by ibohalsinghkoijam** [comment]
sometimes, it is observed that test cases are failed due to timeout error.
