### ISSUE TITLE
Sync Project & Partnership Start/End Dates

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#596]
- Project mouStart and mouEnd should set the values of all partnership's mouStart and mouEnd that are null.
- Also partnerships start/end should default to project start/end if already set.

**Comment by CarsonF** [comment]
There's more too for updating existing partnership dates based on project status. I can't remember of the top of my head. @sethmcknight feel free to help doc if you can.

**Comment by CarsonF** [comment]
Thinking about it more I think there's a better way. I think really we want to express that:
1. this partnership matches the project's date range 
2. this partnership is a subset of the project's date range. i.e. ends before the project does or starts after the project does

Therefore we could have the null values represent _inheriting_ from the project's range, and actual values be the "overrides".
Then we would need computed properties to determine the current value of the range - the override values or project's values.

Taking this approach means we don't have to figure out all the edge cases in the _assumptions_ of what the user what's do. Which is inherently fragile.

**Comment by CarsonF** [comment]
I've done something similar in my language-api branch.
I have a [calculated `population` field](https://github.com/SeedCompany/cord-api-v3/blob/2134ff8e95822b2d499dc2fed9e68714f8e08485/src/components/language/language.resolver.ts#L64-L82) that uses the [`populationOverride` field](https://github.com/SeedCompany/cord-api-v3/blob/2134ff8e95822b2d499dc2fed9e68714f8e08485/src/components/language/dto/language.dto.ts#L43-L46) if defined or it fallsback to the `ethnoluge.population` field.

We could have the same pattern here:
- `mouStartOverride` & `mouEndOverride` fields
- calculated `mouStart` & `mouEnd` fields which use those override fields or fallback to the project's `mouStart/mouEnd`.

**Comment by sethmcknight** [comment]
> I've done something similar in my language-api branch.
> I have a [calculated `population` field](https://github.com/SeedCompany/cord-api-v3/blob/2134ff8e95822b2d499dc2fed9e68714f8e08485/src/components/language/language.resolver.ts#L64-L82) that uses the [`populationOverride` field](https://github.com/SeedCompany/cord-api-v3/blob/2134ff8e95822b2d499dc2fed9e68714f8e08485/src/components/language/dto/language.dto.ts#L43-L46) if defined or it fallsback to the `ethnoluge.population` field.
> 
> We could have the same pattern here:
> 
> * `mouStartOverride` & `mouEndOverride` fields
> * calculated `mouStart` & `mouEnd` fields which use those override fields or fallback to the project's `mouStart/mouEnd`.

@CarsonF this sounds good to me

**Comment by candleshine** [comment]
If I may change the terminology.  The "Override fields" are the fields on the Partnership.  The calculated fields are the ones on the project.  The Create/Update does not need to change at all.  Instead there just needs to be a change to the query logic.  

If there is a partnership mouStart/mouEnd, then you display those dates as override.  If those don't exist, that means the dates aren't overridden and you display the project mouStart/mouEnd

**Comment by CarsonF** [comment]
> The "Override fields" are the fields on the Partnership. The calculated fields are the ones on the project.

The project ones are also not "calculated". They are not based on anything else.

> If there is a partnership mouStart/mouEnd, then you display those dates as override. If those don't exist, that means the dates aren't overridden and you display the project mouStart/mouEnd

That works until we need to make an edit. Then the FE isn't sure if the date is an override or if it came from the project.
That's why partnership has both override fields and calculated fields that pick the one in-use.
