### ISSUE TITLE
Create Organization provides error "failed to create default org"

### ISSUE THREAD

**Issue by ibohalsinghkoijam** [SeedCompany/cord-api-v3#601]
The following query return  -> (no changes, no records)

MATCH (publicSg:PublicSecurityGroup { active: true })
CREATE (orgSg:OrgPublicSecurityGroup:SecurityGroup {
      active: true,
      id: 'Z38dwR49VM',
      createdAt: datetime()
    })-[:organization]->(org:Organization:BaseNode {
      active: true,
      id: 'jPQv9n8ID',
      createdAt: datetime(),
      owningOrgId: 'Seed Company'
    })-[:name { active: true, createdAt: datetime() }]->(name:Property:OrgName {
      active: true,
      createdAt: datetime(),
      value: 'olive'
    })
WITH *
CREATE (publicSg)-[:permission { active: true }]->(perm:Permission { active: true, property: 'name', read: true })-[:baseNode { active: true }]->(org)
RETURN org

**Comment by ibohalsinghkoijam** [comment]
<img width="1393" alt="CreatingOrganzationError" src="https://user-images.githubusercontent.com/24403111/85701903-80130c80-b6fb-11ea-8902-83c9c70759ab.png">

**Comment by ibohalsinghkoijam** [comment]
<img width="1393" alt="CreatingOrganzationError" src="https://user-images.githubusercontent.com/24403111/85701958-8f925580-b6fb-11ea-9466-f91de1f5f791.png">

**Comment by ibohalsinghkoijam** [comment]
If we got deleted 'root user' or unable to create 'root user' during bootstrapping of the server.

**Comment by michaelmarshall** [comment]
this behavior is experienced when you wipe your DB without restarted the api server. You need to restart the server every time you wipe the db.
