### ISSUE TITLE
Able to create Partnership with fake organizationId

### ISSUE THREAD

**Issue by ibohalsinghkoijam** [SeedCompany/cord-api-v3#602]
Steps to reproduce:

STEP 1 - createPartnership with fake organizationId and projectId using playground. Partnership is created successfully.

STEP 2 - execute query with playground
query {
  partnership(id: "TaKQf0JYu") {
    organization {
     id
    }
  }
}

Observed Result - Getting error "Cannot return null for non-nullable field Organization.id" (attached with screen shot)
Expected Result - Unable to create Partnership if organization does not exist. There should be validation messages.

**Comment by ibohalsinghkoijam** [comment]
<img width="1269" alt="PartnershipError" src="https://user-images.githubusercontent.com/24403111/85711967-72fb1b00-b705-11ea-8e19-8e3a51e8ee6f.png">

**Comment by michaelmarshall** [comment]
@candleshine I saw your comment in the commit. Can you create a ticket for the test refactor after the merge?

**Comment by michaelmarshall** [comment]
closed #631
