### ISSUE TITLE
Organization >Create > Org can be created with just spaces

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#604]
**Describe the bug**
Organization >Create > Org can be created with just spaces

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap and execute request.

**Expected Result**
Validation message should be returned as Org name has <=2 chars.

**Actual Result**
Org is created successfully

![image](https://user-images.githubusercontent.com/5212585/85755622-bd8f8e00-b72b-11ea-84a7-7d4dd20df5ed.png)

Commit # 835a471

**Comment by candleshine** [comment]
@michaelmarshall @CarsonF probably enforce this on the front end, not need to catch on the backend.  Or do you want to give a regexp that will be either stripped or rejected cases?
Same comment applies to #605

**Comment by CarsonF** [comment]
Yeah I'm not too worried about this. We already trim strings, I believe. This also doesn't cause a data problem. Like a relationship to an ID that doesn't actually exist. Also the name can be edited when ever. 

If we do end up doing something on the API, it can be with decorators on those input fields.
