### ISSUE TITLE
Organization > Create > Org can be created with just special characters

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#605]
**Describe the bug**
Organization >Create > Org can be created with just special characters

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap and execute request.

**Expected Result**
Validation message should be returned as Org name doesn't have alphabetical characters

**Actual Result**
Org is created successfully

![image](https://user-images.githubusercontent.com/5212585/85756454-70f88280-b72c-11ea-8133-be20fccf62d4.png)

Commit # 835a471

**Comment by CarsonF** [comment]
This is ok
