### ISSUE TITLE
[Bug] When created language engagement asking for status errors

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#609]
**Describe the bug**
When creating a language engagement, if status is asked in the return values the response errors

**Steps to Reproduce**
Create Language Engagement in the playground, providing the project id and language id, in the return value ask for the status field.  See screenshot

**Expected and Actual Results**
ER: successful query and status value returns
AR: query fails with `Cannot return null for non-nullable field LanguageEngagement.status.`

**Screenshots**
<img width="1584" alt="Screen Shot 2020-06-25 at 1 48 33 PM" src="https://user-images.githubusercontent.com/43487134/85797355-4688d400-b6f0-11ea-850d-5dcd97d9fd96.png">

**Platform/Environment**  
Local dev env in gql playground

Desktop:

Smartphone:

**Additional context**

**Comment by michaelmarshall** [comment]
got viewing status working:
![image](https://user-images.githubusercontent.com/1165460/85817032-7eb10680-b732-11ea-90a4-76c41c9a70ea.png)
but it breaks other tests.

**Comment by michaelmarshall** [comment]
I thought it might be a security group issue so when I looked into that I realized that many of our security groups were being created without IDs. which means no one would be able to associate users to them. I added IDs to all SGs. 

Status wasn't being added to the engagement when it was created, so I added that then made sure it was read out. Some how that broke some tests. @ibohalsinghkoijam if you can finish this, I am going to sleep now and check in when I get up.

**Comment by michaelmarshall** [comment]
branch is `engagement-status`

**Comment by punamasawa777** [comment]
@michaelmarshall , Fixed all the broken Testcases in branch engagement-status

**Comment by frankyma** [comment]
tested with @michaelmarshall on June 26 and still broken.  Test this on language engagements, and make sure when creating a new language engagement only supply the required `projectId` and `languageId`

**Comment by candleshine** [comment]
status and modifiedAt are not part of the return value of read.  I will update

**Comment by candleshine** [comment]
![image](https://user-images.githubusercontent.com/7391036/86249943-8c70ec80-bb75-11ea-8f17-ecf9054ccc4c.png)
