### ISSUE TITLE
Refactor Location to create relationships to area and region

### ISSUE THREAD

**Issue by candleshine** [SeedCompany/cord-api-v3#61]
As a developer, the location CRUD currently stores area and region as a string.  It needs to create a relationship to the area node and the region node

**Comment by candleshine** [comment]
Location is part of an Area
Area is part of a region
the relationship will be called `isIn`

**Comment by michaelmarshall** [comment]
@candleshine we need to sync up with @CarsonF . he's refactored Location DTOs

**Comment by candleshine** [comment]
closed with #224
