### ISSUE TITLE
[Bug] Cannot create internship engagement

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#610]
**Describe the bug**
Cannot create internship engagement mutation

**Steps to Reproduce**
use the `mutation createInternshipEngagement`.  in the input I used my own uID as internId.

**Expected and Actual Results**
ER: Create successful
AR: Generic failure message

**Screenshots**
<img width="1550" alt="Screen Shot 2020-06-25 at 2 32 29 PM" src="https://user-images.githubusercontent.com/43487134/85797709-0544f400-b6f1-11ea-927f-8ff5526b25a8.png">

**Platform/Environment**  
Clear report on what the bug can be reproduced. Please complete the following information accordingly.

Desktop:

Smartphone:

**Additional context**

**Comment by punamasawa777** [comment]
This is Fixed 

Here is Screenshot

<img width="1155" alt="Screenshot 2020-06-26 at 8 32 38 PM" src="https://user-images.githubusercontent.com/64840907/85875111-59370200-b7f1-11ea-9f85-cd92e0d48969.png">

**Comment by frankyma** [comment]
As @michaelmarshall mentioned, need to make all items like position and country of origin required fields on creation for this to work

**Comment by candleshine** [comment]
I will make those fields required

**Comment by candleshine** [comment]
#646 will satisfy the requirements of this ticket, but I think there is some more stability work to be done with internship engagements which will start with #642

**Comment by candleshine** [comment]
![image](https://user-images.githubusercontent.com/7391036/86262953-25a7ff00-bb86-11ea-928a-63e79eaf13c2.png)
