### ISSUE TITLE
Users > No data is returned

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#614]
**Describe the bug**
Users > No data is returned

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap and execute request.

**Expected Results**
User data should be returned in response.

**Actual Results**
![Screenshot (10)](https://user-images.githubusercontent.com/5212585/85832283-67fbc580-b7ad-11ea-87c6-a20719109d7f.png)

**Comment by michaelmarshall** [comment]
@iPiyushPatel can you confirm you have created a session, and are logged in with the user account that registered that user?

**Comment by iPiyushPatel** [comment]
Hi @michaelmarshall 
It's working now. see snap below. 

![image](https://user-images.githubusercontent.com/5212585/86007995-d6eb4f80-ba35-11ea-9c48-1e65eaa20e86.png)


I'll work on writing detailed cases now. 

Thanks,
