### ISSUE TITLE
[Bug] Querying engagements doesn't return internship engagements

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#620]
**Describe the bug**
Querying (all) engagements only returns the language engagements, not internship.

**Steps to Reproduce**
1. create internship engagements and language engagements (will need to create project, language, and use those ids in the playground)
2. run the engagements query

**Expected and Actual Results**
ER: get all the engagements created
AR: only get back the language engagements, internship engagement missing

**Screenshots**
Can see the internship engagement when asked directly
<img width="1303" alt="Screen Shot 2020-06-26 at 2 43 31 PM" src="https://user-images.githubusercontent.com/43487134/85903609-8ff22580-b7bb-11ea-86f2-17a24cd5dbfd.png">

missing from the list
<img width="1434" alt="Screen Shot 2020-06-26 at 2 43 58 PM" src="https://user-images.githubusercontent.com/43487134/85903618-97193380-b7bb-11ea-9f22-f0c8fbedbb7e.png">

**Platform/Environment**  
Clear report on what the bug can be reproduced. Please complete the following information accordingly.

Desktop:

Smartphone:

**Additional context**

**Comment by frankyma** [comment]
Just ran this query on the test data, and while it **did** return both types of engagements from the existing engagement list, it **did not** return a newly created internship engagement.

**Comment by candleshine** [comment]
![image](https://user-images.githubusercontent.com/7391036/86165911-99d89900-bad9-11ea-8a87-a6922ffbcc03.png)
