### ISSUE TITLE
Get All Organization > Returns all records when searched with specific Org Name

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#623]
**Describe the bug**
Get All Organization > Returns all records when searched with specific Org Name

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap and execute request.

**Expected Result**
Result should return only specific organization

**Actual Result**
All organization created by that users are returned 

GraphQL Query:
![image](https://user-images.githubusercontent.com/5212585/86002969-bff52f00-ba2e-11ea-8e46-9e9fb1abdcaf.png)

CordAPIV3# e9d7d88

**Comment by candleshine** [comment]
Repeat of #603

**Comment by michaelmarshall** [comment]
Closing ^^
