### ISSUE TITLE
Get All Organization > No records are returned while filtering by userId

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#624]
**Describe the bug**
Get All Organization > No records are returned while filtering by userId

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap and execute request.

**Expected Result**
Result should return only specific organizations created by given userId

**Actual Result**
No Records are returned. I've noticed that if I remove userId filter then it returns all organizations created by that user. SEE video.
https://www.awesomescreenshot.com/video/291032?key=54b2cd45830f5b3522a0aaaf4d5ff1d0

**GraphQL Query:**
![image](https://user-images.githubusercontent.com/5212585/86003467-73f6ba00-ba2f-11ea-93bd-a29acea04fee.png)

CordAPIV3# e9d7d88

**Comment by CarsonF** [comment]
This is about to be removed from the API so it can be ignored.
