### ISSUE TITLE
Update Project > updateProject > Request is successful even though it doesn't contain mandatory info i.e. name

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#625]
**Describe the bug**
Update Project > updateProject > Request is successful even though it doesn't contain mandatory info i.e. name

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap and execute request.

**Expected Result**
Validation message should be displayed as we haven't provided Name info

**Actual Result**
Request is successful even though it doesn't contain mandatory info i.e. name. See video - https://www.awesomescreenshot.com/video/291230?key=c83f32687d4e72ff8f615542e4a7a2e8

GraphQL Query:
![image](https://user-images.githubusercontent.com/5212585/86007659-57f61700-ba35-11ea-8f61-b90c675a46d7.png)

CordAPIV3# e9d7d88

**Comment by CarsonF** [comment]
Properties on updates are optional. If they are omitted then The are aimed to not be changing. Like a PATCH request.

**Comment by iPiyushPatel** [comment]
Ok, got it @CarsonF
