### ISSUE TITLE
[Bug] querying a language engagement for field modifiedAt errors

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#630]
**Describe the bug**
When querying for a language engagement with the field `modifiedAt` get the error **Cannot return null for non-nullable field LanguageEngagement.modifiedAt.**.  

**Steps to Reproduce**
Using the test data on cord api.  query an existing language engagement with the field `modifiedAt`.  To find your engagements there's an `engagements` query that returns the list

**Please give the commit short hash of the API and Front End repo if you are able to**.  
Run `git rev-parse --short HEAD` in each repo to retrieve the commit hash.    
API:    e9d7d88
FE:      5d92772

**Expected and Actual Results**
ER: get the modified at date
AR: errors out

**Screenshots**
<img width="1533" alt="Screen Shot 2020-06-29 at 11 13 55 AM" src="https://user-images.githubusercontent.com/43487134/86041503-97ebd880-b9fa-11ea-8d58-95b31d015fdb.png">

**Platform/Environment**  
Clear report on what the bug can be reproduced. Please complete the following information accordingly.

Desktop:

Smartphone:

**Additional context**

**Comment by punamasawa777** [comment]
This Issue is Fixed Now with PR #636 

This is due to modifiedAt is not been created 

<img width="1429" alt="Screenshot 2020-06-30 at 6 53 33 PM" src="https://user-images.githubusercontent.com/64840907/86152889-797efd80-bb1e-11ea-869b-d9f24f1dc321.png">
