### ISSUE TITLE
Project > Get all projects > All data is returned even though I've applied filter properties

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#643]
**Describe the bug**
Project > Get all projects > All data is returned even though I've applied filter properties

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap and execute request.

**Expected Result**
Projects results are returned as per requested filters.

**Actual Result**
All the projects are returned. See video - https://www.awesomescreenshot.com/video/307369?key=556a507a6580145b26d3dcf881fea8fe

I've also tested with other filter parameters. 

GraphQL Query:
![image](https://user-images.githubusercontent.com/5212585/86254498-7eea4f80-bbd3-11ea-8a5a-4651fb0940b6.png)

CordAPIV3# 1caff78

**Comment by michaelmarshall** [comment]
Filter hasn't been added back to `projects` yet. This will need to use the new refactor.

**Comment by punamasawa777** [comment]
@michaelmarshall,  Helper function is required to filter data if filter input is Array or other Datatype
currently filter it is working only for strings type

**Comment by michaelmarshall** [comment]
@punamasawa777 yes, that is currently a limitation. feel free to update the helper function to handle more cases. thanks.

**Comment by punamasawa777** [comment]
sure @michaelmarshall, I will look into it

**Comment by punamasawa777** [comment]
@michaelmarshall , I have worked on List and boolean filter & got an issue Did u fixed ? if fixed please let me know as i am blocked..

**Comment by candleshine** [comment]
Punam is asking @michaelmarshall to pick up the branch that he started to finish this filter

**Comment by michaelmarshall** [comment]
I'm now working this alongside other filter-bug issues.

**Comment by reneepe** [comment]
Additional details in https://github.com/SeedCompany/cord-api-v3/issues/768

**Comment by iPiyushPatel** [comment]
Hi @michaelmarshall @CarsonF @reneepe 

As of now, 
**Working Filters** -by  type
**Not Working Filters** - by name,createdAt, modifiedAt, mine	
**Couldn't check due to static response values** - by sensitivity, status, step

I also have one question. What is 'filter by clusters'?
![image](https://user-images.githubusercontent.com/5212585/90480221-91055a80-e14d-11ea-94ba-bc0c16e3bce4.png)

Please suggest if any.

**Comment by tjgersho** [comment]
When a project works on more than one language it is a 'cluster' project. So it'll have more than one engagement, naturally.

**Comment by CarsonF** [comment]
@tjgersho can you change the description of this field to document this?

**Comment by tjgersho** [comment]
Ok. No problems.
