### ISSUE TITLE
Create Project  >  createProject($input: CreateProjectInput!) > Budget value is returned null

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#644]
**Describe the bug**
Create Project  >  createProject($input: CreateProjectInput!) > Budget value is returned null

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap and execute request.

**Expected Result**
Projects results are returned as per requested filters.

**Actual Result**
All the projects returned as results. See video - https://www.awesomescreenshot.com/video/307503?key=4950e41a74ac801819b1452b4f26ddfd

**_P.S.Previously It's working fine and value object is returned with details._**

GraphQL Query:
![image](https://user-images.githubusercontent.com/5212585/86256950-8b23dc00-bbd6-11ea-89f8-82e9f3e2f3f5.png)

CordAPIV3# 1caff78

**Comment by punamasawa777** [comment]
This is Fixed with PR #659 
Here is check

<img width="1134" alt="Screenshot 2020-07-02 at 8 04 21 PM" src="https://user-images.githubusercontent.com/64840907/86376625-e7553180-bca4-11ea-950d-fc66262b89de.png">
