### ISSUE TITLE
Get All Projects > query projects($input: ProjectListInput!) > Getting "Could not find project member" error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#654]
**Describe the bug**
Get All Projects > query projects($input: ProjectListInput!) > Getting "Could not find project member" error

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Projects results are returned.

**Actual Result**
All the projects are not returned as results. See video - https://www.awesomescreenshot.com/video/312192?key=f5f333e46f4f3bcf48bee0f866db83cf

**Please note - it was working till yesterday**

GraphQL Query:
![image](https://user-images.githubusercontent.com/5212585/86322171-20b38000-bc58-11ea-9334-52e74fcf1187.png)
[projects.txt](https://github.com/SeedCompany/cord-api-v3/files/4862297/projects.txt)

CordAPIV3# 911cfa6

**Comment by ibohalsinghkoijam** [comment]
<img width="1313" alt="1 -ticket-654" src="https://user-images.githubusercontent.com/24403111/86355568-828bde00-bc88-11ea-91b5-3961159845c2.png">

**Comment by ibohalsinghkoijam** [comment]
showing remaining query :

<img width="1197" alt="2-ticket-654" src="https://user-images.githubusercontent.com/24403111/86355686-b109b900-bc88-11ea-954a-05c5b33662e0.png">

**Comment by ibohalsinghkoijam** [comment]
@iPiyushPatel , we are unable to see complete query in both postman (video recording) and playground (screenshot). Can you please upload remaining query in left side of playground that can be helpful to replicate or reproduce the scenario ?

**Comment by iPiyushPatel** [comment]
Hi @ibohalsinghkoijam 
I've already attached projects.txt file as well with all details :) , it's easy to miss that actually as per GITHUB UI. Can you check?

**Comment by ibohalsinghkoijam** [comment]
I found it. Thank you @iPiyushPatel

**Comment by iPiyushPatel** [comment]
Hi @ibohalsinghkoijam 
Here are details for creating project:

Input:
{
  "input": {
    "project": {
      "name": "{{projectName}}",
      "type": "{{projectType}}",
      "locationId": "{{locationId}}",
      "mouStart": "{{mouStart}}",
      "mouEnd": "{{mouEnd}}",
      "estimatedSubmission": "{{estimatedSubmission}}"
    }
  }
}


Query:
mutation createProject($input: CreateProjectInput!) {
  createProject(input: $input) {
    project {
      id
      createdAt
      type
      sensitivity
      name {
        value
        canRead
        canEdit
      }
      deptId {
        value
        canRead
        canEdit
      }
      step {
        value
        canRead
        canEdit
      }
      status
      location {
        value {
          id
          name {
            value
            canRead
            canEdit
          }
          region {
            value {
              id
              name {
                value
                canRead
                canEdit
              }
              zone {
                value {
                  id
                  name {
                    value
                    canRead
                    canEdit
                  }
                  director {
                    value {
                      id
                      email {
                        value
                        canRead
                        canEdit
                      }
                      realFirstName {
                        value
                        canRead
                        canEdit
                      }
                      realLastName {
                        value
                        canRead
                        canEdit
                      }
                      displayFirstName {
                        value
                        canRead
                        canEdit
                      }
                      displayLastName {
                        value
                        canRead
                        canEdit
                      }
                      phone {
                        value
                        canRead
                        canEdit
                      }
                      timezone {
                        canRead
                        canEdit
                        value {
                          name
                          lat
                          long
                          countries {
                            code
                            name
                            zones {
                              name
                              lat
                              long
                              countries {
                                code
                              }
                            }
                          }
                        }
                      }
                      bio {
                        value
                        canRead
                        canEdit
                      }
                      status {
                        value
                        canRead
                        canEdit
                      }
                      fullName
                      firstName
                      avatarLetters
                      unavailabilities {
                        items {
                          id
                          description {
                            value
                            canRead
                            canEdit
                          }
                          start
                          end
                          createdAt
                        }
                        total
                        hasMore
                        canCreate
                        canRead
                      }
                      organizations {
                        items {
                          id
                          name {
                            value
                            canRead
                            canEdit
                          }
                          avatarLetters
                          createdAt
                        }
                        total
                        hasMore
                        canCreate
                        canRead
                      }
                      education {
                        items {
                          id
                          degree {
                            value
                            canRead
                            canEdit
                          }
                          major {
                            value
                            canRead
                            canEdit
                          }
                          institution {
                            value
                            canRead
                            canEdit
                          }
                          createdAt
                        }
                        total
                        hasMore
                        canCreate
                        canRead
                      }
                    }
                    canRead
                    canEdit
                  }
                  createdAt
                }
                canRead
                canEdit
              }
              director {
                value {
                  id
                  email {
                    value
                    canRead
                    canEdit
                  }
                  realFirstName {
                    value
                    canRead
                    canEdit
                  }
                  realLastName {
                    value
                    canRead
                    canEdit
                  }
                  displayFirstName {
                    value
                    canRead
                    canEdit
                  }
                  displayLastName {
                    value
                    canRead
                    canEdit
                  }
                  phone {
                    value
                    canRead
                    canEdit
                  }
                  timezone {
                    value {
                      name
                      lat
                      long
                      countries {
                        code
                        name
                        zones {
                          name
                          lat
                          long
                          countries {
                            code
                          }
                        }
                      }
                    }
                    canRead
                    canEdit
                  }
                  bio {
                    value
                    canRead
                    canEdit
                  }
                  status {
                    value
                    canRead
                    canEdit
                  }
                  fullName
                  firstName
                  avatarLetters
                  unavailabilities {
                    items {
                      id
                      description {
                        value
                        canRead
                        canEdit
                      }
                      start
                      end
                    }
                    total
                    hasMore
                    canCreate
                    canRead
                  }
                  organizations {
                    items {
                      id
                      name {
                        value
                        canRead
                        canEdit
                      }
                      avatarLetters
                      createdAt
                    }
                    total
                    hasMore
                    canCreate
                    canRead
                  }
                  education {
                    items {
                      id
                      degree {
                        value
                        canRead
                        canEdit
                      }
                      major {
                        value
                        canRead
                        canEdit
                      }
                      institution {
                        value
                        canRead
                        canEdit
                      }
                      createdAt
                    }
                    total
                    hasMore
                    canCreate
                    canRead
                  }
                  createdAt
                }
                canRead
                canEdit
              }
              createdAt
            }
            canRead
            canEdit
          }
          createdAt
        }
        canRead
        canEdit
      }
      mouStart {
        value
        canRead
        canEdit
      }
      mouEnd {
        value
        canRead
        canEdit
      }
      estimatedSubmission {
        value
        canRead
        canEdit
      }
      modifiedAt
      avatarLetters
      team {
        total
        hasMore
        canCreate
        canRead
        items {
          id
          createdAt
          #modifiedAt
          user {
            value {
              id
              createdAt
              email {
                value
                canRead
                canEdit
              }
              realFirstName {
                value
                canRead
                canEdit
              }
              realLastName {
                value
                canRead
                canEdit
              }
              displayFirstName {
                value
                canRead
                canEdit
              }
              displayLastName {
                value
                canRead
                canEdit
              }
              phone {
                value
                canRead
                canEdit
              }
              timezone {
                value {
                  name
                  lat
                  long
                  countries {
                    code
                    name
                    zones {
                      name
                      lat
                      long
                      countries {
                        code
                      }
                    }
                  }
                }
                canRead
                canEdit
              }
              bio {
                value
                canRead
                canEdit
              }
              status {
                value
                canRead
                canEdit
              }
              fullName
              firstName
              avatarLetters
              unavailabilities {
                total
                hasMore
                canCreate
                canRead
                items {
                  id
                  createdAt
                  start
                  end
                  description {
                    value
                    canRead
                    canEdit
                  }
                }
              }
              organizations {
                items {
                  id
                  name {
                    value
                    canRead
                    canEdit
                  }
                  avatarLetters
                  createdAt
                }
                total
                hasMore
                canCreate
                canRead
              }
              education {
                canRead
                hasMore
                canCreate
                total
                items {
                  id
                  createdAt
                  degree {
                    value
                    canRead
                    canEdit
                  }
                  major {
                    value
                    canRead
                    canEdit
                  }
                  institution {
                    value
                    canRead
                    canEdit
                  }
                }
              }
            }
            canRead
            canEdit
          }
          roles {
            value
            canRead
            canEdit
          }
        }
      }
      engagements {
        total
        hasMore
        canCreate
        canRead
        items {
          id
          createdAt
          status
          ceremony {
            value {
              id
              createdAt
              type
              planned {
                value
                canRead
                canEdit
              }
              estimatedDate {
                value
                canRead
                canEdit
              }
              actualDate {
                value
                canRead
                canEdit
              }
            }
            canRead
            canEdit
          }
          completeDate {
            value
            canRead
            canEdit
          }
          disbursementCompleteDate {
            value
            canRead
            canEdit
          }
          communicationsCompleteDate {
            value
            canRead
            canEdit
          }
          startDate {
            value
            canRead
            canEdit
          }
          endDate {
            value
            canRead
            canEdit
          }
          initialEndDate {
            value
            canRead
            canEdit
          }
          lastSuspendedAt {
            value
            canRead
            canEdit
          }
          lastReactivatedAt {
            value
            canRead
            canEdit
          }
          statusModifiedAt {
            value
            canRead
            canEdit
          }
          modifiedAt
        }
      }
      budget {
        value {
          id
          createdAt
          status
          records {
            id
            createdAt
            fiscalYear {
              value
              canRead
              canEdit
            }
            amount {
              value
              canRead
              canEdit
            }
            organization {
              value {
                id
                createdAt
                name {
                  value
                  canRead
                  canEdit
                }
                avatarLetters
              }
              canRead
              canEdit
            }
          }
          total
        }
        canRead
        canEdit
      }
      partnerships {
        canRead
        hasMore
        canCreate
        total
        items {
          id
          createdAt
          agreementStatus {
            value
            canRead
            canEdit
          }
          mouStatus {
            value
            canRead
            canEdit
          }
          mouStart {
            value
            canRead
            canEdit
          }
          mouEnd {
            value
            canRead
            canEdit
          }
          organization {
            id
            name {
              value
              canRead
              canEdit
            }
            avatarLetters
            createdAt
          }
          types {
            value
            canRead
            canEdit
          }
          mou {
            value {
              id
              createdAt
              type
              category
              mimeType
              name
              size
              modifiedAt
              downloadUrl
              createdBy {
                id
                createdAt
                email {
                  value
                  canRead
                  canEdit
                }
                realFirstName {
                  value
                  canRead
                  canEdit
                }
                realLastName {
                  value
                  canRead
                  canEdit
                }
                displayFirstName {
                  value
                  canRead
                  canEdit
                }
                displayLastName {
                  value
                  canRead
                  canEdit
                }
                phone {
                  value
                  canRead
                  canEdit
                }
                timezone {
                  value {
                    name
                    lat
                    long
                    countries {
                      code
                      name
                      zones {
                        name
                        lat
                        long
                        countries {
                          code
                        }
                      }
                    }
                  }
                  canRead
                  canEdit
                }
                bio {
                  value
                  canRead
                  canEdit
                }
                status {
                  value
                  canRead
                  canEdit
                }
                fullName
                firstName
                avatarLetters
                unavailabilities {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    description {
                      value
                      canRead
                      canEdit
                    }
                    start
                    end
                  }
                }
                organizations {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    name {
                      value
                      canRead
                      canEdit
                    }
                    avatarLetters
                  }
                }
                education {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    degree {
                      value
                      canRead
                      canEdit
                    }
                    major {
                      value
                      canRead
                      canEdit
                    }
                    institution {
                      value
                      canRead
                      canEdit
                    }
                  }
                }
              }
              modifiedBy {
                id
                createdAt
                email {
                  value
                  canRead
                  canEdit
                }
                realFirstName {
                  value
                  canRead
                  canEdit
                }
                realLastName {
                  value
                  canRead
                  canEdit
                }
                displayFirstName {
                  value
                  canRead
                  canEdit
                }
                displayLastName {
                  value
                  canRead
                  canEdit
                }
                phone {
                  value
                  canRead
                  canEdit
                }
                timezone {
                  value {
                    name
                    lat
                    long
                    countries {
                      code
                      name
                      zones {
                        name
                        lat
                        long
                        countries {
                          code
                        }
                      }
                    }
                  }
                  canRead
                  canEdit
                }
                bio {
                  value
                  canRead
                  canEdit
                }
                status {
                  value
                  canRead
                  canEdit
                }
                fullName
                firstName
                avatarLetters
                unavailabilities {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    description {
                      value
                      canRead
                      canEdit
                    }
                    start
                    end
                  }
                }
                organizations {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    name {
                      value
                      canRead
                      canEdit
                    }
                    avatarLetters
                  }
                }
                education {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    degree {
                      value
                      canRead
                      canEdit
                    }
                    major {
                      value
                      canRead
                      canEdit
                    }
                    institution {
                      value
                      canRead
                      canEdit
                    }
                  }
                }
              }
              children {
                items {
                  id
                  createdAt
                  type
                  category
                  name
                  createdBy {
                    id
                    createdAt
                    email {
                      value
                      canRead
                      canEdit
                    }
                    realFirstName {
                      value
                      canRead
                      canEdit
                    }
                    realLastName {
                      value
                      canRead
                      canEdit
                    }
                    displayFirstName {
                      value
                      canRead
                      canEdit
                    }
                    displayLastName {
                      value
                      canRead
                      canEdit
                    }
                    phone {
                      value
                      canRead
                      canEdit
                    }
                    timezone {
                      value {
                        name
                        lat
                        long
                        countries {
                          code
                          name
                          zones {
                            name
                            lat
                            long
                            countries {
                              code
                            }
                          }
                        }
                      }
                      canRead
                      canEdit
                    }
                    bio {
                      value
                      canRead
                      canEdit
                    }
                    status {
                      value
                      canRead
                      canEdit
                    }
                    fullName
                    firstName
                    avatarLetters
                    unavailabilities {
                      canRead
                      hasMore
                      canCreate
                      total
                      items {
                        id
                        createdAt
                        description {
                          value
                          canRead
                          canEdit
                        }
                        start
                        end
                      }
                    }
                    organizations {
                      canRead
                      hasMore
                      canCreate
                      total
                      items {
                        id
                        createdAt
                        name {
                          value
                          canRead
                          canEdit
                        }
                        avatarLetters
                      }
                    }
                    education {
                      canRead
                      hasMore
                      canCreate
                      total
                      items {
                        id
                        createdAt
                        degree {
                          value
                          canRead
                          canEdit
                        }
                        major {
                          value
                          canRead
                          canEdit
                        }
                        institution {
                          value
                          canRead
                          canEdit
                        }
                      }
                    }
                  }
                  parents {
                    id
                    createdAt
                    type
                    category
                    name
                    parents {
                      id
                      type
                    }
                    createdBy {
                      id
                      createdAt
                      email {
                        value
                        canRead
                        canEdit
                      }
                      realFirstName {
                        value
                        canRead
                        canEdit
                      }
                      realLastName {
                        value
                        canRead
                        canEdit
                      }
                      displayFirstName {
                        value
                        canRead
                        canEdit
                      }
                      displayLastName {
                        value
                        canRead
                        canEdit
                      }
                      phone {
                        value
                        canRead
                        canEdit
                      }
                      timezone {
                        value {
                          name
                          lat
                          long
                          countries {
                            code
                            name
                            zones {
                              name
                              lat
                              long
                              countries {
                                code
                              }
                            }
                          }
                        }
                        canRead
                        canEdit
                      }
                      bio {
                        value
                        canRead
                        canEdit
                      }
                      status {
                        value
                        canRead
                        canEdit
                      }
                      fullName
                      firstName
                      avatarLetters
                      unavailabilities {
                        canRead
                        hasMore
                        canCreate
                        total
                        items {
                          id
                          createdAt
                          description {
                            value
                            canRead
                            canEdit
                          }
                          start
                          end
                        }
                      }
                      organizations {
                        canRead
                        hasMore
                        canCreate
                        total
                        items {
                          id
                          createdAt
                          name {
                            value
                            canRead
                            canEdit
                          }
                          avatarLetters
                        }
                      }
                      education {
                        canRead
                        hasMore
                        canCreate
                        total
                        items {
                          id
                          createdAt
                          degree {
                            value
                            canRead
                            canEdit
                          }
                          major {
                            value
                            canRead
                            canEdit
                          }
                          institution {
                            value
                            canRead
                            canEdit
                          }
                        }
                      }
                    }
                  }
                }
                total
                hasMore
              }
              parents {
                id
                createdAt
                type
                category
                name
                parents {
                  id
                  type
                  # also contains other fields as parent 'Parents'
                }
                createdBy {
                  id
                  createdAt
                  email {
                    value
                    canRead
                    canEdit
                  }
                  realFirstName {
                    value
                    canRead
                    canEdit
                  }
                  realLastName {
                    value
                    canRead
                    canEdit
                  }
                  displayFirstName {
                    value
                    canRead
                    canEdit
                  }
                  displayLastName {
                    value
                    canRead
                    canEdit
                  }
                  phone {
                    value
                    canRead
                    canEdit
                  }
                  timezone {
                    value {
                      name
                      lat
                      long
                      countries {
                        code
                        name
                        zones {
                          name
                          lat
                          long
                          countries {
                            code
                          }
                        }
                      }
                    }
                    canRead
                    canEdit
                  }
                  bio {
                    value
                    canRead
                    canEdit
                  }
                  status {
                    value
                    canRead
                    canEdit
                  }
                  fullName
                  firstName
                  avatarLetters
                  unavailabilities {
                    canRead
                    hasMore
                    canCreate
                    total
                    items {
                      id
                      createdAt
                      description {
                        value
                        canRead
                        canEdit
                      }
                      start
                      end
                    }
                  }
                  organizations {
                    canRead
                    hasMore
                    canCreate
                    total
                    items {
                      id
                      createdAt
                      name {
                        value
                        canRead
                        canEdit
                      }
                      avatarLetters
                    }
                  }
                  education {
                    canRead
                    hasMore
                    canCreate
                    total
                    items {
                      id
                      createdAt
                      degree {
                        value
                        canRead
                        canEdit
                      }
                      major {
                        value
                        canRead
                        canEdit
                      }
                      institution {
                        value
                        canRead
                        canEdit
                      }
                    }
                  }
                }
              }
            }
            canRead
            canEdit
          }
          agreement {
            value {
              id
              createdAt
              type
              category
              name
              parents {
                id
                createdAt
                type
                category
                name
                createdBy {
                  id
                  createdAt
                  email {
                    value
                    canRead
                    canEdit
                  }
                  realFirstName {
                    value
                    canRead
                    canEdit
                  }
                  realLastName {
                    value
                    canRead
                    canEdit
                  }
                  displayFirstName {
                    value
                    canRead
                    canEdit
                  }
                  displayLastName {
                    value
                    canRead
                    canEdit
                  }
                  phone {
                    value
                    canRead
                    canEdit
                  }
                  timezone {
                    value {
                      name
                      lat
                      long
                      countries {
                        code
                        name
                        zones {
                          name
                          lat
                          long
                          countries {
                            code
                          }
                        }
                      }
                    }
                    canRead
                    canEdit
                  }
                  bio {
                    value
                    canRead
                    canEdit
                  }
                  status {
                    value
                    canRead
                    canEdit
                  }
                  fullName
                  firstName
                  avatarLetters
                  unavailabilities {
                    canRead
                    hasMore
                    canCreate
                    total
                    items {
                      id
                      createdAt
                      description {
                        value
                        canRead
                        canEdit
                      }
                      start
                      end
                    }
                  }
                  organizations {
                    canRead
                    hasMore
                    canCreate
                    total
                    items {
                      id
                      createdAt
                      name {
                        value
                        canRead
                        canEdit
                      }
                      avatarLetters
                    }
                  }
                  education {
                    canRead
                    hasMore
                    canCreate
                    total
                    items {
                      id
                      createdAt
                      degree {
                        value
                        canRead
                        canEdit
                      }
                      major {
                        value
                        canRead
                        canEdit
                      }
                      institution {
                        value
                        canRead
                        canEdit
                      }
                    }
                  }
                }
                parents {
                  id
                  type
                  # also contains other fields as parent 'Parents'
                }
              }
              createdBy {
                id
                createdAt
                email {
                  value
                  canRead
                  canEdit
                }
                realFirstName {
                  value
                  canRead
                  canEdit
                }
                realLastName {
                  value
                  canRead
                  canEdit
                }
                displayFirstName {
                  value
                  canRead
                  canEdit
                }
                displayLastName {
                  value
                  canRead
                  canEdit
                }
                phone {
                  value
                  canRead
                  canEdit
                }
                timezone {
                  value {
                    name
                    lat
                    long
                    countries {
                      code
                      name
                      zones {
                        name
                        lat
                        long
                        countries {
                          code
                        }
                      }
                    }
                  }
                  canRead
                  canEdit
                }
                bio {
                  value
                  canRead
                  canEdit
                }
                status {
                  value
                  canRead
                  canEdit
                }
                fullName
                firstName
                avatarLetters
                unavailabilities {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    description {
                      value
                      canRead
                      canEdit
                    }
                    start
                    end
                  }
                }
                organizations {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    name {
                      value
                      canRead
                      canEdit
                    }
                    avatarLetters
                  }
                }
                education {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    degree {
                      value
                      canRead
                      canEdit
                    }
                    major {
                      value
                      canRead
                      canEdit
                    }
                    institution {
                      value
                      canRead
                      canEdit
                    }
                  }
                }
              }
              mimeType
              size
              modifiedAt
              modifiedBy {
                id
                createdAt
                email {
                  value
                  canRead
                  canEdit
                }
                realFirstName {
                  value
                  canRead
                  canEdit
                }
                realLastName {
                  value
                  canRead
                  canEdit
                }
                displayFirstName {
                  value
                  canRead
                  canEdit
                }
                displayLastName {
                  value
                  canRead
                  canEdit
                }
                phone {
                  value
                  canRead
                  canEdit
                }
                timezone {
                  value {
                    name
                    lat
                    long
                    countries {
                      code
                      name
                      zones {
                        name
                        lat
                        long
                        countries {
                          code
                        }
                      }
                    }
                  }
                  canRead
                  canEdit
                }
                bio {
                  value
                  canRead
                  canEdit
                }
                status {
                  value
                  canRead
                  canEdit
                }
                fullName
                firstName
                avatarLetters
                unavailabilities {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    description {
                      value
                      canRead
                      canEdit
                    }
                    start
                    end
                  }
                }
                organizations {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    name {
                      value
                      canRead
                      canEdit
                    }
                    avatarLetters
                  }
                }
                education {
                  canRead
                  hasMore
                  canCreate
                  total
                  items {
                    id
                    createdAt
                    degree {
                      value
                      canRead
                      canEdit
                    }
                    major {
                      value
                      canRead
                      canEdit
                    }
                    institution {
                      value
                      canRead
                      canEdit
                    }
                  }
                }
              }
              children {
                total
                hasMore
                items {
                  id
                  createdAt
                  type
                  category
                  name
                  createdBy {
                    id
                    createdAt
                    email {
                      value
                      canRead
                      canEdit
                    }
                    realFirstName {
                      value
                      canRead
                      canEdit
                    }
                    realLastName {
                      value
                      canRead
                      canEdit
                    }
                    displayFirstName {
                      value
                      canRead
                      canEdit
                    }
                    displayLastName {
                      value
                      canRead
                      canEdit
                    }
                    phone {
                      value
                      canRead
                      canEdit
                    }
                    timezone {
                      value {
                        name
                        lat
                        long
                        countries {
                          code
                          name
                          zones {
                            name
                            lat
                            long
                            countries {
                              code
                            }
                          }
                        }
                      }
                      canRead
                      canEdit
                    }
                    bio {
                      value
                      canRead
                      canEdit
                    }
                    status {
                      value
                      canRead
                      canEdit
                    }
                    fullName
                    firstName
                    avatarLetters
                    unavailabilities {
                      canRead
                      hasMore
                      canCreate
                      total
                      items {
                        id
                        createdAt
                        description {
                          value
                          canRead
                          canEdit
                        }
                        start
                        end
                      }
                    }
                    organizations {
                      canRead
                      hasMore
                      canCreate
                      total
                      items {
                        id
                        createdAt
                        name {
                          value
                          canRead
                          canEdit
                        }
                        avatarLetters
                      }
                    }
                    education {
                      canRead
                      hasMore
                      canCreate
                      total
                      items {
                        id
                        createdAt
                        degree {
                          value
                          canRead
                          canEdit
                        }
                        major {
                          value
                          canRead
                          canEdit
                        }
                        institution {
                          value
                          canRead
                          canEdit
                        }
                      }
                    }
                  }
                  parents {
                    id
                    createdAt
                    type
                    category
                    name
                    createdBy {
                      id
                      createdAt
                      email {
                        value
                        canRead
                        canEdit
                      }
                      realFirstName {
                        value
                        canRead
                        canEdit
                      }
                      realLastName {
                        value
                        canRead
                        canEdit
                      }
                      displayFirstName {
                        value
                        canRead
                        canEdit
                      }
                      displayLastName {
                        value
                        canRead
                        canEdit
                      }
                      phone {
                        value
                        canRead
                        canEdit
                      }
                      timezone {
                        value {
                          name
                          lat
                          long
                          countries {
                            code
                            name
                            zones {
                              name
                              lat
                              long
                              countries {
                                code
                              }
                            }
                          }
                        }
                        canRead
                        canEdit
                      }
                      bio {
                        value
                        canRead
                        canEdit
                      }
                      status {
                        value
                        canRead
                        canEdit
                      }
                      fullName
                      firstName
                      avatarLetters
                      unavailabilities {
                        canRead
                        hasMore
                        canCreate
                        total
                        items {
                          id
                          createdAt
                          description {
                            value
                            canRead
                            canEdit
                          }
                          start
                          end
                        }
                      }
                      organizations {
                        canRead
                        hasMore
                        canCreate
                        total
                        items {
                          id
                          createdAt
                          name {
                            value
                            canRead
                            canEdit
                          }
                          avatarLetters
                        }
                      }
                      education {
                        canRead
                        hasMore
                        canCreate
                        total
                        items {
                          id
                          createdAt
                          degree {
                            value
                            canRead
                            canEdit
                          }
                          major {
                            value
                            canRead
                            canEdit
                          }
                          institution {
                            value
                            canRead
                            canEdit
                          }
                        }
                      }
                    }
                    parents {
                      id
                      type
                      # also contains other fields as parent 'Parents'
                    }
                  }
                }
              }

              downloadUrl
            }
            canRead
            canEdit
          }
        }
      }
      rootDirectory {
        id
        createdAt
        type
        category
        name
        parents {
          id
          createdAt
          type
          category
          name
          parents {
            id
            name
            type
            # also contains other fields as parent 'parents'
          }
          createdBy {
            id
            createdAt
            email {
              value
              canRead
              canEdit
            }
            realFirstName {
              value
              canRead
              canEdit
            }
            realLastName {
              value
              canRead
              canEdit
            }
            displayFirstName {
              value
              canRead
              canEdit
            }
            displayLastName {
              value
              canRead
              canEdit
            }
            phone {
              value
              canRead
              canEdit
            }
            timezone {
              value {
                name
                lat
                long
                countries {
                  code
                  name
                  zones {
                    name
                    lat
                    long
                    countries {
                      code
                    }
                  }
                }
              }
              canRead
              canEdit
            }
            bio {
              value
              canRead
              canEdit
            }
            status {
              value
              canRead
              canEdit
            }
            fullName
            firstName
            avatarLetters
            unavailabilities {
              canRead
              hasMore
              canCreate
              total
              items {
                id
                createdAt
                description {
                  value
                  canRead
                  canEdit
                }
                start
                end
              }
            }
            organizations {
              canRead
              hasMore
              canCreate
              total
              items {
                id
                createdAt
                name {
                  value
                  canRead
                  canEdit
                }
                avatarLetters
              }
            }
            education {
              canRead
              hasMore
              canCreate
              total
              items {
                id
                createdAt
                degree {
                  value
                  canRead
                  canEdit
                }
                major {
                  value
                  canRead
                  canEdit
                }
                institution {
                  value
                  canRead
                  canEdit
                }
              }
            }
          }
        }
        createdBy {
          id
          createdAt
          email {
            value
            canRead
            canEdit
          }
          realFirstName {
            value
            canRead
            canEdit
          }
          realLastName {
            value
            canRead
            canEdit
          }
          displayFirstName {
            value
            canRead
            canEdit
          }
          displayLastName {
            value
            canRead
            canEdit
          }
          phone {
            value
            canRead
            canEdit
          }
          timezone {
            value {
              name
              lat
              long
              countries {
                code
                name
                zones {
                  name
                  lat
                  long
                  countries {
                    code
                  }
                }
              }
            }
            canRead
            canEdit
          }
          bio {
            value
            canRead
            canEdit
          }
          status {
            value
            canRead
            canEdit
          }
          fullName
          firstName
          avatarLetters
          unavailabilities {
            canRead
            hasMore
            canCreate
            total
            items {
              id
              createdAt
              description {
                value
                canRead
                canEdit
              }
              start
              end
            }
          }
          organizations {
            canRead
            hasMore
            canCreate
            total
            items {
              id
              createdAt
              name {
                value
                canRead
                canEdit
              }
              avatarLetters
            }
          }
          education {
            canRead
            hasMore
            canCreate
            total
            items {
              id
              createdAt
              degree {
                value
                canRead
                canEdit
              }
              major {
                value
                canRead
                canEdit
              }
              institution {
                value
                canRead
                canEdit
              }
            }
          }
        }
        children {
          total
          hasMore
          items {
            id
            createdAt
            type
            category
            name
            createdBy {
              id
              createdAt
              email {
                value
                canRead
                canEdit
              }
              realFirstName {
                value
                canRead
                canEdit
              }
              realLastName {
                value
                canRead
                canEdit
              }
              displayFirstName {
                value
                canRead
                canEdit
              }
              displayLastName {
                value
                canRead
                canEdit
              }
              phone {
                value
                canRead
                canEdit
              }
              timezone {
                value {
                  name
                  lat
                  long
                  countries {
                    code
                    name
                    zones {
                      name
                      lat
                      long
                      countries {
                        code
                      }
                    }
                  }
                }
                canRead
                canEdit
              }
              bio {
                value
                canRead
                canEdit
              }
              status {
                value
                canRead
                canEdit
              }
              fullName
              firstName
              avatarLetters
              unavailabilities {
                canRead
                hasMore
                canCreate
                total
                items {
                  id
                  createdAt
                  description {
                    value
                    canRead
                    canEdit
                  }
                  start
                  end
                }
              }
              organizations {
                canRead
                hasMore
                canCreate
                total
                items {
                  id
                  createdAt
                  name {
                    value
                    canRead
                    canEdit
                  }
                  avatarLetters
                }
              }
              education {
                canRead
                hasMore
                canCreate
                total
                items {
                  id
                  createdAt
                  degree {
                    value
                    canRead
                    canEdit
                  }
                  major {
                    value
                    canRead
                    canEdit
                  }
                  institution {
                    value
                    canRead
                    canEdit
                  }
                }
              }
            }
            parents {
              id
              type
            }
          }
        }
      }
    }
  }
}
----

Do let me know if you need anything else.
