### ISSUE TITLE
Get All Users> User status value is returned "null" whose status was "Active" while registration

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#655]
**Describe the bug**
Get All Users> User status value is returned "null" whose status was "Active" while registration

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
User status should be return exactly same value as user gave while registering.

**Actual Result**
User status value is returned "null". See video - https://www.awesomescreenshot.com/video/314574?key=6f0165a64adb99433f2d18337b2a7d06

GraphQL Query: (Register)
![image](https://user-images.githubusercontent.com/5212585/86361111-fa5e0680-bc90-11ea-9940-227cd39b3aa3.png)

GraphQL Query: (Users)
![image](https://user-images.githubusercontent.com/5212585/86361478-8c660f00-bc91-11ea-848c-627b9f2c31d2.png)

[Users.txt](https://github.com/SeedCompany/cord-api-v3/files/4864451/Users.txt)

CordAPIV3# 911cfa6

**Comment by zkhin** [comment]
Hey, @iPiyushPatel  I tried on my side and it returns correct `status` value.
![create-user](https://user-images.githubusercontent.com/4212008/86402036-87837880-bcee-11ea-8c1f-24db7c73b028.png)
![user-list](https://user-images.githubusercontent.com/4212008/86402045-88b4a580-bcee-11ea-808c-353e0f066b9e.png)
