### ISSUE TITLE
Get All Users> User timezone value is returned "null" whose timezone was provideed while registration

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#665]
**Describe the bug**
Register User > User timezone value is returned "null" in registration response whose timezone was provided in input.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
User timezone value should be return exactly same value as user gave while registering.

**Actual Result**
User timezone value is returned "null". See video - https://www.awesomescreenshot.com/video/322358?key=112e6b5c51a92ac4dbb49537df6710a7

GraphQL Query: (Register)
![image](https://user-images.githubusercontent.com/5212585/86464382-08715d00-bd4d-11ea-8a52-9b1ca04f42e0.png)

[register.txt](https://github.com/SeedCompany/cord-api-v3/files/4869377/register.txt)

CordAPIV3# 6f08d00

**Comment by CarsonF** [comment]
The value has to be a valid IANA timezone now. Since what you passed in is not valid it wasn't matched with a timezone object. 

What really needs to happen is validation on input that the string is a valid timezone. 
That could be done with a decorator on the field.
It's easy to valid it:
```ts
new IANAZone(string).valid
```

**Comment by iPiyushPatel** [comment]
Ok, got it @CarsonF . I will update test to have valid IANA timezone now. Ok, so for putting validation , should I create new bug or this is ok ? Please suggest if any.

**Comment by CarsonF** [comment]
I think this one is fine.

@zkhin you seem to be quick on the decorators, want to tackle this?

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
Can you please provide example for valid IANA timezone json values ? I tried but didn't succeed :( 

Thanks,

**Comment by CarsonF** [comment]
You can list them from the API with `timezones` query

**Comment by iPiyushPatel** [comment]
Ok, got it thanks @CarsonF
