### ISSUE TITLE
Cannot read my own User.phone

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#668]
![Screen Shot 2020-07-03 at 1 11 20 PM](https://user-images.githubusercontent.com/932566/86490935-c0434200-bd2e-11ea-94e1-21f42eb6cea3.png)

**Comment by ibohalsinghkoijam** [comment]
This error can be reproduced when registered user without phone number.

**Comment by candleshine** [comment]
I think the expected behaviour is that `value` needs to be added and should be `null`.  `canRead` can remain false.  `canEdit` can remain `true`.  

`canEdit` true means this person can update the missing phone number.

**Comment by CarsonF** [comment]
`canRead` should be true for your own user. It also doesn't really make sense that `canEdit` can be true while `canRead` is false.

**Comment by ibohalsinghkoijam** [comment]
<img width="1142" alt="686-fixed-with-679" src="https://user-images.githubusercontent.com/24403111/87150426-a32ee600-c2cf-11ea-85da-9c167c45f8df.png">

**Comment by ibohalsinghkoijam** [comment]
This ticket-668 is fixed with 679
