### ISSUE TITLE
Get All Partnerships > query partnerships($input: PartnershipListInput!) > Getting “Cannot return null for non-nullable fields organization, mou and agreement” error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#672]
**Describe the bug**
Get All Partnerships > query query partnerships($input: PartnershipListInput!) > Getting “Cannot return null for non-nullable fields organization, mou and agreement” error.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Partnership results are returned.

**Actual Result**
All the partnership are not returned as results. See video - https://www.awesomescreenshot.com/video/339180?key=42082e8121ac42ff2f82ae01bda8f788

GraphQL Query(organization field):
![image](https://user-images.githubusercontent.com/5212585/86596325-a5cfc980-bfb7-11ea-9388-1a4e8b3d0cef.png)

GraphQL Query(mou field):
![image](https://user-images.githubusercontent.com/5212585/86596567-0a8b2400-bfb8-11ea-9195-04d29553c546.png)

GraphQL Query(agreement field):
![image](https://user-images.githubusercontent.com/5212585/86596696-4a520b80-bfb8-11ea-8982-b8d1f6b215db.png)

**Query and Input File**
[partnerships.txt](https://github.com/SeedCompany/cord-api-v3/files/4879150/partnerships.txt)

CordAPIV3# 07d3bd7

**Comment by zkhin** [comment]
@michaelmarshall This issue can be closed.
