### ISSUE TITLE
Project permission bugs

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#674]
Created a project, and requested details.
- [ ] name.canRead/Edit is false but the value is still returned
  - [ ] `canRead/Edit` should be true since I created the project & while it's status is in development
  - [ ] `value` should not be returned if `canRead` is false
- [ ] `location`, `mouStart`, `mouEnd`'s `canRead/Edit` should be true since I created the project & while it's status is in development
- [ ] `engagements.canCreate` should be true since I created the project & while it's status is in development

API: https://github.com/SeedCompany/cord-api-v3/commit/8b7caae7f7c03cca1ef71790cd57ead6b9116d15

![Screen Shot 2020-07-06 at 1 07 36 PM](https://user-images.githubusercontent.com/932566/86624904-c719c100-bf89-11ea-8c7b-c97c7744362f.png)

**Comment by zkhin** [comment]
@CarsonF Should I have to return `canRead: true, canEdit: true` even if those (`name`, `location`, `mouStart`, `mouEnd`) fields' values are null since I created the project & while it's status is in development

**Comment by CarsonF** [comment]
Yeah. Talking with @michaelmarshall too he says that we should just always create those fields with a default value of null if omitted from input during the create mutation. That way they are available to query later.

**Comment by zkhin** [comment]
I think if the `value` is null, it doesn't create `Property` node so the permission fields are always `false`
If I try to create Property node with `null` value, it gives an error...

**Comment by CarsonF** [comment]
> I think if the `value` is null, it doesn't create `Property` node so the permission fields are always `false`

Yeah that's my understanding too.

> If I try to create Property node with `null` value, it gives an error...

What error? from cypher? or our code?

**Comment by zkhin** [comment]
Seems it's from cypher.
`Neo.ClientError.Schema.ConstraintValidationFailed`

**Comment by CarsonF** [comment]
That's constraints we've placed. You might need to clear them as they've changed recently (they'll get re-added on server boot).
Michael says `call apoc.schema.assert({},{})` does the trick.

Of course this could be from a constraint we still have. Either way we need it removed.

**Comment by zkhin** [comment]
![image](https://user-images.githubusercontent.com/4212008/86660474-1dd8d680-c02e-11ea-9174-9848f7bb3296.png)
I added this like above but it gives error
`Neo4jError: There is no procedure with the name `apoc.schema.assert` registered for this database instance. Please ensure you've spelled the procedure name 
correctly and that the procedure is properly deployed.`

Can you let me know what's wrong on my side...

**Comment by CarsonF** [comment]
If you don't have `apoc` installed, click on your management tab in the db hamburger menu and go to the plugin tab and install it.

**Comment by zkhin** [comment]
Woooow! It works like a charm lol. Thank you!

**Comment by zkhin** [comment]
One quick question. Should I have to leave `CALL apoc.schema.assert({},{})` in `constraints` all the time?

**Comment by CarsonF** [comment]
No, that would undo all the constraints we are trying to add.

**Comment by zkhin** [comment]
Okay, got it. Thank you!
