### ISSUE TITLE
Engagement service: ensure nulls are created for all optional properties

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#681]
The quirks of our db schema and queries are such that when a property node is missing from a base node, its returns some unexpected results. An easy fix is to create all nodes with all the properties they can hold, using `null`s for properties that the caller doesn't supply on creation. 

1. Ensure this service's create function uses null for all properties not supplied on creation.
2. Update tests to create this base node with a partial input object to verify the refactor.

**Comment by punamasawa777** [comment]
This is Fixed with PR #697 

here is check

<img width="1434" alt="Screenshot 2020-07-08 at 4 56 07 PM" src="https://user-images.githubusercontent.com/64840907/86954149-1a9b3300-c173-11ea-9015-8a5874ff46c1.png">
