### ISSUE TITLE
Register > register($input: RegisterInput!) > User can register successfully with alphabetic characters in phone field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#683]
**Describe the bug**
Register > register($input: RegisterInput!) > User can register successfully with alphabetic characters in phone field

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Validation message should be returned for 'phone ' field.

**Actual Result**
Registration is done successfully. See video - https://www.awesomescreenshot.com/video/346386?key=b423bc5184f96e7f9072fa6830a873bf

GraphQL Query(register):
![image](https://user-images.githubusercontent.com/5212585/86779371-1a1e7180-c079-11ea-81fe-d5c2d8ffee71.png)

**Query and Input File**
[register_phone_characters.txt](https://github.com/SeedCompany/cord-api-v3/files/4884716/register_phone_characters.txt)

CordAPIV3# 8b7caae

**Comment by reneepe** [comment]
Bug verified.
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/6dcb6cb2-3287-4d84-9644-bda008ad0247)

**Comment by punamasawa777** [comment]
@michaelmarshall , Should Phone Number include Country code as well or not required?

**Comment by punamasawa777** [comment]
@michaelmarshall , @sethmcknight , @CarsonF 
Here is Docs for Validation   [https://github.com/typestack/class-validator]

choosing between two methods
1. @IsMobilePhone (Follows only MobileNo of 10 or 12 Digits or Valid Mobile No)
2. @IsPhoneNumber (+ Country Code as Prefix and then Followed by Number)

Let me know

**Comment by sethmcknight** [comment]
Closing out, we don't ask for phone number on register anymore.
