### ISSUE TITLE
Get all Partnerships  > query partnerships($input: PartnershipListInput!) > Same partnership Objects are returned in partnership listing

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#691]
**Describe the bug**
Get all Partnerships  > query partnerships($input: PartnershipListInput!) > Same partnership Objects are returned in partnership listing.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Unique object with unique details should be returned in partnership listing. e.g. Id has to be unique etc.

**Actual Result**
Two Partnership Object with same details are returned i.e. ID etc are exactly the same. See video - https://www.awesomescreenshot.com/video/355056?key=96aab7dd608572bede2ab63aea860886

GraphQL Query ( createPartnership ):
![image](https://user-images.githubusercontent.com/5212585/86921763-4acddc00-c149-11ea-985f-486d0b0e868d.png)

GraphQL Query ( partnerships ):
![image](https://user-images.githubusercontent.com/5212585/86921919-85d00f80-c149-11ea-89a5-593647415f33.png)

**Query and Input File**
[createPartnership.txt](https://github.com/SeedCompany/cord-api-v3/files/4890803/createPartnership.txt)
[partnerships.txt](https://github.com/SeedCompany/cord-api-v3/files/4890804/partnerships.txt)

CordAPIV3# 3dd7156

**Comment by punamasawa777** [comment]
This is fixed with PR PR #730 

Here is check 

<img width="1432" alt="Screenshot 2020-07-13 at 7 08 09 PM" src="https://user-images.githubusercontent.com/64840907/87321458-e2686b80-c549-11ea-9f04-e12be0f600fc.png">
