### ISSUE TITLE
Get all Locations > query locations($input : LocationListInput!) > Input - Filter is mandatory 

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#695]
**Describe the bug**
Get all Locations > query locations($input : LocationListInput!) > Input - Filter is mandatory 

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Location results are returned and Filter input shouldn't be mandatory. 

**Actual Result**
Getting "Expected parameter(s): filter" error.

GraphQL Query ( partnerships ):
![image](https://user-images.githubusercontent.com/5212585/86937324-bc635580-c15c-11ea-97d3-5398f6fcd43f.png)

**Query and Input File**
[locations_FilterError.txt](https://github.com/SeedCompany/cord-api-v3/files/4891569/locations_FilterError.txt)

CordAPIV3# 3dd7156

**Comment by CarsonF** [comment]
It's a DB query error

**Comment by zkhin** [comment]
@CarsonF If the filter input is not provided, should I have to return all locations?

**Comment by CarsonF** [comment]
Exactly.

**Comment by CarsonF** [comment]
Here's an example of a conditional where clause
https://github.com/SeedCompany/cord-api-v3/blob/dd8863a98b01a81e936235c7d9da879ec4a5f8ed/src/components/file/file.repository.ts#L103-L112

**Comment by reneepe** [comment]
@zkhin I'm getting the following error.

![image](https://user-images.githubusercontent.com/38309285/87360759-c9a38a00-c538-11ea-9400-daa8eec56bdd.png)

**Comment by CarsonF** [comment]
@reneepe That's your error. You've defined `$input` variable in your locations query (first line), but then have not provided it in the _query variables_ panel at the bottom.

You don't have to define the query with a variable, you could just hardcode the necessary parameters in the locations input (line 2). That's usually what I do.
For example,
```gql
query {
  location(id: "12asdf34") {
    ...
  }
}
```
Or in this case specifically
```gql
query {
  locations(input: { page: 1, count: 25 }) {
    ...
  }
}
```
All of those parameters are optional though so you could just omit them
```gql
query {
  locations {
    ...
  }
}
```
