### ISSUE TITLE
Incorrect Error Wording for Registering with Existing Account Information

### ISSUE THREAD

**Issue by reneepe** [SeedCompany/cord-api-v3#699]
Error message appears as "Node(61) already exists with label `EmailAddress` and property `value` = 'renee.testing961@gmail.com'" when a new user registers with an existing user's information.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/6328b5bb-6873-4da7-9f1d-5f2077ff0474)

**Comment by frankyma** [comment]
Moving this issue to BE as discussed with @CarsonF

**Comment by CarsonF** [comment]
I want to get another pass at the error handling in so we can specify that this error is on the email field.

**Comment by punamasawa777** [comment]
@CarsonF , Can i know the Exact Text for the Error message.

**Comment by CarsonF** [comment]
I think this is actually already fixed with #701. @reneepe do you want to confirm?

**Comment by reneepe** [comment]
It displays the message correctly now.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/66247171-4645-4f90-845f-47712e0989bd)
