### ISSUE TITLE
migrate user-role, model, service, resolver

### ISSUE THREAD

**Issue by candleshine** [SeedCompany/cord-api-v3#7]
User-role  model service and resolver to migrate from cord repo to follow the pattern now set in organization and language

**Comment by candleshine** [comment]
@michaelmarshall 
a user-role, in Cord, is really just a title and a possible associated location.  For example: Field Coordinator for Ireland or Regional Director for Asia.  I think some roles are not-location based eg: office of the president.  

In the old DB, these became properties on a user object.  I think these can be two nodes that users get relationships with .  
so all field coordinators get -is-> Role: FC
-located-> Ireland... or whatever verb you think makes sense.  

what that means is, we don't really CRUD the Role.  We update the user with relationship with a ROLE node.  

Am I thinking right in Graph?

**Comment by candleshine** [comment]
DO not continue this ticket until further notice.  The user role schema is uncertain and will change

**Comment by michaelmarshall** [comment]
closing, too old.
