### ISSUE TITLE
Get All Users > query users($input: UserListInput) > 'total' number of users data looks incorrect (i.e. whooping 78K+) )

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#707]
**Describe the bug**
Get All Users > query users($input: UserListInput) > 'total' number of users data looks incorrect (i.e. whooping 78K+) )

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Users total info is correct.

**Actual Result**
 'total' number of users data looks incorrect (i.e. whooping 78K+) ). See video - https://www.awesomescreenshot.com/video/364100?key=89a1d762a55241cfbf12c87eb5f3085b

Via postman & seeing on UI have different counts for users.

Also i double check while seeing 100 record per page on 60th page and it returned null, so something is wrong here.
![image](https://user-images.githubusercontent.com/5212585/87048829-da42c000-c219-11ea-9d90-c6e2c971ffeb.png)

GraphQL Query: (Users)
![image](https://user-images.githubusercontent.com/5212585/87046823-43750400-c217-11ea-9618-9e0ead24aaaa.png)

**Query and Input File**
[users_bigTotal.txt](https://github.com/SeedCompany/cord-api-v3/files/4897186/users_bigTotal.txt)

CordAPIV3# e5a7ad9

**Comment by zkhin** [comment]
@iPiyushPatel I created over 10K users and tried to reproduce this issue but it works fine on my side. Can you still reproduce on your side?

**Comment by iPiyushPatel** [comment]
Hi @zkhin 

I've looked into this further and compared User Records displayed on Neo4J browser (http://localhost:7474/browser/) & returned via API.
Still I see record count is different on both i.e. Neo4j browser say 368 where as API returns 80647 . I've also tried creating a new one and both increased by +1 :) 

SEE: https://drive.google.com/file/d/13wQwPRfsykjXdNuDBOscf9sfUowOaQb3/view?usp=drivesdk

I've used below query to get data on Neo4J browser: MATCH (n:User) RETURN count(n) as count

Let me know if you still any other information or have any feedback/suggestion for me.

Thanks,

**Comment by zkhin** [comment]
`MATCH (n:User {active: true}) RETURN count(n) as count`
It really matches exactly with the API total and neo4j results on my side.

**Comment by iPiyushPatel** [comment]
Hi @zkhin 
I've tested using this query and still I get a discrepancy in data. Maybe I have an old database. I'm bit unsure whether I should wipe database and start again, also not sure whether it's an advisable solution or not. What do you suggest? 

Also @michaelmarshall @CarsonF - can you please advise on database clean up?  As there are more tickets can't be replicable by Devs but I can easily replicate them with my database, this is one of them.

Please suggest if any. 

Thanks,

**Comment by iPiyushPatel** [comment]
I've verified after db wipe and I can't replicate this issue anymore. hence I'm closing. cc @CarsonF @michaelmarshall
