### ISSUE TITLE
Bug: 500 when creating Language

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#714]
**Describe the bug**
Got a 500 when creating a Language with generic error InternalServerError.  There were human readable errors prior when my validation failed

**Steps to Reproduce**
Use the createLanguage query in the playground

**Please give the commit short hash of the API and Front End repo if you are able to**.  
Run `git rev-parse --short HEAD` in each repo to retrieve the commit hash.    
API:    e5a7ad9
FE:      n/a

**Expected and Actual Results**
ER: successfully create language or human readable error message

AR: generic failure message, but sometimes the new language does get created (can be found with a list query)

**Screenshots**
If applicable, add screenshots of the failure to highlight the defect.
<img width="1446" alt="Screen Shot 2020-07-09 at 4 03 59 PM" src="https://user-images.githubusercontent.com/43487134/87099695-49f78180-c1ff-11ea-9c15-8cf2e5410cfd.png">

**Platform/Environment**  
Clear report on what the bug can be reproduced. Please complete the following information accordingly.

Desktop:

Smartphone:

**Additional context**

**Comment by punamasawa777** [comment]
@frankyma , I have tried with latest master branch,
It is working & here is Result

can you check and let me know

<img width="1428" alt="Screenshot 2020-07-10 at 8 42 30 PM" src="https://user-images.githubusercontent.com/64840907/87172146-6aa00400-c2f1-11ea-9f6a-df72fe8efbe1.png">

**Comment by frankyma** [comment]
@punamasawa777 Just pulled master and got a 500 again. For what it's worth I'm using the test suite data logged in as root user.

**Comment by candleshine** [comment]
This is a catch-all error message if it falls through the rest of the error checks.  If there should be a different error code, please let us know what you want it to be.  

Sounds like Frank and Punam connected.  Frank wiped db and it is not causing error any longer.
