### ISSUE TITLE
Neo4jError: Variable `engagementId` not defined

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#716]
```
Neo4jError: Variable `engagementId` not defined (line 10, column 7 (offset: 1168))
"WHERE engagementId.value CONTAINS $value2"
       ^

    at DatabaseService.list (src/core/database/database.service.ts:759:32)
    at ProductService.list (src/components/product/product.service.ts:102:34)
    at EngagementService.listProducts (src/components/engagement/engagement.service.ts:391:40)
```
8476112b1c4b235f6807309e7ee36a6b381a65c5

**Comment by zkhin** [comment]
@CarsonF Do we create `engagementId` property while creating `product`? 
https://github.com/SeedCompany/cord-api-v3/blob/8476112b1c4b235f6807309e7ee36a6b381a65c5/src/components/engagement/engagement.service.ts#L386-L407

**Comment by CarsonF** [comment]
No it's pre-existing. A product belongs to an engagement.

**Comment by zkhin** [comment]
Okay, then I think we need to rewrite the `listProducts` to fetch all Products which belongs to that engagement.
This issue occurs because it tries to find Products by `engagementId` in filter

**Comment by CarsonF** [comment]
Oh ok so that generic list provides a way to get a list of all products regardless of the engagement they are attached to.

**Comment by zkhin** [comment]
Yes, right. If we don't provide `engagementId` in filter, it will get all products regardless of that engagement.

**Comment by CarsonF** [comment]
I think for now we want to keep both of those functionalities.

**Comment by zkhin** [comment]
If you want to keep current `listProducts` function, then we need to refactor `product.service.ts/list` function. So if there's `engagementId` in filter, we need to write query to fetch products by `engagementId`

**Comment by zkhin** [comment]
@CarsonF Can you let me know what is the `Relationship` between `Product` and `Engagement`? I wonder if we create a relation between `Product` and `LanguageEngagement` while creating `LanguageEngagement`. Is there other mutation that adds product to engagement?

**Comment by CarsonF** [comment]
No products are created after the language engagement is created. There can be 0+ products on a language engagement.
The mutation is `createProduct`.

**Comment by zkhin** [comment]
It will be blocked until we create relation between `Product` and `LanguageEngagement` while creating `Product`

**Comment by CarsonF** [comment]
Please continue forward with that.
