### ISSUE TITLE
Get all Budgets > query budgets($input: BudgetListInput!) > 'total' is returned wrong

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#721]
**Describe the bug**
Get all Budgets > query budgets($input: BudgetListInput!) > 'total' is returned wrong

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Total number of budget records should be returned as 'total'. It should remain constant & equal to total records (It does work the correctly in Project & other module)

**Actual Result**
'total' is returned same as the requested input count . See video - https://drive.google.com/file/d/1l9PeZApwrgkw6JVblkSS_8v8SBuF8oyd/view

GraphQL Query ( budgets ):
![image](https://user-images.githubusercontent.com/5212585/87225161-ab0e8900-c3a8-11ea-99dc-6d3b81208ae9.png)

**Query and Input File**
[budgets_total.txt](https://github.com/SeedCompany/cord-api-v3/files/4906839/budgets_total.txt)

CordAPIV3# 395d59a

**Comment by punamasawa777** [comment]
This is Fixed with PR #728 

Here is check

<img width="1434" alt="Screenshot 2020-07-13 at 3 21 31 PM" src="https://user-images.githubusercontent.com/64840907/87318476-075adf80-c546-11ea-9290-78ffed00855c.png">
