### ISSUE TITLE
Get all Budgets > query budgets($input: BudgetListInput!) > Input - filter should not be mandatory field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#723]
**Describe the bug**
Get all Budgets > query budgets($input: BudgetListInput!) > Input - filter should not be mandatory field

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Filter should not be mandatory field for budgets query.

**Actual Result**
Response returned with error when filter is not provided in query inputs. See video - https://drive.google.com/file/d/1zUuAUJJVGe5GGew_Ye6EEMPu5LQL-ONe/view?usp=drivesdk

GraphQL Query ( budgets ):
![image](https://user-images.githubusercontent.com/5212585/87225820-46a1f880-c3ad-11ea-8dd8-ea5c75c13e38.png)

**Query and Input File**
[budgets_filterRequired.txt](https://github.com/SeedCompany/cord-api-v3/files/4906876/budgets_filterRequired.txt)

CordAPIV3# 395d59a

**Comment by punamasawa777** [comment]
This is fixed with PR #728 

Here is check

<img width="1430" alt="Screenshot 2020-07-13 at 3 23 27 PM" src="https://user-images.githubusercontent.com/64840907/87318889-92d47080-c546-11ea-9985-8cf91230f84c.png">
