### ISSUE TITLE
Registration and Login > Getting "Response code 500 (Internal Server Error)" error during Registration and Login  intermittently (via Web & API)

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#726]
**Describe the bug**
Registration and Login > Getting "Response code 500 (Internal Server Error)" error during Registration and Login intermittently (via Web & API)

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

Or
Go to http://localhost:3001/login and try login or registration. 

**Expected Result**
User should able to Register/Login in when correct details are provided as input.

**Actual Result**
Getting "Response code 500 (Internal Server Error)" error during Registration and login. 
See video - https://drive.google.com/file/d/118WRlmbkNHimcvreW82W2YZw9hxu53us/view?usp=drivesdk
See video - https://drive.google.com/file/d/1ILRWxoqxhR_6QrHplCxw3tAIb7mYVeXS/view?usp=drivesdk
Please note - on many tries, I was able to login just few time .

GraphQL Query ( register ):
![image](https://user-images.githubusercontent.com/5212585/87278699-baa1e500-c502-11ea-888c-2d34353e60d2.png)

GraphQL Query ( login ):
![image](https://user-images.githubusercontent.com/5212585/87277283-9db7e280-c4ff-11ea-9854-c45ae09e404d.png)

**Query and Input File**
[register_500Err.txt](https://github.com/SeedCompany/cord-api-v3/files/4911038/register_500Err.txt)

CordAPIV3# 395d59a

**Comment by zkhin** [comment]
Cannot reproduce this issue.

**Comment by CarsonF** [comment]
GItHub was having an outage during this time. https://www.githubstatus.com/incidents/j597fw8kv04c
We depend directly on it for timezone files.
We have an issue open for making this dependency less critical. https://github.com/SeedCompany/cord-api-v3/issues/664

But it only occurs when GitHub is down so it's low priority.

**Comment by iPiyushPatel** [comment]
Thanks @CarsonF for information. As we've already a open bug for tacking this, Should I close this ?  cc @michaelmarshall

**Comment by CarsonF** [comment]
That's good with me :+1:

**Comment by iPiyushPatel** [comment]
Ok,  Thanks for confirmation. I'm closing this. @CarsonF
