### ISSUE TITLE
Create Project > mutation createProject($input: CreateProjectInput!) > Error message doesn't specify required fields missing information for mouStart, mouEnd and estimatedSubmission

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#727]
**Describe the bug**
Create Project > mutation createProject($input: CreateProjectInput!) > Error message doesn't specify required fields missing information for mouStart, mouEnd and estimatedSubmission

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Error message showing information about required fields missing.

**Actual Result**
Error message doesn't specify required fields missing information for mouStart, mouEnd and estimatedSubmission
See video - https://drive.google.com/file/d/1VoLuyT8fNZsXyrirJQeAhRNY1s9ZH9yN/view?usp=drivesdk

GraphQL Query ( createProject ):
![image](https://user-images.githubusercontent.com/5212585/87282099-8bdf3b00-c511-11ea-9ea0-f99076c68748.png)

**Query and Input File**
[createProject_fieldMissing.txt](https://github.com/SeedCompany/cord-api-v3/files/4911223/createProject_fieldMissing.txt)

CordAPIV3# 395d59a

**Comment by zkhin** [comment]
Cannot reproduce this issue.

**Comment by CarsonF** [comment]
Only `name` and `type` are required; since you have those there are no fields missing. 
I'm pretty sure I've ran into this error before too

**Comment by zkhin** [comment]
This issue happens when the `userId` is null but the valid token exists. @iPiyushPatel Do you try to create a `Project` after running e2e tests?

**Comment by iPiyushPatel** [comment]
Hi @CarsonF @zkhin 
I'm not sure how to explain it better, but it's only issue when you don't provide 3 input parameters i.e. mouStart, mouEnd and estimatedSubmission

In my case, token/login looks good and even project created while giving all fields. 

SEE video : https://drive.google.com/file/d/136VLHpv9k2KJX5y09ke-OeDwPyyCOYaB/view?usp=drivesdk

Let me know if I can still provide you better info. 

Thanks,

**Comment by candleshine** [comment]
I have written tests for 

- no mouStart, mouEnd, estimatedSubmission
- no mouStart, yes mouEnd and estimatedSubmission
and then your example in the image
- no mouStart, yes mouEnd, estimatedSubmission, empty string in locationId

all these pass.  Submitting tests to PR
