### ISSUE TITLE
Get All Organizations > query organizations($input : OrganizationListInput) > Organization item is duplicated after updating and returned twice in Organizations Listing.

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#745]
**Describe the bug**
Get All Organizations > query organizations($input : OrganizationListInput) > Organization item is duplicated after updating and returned twice in Organizations Listing.

**Steps to Reproduce**
1. Create organization
2. Get All Organizations (created organization is present single time)
3. Update the created Organization
4. Get All Organizations (created organization is present twice)

On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Organizations results has to be unique. i.e 'id' should be unique for each organization item.

**Actual Result**
When organization is updated, It is returned twice in organizations listing.
See video - https://drive.google.com/file/d/1JXVxMGRvV84h53XVIsksV606c9qgfmXV/view?usp=drivesdk

GraphQL Query ( createOrganization ):
![image](https://user-images.githubusercontent.com/5212585/87525817-a3e8c300-c6a7-11ea-973a-3dad7b3ef35c.png)

GraphQL Query ( updateOrganization ):
![image](https://user-images.githubusercontent.com/5212585/87525890-be22a100-c6a7-11ea-8912-8a6f5bc3295b.png)

GraphQL Query ( organizations ):
![image](https://user-images.githubusercontent.com/5212585/87526077-faee9800-c6a7-11ea-8d37-67432545b666.png)

**Query and Input File**
[createOrganization_duplicate.txt](https://github.com/SeedCompany/cord-api-v3/files/4924103/createOrganization_duplicate.txt)
[updateOrganization_duplicate.txt](https://github.com/SeedCompany/cord-api-v3/files/4924104/updateOrganization_duplicate.txt)
[organizations_duplicate.txt](https://github.com/SeedCompany/cord-api-v3/files/4924106/organizations_duplicate.txt)

CordAPIV3# 37e39cc

**Comment by candleshine** [comment]
@michaelmarshall Update of Organizations has been removed by you, right?  There is no longer a security group with edit:true on Orgs.  

Is this ticket valid?  

Also, should we remove the updateOrganization resolver?

**Comment by michaelmarshall** [comment]
Ya I may have removed the edit sg, that was a mistake. please add it back in so the org creator can edit the name. thx.
