### ISSUE TITLE
Get All Organizations > query organizations($input : OrganizationListInput) > No organization items returned when filtered by 'userId'

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#746]
**Describe the bug**
Get All Organizations > query organizations($input : OrganizationListInput) > No organization items returned when filtered by 'userId'

**Steps to Reproduce**
1. Login
2. Create Organization
3. Get all Organizations (use filter as query input and provide logged in user id as input to 'userId' field of Filter )

On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Organizations results are returned.

**Actual Result**
No organization items returned when filtered by 'userId'.
See video - https://drive.google.com/file/d/183CpKqhzcPa8DhrleRk92AD9QjfvugT6/view?usp=drivesdk

GraphQL Query ( createOrganization ):
![image](https://user-images.githubusercontent.com/5212585/87528023-96810800-c6aa-11ea-89c9-64bfe51df00f.png)

GraphQL Query ( organizations ):
![image](https://user-images.githubusercontent.com/5212585/87528218-dcd66700-c6aa-11ea-9d43-5c4b0b3bb981.png)

**Query and Input File**
[createOrganization_idFilter.txt](https://github.com/SeedCompany/cord-api-v3/files/4924182/createOrganization_idFilter.txt)
[organizations_idFilter.txt](https://github.com/SeedCompany/cord-api-v3/files/4924185/organizations_idFilter.txt)

CordAPIV3# 37e39cc

**Comment by CarsonF** [comment]
This filter is going away so you don't have to test it.

**Comment by reneepe** [comment]
@CarsonF Is this good to close in that case?

**Comment by zkhin** [comment]
@CarsonF @reneepe It can be closed because `userId` is removed from the filter.
