### ISSUE TITLE
Get All Organizations > query organizations($input : OrganizationListInput) > Filter by 'name' is case sensitive

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#747]
**Describe the bug**
Get All Organizations > query organizations($input : OrganizationListInput) > Filter by 'name' is case sensitive.

**Steps to Reproduce**
1. Create Organization
3. Get all Organizations (use filter as query input and provide above created organization name as input to 'name' field of Filter )

On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Organizations with matching filter name are returned irrespective case i.e ABC = abc = ABc = aBC

**Actual Result**
Filter by 'name' is case sensitive. It only works when organization name with exact case is provided as input.
See video - https://drive.google.com/file/d/1zyztNMgPOShuWP9JGtkGrN3LEbPorvd4/view?usp=drivesdk

GraphQL Query ( createOrganization ):
![image](https://user-images.githubusercontent.com/5212585/87531146-e9f55500-c6ae-11ea-8491-670ce7602faa.png)

GraphQL Query ( organizations ):
![image](https://user-images.githubusercontent.com/5212585/87531242-0d200480-c6af-11ea-942f-82edb49c3ff5.png)

**Query and Input File**
[createOrganization_nameFilter.txt](https://github.com/SeedCompany/cord-api-v3/files/4924374/createOrganization_nameFilter.txt)
[organizations_nameFilter.txt](https://github.com/SeedCompany/cord-api-v3/files/4924375/organizations_nameFilter.txt)

CordAPIV3# 37e39cc

**Comment by candleshine** [comment]
@michaelmarshall I disagree with this expected result

**Comment by reneepe** [comment]
Bug verified. Name filter is case-sensitive.

![image](https://user-images.githubusercontent.com/38309285/87616329-cea43d00-c6e2-11ea-90ec-47551e21c353.png)

![image](https://user-images.githubusercontent.com/38309285/87616381-e24fa380-c6e2-11ea-9532-93f23a4e3e43.png)
