### ISSUE TITLE
Get All Organizations > query organizations($input : OrganizationListInput) > Sort by Name with 'ASC / DESC' order is not working

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#748]
**Describe the bug**
Get All Organizations > query organizations($input : OrganizationListInput) > Sort by Name with 'ASC / DESC' order is not working.

**Steps to Reproduce**
1. Create Organization
2. Get All Organizations

On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Organization items should be sorted by Name in ascending / descending order.

**Actual Result**
Sort by Name with 'ASC / DESC' order is not working.
See video - https://drive.google.com/file/d/1yATOm5p22PWzxVGJV0lSklj4SJJkX2TO/view?usp=drivesdk

GraphQL Query ( createOrganization ):
![image](https://user-images.githubusercontent.com/5212585/87554470-ca235880-c6d1-11ea-9fcc-2916a4d5d900.png)

GraphQL Query ( organizations ):
![image](https://user-images.githubusercontent.com/5212585/87554685-0f478a80-c6d2-11ea-8cae-eadc4a85d020.png)

**Query and Input File**
[sortName_createOrganization.txt](https://github.com/SeedCompany/cord-api-v3/files/4925741/sortName_createOrganization.txt)
[sortName_organizations.txt](https://github.com/SeedCompany/cord-api-v3/files/4925742/sortName_organizations.txt)

CordAPIV3# 37e39cc

**Comment by reneepe** [comment]
@iPiyushPatel  It's working in ascending and descending order. Please check that it works for you too. Thanks.

![image](https://user-images.githubusercontent.com/38309285/87615151-08c00f80-c6e0-11ea-9fc6-8c15f1fa934b.png)

![image](https://user-images.githubusercontent.com/38309285/87615184-20979380-c6e0-11ea-8f4b-7f2f9569b56c.png)

**Comment by iPiyushPatel** [comment]
Hi @reneepe 

I can still replicate the issue. Please see the video - https://drive.google.com/file/d/1mZvrYQ-EXuSrhc1Z3ZgMYPy7q3NNlENB/view?usp=drivesdk

Thanks

**Comment by reneepe** [comment]
When listing Organization Names that begin with uppercase and lowercase names, the uppercase names are sorted and listed first and then the lowercase names are sorted and listed next. 

The expectation is that the names would be listed in alphabetical order regardless of the name's first letter case. See below.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/3c9077df-e4cf-47ff-97e9-c4f1f8a3e848)

**Comment by elisabeth-sorrell** [comment]
PR https://github.com/SeedCompany/cord-api-v3/pull/1073 also covers this

**Comment by ParkeBrown** [comment]
@sethmcknight is it true that this is still unresolved or was it resolved by #1073 ?

**Comment by sethmcknight** [comment]
@ParkeBrown I just tested in Beta. It looks like it is sorting Z > A regardless of sort order. I would consider this unresolved.

**Comment by elisabeth-sorrell** [comment]
@sethmcknight @ParkeBrown I was able to successfully sort organizations on name last night. I don't understand why it's not working in beta....?
@michaelmarshall there isn't an environment difference that would show different behaviors where one sorts correctly and the other doesn't, is there?

**Comment by sethmcknight** [comment]
> @sethmcknight @ParkeBrown I was able to successfully sort organizations on name last night. I don't understand why it's not working in beta....?
> @michaelmarshall there isn't an environment difference that would show different behaviors where one sorts correctly and the other doesn't, is there?

@elisabeth-sorrell I'm not sure either. We can wait to see if @michaelmarshall has any insight.

**Comment by michaelmarshall** [comment]
No insight here. It's the same DB instance type as what we dev on.

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown Still looking successful to me.... would it be okay for me to put this in review and see if Piyush can confirm?

**Comment by iPiyushPatel** [comment]
@elisabeth-sorrell @ParkeBrown 
I've verified on the latest develop b2c47c7 branch and it's working fine.
