### ISSUE TITLE
Get All Users > query users($input: UserListInput) > Filter by 'displayFirstName' and 'displayLastName' is case sensitive

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#760]
**Describe the bug**
Get All Users > query users($input: UserListInput) > Filter by 'displayFirstName' and 'displayLastName' is case sensitive.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Users with matching filter 'displayFirstName' and filter 'displayLastName' are returned irrespective case i.e ABC = abc = ABc = aBC

**Actual Result**
Filter by 'name' is case sensitive. It only returns users when 'displayFirstName' or 'displayLastName'with exact case is provided as input. See video - https://drive.google.com/file/d/1Q7C8YFq8UI6UURT6Sj-YqpctyKMglNE9/view?usp=drivesdk

GraphQL Query ( users - displayFirstName ):
![image](https://user-images.githubusercontent.com/5212585/87635879-65addb00-c75d-11ea-824c-5ed2d672b1f0.png)
![image](https://user-images.githubusercontent.com/5212585/87635994-9857d380-c75d-11ea-9e99-7246600d3df7.png)

GraphQL Query ( users - displayLastName ):
![image](https://user-images.githubusercontent.com/5212585/87636400-54190300-c75e-11ea-9b63-cccd62e8d069.png)
![image](https://user-images.githubusercontent.com/5212585/87636553-917d9080-c75e-11ea-8ccd-281c97a72850.png)

**Query and Input File**
[users_FILTER_displayFirstName_err.txt](https://github.com/SeedCompany/cord-api-v3/files/4929776/users_FILTER_displayFirstName_err.txt)
[users_FILTER_displayLastName_err.txt](https://github.com/SeedCompany/cord-api-v3/files/4929778/users_FILTER_displayLastName_err.txt)

CordAPIV3# d2c1f51

**Comment by punamasawa777** [comment]
Issue is Fixed with PR #764 

Here is check
<img width="1429" alt="Screenshot 2020-07-16 at 8 22 24 PM" src="https://user-images.githubusercontent.com/64840907/87687692-a7fa0b00-c7a3-11ea-98f2-93b1998ef369.png">
