### ISSUE TITLE
Get All Locations > locations(input: LocationListInput): LocationListOutput! > Not getting any location results

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#763]
**Describe the bug**
Get All Locations > locations(input: LocationListInput): LocationListOutput! > Not getting any location results.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap.

**Expected Result**
Location results are returned.

**Actual Result**
Not getting any location results.

GraphQL Query ( locations ):
![image](https://user-images.githubusercontent.com/5212585/87681823-bb55a800-c79c-11ea-8ed1-0630d37a6b42.png)

CordAPIV3# d2c1f51

**Comment by candleshine** [comment]
@iPiyushPatel I need to see who created and who is querying these locations.  

Locations are currently locked to the person creating them.

**Comment by candleshine** [comment]
@michaelmarshall @sethmcknight security wise, I think locations and organizations are in the same boat.  Should be almost public knowledge.  Maybe there are subpieces that are closed off.  What do you want me to do here?

**Comment by michaelmarshall** [comment]
We'll need to add the necessary location props to be public. If you feel comfortable doing that then go ahead. @candleshine

**Comment by reneepe** [comment]
Bug reproduced. Location that user created isn't appearing in results.
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/61361a49-79e1-434b-a86b-cc7e2f5f9d30)

**Comment by zkhin** [comment]
@reneepe @michaelmarshall I think this ticket could be closed after this commit merged (https://github.com/SeedCompany/cord-api-v3/commit/885bc933c568d0f404f482d232b3270191e87793)

**Comment by reneepe** [comment]
Bug fixed. Locations that user created appear in results.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/eebe7880-b633-408d-a2f0-c5ba6b4a0623)
