### ISSUE TITLE
Get All Users > query users($input: UserListInput) > Data is still returned when 'sort' value is empty or having invalid data (i.e any string apart from "id")

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#776]
**Describe the bug**
Get All Users > query users($input: UserListInput) > Data is still returned when 'sort' value is empty or having invalid data (i.e any string apart from "id")

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Error should be thrown for invalid input to the 'sort' field.

**Actual Result**
No error thrown for invalid input to the 'sort' field and request sent successfully. See video - https://drive.google.com/file/d/18jnToKrzyFe0_nHu10Sh0Kv6NhJbjdfj/view?usp=drivesdk

GraphQL Query ( users ):
![image](https://user-images.githubusercontent.com/5212585/87899146-e4608c00-ca6d-11ea-9aad-f3626e2322e0.png)

**Query and Input File**
[users_sortNoErr.txt](https://github.com/SeedCompany/cord-api-v3/files/4945468/users_sortNoErr.txt)

CordAPIV3# bebdc85

**Comment by CarsonF** [comment]
We are loose on what values of sorted on can be, so this can't be validated at the graphql layer. Whether the value is valid is pretty close to the db query so I didn't do any validation up front either. I would expect that an invalid value would still return the same results - it just wouldn't be sorted in any order.

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
I got your point. I see similar issue on Organization as well. I'm not raising any new issue then. Please suggest if any.

**Comment by reneepe** [comment]
@CarsonF would you say that we hold off on testing "invalid" values in the sort field, and, instead, focus on testing whether the lists are correctly sorted by valid values?

**Comment by CarsonF** [comment]
@reneepe Yes, I think that's a better first step 👍
