### ISSUE TITLE
Get User By Id > query user($id: ID!) > User data is returned even if 'id' is not provided in input

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#777]
**Describe the bug**
Get User By Id > query user($id: ID!) > User data is returned even if 'id' is not provided in input

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
User data should not be returned and proper validation message should be thrown for empty 'id' field.

**Actual Result**
User data is returned even if 'id' is not provided in input. See video - https://drive.google.com/file/d/1Q7ANesSIXGv5JR4pDlw4f3Jr9WLpAnEH/view?usp=drivesdk

GraphQL Query ( user ):
![image](https://user-images.githubusercontent.com/5212585/87902449-3e198400-ca77-11ea-9307-41ef5ca9549d.png)

**Query and Input File**
[user_dataWithoutIDinput.txt](https://github.com/SeedCompany/cord-api-v3/files/4945650/user_dataWithoutIDinput.txt)

CordAPIV3# bebdc85

**Comment by CarsonF** [comment]
Is this only working because the `id` is empty? That's what my guess is.

We need to apply the `IsShortID` validator to the `IdArg` decorator. That way these `id`'s that are outside of input objects are also validated.

**Comment by punamasawa777** [comment]
Fixed with PR #779 

Here is check

<img width="1433" alt="Screenshot 2020-07-20 at 7 08 40 PM" src="https://user-images.githubusercontent.com/64840907/87957315-bad74d00-cacd-11ea-9386-04b5d37498f9.png">

**Comment by michaelmarshall** [comment]
@punamasawa777 please see Carson's comment and go with that approach. Thanks.
