### ISSUE TITLE
query createOrganization > AvatarLetters are returned blank for Organization name contains Capital and Small letters

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#789]
**Describe the bug**
query createOrganization > AvatarLetters are returned blank for Organization name contains Capital and Small letters.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
AvatarLetters are returned according to the Organization name.

**Actual Result**
AvatarLetters are returned blank for Organization name contains Capital and Small letters.
See video - https://drive.google.com/file/d/1Rf0uEnmDyR-Yz0wS5ACIZwfWo4T8a5vk/view?usp=drivesdk

GraphQL Query ( createOrganization ):
![image](https://user-images.githubusercontent.com/5212585/88022105-498aaf00-cb4c-11ea-855a-dd4b513007e8.png)

**Query and Input File**
[createOrganization_avtarLettersNULL.txt](https://github.com/SeedCompany/cord-api-v3/files/4951776/createOrganization_avtarLettersNULL.txt)

CordAPIV3# 65945ca

**Comment by candleshine** [comment]
Org Names that are valid do not include mix case words like `orgName`. 
Expected behavior is 
`Seed Company` `SC`
`seed company` `sc`
`Seed company` `S`
`seed Company` `C`
`Project 2020` `P2`
`project 2020` `p2`
`orgName` `` (blank)
@sethmcknight is this acceptable or do you want any of these to change?  If acceptable, please feel free to close this ticket

**Comment by iPiyushPatel** [comment]
Any conclusion on this issue as I'm seeing same issue on Organization, Users, Project as well?

@candleshine @sethmcknight @CarsonF @michaelmarshall

**Comment by reneepe** [comment]
Bug verified. Avatar Letters are returned blank when an organization's name has a lower case letter first (ie, "orG").

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/6e70eddc-0c6c-4703-832e-8b468ebe0652)

Avatar Letters return data when the organization's name is in one case (ie, "org," or "ORG") or it has a capital letter first (ie, "Org").  

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/fa9aa5b9-8b18-455b-8a98-5697dd436d98)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/88e0ee70-df07-406e-a30c-6046a57d8a09)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/7aa77f8f-3e5c-46e7-b4de-01da239658ff)

**Comment by zkhin** [comment]
@iPiyushPatel 
- If the string has uppercase characters we use the uppercase pattern which will ignore lowercase characters after word-like boundaries.
- If the string doesn't have any uppercase characters we fallback to the lowercase pattern which is less ideal but gives something instead of an empty string.

**Comment by zkhin** [comment]
@CarsonF If the orgName is `orgT` then should it be `uppercasePattern` or `lowercasePattern`?

**Comment by CarsonF** [comment]
Well this only happens for upper case pattern, which is expecting a title case, not camel case. We could check if the result is empty and run it through the lower case pattern if so.

**Comment by CarsonF** [comment]
Can you add it to the test file as well? I would expect `orgName` to return `o`.

**Comment by zkhin** [comment]
Sure, I will add

**Comment by zkhin** [comment]
@CarsonF How's about `org T`? It returns `T` right now.

**Comment by CarsonF** [comment]
@zkhin ideally it would be `org T` would be `oT` but I'm ok with it just being `T` right now.

**Comment by iPiyushPatel** [comment]
Hi @CarsonF @zkhin @michaelmarshall @reneepe 

I've tested this on the latest master c4c11b73 and observed the below results.

org T => T
orgTest => o
OrgTest => O
Org Name => ON
Org_Name => O
_Name => ""
Name_Org => N
ORG => O
org => o

**Comment by CarsonF** [comment]
Those look good to me. We could handle the underscores, but in practice they are never used. 
These are the cases we are really trying to handle:
https://github.com/SeedCompany/cord-api-v3/blob/b8e12a846b1fbd24798ab74acd06b31ebc5e46e1/src/common/firstLettersOfWords.test.ts#L5-L27
