### ISSUE TITLE
query createProject > User value returned null

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#795]
**Describe the bug**
query createProject > User value returned null.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
User data should be returned with all details.

**Actual Result**
User value returned null.
See video - https://drive.google.com/file/d/1JVRDcN4r9qTLwLGp-q71P_MIEyGKX4JQ/view?usp=drivesdk

**Note**
It was working fine till yesterday.

GraphQL Query ( createProject ):
![Desktop_screenshot](https://user-images.githubusercontent.com/5212585/88131698-34208e00-cbfb-11ea-9e07-9f6b476c0abc.png)

**Query and Input File**
[createProject_userValue_NULL.txt](https://github.com/SeedCompany/cord-api-v3/files/4957660/createProject_userValue_NULL.txt)

CordAPIV3# 61d3e7f

**Comment by CarsonF** [comment]
Yes if you've just created the project you should be able to read yourself in the team.

**Comment by reneepe** [comment]
Bug verified.
![image](https://user-images.githubusercontent.com/38309285/88178996-3681e880-cbf9-11ea-9e8c-9b27eb1dc97d.png)

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
I didn't get your comment. Can you please elaborate further?

**Comment by CarsonF** [comment]
I was just agreeing with you and adding more context.

**Comment by iPiyushPatel** [comment]
Ok, got it @CarsonF Thanks,

**Comment by punamasawa777** [comment]
Fixed with PR #812

Here is Check

<img width="1429" alt="Screenshot 2020-07-23 at 5 34 03 PM" src="https://user-images.githubusercontent.com/64840907/88298503-e00eca00-cd1e-11ea-9097-9d30cd59a40e.png">

**Comment by reneepe** [comment]
Bug fix verified.
![image](https://user-images.githubusercontent.com/38309285/88341081-ebf09100-cd0a-11ea-819c-f961095a305e.png)


@iPiyushPatel Please rerun your test and validate. Thanks!

**Comment by iPiyushPatel** [comment]
I can still regenerate the issue. See video - https://drive.google.com/file/d/13SZhkFAQ7lUimeXutXtkECMimJW-PbTr/view?usp=drivesdk

I'm on the latest master. @reneepe
