### ISSUE TITLE
query createLanguage > Multiple minLength validation messages for the same field of ethnologue. ( code, provisionalCode )

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#798]
**Describe the bug**
query createLanguage > Multiple minLength validation messages for the same field of ethnologue. ( code, provisionalCode )

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Field should have single minLength validation message.

**Actual Result**
Multiple minLength validation messages for the same field of ethnologue.
See video - https://drive.google.com/file/d/1kbAmErUDsb6cCaH6rDZAiB2endi5_CT3/view?usp=drivesdk

GraphQL Query ( createLanguage - code ):
![image](https://user-images.githubusercontent.com/5212585/88192484-31a15100-cc5a-11ea-80ee-04bb492537a6.png)

GraphQL Query ( createLanguage - provisionalCode ):
![image](https://user-images.githubusercontent.com/5212585/88192879-aa081200-cc5a-11ea-9315-6a3c39263e56.png)

**Query and Input File**
[createLanguage_multiLengthMsg_ISSUE.txt](https://github.com/SeedCompany/cord-api-v3/files/4960744/createLanguage_multiLengthMsg_ISSUE.txt)

CordAPIV3# 61d3e7f

**Comment by candleshine** [comment]
Interesting thing, I could recreate this error on GraphQL Playground but not in the Jest test suite.  

Anyway, in talking to @michaelmarshall this is migrated data and won't be subject to user input and will not need validation.
