### ISSUE TITLE
query createPartnership > getting "Failed to create partnership" error when 'types' field not provided

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#802]
**Describe the bug**
query createPartnership > getting "Failed to create partnership" error when 'types' field not provided.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Required Field Validation error should be thrown for mandatory field validation. It works the same way for other mandatory fields.

**Actual Result**
getting "Failed to create partnership" error when 'types' field not provided.
See video - https://drive.google.com/file/d/10H8YlDmQ-SqIRXsY-KPyIdwhJnI6e28T/view?usp=drivesdk

**Note**
It's working fine till yesterday without 'types' field.

GraphQL Query ( createPartnership ):
![image](https://user-images.githubusercontent.com/5212585/88248132-bc676780-ccbd-11ea-9fd6-35e254af54a3.png)

**Query and Input File**

CordAPIV3# 76b220c

**Comment by reneepe** [comment]
Bug verified.
![image](https://user-images.githubusercontent.com/38309285/88282974-8e335900-ccb8-11ea-9456-b62fb31d8548.png)
