### ISSUE TITLE
query partnerships > "Cannot return null for non-nullable field SecuredPartnershipTypes.value" error for 'types' field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#803]
**Describe the bug**
query partnerships > "Cannot return null for non-nullable field SecuredPartnershipTypes.value" error for 'types' field

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Partnerships are returned.

**Actual Result**
Getting ""Cannot return null for non-nullable field SecuredPartnershipTypes.value" error when 'types' field in query output
See video - https://drive.google.com/file/d/1rDMe7q__NE1-im9xparm4w9KYB8ypiIA/view?usp=drivesdk

**Note**
It was working fine till yesterday.

GraphQL Query ( partnerships ):
![image](https://user-images.githubusercontent.com/5212585/88249159-33522f80-ccc1-11ea-97a1-0b43d265b7e7.png)

**Query and Input File**
[partnerships_typesFieldERR.txt](https://github.com/SeedCompany/cord-api-v3/files/4963679/partnerships_typesFieldERR.txt)

CordAPIV3# 76b220c

**Comment by ibohalsinghkoijam** [comment]
@michaelmarshall , Refactor partnership 'readone' broke #596 (Sync Project & Partnership Start/End Dates).

**Comment by ibohalsinghkoijam** [comment]
<img width="1377" alt="1-partnership-refactor-issue" src="https://user-images.githubusercontent.com/24403111/88275629-539ee000-ccfb-11ea-84d6-f55700e61e37.png">

**Comment by reneepe** [comment]
Bug verified. Including Types in Partnership query returns below error.
![image](https://user-images.githubusercontent.com/38309285/88288898-66e18980-ccc2-11ea-9a4d-12a2bf46f45c.png)

**Comment by michaelmarshall** [comment]
thank you @ibohalsinghkoijam since @zkhin just refactored it, I'd like him to work this. Thanks.

**Comment by zkhin** [comment]
> @michaelmarshall , Refactor partnership 'readone' broke #596 (Sync Project & Partnership Start/End Dates). Should I handle this or some other will handle this ?

@michaelmarshall @ibohalsinghkoijam 
I think the `projectMouStart` and `projectMouEnd` will be the same with `mouStart` and `mouEnd`, right?
https://github.com/SeedCompany/cord-api-v3/blob/140317e9fd7112a83acd20ed6425d301efb490bd/src/components/partnership/partnership.service.ts#L354~L387

**Comment by ibohalsinghkoijam** [comment]
@michaelmarshall, I have fixed broke changes for #596 (Sync Project & Partnership Start/End Dates), but i am still getting the error in playground. If I tried to run the cypher query inside neo4j browser, it can run query successfully.
