### ISSUE TITLE
mutation createLanguage > 'isDialect' and 'leastOfThese' returned null for the input value 'false'

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#806]
**Describe the bug**
mutation createLanguage > 'isDialect' and 'leastOfThese' returned null for the input value 'false'.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
'isDialect' and 'leastOfThese' should return the same value as requested.

**Actual Result**
'isDialect' and 'leastOfThese' returned null for the input value 'false'.
See video - https://drive.google.com/file/d/15pEf0qItvDTh4PeWxQMt1t4n1r3H3Agk/view?usp=drivesdk

GraphQL Query ( createLanguage ):
![image](https://user-images.githubusercontent.com/5212585/88276719-29e6b880-ccfd-11ea-9d72-af053fdb1757.png)

**Query and Input File**
[createLanguage_isDialectLeaseThese_NULL.txt](https://github.com/SeedCompany/cord-api-v3/files/4965312/createLanguage_isDialectLeaseThese_NULL.txt)

CordAPIV3# 76b220c

**Comment by punamasawa777** [comment]
Fixed with PR #819 

Here is Check 

<img width="1428" alt="Screenshot 2020-07-24 at 8 10 29 PM" src="https://user-images.githubusercontent.com/64840907/88403396-1feeb380-cdea-11ea-9ee4-245c3981a85e.png">

**Comment by iPiyushPatel** [comment]
Hi @michaelmarshall @reneepe 

I can still replicate the same issue on the latest master 29ee3b29 as well as on the integration environment.

See video - https://drive.google.com/file/d/15sKte26PxlG2ZGRy-yEhJN1olL6cHrzO/view?usp=drivesdk
