### ISSUE TITLE
mutation createLanguage > 'canRead' and 'canEdit' flag values returned randomly for Language properties.

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#808]
**Describe the bug**
mutation createLanguage > 'canRead' and 'canEdit' flag values returned randomly for Language properties.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request for multiple times.

**Expected Result**
There should be similar values for 'read' and 'edit' fields.

**Actual Result**
'canRead' and 'canEdit' flag values returned randomly for Language properties.
See video - https://drive.google.com/file/d/1Z-4mHiIZlEIpsGdWr-_E_pouvjhwiAXn/view?usp=drivesdk

GraphQL Query ( createLanguage ):
![image](https://user-images.githubusercontent.com/5212585/88280643-cca23580-cd03-11ea-884a-dbac049ef5e7.png)

![image](https://user-images.githubusercontent.com/5212585/88280770-11c66780-cd04-11ea-8244-bb7710b171cf.png)

**Query and Input File**
[createLanguage_canReadEdit_random.txt](https://github.com/SeedCompany/cord-api-v3/files/4965513/createLanguage_canReadEdit_random.txt)

CordAPIV3# 76b220c

**Comment by punamasawa777** [comment]
Fixed with Language Refactor

Here is check
<img width="1436" alt="Screenshot 2020-07-27 at 3 33 42 PM" src="https://user-images.githubusercontent.com/64840907/88529865-33826000-d01e-11ea-8814-980242fb9bdc.png">

**Comment by candleshine** [comment]
closing

**Comment by iPiyushPatel** [comment]
I can still replicate the same issue on the latest master 29ee3b29 as well as on the integration environment.

See video - https://drive.google.com/file/d/18byvOhUD0YXOUJ5LcBwPE-ceXx-8adZp/view?usp=drivesdk
