### ISSUE TITLE
Cannot return null for non-nullable field InternshipEngagement.intern/mentor.canRead

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#815]
```gql
query {
  engagement(id: "Wf8yc0HJL") {
    id
    ... on InternshipEngagement {
      intern {
        canRead
        canEdit
      }
      mentor {
        canRead
        canEdit
      }
    }
  }
}
```
![Screen Shot 2020-07-23 at 8 27 56 PM](https://user-images.githubusercontent.com/932566/88353434-08002c80-cd23-11ea-8294-8fdea1122d1d.png)

**Comment by CarsonF** [comment]
It's the same error for `intern` and `countryOfOrigin` properties as well.

**Comment by michaelmarshall** [comment]
@punamasawa777 this was just refactored. I'd like @zkhin to take a look. Thanks.

**Comment by punamasawa777** [comment]
@michaelmarshall , @zkhin  This is already fixed, I will raise a PR in short

**Comment by punamasawa777** [comment]
Fixed with PR #838 

Here is Check

<img width="1431" alt="Screenshot 2020-07-28 at 3 01 05 PM" src="https://user-images.githubusercontent.com/64840907/88648552-b837b180-d0e4-11ea-9f14-9f9b40c0bfb7.png">

**Comment by reneepe** [comment]
Bugfix https://github.com/SeedCompany/cord-api-v3/pull/838 verified. "Null" accurately returned as value.

![image](https://user-images.githubusercontent.com/38309285/88724849-2edeaa00-d0f9-11ea-8afb-bf92b8838f83.png)

**Comment by reneepe** [comment]
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/929a2a94-7a16-4bde-ab79-14652e5d4690)
