### ISSUE TITLE
query users > Only recently registered user is returned in User listing even if Multiple registrations are done

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#820]
**Describe the bug**
query users > Only recently registered user is returned in User listing even if Multiple registrations are done

**Steps to Reproduce**
1. Register user multiple times
2. Get All Users (Only recent User is returned in listing)

On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
All users are returned.

**Actual Result**
Only recently registered user is returned in User listing even if Multiple registrations are done.
See video - https://drive.google.com/file/d/1yzV77Q2o-L_OVkLjSWpgnMyn0dt8hz-c/view?usp=drivesdk

GraphQL Query ( users ):
![image](https://user-images.githubusercontent.com/5212585/88400880-95f11b80-cde6-11ea-98db-ae6ba9c2e3e5.png)

**Query and Input File**
[register_SingleUserOnly.txt](https://github.com/SeedCompany/cord-api-v3/files/4972417/register_SingleUserOnly.txt)
[users_SingleUserOnly.txt](https://github.com/SeedCompany/cord-api-v3/files/4972418/users_SingleUserOnly.txt)

CordAPIV3# f655d0c

**Comment by punamasawa777** [comment]
@iPiyushPatel , This is expected behaviour as per SecurityGroup design 
cc @michaelmarshall

**Comment by reneepe** [comment]
Not a bug. Working as designed.
