### ISSUE TITLE
Updating a partnership takes progressively longer then fails

### ISSUE THREAD

**Issue by thomas-adev** [SeedCompany/cord-api-v3#827]
**Describe the bug**
Each time update partnership is called using the graphql api, it is taking a progressively longer time to fulfill the request.
On the fourth update, the call does not resolve.

**Reproduce with playground**
Update a partnership using GraphQL
```
mutation{
  updatePartnership(input:{
    partnership:{
      id:"{{REPLACE WITH PARTNERSHIP ID}}"
      mouStartOverride:"1981-01-01"
      mouEndOverride:"2020-01-01"
      types:[Funding]
    }
  }){
    partnership{
      id
      mouStart{
        value
        canRead
        canEdit
      }
      mouEnd{
        value
        canRead
        canEdit
      }
      mouStartOverride{
        value
        canRead
        canEdit
      }
      mouEndOverride{
        value
        canRead
        canEdit
      }
    }
  }
}
```

**Commit Hash**
API: 5db8886
FE: N/A

**Expected and Actual Results**
Expected: Should be able to call update partnership an unlimited number of times.
Actual: Each call is taking progressively longer till the fourth call never returns.

**Platform/Environment**  

Desktop:
- OS: MacOS Mojave 10.14.6
- Browser: Firefox using graphql playground.
- Version: 78.0.2
- DB: Neo4j 3.5.19

**Comment by zkhin** [comment]
@thomas-adev @michaelmarshall 
Finally, I can reproduce this issue on my side. It only happens when I tried to create/update `partnership` with the `root` user. It doesn't happen with a `normal` user.

**Comment by thomas-adev** [comment]
| Δ Nodes | Δ Relations
-- | -- | --
Update 1 | 6 | 6
Update 2 | 12 | 12
Update 3 | 24 | 24
Update 4 | 48 | 48
Update 5 (incomplete) | 288 | 288

**Comment by tjgersho** [comment]
Each update creates a new node and sets the old node to active = false. So whenever updated properties, new nodes are created.
So 3 nodes and 3 relations are created each time the query above is run. It might cause this issue?!
I tested with root and a normal user and could see it happens in both cases.

**Comment by michaelmarshall** [comment]
It looks like the query is not written correctly because it is adding nodes based on an ever increasing amount of returned rows. I think you should print out the query that is being sent to the db and let's analyze it.

**Comment by tjgersho** [comment]
Thomas, I tried to use the update query for 40 times, but can not reproduce the issue. It is creating only 3 nodes every time. Are you on the latest master branch? Can you verify this issue after wiping the db again?

**Comment by thomas-adev** [comment]
I just pulled latest version of master (662a10a)  and used a fresh DB. Still getting the same behavior.

Zayar pointed out that this only manifests when using a root user. The error occurs when I login with: "devops@tsco.org" but not if I create a new user and execute the mutation that way. Are you able to replicate if you use the root account?

**Comment by tjgersho** [comment]
https://api.v3.cordfield.com/graphql
Can you verify the issue here? So we can test the same query on the same database.

**Comment by tjgersho** [comment]
@thomas-adev , please check this issue on the branch #905.
