### ISSUE TITLE
query organizations > No validation for the invalid or empty 'userId' field in filter 

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#828]
**Describe the bug**
query organizations > No validation for the invalid or empty 'userId' field in filter 

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Validation message should be thrown for invalid or empty 'userId' field in filter

**Actual Result**
Organization results are not returned.
See video - https://drive.google.com/file/d/1PsXry0WXx2CTqIgI7FZ9M76JcKqEJEZp/view?usp=drivesdk

**Note**
This works correctly while query partnerships for 'projectId' field in filter.

GraphQL Query ( organizations ):
![image](https://user-images.githubusercontent.com/5212585/88508645-f35eb580-cffc-11ea-830f-a32369c4d242.png)

GraphQL Query ( partnerships ):
![image](https://user-images.githubusercontent.com/5212585/88508826-53edf280-cffd-11ea-9ffd-96ac3614be0b.png)

**Query and Input File**
[organizations_filter_userId_validation.txt](https://github.com/SeedCompany/cord-api-v3/files/4980215/organizations_filter_userId_validation.txt)
[partnershipsDEMO_filter_userId_validation.txt](https://github.com/SeedCompany/cord-api-v3/files/4980217/partnershipsDEMO_filter_userId_validation.txt)

CordAPIV3# 5db8886

**Comment by reneepe** [comment]
Bug verified. No validation error was triggered when user tries to filter by userId without entering userId data to filter by. 

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/a17e58c4-5b4c-42b1-acd5-59f5b41da3c1)

Expected result is displayed in the partnership query below.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/c1a45b57-d369-42d3-b350-9d14972ba237)
