### ISSUE TITLE
query projects > Response time is > 10 seconds

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#831]
**Describe the bug**
query projects > Response time is > 10 seconds

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Response time should be less than 10 seconds.

**Actual Result**
Response time is between 14 to 26 seconds. I've tried more than 3 times.
See video - https://drive.google.com/file/d/1r7cBZJrWuHXCFCzvTeiPDwNY2ZtCZ5Zx/view?usp=drivesdk

GraphQL Query ( projects less output ):
![image](https://user-images.githubusercontent.com/5212585/88555812-e6b27f80-d045-11ea-887e-931506e070de.png)

GraphQL Query ( projects full output ):
![image](https://user-images.githubusercontent.com/5212585/88556148-4dd03400-d046-11ea-8312-dfdef90ca8c9.png)

**Query and Input File**
[projects_lessOutput_responseTime_Check.txt](https://github.com/SeedCompany/cord-api-v3/files/4982656/projects_lessOutput_responseTime_Check.txt)
[projects_fullOutput_responseTime_Check.txt](https://github.com/SeedCompany/cord-api-v3/files/4982658/projects_fullOutput_responseTime_Check.txt)

CordAPIV3# 5db8886

**Comment by michaelmarshall** [comment]
Profile the Project.readOne query and reduce the DB hits.

**Comment by reneepe** [comment]
Bug verified. Project query with 68 projects returned took over 10 seconds.

**Comment by tjgersho** [comment]
This issue can now be closed because the readOne was refactored.

**Comment by michaelmarshall** [comment]
closing as this was fixed in the readOne refactors.
