### ISSUE TITLE
query languages > Response time > 10 seconds

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#832]
**Describe the bug**
query languages > Response time is taking more than 10 seconds

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
query languages > Response time > 10 seconds

**Actual Result**
Response time is between 14 to 26 seconds. I have tried more than 3 times.
See video - https://drive.google.com/file/d/11DpfeUSBOIV9vxaspmSx3G7jTHFYL4F2/view?usp=drivesdk

GraphQL Query ( languages less output ):
![image](https://user-images.githubusercontent.com/5212585/88556811-0f874480-d047-11ea-9824-9e6ad8f0fd50.png)

GraphQL Query ( languages full output ):
![image](https://user-images.githubusercontent.com/5212585/88557064-62f99280-d047-11ea-9b23-91bfece53b6e.png)

**Query and Input File**
[languages_lessOutput_responseTime_Check.txt](https://github.com/SeedCompany/cord-api-v3/files/4982699/languages_lessOutput_responseTime_Check.txt)
[languages_fullOutput_responseTime_Check.txt](https://github.com/SeedCompany/cord-api-v3/files/4982700/languages_fullOutput_responseTime_Check.txt)

CordAPIV3# 5db8886

**Comment by izquierdoalfredo** [comment]
![before screenshot](https://user-images.githubusercontent.com/68758109/89239569-9b5d1b80-d5c7-11ea-8389-52fee1aaffd4.png)
![New screenshot](https://user-images.githubusercontent.com/68758109/89239575-9ef0a280-d5c7-11ea-8b6b-72606c392f42.png)

**Comment by reneepe** [comment]
Fixed by Refacotr languages query to decrease response time #891
Queries are less than 10s.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/1f24567c-d1fc-4f79-b344-6483283a4f0a)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/17cc8240-61fb-447a-ad42-1a388df9d03c)
