### ISSUE TITLE
query projects > getting "Could not find root directory associated to this project" error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#836]
**Describe the bug**
query projects > getting "Could not find root directory associated to this project" error.

**Steps to Reproduce**
1. Create Project
2. Get All Projects

On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Recently Created Project should be returned in Project list.

**Actual Result**
Project results are not returned and gettting "Could not find root directory associated to this project" error.
See video - https://drive.google.com/file/d/1LGIjq5hpfvCy9MJLrfZy4W60s3e-F2I0/view?usp=drivesdk

**Note**
This works correctly till yesterday.

GraphQL Query ( createProject ):
![image](https://user-images.githubusercontent.com/5212585/88616998-34b19c80-d0b3-11ea-9529-9ea6bd284c2f.png)

GraphQL Query ( projects ):
![image](https://user-images.githubusercontent.com/5212585/88617088-632f7780-d0b3-11ea-8d5e-d4870b40ee17.png)

**Query and Input File**
[createProject_rootDirectlyERR.txt](https://github.com/SeedCompany/cord-api-v3/files/4985861/createProject_rootDirectlyERR.txt)
[projects_rootDirectlyERR.txt](https://github.com/SeedCompany/cord-api-v3/files/4985862/projects_rootDirectlyERR.txt)

CordAPIV3# be3e5ac

**Comment by tjgersho** [comment]
@michaelmarshall , creating a Project with associated root directories is not implemented?! I need to implement it first.

**Comment by tjgersho** [comment]
I tried to reproduce this issue on the latest master, but it is working fine. @reneepe , can you check this issue?
https://i.imgur.com/XA2g6yH.png

**Comment by reneepe** [comment]
Unable to reproduce.

User starts with only one project.
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/9f181d6d-e17c-4b0e-bced-705265b63628)

User added 5 projects. Last project is "Project 9."
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/cd6f1af0-dea7-4eec-bc4a-c62d99b78859)

Query returned 5 newly added projects including "Project 9."
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/6b9f4610-2113-4ebe-8ccc-ff0e50b4b3f1)

**Comment by reneepe** [comment]
@iPiyushPatel Can you retest and see if you're still encountering this issue? Thanks!

**Comment by iPiyushPatel** [comment]
I've tried retesting #836 multiple times but getting errors.
See Video - https://drive.google.com/file/d/1kFHLmqSNG7CKZBxaXd1gR_OV-1horntV/view?usp=sharing

**Comment by tjgersho** [comment]
Your video shows the Timeout error. So this original issue: getting "Could not find root directory associated to this project" error is not the issue now.

**Comment by iPiyushPatel** [comment]
Hi @tjgersho @reneepe @michaelmarshall 
I'm still getting this issue intermittently. 
See Video -  https://drive.google.com/file/d/1fzQ4d9VCpKXXT37rtPeMu0fELJsOOILt/view?usp=drivesdk

**Comment by tjgersho** [comment]
https://github.com/SeedCompany/cord-api-v3/blob/324a00e43c7a888a6320239b257a9f266c8e943b/test/file.e2e-spec.ts#L123
File e2e test is removing all directories for the projects. When I removed this line simply, the consistency check fails in file e2e test.
