### ISSUE TITLE
Project Members Duplicated

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#842]
https://v3.cordfield.com/projects/MuRWWpRpk/members
![Screen Shot 2020-07-28 at 12 24 18 PM](https://user-images.githubusercontent.com/932566/88699756-5b7ccc80-d0cd-11ea-8a4a-d3e7dbb22203.png)

A user can only be a member of a project once.

**Comment by reneepe** [comment]
Bug verified. Project members are duplicated.
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/1f81611a-94a3-46f3-9d07-5fec5cfae816)
