### ISSUE TITLE
Engagements Duplicated

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#844]
A language/user can only be connected (via engagement) to a project once.

https://v3.cordfield.com/projects/2u4opttle

![Screen Shot 2020-07-28 at 12 39 14 PM](https://user-images.githubusercontent.com/932566/88701239-5caef900-d0cf-11ea-8529-3d18babc6dff.png)

**Comment by michaelmarshall** [comment]
![image](https://user-images.githubusercontent.com/1165460/88702247-b19f3f00-d0d0-11ea-886c-4431d8671f64.png)
