### ISSUE TITLE
Project takes too long to load

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#845]
[link](https://v3.cordfield.com/projects/2u4opttle)

A project with 8 engagements takes too long to load. We need to determine which queries are taking the longest (and why) and start optimizing. The goal (for now) is to get this project to load in less than 5 seconds. Use the `DB hits` field in the Neo4j browser when `profile`ing your query as the primary way to determine query performance. Integration gets updated when master is updated. 

Please add a comment when you determine how many DB hits the whole suite of queries are making so we can start collecting data one DB hits vs response time.

**Comment by CarsonF** [comment]
FYI [Apollo Studio performance dashboard](https://studio.apollographql.com/graph/CORD/operations?range=lastDay&schemaTag=dev) is could be a good place to see these measurements.

**Comment by zkhin** [comment]
@michaelmarshall 
https://github.com/SeedCompany/cord-api-v3/blob/master/src/components/engagement/engagement.service.ts#L1204~L1206
I think this section delays the loading project. If we have more than 100 engagements, it will call `readOne` function 100 times.

**Comment by zkhin** [comment]
Seems we need to refactor `engagement.list` again using `org.service` pattern.

**Comment by michaelmarshall** [comment]
yes, its a bad pattern but its where we are at right now because our helper functions aren't built to aggregate requests into one query. 

It will only call the readOne function for the number of rows returned in the list query which should be limited to 25 at the most. less if the FE sets the `count` parameter, which will be a best practice for autocomplete.

**Comment by michaelmarshall** [comment]
the focus of this ticket would then be to `PROFILE` the `list` query and the `readOne` query and reduce the `DB Hits` for each query.

**Comment by michaelmarshall** [comment]
here's a recording were I explain how to profile queries and what to look for:
Share recording with viewers:
https://tsco.zoom.us/rec/share/wY9nNqns_HtOS43BtkzNXaIPJ5_XT6a803MXqaFfy0gXmtuNjEMfh1rckkTU29du Password: v8u1Y^a?

**Comment by zkhin** [comment]
Thank you

**Comment by michaelmarshall** [comment]
np. And I don't think we can use the `org.service` pattern because the engagement object is more complex. At least for now with the helper functions we are using. In the future we will write a new query library that does everything in one query.

**Comment by zkhin** [comment]
Do we still need `initialEndDate` , `statusModifiedAt`, `lastSuspendedAt` and `lastReactivatedAt` fields in engagement? I'd like to cut off the unnecessary fields in `engagement.serivce`.

**Comment by CarsonF** [comment]
Yeah we still need them.

**Comment by zkhin** [comment]
Okay

**Comment by zkhin** [comment]
@michaelmarshall Seems this ticket can be closed since refactored `readOne` methods.
