### ISSUE TITLE
mutation CreateProduct > Product can be created with any input values to the 'produces' field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#858]
**Describe the bug**
mutation CreateProduct > Product can be created with any input values to the 'produces' field.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Specific Validation should be present for the length or inputs to the 'produces' field.

**Actual Result**
Product created successfully with any input values to the 'produces' field.
See video - https://drive.google.com/file/d/1ycZYNSWyhrSZbRSr03jxHZyjmmABLYZu/view?usp=drivesdk

GraphQL Query ( createProduct ):
![image](https://user-images.githubusercontent.com/5212585/88890215-f1942c80-d25e-11ea-9b21-d944ffdfc9a2.png)

**Query and Input File**
[createProduct_producesID.txt](https://github.com/SeedCompany/cord-api-v3/files/4999346/createProduct_producesID.txt)

CordAPIV3# aaecaf0

**Comment by reneepe** [comment]
@michaelmarshall What should be the parameters for the "produces" value? Right now, it appears to have no limit.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/5bffa4f1-1876-4690-8697-c366185856ad)

**Comment by michaelmarshall** [comment]
Not sure yet. A good question to hold for when we implement this.

**Comment by tjgersho** [comment]
@reneepe and @michaelmarshall , produces is an ID for story, film, song, and literacy-material. So this product will have this produces.
produces and scriptureReference can not exists at the same time. If produces is inputted, scriptureReference is no meaning.
Story, film, song and lit-material have their own scriptureReference.

**Comment by iPiyushPatel** [comment]
Hi @tjgersho @reneepe @michaelmarshall 
I can still replicate the issue for the empty input to `produces` field.
See video - https://drive.google.com/file/d/18poxhQxKDJnwHx0JZT5Z-gSx-bzQG6dh/view?usp=drivesdk
