### ISSUE TITLE
mutation CreateProduct > Product created with empty input to the required field 'engagementId'

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#861]
**Describe the bug**
mutation CreateProduct > Product created with empty input to the required field 'engagementId'

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Product should not be created with empty input to the required field and Validation Error should be thrown for 'engagementId' field.

**Actual Result**
Product is created successfully with the empty 'engagementId' field.
See video - https://drive.google.com/file/d/1VDifDqbbQvDgf6bWj9inXxKhCgQ5v1lf/view?usp=drivesdk

GraphQL Query ( createProduct ):
![image](https://user-images.githubusercontent.com/5212585/88917757-eb657680-d285-11ea-8283-361282ad4883.png)

**Query and Input File**
[createProduct_RequiredField_blank.txt](https://github.com/SeedCompany/cord-api-v3/files/5000942/createProduct_RequiredField_blank.txt)

CordAPIV3# aaecaf0

**Comment by reneepe** [comment]
@michaelmarshall Is the engagementId a required field? We're allowed to create products without it.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/ae606487-802f-4174-8752-e2277d44d455)

**Comment by michaelmarshall** [comment]
I'm not sure. We may have singleton products in the DB. meaning there will be only one of them and multiple engagements may point to them. @sethmcknight

**Comment by iPiyushPatel** [comment]
Hi @tjgersho @reneepe @michaelmarshall 
I can still replicate the issue on the latest master 3bec105c.
See video - https://drive.google.com/file/d/1Q-LNOgFBKoKN1TTSKo7-jsOgH4n6qQIg/view?usp=drivesdk
