### ISSUE TITLE
Search Timeout

### ISSUE THREAD

**Issue by jmc637** [SeedCompany/cord-api-v3#864]
**Describe the bug**
When trying to run the search query from the graphql playground get an error about connection.

**Steps to Reproduce**
1. Run api using docker. 
2. Bring up the graphql playground.
3. Create a project. 
4. Submit query for search in graphql playground.

**Expected and Actual Results**
Expect search to return with results. Search returns error about connection.

**Screenshots**
![Screen Shot 2020-07-27 at 10 47 36 AM](https://user-images.githubusercontent.com/16201433/88947545-aa0da080-d25e-11ea-8d7a-aa88c5bd0563.png)

Desktop:
- OS High Sierra 10.13.6

**Comment by reneepe** [comment]
Unable to reproduce the timeout. @jmc637 are you still experiencing this one?
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/4e82e49c-d516-4267-b7ef-4134d0175d36)

**Comment by jmc637** [comment]
Hi, I'm still experiencing this one at the moment. Maybe it's something on my end. I'll check this again today to make sure everything is set up fine and report back.

**Comment by jmc637** [comment]
Hi, still getting the same error when querying using the above format.
<img width="1440" alt="Screen Shot 2020-08-03 at 2 41 33 AM" src="https://user-images.githubusercontent.com/16201433/89153574-29d38d80-d533-11ea-8563-193dfb4c6109.png">

<img width="1440" alt="Screen Shot 2020-08-03 at 2 41 25 AM" src="https://user-images.githubusercontent.com/16201433/89153546-1aecdb00-d533-11ea-804b-289aef6ef31d.png">

It's okay to query by project name?

**Comment by jmc637** [comment]
Hi, I cleared all the data on my end and reran search with new code and this is working now. This may have just been an issue on my end.

**Comment by reneepe** [comment]
Apologies! Just seeing this. To answer your question, I haven't had any issue with querying by the project names either. 

I'll close since it's working for you too now.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/9bcf0146-6a28-4cc7-9f23-b0e1672f8244)
