### ISSUE TITLE
mutation updateProduct > Unable to update Product details with any field inputs to the query variables

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#866]
**Describe the bug**
mutation updateProduct > Unable to update Product details with any field inputs to the query variables

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
1. Product details should be updated. 
2. For the 'produces' field, validation should be present.

**Actual Result**
Unable to update Product details with any field inputs to the query variables.
See video - https://drive.google.com/file/d/1i2aWp8LimTJYYmd_9EaUuEX6cwPkNGqB/view?usp=drivesdk

GraphQL Query ( updateProduct - produces Empty ):
![image](https://user-images.githubusercontent.com/5212585/88997721-f237cc00-d30d-11ea-884d-f1af97bbdf50.png)

GraphQL Query ( updateProduct - produces not empty):
![image](https://user-images.githubusercontent.com/5212585/88997763-1693a880-d30e-11ea-9a78-fbc40dd1fb43.png)

GraphQL Query ( updateProduct - produces not empty error):
![image](https://user-images.githubusercontent.com/5212585/88997856-5c507100-d30e-11ea-9212-2834b62dcb99.png)

GraphQL Query ( updateProduct - fields ):
![image](https://user-images.githubusercontent.com/5212585/88997946-8efa6980-d30e-11ea-82f9-5adb2523088d.png)

**Query and Input File**
[updateProduct_Error.txt](https://github.com/SeedCompany/cord-api-v3/files/5004969/updateProduct_Error.txt)

CordAPIV3# e33b292

**Comment by reneepe** [comment]
Bug still occurring. Still getting errors regardless of the input.
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/a738ab0c-984a-4bcb-b14e-854379bfe341)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/65bb56a6-5439-4fe1-900f-d1c373de0707)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/1df20b5b-fda4-451b-909a-8b68ad07b5e9)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/0d8cede2-33c4-4cf5-b0ef-66c1f85719b1)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/ee77b67a-13ae-4242-9474-e8c9e698cf36)
