### ISSUE TITLE
query products > Getting "Cannot return null for non-nullable field SecuredProductMediums.value." error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#868]
**Describe the bug**
query products > Getting "Cannot return null for non-nullable field SecuredProductMediums.value." error

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
Products list should be returned.

**Actual Result**
Getting "Cannot return null for non-nullable field SecuredProductMediums.value." error.
See video - https://drive.google.com/file/d/1tk17oCjv1ByAEa7otsFOceHTpLPm4Tz9/view?usp=drivesdk

GraphQL Query ( products - Error ):
![image](https://user-images.githubusercontent.com/5212585/89029073-385f5080-d34b-11ea-94db-23ceb8041716.png)

GraphQL Query ( products ):
![image](https://user-images.githubusercontent.com/5212585/89029137-60e74a80-d34b-11ea-8f79-c54b98073543.png)

**Query and Input File**
[products_medimsNullable_ERR.txt](https://github.com/SeedCompany/cord-api-v3/files/5006668/products_medimsNullable_ERR.txt)

CordAPIV3# e33b292

**Comment by reneepe** [comment]
Bug verified. "Cannot return null for non-nullable field SecuredProductMediums.value" error occurs when including mediums in the query.
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/42683dea-dea7-4f6a-b377-7bd7202251a9)

No error occurs when mediums isn't included.
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/2cb169c9-0b1b-422c-b431-95627ff07e6c)

**Comment by tjgersho** [comment]
Should be fixed on the master branch now
