### ISSUE TITLE
Budget Records array is empty

### ISSUE THREAD

**Issue by glassblowerscat** [SeedCompany/cord-api-v3#889]
**Describe the bug**
Querying value of a `Project`'s budget records just returns an empty array

**Steps to Reproduce**
1. Create a new project
2. Run `createPartnership` to create `Funding` partnership between the project and an existing organization
3. Run `updateProject` and provide values for the `mouStart` and `mouEnd` fields (I used `2020-08-04` and `2021-08-04`, respectively)
4. Run the following query and see that `records` is an empty array:

```
query {
  project(id: $id) {
    budget {
      value {
        id
        records {
          id
        }
      }
    }
  }
}
```

**Please give the commit short hash of the API and Front End repo if you are able to**.  
API: `344e5af6`
FE: `456a2384`

**Expected and Actual Results**
Expected: A project with a valid budget, funding partnership, and `mouStart` and `mouEnd` dates should return budget records
Actual: Budget records array is empty

**Platform/Environment**  
Clear report on what the bug can be reproduced. Please complete the following information accordingly.

Desktop:
- OS: MacOS 10.15.4
- Browser: Playground
- Version: N/A

**Comment by thomas-adev** [comment]
@glassblowerscat Can you provide an example of the specific "createPartnership" query you are running along with your query variables.

**Comment by glassblowerscat** [comment]
@thomas-adev Sure! Here's the mutation I just did:

```
mutation {
  createPartnership(input: {partnership: {organizationId: "seedcompanyid", projectId: "XCVtcjJeE", types: Funding}}) {
    partnership {
      id
      types {
        value
      }
    }
  }
}
```

`XCVtcjJeE` is a Translation Project I just created. Here's the return I got back when I sent the mutation:

```
{
  "data": {
    "createPartnership": {
      "partnership": {
        "id": "V_zVbVfWP",
        "types": {
          "value": [
            "Funding"
          ],
          "__typename": "SecuredPartnershipTypes"
        },
        "__typename": "Partnership"
      },
      "__typename": "CreatePartnershipOutput"
    }
  },
  "extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2020-08-05T16:59:38.784Z",
      "endTime": "2020-08-05T16:59:39.552Z",
      "duration": 767455522,
      "execution": {
        "resolvers": [
          {
            "path": [
              "createPartnership"
            ],
            "parentType": "Mutation",
            "fieldName": "createPartnership",
            "returnType": "CreatePartnershipOutput!",
            "startOffset": 7016413,
            "duration": 759833046
          },
          {
            "path": [
              "createPartnership",
              "partnership"
            ],
            "parentType": "CreatePartnershipOutput",
            "fieldName": "partnership",
            "returnType": "Partnership!",
            "startOffset": 767046771,
            "duration": 44476
          },
          {
            "path": [
              "createPartnership",
              "partnership",
              "id"
            ],
            "parentType": "Partnership",
            "fieldName": "id",
            "returnType": "ID!",
            "startOffset": 767118522,
            "duration": 34501
          },
          {
            "path": [
              "createPartnership",
              "partnership",
              "types"
            ],
            "parentType": "Partnership",
            "fieldName": "types",
            "returnType": "SecuredPartnershipTypes!",
            "startOffset": 767189273,
            "duration": 11550
          },
          {
            "path": [
              "createPartnership",
              "partnership",
              "types",
              "value"
            ],
            "parentType": "SecuredPartnershipTypes",
            "fieldName": "value",
            "returnType": "[PartnershipType!]!",
            "startOffset": 767214724,
            "duration": 16468
          }
        ]
      }
    }
  }
}
```

**Comment by thomas-adev** [comment]
I've been unable to replicate so far.

The budget records will show as empty up till the updateProject mutation is run (this would be expected if you create a project with no mouStart or mouEnd as there would be no way to calculate the budget records). Then I'm seeing the event fire and the budget records are showing as expected if you run an updateProject and pass in mouStart and mouEnd as you specified.

**Update Project Mutation Example**
```
mutation{
  updateProject(input:{
    project:{
      id:"{{PROJECT ID HERE}}",
      mouStart:"2020-08-04",
      mouEnd:"2021-08-04"
    }
  }){
    project{
      id
    }
  }
}
```

I see Zayar is jumping on this ticket, so I'll let him take it from here.

**Comment by glassblowerscat** [comment]
Yep, this is the exact mutation I've been running. Is it possible that my db needs a wipe? It hasn't had one in probably about a week

**Comment by thomas-adev** [comment]
I don't think a db wipe is necessary.

**Comment by CarsonF** [comment]
@thomas-adev I believe this change
https://github.com/SeedCompany/cord-api-v3/blob/ae325d77a7cd068fe751fa2bf0af23dd3458f3e2/src/components/partnership/partnership.service.ts#L283-L285
from https://github.com/SeedCompany/cord-api-v3/pull/811 is causing at least some of the pain here. It needs to be reverted. `PartnershipCreatedEvent` should always be ran when a partnership is created. We just need to default `types` to an empty array.

**Comment by CarsonF** [comment]
Also this code should be removed. It's already handled the in event handler right? https://github.com/SeedCompany/cord-api-v3/blob/ae325d77a7cd068fe751fa2bf0af23dd3458f3e2/src/components/partnership/partnership.service.ts#L291-L313

**Comment by thomas-adev** [comment]
Carson, those two changes to the partnership service both make sense. I definitely can see how that early return on line 284 is problematic. It appears it was just implemented to short circuit the method before types was accessed. Your solution of making sure a default empty array exists would be more elegant.

and you are correct that the code to create budget records is redundant. I'll make sure those get updated.
