### ISSUE TITLE
Cannot create user

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#899]
**Describe the bug**
When creating a new user getting **error: Could not find user**. 

**Steps to Reproduce**
Clear and specific actions taken to cause the behavior. Steps should resemble the following:
1. Wipe data
2. in gql playground Start session and register new user
3. Create a person with `createPerson` mutation with minimum values

**Please give the commit short hash of the API and Front End repo if you are able to**.  
Run `git rev-parse --short HEAD` in each repo to retrieve the commit hash.    
API:    edc253ee
FE:      

**Expected and Actual Results**
ER: successfully create user
AR: get an error saying user not found.  If I run the mutation again with the same email I get "email already in use"

**Screenshots**
![Screen Shot 2020-08-06 at 9 50 57 AM](https://user-images.githubusercontent.com/43487134/89559324-5c4ae800-d7ca-11ea-990f-984c5129cf92.png)

**Platform/Environment**  
Clear report on what the bug can be reproduced. Please complete the following information accordingly.

Desktop:

Smartphone:

**Additional context**

**Comment by michaelmarshall** [comment]
Currently, `createPerson` only works when logged in as root. We need it to work for everyone.

**Comment by michaelmarshall** [comment]
This error occurs when a user is created by a non-root user and is caused because the creating user does not have access to the new user's properties. The fix is to add the creating user to the new user's reader security group after the fact.

**Comment by michaelmarshall** [comment]
So the error is thrown on the read query, not the create query.

**Comment by zkhin** [comment]
@michaelmarshall @frankyma Seems this ticket can be closed now since refactored `UserService.readOne` method.

**Comment by frankyma** [comment]
@zkhin have you tried to repo?

**Comment by frankyma** [comment]
Just tested and looks fixed, if it looks good to you too should be good to close
