### ISSUE TITLE
Unable to Create Partnership with All Fields Entered

### ISSUE THREAD

**Issue by reneepe** [SeedCompany/cord-api-v3#902]
User receives 500 "Failed to create partnership" error message when trying to create a partnership with all fields entered.

Steps to reproduce:
1. Go to the playground
2. Enter query data as below and in attached document.
3. Press Play

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/9aa64fbe-b076-4cc2-9d5d-20e1193a8bcd)

API: e62f8ea8
FE: 2e940964

Expected Results: Partnership is created
Actual Results: Partnership isn't created.

Desktop:

OS: Windows 10 Pro 1903
Browser: Chrome
Version: 84.0.4147.105

[Create Partnership Error 8.6.20.txt](https://github.com/SeedCompany/cord-api-v3/files/5037048/Create.Partnership.Error.8.6.20.txt)

**Comment by zkhin** [comment]
That's because of `mou` and `agreement`'s uploadId. 
@CarsonF This issue occurs while creating `FileVersion`: `Could not find upload`. Can you clarify why this issue happens? I think it's because we are testing on local.

**Comment by CarsonF** [comment]
It's because there's not been a file uploaded with that ID, so it's a user problem. The response should reflect that. The try/catch over the whole method is hiding it.

**Comment by zkhin** [comment]
Can you let me know the `mutation` query to upload file with the requested file upload `id`?

**Comment by CarsonF** [comment]
It's not a graphql mutation. You have to make a PUT request to `url` given from `requestFileUpload` mutation with the file as the body.

**Comment by zkhin** [comment]
Got it, thank you!

**Comment by CarsonF** [comment]
Those files are optional btw. We won't be even offering them for partnership creation on the frontend (only for updates).

**Comment by zkhin** [comment]
I see
