### ISSUE TITLE
Cannot read country of origin on newly created Internship Engagement

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#906]
**Describe the bug**
Create a new internship engagement with minimum values (w/o country of origin id), and the country of origin returns `canRead: false`

**Steps to Reproduce**
With root user, create an internship engagement with only project id, intern id and project id, and ask for the canRead property in the country of origin return value

**Please give the commit short hash of the API and Front End repo if you are able to**.  
Run `git rev-parse --short HEAD` in each repo to retrieve the commit hash.    
API:    edc253ee
FE:      

**Expected and Actual Results**
ER: Country of Origin canRead property is true
AR: property is false

**Screenshots**

![Screen Shot 2020-08-06 at 2 57 42 PM](https://user-images.githubusercontent.com/43487134/89586826-3d158000-d7f5-11ea-8100-a35674fddb22.png)

**Platform/Environment**  
Clear report on what the bug can be reproduced. Please complete the following information accordingly.

Desktop:

Smartphone:

**Additional context**

**Comment by tjgersho** [comment]
@michaelmarshall , The query creates a new internship engagement without Country filed related by countryOfOrigin. In this case, countryOfOrigin.canRead and canEdit make sense? If so, canRead and canEdit should be true? Currently, canRead returns false when Country filed does not exist in that Engagement.

[the code](https://github.com/SeedCompany/cord-api-v3/blob/99300401911c8710888bfebee24a71662be65a03/src/core/database/query.helpers.ts#L921-L925)

**Comment by frankyma** [comment]
my 2 cents is that canRead and canEdit are both permission fields that are independent of whether or not the value exists.  For example, if the country doesn't exist but canRead and canEdit is true, then it signals the FE that a user can add and thus read back a country

**Comment by reneepe** [comment]
Bug fixed by https://github.com/SeedCompany/cord-api-v3/pull/924. Bug reproduction and retest results below.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/45533082-f6be-4bc2-93ae-8ec78d5d04fd)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/4e899be9-1a3e-4e96-9c51-a8773eaf5ac6)!
