### ISSUE TITLE
Create Partnership > Agreement and MOU UploadId Errors

### ISSUE THREAD

**Issue by reneepe** [SeedCompany/cord-api-v3#910]
User receives "Field \"CreateDefinedFileVersionInput.name\" of required type \"String!\" was not provided" error messages when trying to create partnerships with an agreement uploadId and with a mou uploadId but no optional names.

Steps to reproduce:
1. Go to the playground
2. Enter query data as below and in attached document.
3. Press Play

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/14861b33-1683-4d05-a546-6513b5e587e1)

![image](https://user-images.githubusercontent.com/38309285/89653551-3c342b00-d895-11ea-8133-15b99ef62df5.png)

API: 6c7b6c92
FE: 2e940964

Expected Results: Partnership is created
Actual Results: Partnership isn't created with only the agreement uploadId. Partnership isn't created with only the mou uploadId.

Desktop:

OS: Windows 10 Pro 1903
Browser: Chrome
Version: 84.0.4147.105

**Comment by zkhin** [comment]
@reneepe The `agreement` and `mou`'s name fields are not optional.

**Comment by reneepe** [comment]
@zkhin Names was showing in docs as optional. But if it's required now then disregard.

**Comment by CarsonF** [comment]
Yes names are required.

**Comment by michaelmarshall** [comment]
@CarsonF Sounds like we need Carson and Seth to review the DB schema doc.
