### ISSUE TITLE
Create Partnership > Agreement and MOU UploadId with Name Errors

### ISSUE THREAD

**Issue by reneepe** [SeedCompany/cord-api-v3#911]
User receives "Failed to create partnership" error messages when trying to create partnerships with an agreement uploadId and with a mou uploadId and optional names.

Steps to reproduce:

Go to the playground
Enter query data as below and in attached document.
Press Play
See error

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/210c1ea9-a710-4a3b-89d5-346e7ffeda38)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/3cc093b7-4284-4d39-b9a4-c0e0f530511e)

API: 6c7b6c92
FE: 2e940964

Expected Results: Partnerships are created
Actual Results: Partnership isn't created with the agreement uploadId and name. Partnership isn't created with the mou uploadId and name.

Desktop:

OS: Windows 10 Pro 1903
Browser: Chrome
Version: 84.0.4147.105

**Comment by zkhin** [comment]
@reneepe It's the same ticket with #902.
Did you upload file with that requested upload `id`?

**Comment by reneepe** [comment]
@zkhin Yes this is a duplicate. I didn't know what triggered https://github.com/SeedCompany/cord-api-v3/issues/902 when I created this issue. Thanks!
