### ISSUE TITLE
Create Partnership > No Input for Types > Types Return Value is left empty

### ISSUE THREAD

**Issue by reneepe** [SeedCompany/cord-api-v3#912]
Types return should be null value if there's no types input.

Steps to reproduce:

Go to the playground
Enter query data as below and in attached document.
Press Play
See error

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/28d87040-52a7-4360-b831-1c658b844cc1)

API: 6c7b6c92
FE: 2e940964

Expected Results: Types return a null value.
Actual Results: Types value is left empty.

Desktop:

OS: Windows 10 Pro 1903
Browser: Chrome
Version: 84.0.4147.105

**Comment by zkhin** [comment]
@reneepe I think this is not a bug. The `types` field is enum list and it should be an empty array if there's no value.
@CarsonF Can you clarify this issue?

**Comment by CarsonF** [comment]
That's correct @zkhin. Empty values for array fields are empty arrays. Except for a couple edge cases.
