### ISSUE TITLE
Update product is broke

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#922]
As a user I want to update the scripture references with `UpdateProduct` mutation.  currently the update call succeeds but the scriptureReferences are unchanged.  (Please make sure the update with field `scriptureReferencesOverride` and `scriptureReferences` both work) 

<img width="1643" alt="Screen Shot 2020-08-07 at 3 37 46 PM" src="https://user-images.githubusercontent.com/43487134/89807092-e8bc1a00-daec-11ea-836d-2cbb3af9ae49.png">

**Comment by michaelmarshall** [comment]
Seems like product update is broke. Correct me if I'm wrong.

**Comment by tjgersho** [comment]
Right. I am completing the update mutation with scriptureRef and scriptureRefOverride.

**Comment by frankyma** [comment]
The rest of the update functionality seems fine
