### ISSUE TITLE
Cannot query Story derivative product

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#923]
## Current Behavior
Error on querying a product with a `Story` Producible (may be true for other producibles also)

## Expected Behavior

Able to get product successfully

## Steps to Reproduce

1.  Create a story producible with `createStory` 
2.  Create a product with that producible id value i the `produces` field.  Should be successful
3. query that created product asking for the produces values (see screenshot)

```
fragment Producible on Producible {
  id
  __typename
  createdAt
  ...on Film {
    name {
      ...ss
    }
  }
  ...on LiteracyMaterial {
    name {
      ...ss
    }
  }
  ...on Story {
    name {
      ...ss
    }
  }
  ...on Song {
    name {
      ...ss
    }
  }
}

fragment ss on SecuredString {
  canEdit
  canRead
  value
}
```

(please confirm this works on the other producible types also)

## Screenshots
![Screen Shot 2020-08-10 at 2 34 21 PM](https://user-images.githubusercontent.com/43487134/89834296-69900b80-db17-11ea-871b-798683b3452d.png)

## Environment

| Tech      | Version / Name |
| --------- | -------------- |
| API       | **cd822c58**               |
| FE        |                |
| OS/Device |                |
| Browser   |                |

**Comment by reneepe** [comment]
Bug fixed by https://github.com/SeedCompany/cord-api-v3/pull/925. Bug reproduction and retest results below.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/a439b22a-07df-4fc3-ac48-2b7ebd112ffe)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/3af556d3-7235-4eb3-b3e8-f7fd58d67d35)
