### ISSUE TITLE
Error when querying languages when there's no language in database

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#931]
## Current Behavior
When querying languages when there's no language in database, gets a 500 

## Expected Behavior
Gets empty list

## Steps to Reproduce

1. wipe database, start session, login as root
2. query languages

## Screenshots
![Screen Shot 2020-08-12 at 10 32 33 AM](https://user-images.githubusercontent.com/43487134/90047950-9fec9880-dc87-11ea-8a19-ff921c0bdcb1.png)

## Environment

| Tech      | Version / Name |
| --------- | -------------- |
| API       |                |
| FE        |                |
| OS/Device |                |
| Browser   |                |

**Comment by reneepe** [comment]
Bug verified.
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/93882800-95b8-4346-9f1f-5d0aa58e3d1a)
