### ISSUE TITLE
Partnership.fundingType

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#938]
When a Partner is added to a Partnership as a Managing Partner, users should select the Financial Reporting Type from:
- Funded
- Field Engaged

**Comment by zkhin** [comment]
@sethmcknight 
Can you clarify that I understood your requirements correctly?
- Add new optional `fundingType` field to `Partnership`
- This field can only be set to `Funded` or `FieldEngaged` when the `Partnership.types` includes the `Managing` type.

**Comment by CarsonF** [comment]
Exactly 👍
