### ISSUE TITLE
Product ScriptureReferences book's whitespace removed

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-api-v3#940]
## Current Behavior
When creating a product with scriptureReferences, the book string has the string removed

## Expected Behavior

The book string is saved as is

## Steps to Reproduce
1. create language engagement
2. Create Product with Scripture reference, in the book field, include a space, like "1 Kings"
3. ask for the scripture references in the return value

## Screenshots
![Screen Shot 2020-08-13 at 5 41 30 PM](https://user-images.githubusercontent.com/43487134/90200413-94cf6080-dd8c-11ea-8c56-5c6b57d36278.png)

## Environment

| Tech      | Version / Name |
| --------- | -------------- |
| API       |                |
| FE        |                |
| OS/Device |                |
| Browser   |                |

**Comment by tjgersho** [comment]
If the inputted book is one of [booknames](https://github.com/SeedCompany/cord-api-v3/blob/20e63036ee6854f168c0e45ca8a23759db17b63b/src/components/scripture/books.ts#L22), it returns first value of booknames.  [code](https://github.com/SeedCompany/cord-api-v3/blob/20e63036ee6854f168c0e45ca8a23759db17b63b/src/components/scripture/reference.ts#L113)

As a result, it returns `1Kings` for 1 Kings, First Kings, 1 King, 1 Ki, 1 Kin and 1 Kng(all inputs in `booknames` array).
Bug?

**Comment by frankyma** [comment]
Not sure if this is a but I fixed the FE to take this in mind
