### ISSUE TITLE
query literacyMaterials > Sort by Name with 'ASC / DESC' order is not working

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#945]
**Describe the bug**
query literacyMaterials > Sort by Name with 'ASC / DESC' order is not working

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
LiteracyMaterial items should be sorted by Name in ascending / descending order.

**Actual Result**
Sort by Name with 'ASC / DESC' order is not working.
See video - https://drive.google.com/file/d/1ut2O4Y6_yLrEz7UrjvAPKnG9YDpSJEFS/view?usp=drivesdk

GraphQL Query ( literacyMaterials - ASC):
https://drive.google.com/file/d/1BDqZplDcQm0sv3AUydezNwYN330V1ZPf/view?usp=sharing

GraphQL Query ( literacyMaterials - DESC ):
https://drive.google.com/file/d/1Z_UsdWRTMVecfhmVDNTA0Yn7SEHRrbCR/view?usp=sharing

**Query and Input File**
https://drive.google.com/file/d/1aQw0bGC8bYVpW90dHoe2ZJZRF_SOvTyN/view?usp=sharing

CordAPIV3# 544d30c6

**Comment by tjgersho** [comment]
I think this sorting behavior is correct and all services behave the same.
Numerical value, uppercase and lowercase in order

**Comment by iPiyushPatel** [comment]
Hi @tjgersho 
I have tested on the local and integration environment as well. Still, I'm getting the same issue.

**Comment by tjgersho** [comment]
I think that is not the issue. Can you check other services like the project or engagement for the order behavior?

**Comment by tjgersho** [comment]
Sorry, suddenly, closed and reopened it.

**Comment by frankyma** [comment]
@iPiyushPatel I just tested and literacy sorting is working for me.  If it's still broken for you on the latest master can you please give full steps to reproduce starting from a blank database?

**Comment by iPiyushPatel** [comment]
Hi @frankyma @CarsonF @michaelmarshall 

**Steps to Reproduce:**
1. Clear database.
2. Create literacyMaterial with name "auto".
3. Create literacyMaterial with name "Litereracy".
4. Create literacyMaterial with name "zone".
5. Create literacyMaterial with name "Auto".
6. Create literacyMaterial with name "Zone".
7. Get all literacyMaterials with `ASC/DESC` order.

I can still replicate this issue on the latest master 466465b7
See Video: https://drive.google.com/file/d/10dFSXuZh1XWIKgoPZq6H3Tyv796BG9zn/view

**Comment by frankyma** [comment]
Thanks Piyush, I'm able to reproduce.  Must be the capitalization, looking into it.

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown @CarsonF @parashara1 @frankyma 
I've verified on latest develop 5f8f59c and can't reproduce this issue
See video :

https://user-images.githubusercontent.com/5212585/134879833-51c1fd36-b42b-48be-bd33-fcb7fbee007d.mp4
