### ISSUE TITLE
mutation createPartnership > Getting "Could not find Project" error sometimes and logging in again resolve the issue

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#946]
**Describe the bug**
mutation createPartnership > Getting "Could not find Project" error sometimes and logging in again resolve the issue

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
If there is a session expired, then the proper error message should be displayed or Partnership should be created.

**Actual Result**
Getting "Could not find Project" error sometimes and logging in again resolve the issue and Partnership is created successfully.
See video - https://drive.google.com/file/d/13nj8AjTZyBVAttZnU8Z5qVG0vrINS1g1/view?usp=drivesdk

GraphQL Query ( createPartnership ):
https://drive.google.com/file/d/1WWNJbTJX3f7_bmTk4PAbpymBI-CKUK65/view?usp=sharing

**Query and Input File**
https://drive.google.com/file/d/1HSo1IopbrQID_mGtW6YJ4RPc_kH-EEPK/view?usp=sharing

CordAPIV3# 544d30c6

**Comment by zkhin** [comment]
@iPiyushPatel This can be fixed now after refactoring `readOne` methods.
@michaelmarshall Can we create `Partnership` without logging in?

**Comment by iPiyushPatel** [comment]
Hi @zkhin @michaelmarshall 

I'm no longer getting this type of error for valid `projectId` input to mutation `createPartnership`.

I have observed below things on latest master c4c11b73 :
1. We can create Partnership irrespective of user 'logged in' or  'logged out' with valid inputs to query.
See Video - https://drive.google.com/file/d/1TUnfntuUpjIsXdb2ub08Ys4QbufCoSEm/view?usp=drivesdk

2. We can not create Organization, Education, Film, Language, LiteracyMaterial, Project, Song, Story after 'Log Out'.

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown 
I've tested on the develop f294fe28 and it's working fine.
See video: 

https://user-images.githubusercontent.com/5212585/117923139-2b778080-b311-11eb-9900-6d5b162bdb79.mp4
