### ISSUE TITLE
mutation deleteOrganization > Same organization can be deleted multiple times without error after the user logged out

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#948]
**Describe the bug**
mutation deleteOrganization > Same organization can be deleted multiple times without error after the user logged out

**Steps to Reproduce**
1. Login
2. Create an Organization
3. Logout
4. Delete Organization multiple times

**Expected Result**
1. If there is a session expired, then the proper error message should be displayed.
2. The same Organization should not be allowed to delete multiple times and on Deleting again, the proper error should be thrown.

**Actual Result**
Same organization can be deleted multiple times without error after the user logged out.
See video - https://drive.google.com/file/d/1SK8lxe07YiZVmNoaqcsHzdy5437Imuww/view?usp=drivesdk

GraphQL Query ( createOrganization):
https://drive.google.com/file/d/1fHeLL4nubqJ1j2OBUvuKOY-_q0D_33nj/view?usp=sharing

GraphQL Query ( deleteOrganization ):
https://drive.google.com/file/d/1UVqm4cZasJgngOUNDCJ_CuH1H41J3paY/view?usp=sharing

**Query and Input File**
createOrganization - https://drive.google.com/file/d/19N7O8M2GTLQKqvp6HfMfN8GE-yWe9yWz/view?usp=sharing
deleteOrganization - https://drive.google.com/file/d/1hbCd241YKr_gbhLFWJ330GzcAPTSzhe2/view?usp=sharing

CordAPIV3# 544d30c6

**Comment by reneepe** [comment]
Bug fixed. Organization cannot be deleted while user is logged out. User can only delete organization when logged in. Error is triggered when logged in user tries to delete the same organization multiples times. The same error appears if user logs out and tries to delete an already deleted organization.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/7ef99a4f-7d0d-4e05-8701-3b96cd9ecab0)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/7ce42bb0-ce55-4d91-9a17-ce012aa619f4)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/a36c9b22-a4ef-44d9-b094-f994f3fcf88b)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/63c36f51-a2d3-4ee3-b4fc-05a2b8d2d382)
