### ISSUE TITLE
mutation createProduct > Getting "could not find producible node" error on any random input to 'produces' field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#952]
**Describe the bug**
mutation createProduct > Getting "could not find producible node" error on any random input to 'produces' field.

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
The better Error message should be displayed for invalid inputs to 'produces' field.

**Actual Result**
Getting "could not find producible node" error on any random input to 'produces' field.
See video - https://drive.google.com/file/d/1nBeH5exvJCCjvw9m34mC7myY8hZW-MKG/view?usp=sharing

GraphQL Query ( createProduct ):
https://drive.google.com/file/d/1w_iIHQgOY1BurmZZthUe0RtQ1x6gY7mQ/view?usp=sharing
https://drive.google.com/file/d/1E0u4GDwdwBDPVR-Lx9C8OSXJEtaRjLyx/view?usp=sharing

**Query and Input File**
https://drive.google.com/file/d/1Wd_DicC9PuL7OMlMZP-DTfosQz-kq10p/view?usp=sharing

CordAPIV3# 544d30c6

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466995188) by [Unito](https://www.unito.io)

**Comment by tjgersho** [comment]
`Could not find producible node. It should be a valid ID for a story/film/song/literacy material. `
How about this error message?
