### ISSUE TITLE
mutation createStory > Getting "Could not create story" error when 'scriptureReferences' field is provided to query input

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#954]
**Describe the bug**
mutation createStory > Getting "Could not create story" error when 'scriptureReferences' field is provided to query input

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
Story should be created successfully with 'scriptureReferences' field as a query input

**Actual Result**
Getting "Could not create story" error when 'scriptureReferences' field is provided to query input.
See video - https://drive.google.com/file/d/143t62pcOW_LqPSKVmCffegD3gQrdwrcC/view?usp=drivesdk

GraphQL Query ( createStory ):
https://drive.google.com/file/d/1bWQeDiAeA-KPUeuK0RHeH0bMkPQz9HOg/view?usp=sharing

**Query and Input File**
https://drive.google.com/file/d/15bv8PaQ2ZgCIj-_yY8v9LZRkd3z7gp1E/view?usp=sharing

CordAPIV3# 544d30c6

**Comment by reneepe** [comment]
Bug verified. User unable to create stories with scriptureReferences.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/96aee312-0dea-4ff4-b363-b7405507c9a9)
