### ISSUE TITLE
Register > Getting 'Email address is already in use' error for the deleted user details

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#955]
**Describe the bug**
Register > Getting 'Email address is already in use' error for the deleted user details

**Steps to Reproduce**
1. Register the user1
2. Login with user1
3. Delete the user1
4. Again register with user1 
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
User should be allowed to registration successfully

**Actual Result**
Getting 'Email address is already in use' error for the deleted user details
See video - https://drive.google.com/file/d/1KMI7o8Qzr_5k7YpXtWPzStG_ynMtB--S/view?usp=drivesdk

GraphQL Query( register ):
![image](https://user-images.githubusercontent.com/5212585/90248212-e263d000-de55-11ea-9bfd-2aecc99c0d62.png)

GraphQL Query( login ):
![image](https://user-images.githubusercontent.com/5212585/90247898-2e624500-de55-11ea-969b-f29763fd47c7.png)

GraphQL Query( delete ):
![image](https://user-images.githubusercontent.com/5212585/90247997-5ea9e380-de55-11ea-8b93-ee0f81d50e77.png)

GraphQL Query( register again ):
![image](https://user-images.githubusercontent.com/5212585/90247479-4be2df00-de54-11ea-88dd-a7debab28dd9.png)

**Query and Input File**
[Registration_issue.txt](https://github.com/SeedCompany/cord-api-v3/files/5074505/Registration_issue.txt)
[Login_issue.txt](https://github.com/SeedCompany/cord-api-v3/files/5074506/Login_issue.txt)
[delete_issue.txt](https://github.com/SeedCompany/cord-api-v3/files/5074507/delete_issue.txt)

CordAPIV3# 544d30c6

**Comment by reneepe** [comment]
Bug verified. User is unable to re-register after being deleted. Processing logout and again deleteUser also returns "Could not find user" response.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/3ad538cf-3817-46e7-a601-51d03a34646e)
