### ISSUE TITLE
mutation updateProduct > Getting "502 Bad Gateway" error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#965]
**Describe the bug**
mutation updateProduct > Getting "502 Bad Gateway" error.

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
Product should be updated with requested details.

**Actual Result**
Getting "502 Bad Gateway" error.
See video - https://drive.google.com/file/d/1zppoCRdrpPOOW5FoHxTFcBRybJnCHyMe/view?usp=drivesdk

GraphQL Query ( updateProduct ):
![image](https://user-images.githubusercontent.com/5212585/90332197-b2910580-dfd8-11ea-910d-6d0a94e98428.png)

**Query and Input File**
[updateProduct_502BadGatewayERR.txt](https://github.com/SeedCompany/cord-api-v3/files/5080468/updateProduct_502BadGatewayERR.txt)

Environment: Integration

**Comment by reneepe** [comment]
Unable to reproduce. 

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/168713c1-795b-45fc-8a21-de1776f157fc)

**Comment by iPiyushPatel** [comment]
@reneepe 
I've tested on the latest master af9851eb and its working fine.
