### ISSUE TITLE
mutation updateProduct > Getting "No book matched" error while 'scriptureReferences' is provided as input instead of 'produces' field for updating product

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#966]
**Describe the bug**
mutation updateProduct > Getting "No book matched" error while 'scriptureReferences' is provided as input instead of 'produces' field for updating product.

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
A product should be updated successfully or a Proper field validation message should be displayed.

**Actual Result**
Getting "No book matched" error while 'scriptureReferences' is provided as input instead of 'produces' field for updating product.
See video - https://drive.google.com/file/d/1FuxXD7ZAzVUstFLdK_r5geB0dZ1Y1mMD/view?usp=drivesdk

GraphQL Query ( updateProduct ):
![image](https://user-images.githubusercontent.com/5212585/90355137-211da400-e069-11ea-8597-af696f4b181a.png)

**Query and Input File**
[updateProduct_NoBookMatched.txt](https://github.com/SeedCompany/cord-api-v3/files/5082051/updateProduct_NoBookMatched.txt)

Environment: Integration

**Comment by tjgersho** [comment]
Can you check #942 ?

**Comment by tjgersho** [comment]
This issue can be closed now.

**Comment by reneepe** [comment]
Unable to reproduce. 
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/7446fd82-7801-4ff3-9adb-4fc305c66966)
