### ISSUE TITLE
Fix project test: list view of project members by project id

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#971]
This test experiences an intermittent bug and we skipped it. Try to unskip and see if you can determine the root cause and fix it.

**Comment by reneepe** [comment]
VERIFIED - The type, name, roles, creation data, project member ids, and total of project members return correctly.

![image](https://user-images.githubusercontent.com/38309285/92195726-a52ea480-ee3b-11ea-9cb0-d7f09a77c7bc.png)
