### ISSUE TITLE
query partnerships > Response time is > 10 seconds ( between 23 to 70 seconds )

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#977]
**Describe the bug**
query partnerships > Response time is > 10 seconds ( between 23 to 70 seconds )

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
Response time should be less than 10 seconds.

**Actual Result**
Response time is between 23 to 70 seconds. I've tried multiple times.
See video - https://drive.google.com/file/d/1RbKdF_Np66jp_fgTAa_UXYG1GqvrzGg8/view?usp=drivesdk

GraphQL Query ( partnerships less output ):
![image](https://user-images.githubusercontent.com/5212585/90482676-33730d00-e151-11ea-9c37-3fd8b1ba3a11.png)

GraphQL Query ( partnerships full output ):
![image](https://user-images.githubusercontent.com/5212585/90482513-f870d980-e150-11ea-84f2-082e76541273.png)

**Query and Input File**
[partnerships_lessOutput_responseTime.txt](https://github.com/SeedCompany/cord-api-v3/files/5088894/partnerships_lessOutput_responseTime.txt)
[partnerships_fullOutput_responseTime.txt](https://github.com/SeedCompany/cord-api-v3/files/5088895/partnerships_fullOutput_responseTime.txt)

CordAPIV3# 29ee3b29

**Comment by izquierdoalfredo** [comment]
Hi @iPiyushPatel 
I checked less and fulloutput response time several times
both response times are less than 10s

This is fulloutput response time
![image](https://user-images.githubusercontent.com/68758109/91465699-1c70a100-e85c-11ea-8dfe-a7641d961cfc.png)

This is lessoutput response time
![image](https://user-images.githubusercontent.com/68758109/91466044-930d9e80-e85c-11ea-8f80-c15090ebba00.png)

**Comment by iPiyushPatel** [comment]
Hi @izquierdoalfredo ,@reneepe,@michaelmarshall 
Verified on latest master and working fine now
I am closing this issue
