### ISSUE TITLE
mutation createProject > 'mouStart' returned null when not provided to query inputs

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#980]
**Describe the bug**
mutation createProject > 'mouStart' returned null when not provided to query inputs.

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
By default current date should be returned for 'mouStart' value if not provided. (It works correctly for createPartnership )

**Actual Result**
'mouStart' returned null when not provided to query inputs.
See video - https://drive.google.com/file/d/11WfRaoA0b57SJp97cLFBhcoVWWDH-ZxR/view?usp=drivesdk

GraphQL Query ( createProject ):
![image](https://user-images.githubusercontent.com/5212585/90507965-6bd81280-e174-11ea-987f-ffc970837d45.png)

GraphQL Query ( createPartnership ):
![image](https://user-images.githubusercontent.com/5212585/90508070-9f1aa180-e174-11ea-9697-e21a279845d5.png)

**Query and Input File**
[createProject_mouStart_NULL_ifRemoved.txt](https://github.com/SeedCompany/cord-api-v3/files/5090080/createProject_mouStart_NULL_ifRemoved.txt)
[createPartnership_anotherUserUpdate_ISSUE.txt](https://github.com/SeedCompany/cord-api-v3/files/5090081/createPartnership_anotherUserUpdate_ISSUE.txt)

CordAPIV3# 29ee3b29

**Comment by zkhin** [comment]
@iPiyushPatel 
I don't think we are returning the current date if the `mouStart` value is not provided in the `Project Service`.
In the Partnership, if the `mouStartOverride` value is `null`, it will return the associated `Project`'s `mouStart` value for `Partnership`'s `mouStart` value.

https://user-images.githubusercontent.com/5212585/90508070-9f1aa180-e174-11ea-9697-e21a279845d5.png
So this Partnership's `mouStart` is maybe Project's `mouStart` value.

**Comment by iPiyushPatel** [comment]
@zkhin 
I tried creating a partnership with `projectId ` which has `null` value for `mouStart` field, but still it returns current date for `mouStart` field.
See video - https://drive.google.com/file/d/1UQZOKShUgjWrxynX8UUswvsB7Q0EKKt4/view?usp=drivesdk

**Comment by zkhin** [comment]
@iPiyushPatel Can you try to create Partnership without `mouStatus` and `agreementStatus`?

**Comment by thomas-adev** [comment]
@iPiyushPatel I've submitted a pull request for this issue: https://github.com/SeedCompany/cord-api-v3/pull/1058/commits/4cac91f847dae54a1b5aa605dfd6d0e905533e7f

**Comment by CarsonF** [comment]
The mouStart should not be the current date. It is 99% in the future.

The partnership start date is an override and overrides should never be set by default.

**Comment by thomas-adev** [comment]
Ok, @CarsonF so the behavior noted in this issue is not actually a bug?

**Comment by CarsonF** [comment]
Correct for projects. I can't tell, is partnerships defaulting a start date? If it is, it shouldn't either.

**Comment by thomas-adev** [comment]
I have tested and not been able to replicate the partnership mouStart defaulting to the current date so I assume that at least off the current version of master it does not.
